/**
 * 카탈로그 단일 진실 원천 — 아이템 식별/로어/스프라이트.
 *
 * 한 배열이 다음을 모두 공급한다:
 *  - DB 시드 (`scripts/seed-catalog.ts`, `catalogItems`)
 *  - 스프라이트 파이프라인 프롬프트 (`scripts/sprite-pipeline.ts`)
 *  - 도감/인벤토리/공유 UI 표시명
 *  - 확률 공시 슬롯별 종 수
 *
 * 규칙 (GDD §3.1 / docs/LORE.md):
 *  - 등급·희소성·성능 차등 **없음**. 아이템 차이는 외관·도감·로어뿐.
 *  - `key`: 영문 snake. `public/sprites/<slot>/<key>.png` 파일명 = `catalogItems.spriteKey`.
 *  - `lore`: 보스 스토리 톤(장엄·서사·간결, ~60~120자). 등급/성능 표현 금지.
 *  - `art`: Pixellab 64×64 생성 키워드(형태·재질·색·분위기). 글로우/등급 제외(GDD §6 — 코드가 강화 글로우 부여).
 *  - 세계관 연결은 느슨하게(~40%): region 이 5권역이면 보스의 땅과 엮임, '자유'면 권역 무관.
 *
 * 목표: 슬롯당 50종(무기/방어구/장신구 = 150), 이후 가변 추가(GDD §10).
 */

export type CatalogSlot = 'weapon' | 'armor' | 'accessory';

export type CatalogRegion =
  | '늪지대'
  | '오크 부락'
  | '고대 룬 산맥'
  | '서쪽 화산'
  | '타락천사'
  | '자유';

/** 로어 정서 — 배치 내 고르게 분포(한 톤이 슬롯의 ~1/4 초과 금지). docs/LORE.md §1. */
export type CatalogTone =
  | '장엄'
  | '담백'
  | '위트'
  | '비애'
  | '기괴'
  | '일상'
  | '영웅담'
  | '수수께끼';

export interface CatalogItem {
  /** 영문 snake — 스프라이트 파일/스프라이트키 식별자. 전역 유니크. */
  key: string;
  slot: CatalogSlot;
  /** 한국어 표시명 (도감/인벤토리/공유). */
  nameKo: string;
  region: CatalogRegion;
  /** 로어 정서(다양성 강제용). docs/LORE.md §1. */
  tone: CatalogTone;
  /** 한국어 로어 (~120~260자, 2~4문장). 아이템마다 고유 사연·개성. 등급/성능 언급 금지. */
  lore: string;
  /** Pixellab 64×64 생성 키워드 (영문, 글로우/등급 제외). */
  art: string;
}

const STYLE = 'clean readable silhouette, fantasy RPG pixel art inventory icon, transparent background';

/** 슬롯별 묶음을 합쳐 단일 export. 배치(슬롯)별로 확장한다. */

// ─────────────────────────────────────────────────────────────────────────────
// 무기 (목표 50) — 배치 1/약4
// ─────────────────────────────────────────────────────────────────────────────
const WEAPONS: CatalogItem[] = [
  {
    key: 'marsh_rusted_blade',
    slot: 'weapon',
    nameKo: '녹슨 늪칼',
    region: '늪지대',
    tone: '담백',
    lore: '수선 의뢰서. 「맡기는 것: 한손검 하나. 상태: 날 전체가 검붉게 삭음. 늪 우물 바닥에서 건졌다 함. 부탁: 쓸 만하게 갈아 주시오. 값은 부르는 대로.」 — 대장장이 답: 「갈 게 없어 그냥 돌려보냅니다. 녹을 벗겨 보니 이 나간 데가 하나도 없고, 그 녹이 외려 날을 단단히 붙들고 있더이다. 손대면 그게 풀립니다. 값은 안 받습니다. 그냥 차고 다니시오.」 의뢰인은 정말 그 말대로 그대로 차고 다녔다. 같은 묶음의 다음 장은 다른 검, 또 다른 검으로 이어지는데, 이 검 건은 짧은 답 한 줄로 끝나 있다.',
    art: `plain one-handed sword, pitted reddish-rusted iron blade, dried swamp mud, leather-wrapped grip, simple crossguard, understated, ${STYLE}`,
  },
  {
    key: 'ashfall_obsidian_dagger',
    slot: 'weapon',
    nameKo: '화산재 흑요석 단검',
    region: '서쪽 화산',
    tone: '기괴',
    lore: '같은 단검을 들여다본 두 사람의 말을 나란히 둔다. 갑: "칼날에 내 얼굴이 비쳤소. 그뿐이오." 을: "갑이 거짓말이오. 그 얼굴, 갑이 안 짓던 표정을 짓고 있었소. 내가 옆에서 똑똑히 봤소." 갑: "을이 헛것을 본 게지. 나는 멀쩡했소." 을: "그럼 왜 갑은 그날 뒤로 칼집을 열 때마다 고개를 옆으로 트시오?" 둘은 끝까지 말을 안 맞췄다. 단검은 지금 둘 다 아닌 다른 사람 손에 넘어가 있고, 그 사람은 아직 한 번도 칼날을 똑바로 들여다보지 않은 채 허리에만 차고 다닌다.',
    art: `short dagger, glassy black obsidian blade, faint distorted reflection, fractured razor edge, charred bone handle, eerie, ${STYLE}`,
  },
  {
    key: 'runescar_warhammer',
    slot: 'weapon',
    nameKo: '룬흉터 전쟁망치',
    region: '고대 룬 산맥',
    tone: '장엄',
    lore: '산이 무너진 비탈, 큰 돌 하나에 글이 새겨져 있다. 「여기, 산의 화 한 줌이 떨어진 자리. 그것으로 이 망치를 벼렸다.」 그 아래로 세월 따라 다른 손들이 한 줄씩 더 새겼다. 한 줄: 「들어 보았다. 두 발이 땅에 박히는 줄 알았다.」 그 밑: 「내려친 자리에 한참 낮은 울림이 남더라.」 맨 아래, 글씨 서툰 한 줄: 「나는 못 들었다. 너무 무거워 들지를 못해서.」 망치는 지금 그 돌 곁에 세워져 있다. 지나는 사람마다 한 번 들었다 도로 내려놓고는, 제 줄을 새길지 말지 한참 서 있다 그냥 간다.',
    art: `massive two-handed warhammer, grey carved-stone head, vivid blue rune cracks, iron-banded oak haft, monumental, ${STYLE}`,
  },
  {
    key: 'orcfang_cleaver',
    slot: 'weapon',
    nameKo: '오크 송곳니 도끼',
    region: '오크 부락',
    tone: '위트',
    lore: '장터 떨이 목록 스물셋 번. 「외날 도끼 하나. 오크 부락에서 나옴. 자루에 큰 어금니 박힘(족장 본인 것이라 함). 잘 듦, 보증.」 값을 부르기 시작 — 아무도 안 부른다. 다시 — 여전히 잠잠. 파는 사람이 어금니 사연을 곁들였다. "이빨이 둘이면 무는 힘도 둘이라 했답니다." 듣던 누가 받았다. "그게 무슨 소리요?" 파는 사람도 답을 못 했다. 그날도, 그다음 날도 끝내 안 팔렸다. 도끼는 다시 창고로 들어갔다가 같은 스물셋 번으로 또 목록에 올랐고, 잘 듦 보증만 매번 그대로 붙어 있었다.',
    art: `one-handed broad cleaver axe, chipped crescent iron blade, large tusk wedged into haft, crude lashings, rugged, ${STYLE}`,
  },
  {
    key: 'fallen_grace_rapier',
    slot: 'weapon',
    nameKo: '타락한 은총의 레이피어',
    region: '타락천사',
    tone: '비애',
    lore: '어느 약방 처방전 한 장. 「증상: 이 가는 검을 지닌 뒤로 잠을 설침. 뽑을 때마다 깃털 스치는 소리가 나고, 그때 떠오르는 얼굴이 있다 함.」 처방: 「먹는 약 없음. 대신 — 하루 한 번만 뽑을 것. 뽑거든 그 소리를 끝까지 들을 것. 도중에 칼집에 도로 넣으면 다음 날 더 오래 들린다.」 끝에 작게: 「오래 지닌 사람일수록 점점 덜 뽑게 된다. 그게 차도다.」 처방을 받은 이는 그 뒤로 검을 벽에 걸어 두었다. 한 달에 한 번쯤 내려 천으로 닦고는, 뽑지는 않은 채 도로 걸어 두었다.',
    art: `slender thrusting rapier, pale silver blade, tarnished gold swept hilt, faint black feather etching, somber elegant, ${STYLE}`,
  },
  {
    key: 'iron_field_sword',
    slot: 'weapon',
    nameKo: '무쇠 야전검',
    region: '자유',
    tone: '일상',
    lore: '칼과 함께 오는 종이에는 〈주의〉만 적혀 있다. 하나 — 이 검은 천 자루 중 하나다. 네 것이라 여기지 마라. 둘 — 이가 나가면 갈고, 자루가 닳으면 그 자리에서 새로 감아라. 셋 — 부러져도 슬퍼하지 마라, 다음 자루를 꺼내면 된다. 넷 — 이름을 붙이지 마라, 붙이면 잃었을 때 곤란해진다. 종이에 「쓰는 법」도 「내력」도 없다. 주의 넷이 전부다. 그 넷을 그대로 지킨 병사들이 이 검으로 변경을 여러 번 막아냈고, 그래서 종이에 더 보탤 줄이 끝내 생기지 않았다.',
    art: `standard-issue one-handed arming sword, straight iron blade, re-wrapped worn grip, plain pommel, utilitarian, ${STYLE}`,
  },
  {
    key: 'wanderer_oak_staff',
    slot: 'weapon',
    nameKo: '방랑자의 떡갈나무 지팡이',
    region: '자유',
    tone: '수수께끼',
    lore: '길잡이가 마을 사이 거리를 적어 둔 표가 있다. 보리골—갈대마을 이틀. 갈대마을—잿재울 사흘. 잿재울—옹기점 하루 반. 그 줄들 사이에 글씨가 다른 한 칸이 끼어 있다. 「떡갈나무 지팡이 짚은 노인과 함께 갈 때: 거리는 같음. 다만 그해 그 길가 마을들 농사가 잘된다고 함. 근거 없음. 지우려다 그냥 둠.」 표를 베끼는 사람마다 그 칸을 빼려다, 끝내 같이 옮겨 적었다. 노인이 지금 어느 마을에 있는지는 표에 없고, 지팡이만 한 헛간에 세워진 채 다음 베끼는 손을 기다린다.',
    art: `tall wooden wizard staff, gnarled oak shaft, smooth hand-worn grip, dull clouded stone at crown, enigmatic, ${STYLE}`,
  },
  {
    key: 'hunter_greenwood_bow',
    slot: 'weapon',
    nameKo: '푸른숲 사냥활',
    region: '자유',
    tone: '영웅담',
    lore: '아이들이 돌 던지며 세는 동요다. 「하나, 눈밭에 엎드린 사냥꾼 / 둘, 외양간 노린 늑대 / 셋, 사흘 밤 / 넷, 활은 하나 / 다섯, 늑대 머리 떨어지고 / 여섯, 양은 다 살고 / 일곱, 영웅이라 부르니 / 여덟, 그는 그냥 웃네 / 아홉, 운이 좋았다고 / 열, 추웠을 뿐이라고.」 열까지 세면 술래가 바뀐다. 정말 그 겨울 한 사냥꾼이 사흘을 엎드려 우두머리를 잡았고, 활은 지금도 그 집 벽에 걸려 있다. 동요의 「열」을 셀 때 아이들 목소리가 늘 한 번 작아지는데, 누가 그러라 한 적은 없고 그냥 대대로 그렇게 됐다.',
    art: `curved wooden recurve shortbow, taut sinew bowstring, frost-pale wood grain, worn grip wrap, vertical, heroic, ${STYLE}`,
  },
  {
    key: 'marsh_reed_spear',
    slot: 'weapon',
    nameKo: '늪 갈대창',
    region: '늪지대',
    tone: '일상',
    lore: '장물 사고파는 자의 장부 한 줄. 「들어온 것: 늪 갈대창 하나. 값: 거의 없음 — 집집마다 문가에 한 자루씩 있는 물건. 비고: 훔친 놈도 무기인 줄 알고 가져왔다가, 자루에 밴 빨랫줄 받친 흔적 보고 김샜다 함.」 되팔려 내놨지만 아무도 안 샀다. 늪 사람이면 제 문가에서 하나 들면 그만이니까. 결국 그자도 그 창을 제 가게 문가에 세워 두고 늘어진 빨랫줄을 받쳤다. 훔쳐져 한 바퀴 돌아온 갈대창은 그렇게 또, 무기가 아니라 살림으로 제자리를 찾았다.',
    art: `long thrusting spear, dark hardened reed shaft, narrow leaf-shaped iron head, doorway-leaning wear, mundane, ${STYLE}`,
  },
  {
    key: 'emberforged_greatsword',
    slot: 'weapon',
    nameKo: '잉걸불 대검',
    region: '서쪽 화산',
    tone: '장엄',
    lore: '이 대검 이야기는 마을을 건너며 한 대목씩 어긋난다. 화산 마을에선 「가장 깊은 화덕에서 벼렸다, 식는 데 보름」이다. 다음 마을에선 「화산 틈에 며칠 누여 식혔다」가 되고, 그다음 마을에선 「용이 직접 불어 만들었다」가 되며, 더 멀리 가면 「휘두르면 산이 한 번 운다」까지 붙는다. 정작 그 칼을 만진 늙은 대장장이는 보름도 며칠도 다 틀렸다며, 다만 너무 무거워 숨 한 번에 한 번밖에 못 휘둘렀던 것만은 맞다고 했다. 칼은 지금 그 대장간 벽에 걸려 있고, 이야기는 칼보다 훨씬 먼 마을까지 가 있다.',
    art: `large two-handed greatsword, broad heat-grained steel blade, deep ash river streaks, long wrapped grip, imposing, ${STYLE}`,
  },
  {
    key: 'glass_question_scepter',
    slot: 'weapon',
    nameKo: '물음의 유리홀',
    region: '자유',
    tone: '수수께끼',
    lore: '점치는 노파가 이 홀을 흔들어 보고 한 풀이. "속이 빈 유리알인데 흔들면 뭔가 또르르 굴러요. 소리는 분명한데 안엔 아무것도 없지. 이런 패는 — 답이 먼저 온 패예요. 물음이 아직 안 온 거고." 누가 물었다. "그럼 뭘 물어야 하오?" 노파가 받았다. "그걸 알면 점은 왜 봐. 답을 들고 다니다 보면 언젠가 딱 맞는 물음을 만나요. 끝내 못 만나는 사람도 있고." 그 풀이를 들은 한 사람은 평생 답만 품고 살다, 죽기 직전에야 그 물음을 만났다며 한참 웃다 갔다. 홀은 그 머리맡에 그대로 놓여, 다음 사람의 잠을 기다린다.',
    art: `short ornate scepter, hollow clear glass orb at head, faint something-inside rattle, banded silver shaft, mysterious, ${STYLE}`,
  },
  {
    key: 'orc_bonk_maul',
    slot: 'weapon',
    nameKo: '오크 박치기 둔기',
    region: '오크 부락',
    tone: '위트',
    lore: '부락 마당에서 열린 다툼 판결을 옮긴다. 「사건: 갑이 을의 천막을 둔기로 부쉈다고 함. 을: 갑이 휘둘렀다. 갑: 안 휘둘렀다, 들고만 있었는데 을이 알아서 자빠졌다. 증거: 뼈를 통째로 묶어 만든 둔기 하나, 흠 없음.」 판결: 「둔기가 멀쩡하니 휘둘렀다 단정 못 함. 다만 갑이, 그 둔기 만든 자가 같은 날 비탈에서 굴러 죽은 일을 두고 「그게 내 솜씨 증명」이라 우겨 마당을 어지럽힌 죄로, 을의 천막을 다시 세워 줄 것.」 둔기는 보관 창고에 들어갔다가, 다음 다툼의 증거로 또 불려 나왔다.',
    art: `crude heavy bludgeon, single huge joint-bone head, thick leather lashings, lopsided, comically brutal, ${STYLE}`,
  },
  {
    key: 'parted_twin_daggers',
    slot: 'weapon',
    nameKo: '엇갈린 쌍단검',
    region: '자유',
    tone: '비애',
    lore: '분실물 보관소 회신. 「접수번호 …. 들어온 물건: 굽은 외날 단검 한 자루. 특징: 무게중심이 한쪽으로 미세하게 치우침. 신고인 진술 — 본래 두 자매가 한 자루씩 나눠 가졌고, 다시 맞대기로 했다 함. 찾는 것은 이것이 아니라 짝이 되는 다른 한 자루. 보관소 회신: 해당 물건 미발견. 들어온 한 자루는 보관 연장함. 짝 없이도 들 수 있으나 손이 자꾸 빈쪽을 더듬는다는 신고인 추가 진술은 참고만 함.」 그 한 자루는 지금도 보관소 선반에 번호표를 단 채 놓여, 매년 보관 기한이 한 줄씩 늘어 적힌다.',
    art: `single curved dagger, faint mark where a twin once paired, dark wrapped handle, slightly off-balance, lonesome, ${STYLE}`,
  },
  {
    key: 'tollkeeper_glaive',
    slot: 'weapon',
    nameKo: '통행세 받던 언월도',
    region: '자유',
    tone: '일상',
    lore: '다리 통행세 영수증 묶음에는 문지기가 여백에 적어 둔 잔글씨가 섞여 있다. 한 장 옆: 「소 두 마리 끌고 온 자, 시끄러웠음. 그래도 셈은 안 속임.」 다른 장: 「급한 전령. 그냥 보냄. 창은 안 들었음.」 또 다른 장: 「오늘 비. 창에 먼지가 빗물에 줄줄이 흘러내림.」 영수증 숫자보다 이 잔글씨가 더 많다. 문지기가 떠난 뒤 다음 사람이 묶음을 물려받았는데, 며칠 안 가 그도 여백에 잔글씨를 적기 시작했다. 창은 여전히 초소 벽 같은 자리에 기대어 있다.',
    art: `polearm glaive, long worn wooden shaft, single curved blade thick with road dust, leaning-post wear, mundane, ${STYLE}`,
  },
  {
    key: 'fallen_feather_scythe',
    slot: 'weapon',
    nameKo: '깃 떨군 낫',
    region: '타락천사',
    tone: '기괴',
    lore: '농사 절기표 한 장. 「입춘 — 씨 고르기. 곡우 — 모판. 망종 — 모내기. 백로 — 거둠 시작.」 그 거둠 칸 옆에 글씨가 다른 한 줄이 끼어 있다. 「이 낫으로 거둘 때: 벤 자리에 검은 깃이 떨어져도 그날 일 멈추지 말 것. 줍지도 말 것. 줍던 해에 거둠이 늦었음.」 절기표를 새로 베껴 거는 집마다 그 줄을 빼려다, 거둠이 늦을까 봐 끝내 같이 옮겨 적었다. 낫은 헛간 못에 걸려 절기표 바로 아래에 있고, 백로 무렵이면 누구든 절기표보다 그 줄을 먼저 본다.',
    art: `war scythe, long curved blade, black feather-bound shaft, pale wing-bone fittings, unsettling, ${STYLE}`,
  },
  {
    key: 'butcher_falchion',
    slot: 'weapon',
    nameKo: '푸줏간 팔치온',
    region: '자유',
    tone: '위트',
    lore: '가게를 넘길 때 함께 적힌 인계 목록. 「넘기는 것: 푸줏간 한 칸. 도마 둘, 갈고리 여섯, 넓적칼 하나(뼈 끊던 것). 비고: 넓적칼은 전 주인이 외상값 받으러 나간 뒤 안 돌아와, 가게에 딸려 그대로 넘어감.」 새 주인은 그 칼을 무기랍시고 떠벌리는 손님들에게 몇 번 빌려줬다가, 빌려 간 자들이 하나같이 김샌 얼굴로 돌려주는 걸 보고 그만뒀다. 칼은 도마 옆 같은 자리에 그대로 걸려, 다음 인계 목록에도 같은 한 줄로 또 적힐 참이다.',
    art: `wide heavy falchion, broad cleaver-like steel blade, nicked edge, plain wooden grip, butcher-tool origin, ${STYLE}`,
  },
  {
    key: 'dawn_charge_saber',
    slot: 'weapon',
    nameKo: '여명 돌격 사브르',
    region: '자유',
    tone: '영웅담',
    lore: '군적 담당이 그날 적은 셈이다. 출진 기병 스물, 맨 앞에 세운 칼 하나, 적은 예순 너머, 안개는 안 걷힘. 돌격이 끝나고 다시 적었다. 안장에 다시 앉은 자 열하나, 잃은 말 아홉, 땅에 닿은 깃발 없음. 그 열하나는 칼을 한 자루씩 따로 챙기지 않고, 맨 앞에 섰던 이 사브르 하나를 돌아가며 닦았다. 한 사람이 사흘, 다음 사람이 또 사흘. 칼날의 흙빛은 닦을수록 옅어지다 어느 선에서 더는 지워지지 않았고, 그들은 딱 그 선까지만 닦은 뒤 칼을 다음 사람 손에 쥐여 주었다.',
    art: `curved cavalry saber, slender single-edged blade, brass knuckle-guard, faded ribbon on hilt, heroic, ${STYLE}`,
  },
  {
    key: 'marsh_hook_sickle',
    slot: 'weapon',
    nameKo: '늪 갈고리 낫',
    region: '늪지대',
    tone: '기괴',
    lore: '늪 출입 장부. 「드는 사람 이름 / 든 시각 / 나온 시각」 칸이 줄줄이 채워져 있다. 거의 다 같은 날 안에 나온 시각이 적혀 있다. 한 줄만 다르다. 「뱀장어잡이. 갈고리 낫 지참. 든 시각 새벽. 나온 시각 — 빈칸.」 그 아래로는 그 사람 이름이 다시 나오지 않는다. 낫은 그가 들어간 진흙 구멍 자리에 박힌 채 발견됐고, 누가 뽑아 장부 보관함 옆에 세워 두었다. 장부는 지금도 쓰이는데, 그 빈칸 한 줄만은 누구도 채우거나 지우지 않고 그대로 둔다.',
    art: `hooked sickle, curved barbed iron hook, mud-caked short handle, frayed pull-cord, eerie swamp, ${STYLE}`,
  },
  {
    key: 'orc_horn_club',
    slot: 'weapon',
    nameKo: '오크 뿔나팔 곤봉',
    region: '오크 부락',
    tone: '일상',
    lore: '부락 어귀에 걸린 하루 알림판. 「첫닭 — 곤봉 한 번: 교대. 해 오를 때 — 곤봉 두 번: 천막 점검. 한낮 — 알림 없음. 해 질 때 — 곤봉 한 번: 교대. 밤 — 곤봉 자루로 헐거운 말뚝 박기.」 알림판 맨 밑에 작게: 「곤봉 부는 것보다 박는 게 먼저. 헷갈리면 박아라.」 신호병이 셋 바뀌는 동안 알림판은 같은 자리에 같은 글로 걸려 있었고, 곤봉도 그 옆 못에 같은 자리로 걸렸다. 부락의 하루는 그 판 그대로 굴러간다.',
    art: `crude wooden club, horn trumpet lashed to the head, stake-driving wear, leather wrap, mundane, ${STYLE}`,
  },
  {
    key: 'rune_split_longsword',
    slot: 'weapon',
    nameKo: '룬으로 갈라진 장검',
    region: '고대 룬 산맥',
    tone: '기괴',
    lore: '유리·거울 다듬는 장인에게 들어온 일감 메모. 「의뢰: 장검 날 한가운데 갈라진 틈을 메워 달라.」 장인 답: 「못 함. 그 틈은 유리도 쇠도 아닌 것이 물려 있어, 메우려 손대면 들여다보는 쪽이 먼저 빨려 들어간다. 시험 삼아 한 번 봤다가 하루를 멍하니 보냈다. 두 번은 안 본다. 의뢰 반려.」 메모 끝에 한 줄 더: 「가져온 사람에게도 그 틈은 벽 쪽으로 두라 일러 보냄.」 장검은 결국 그 집 벽에, 정말 틈이 벽을 향하게 세워졌다.',
    art: `long straight longsword, deep crack splitting the blade lengthwise, unnaturally deep gap, stone-grey temper, eerie, ${STYLE}`,
  },
  {
    key: 'widow_estoc',
    slot: 'weapon',
    nameKo: '미망인의 에스톡',
    region: '자유',
    tone: '비애',
    lore: '결투 입회를 섰던 자의 비망록 한 쪽. 「오늘, 남편 잃은 여인의 결투에 입회. 그 가는 검을 들고 나왔다. 결과를 적어야 하는데 손이 안 나간다. 이긴 것도 진 것도 아닌 결투를 나는 처음 봤다. 검집 안쪽에 칼끝으로 눌러 쓴 글이 있었다 — 이번이 마지막. 결투를 말한 건지 다른 걸 말한 건지 나는 모른다.」 비망록은 거기서 한 장이 비고, 다음 장은 아무 일 없던 듯 다른 결투 기록으로 이어진다. 검은 한참 뒤 고물 궤짝에서 그 비망록과 함께 나왔다.',
    art: `long rigid estoc, narrow needle-like thrusting blade, plain dark hilt, worn engraved scabbard motif, mournful, ${STYLE}`,
  },
  {
    key: 'ember_falx',
    slot: 'weapon',
    nameKo: '잉걸 팔크스',
    region: '서쪽 화산',
    tone: '수수께끼',
    lore: '주물간에 남은 거푸집 도면 한 장. 칼 모양 골이 그려져 있고, 치수와 쇳물 양이 또박또박 적혀 있다. 그런데 도면 한쪽 귀퉁이에 글씨가 다른 물음이 적혀 있다. 「이 골은 누가 팠는가? 용암이 식으며 저절로 패였다는데, 하필 칼 모양으로?」 그 아래 답은 없고, 줄만 길게 그어져 있다. 이 칼을 쥔 사람들은 하나같이 비슷한 말을 한다. 내가 휘두른 게 아니라 칼이 안쪽으로 뭔가를 끌어당기는 것 같았다고. 도면은 지금 그 주물간 못에 핀으로 박혀, 칼보다 더 자주 들여다보는 물건이 되었다.',
    art: `inward-curved falx blade, single hooked edge, fire-grained dark steel, gaze-pulling curve, mysterious, ${STYLE}`,
  },
  {
    key: 'ledger_quarterstaff',
    slot: 'weapon',
    nameKo: '장부 지팡이',
    region: '자유',
    tone: '일상',
    lore: '세금 장부 맨 끝 결산 면. 숫자가 줄줄이 맞아떨어진 아래, 다른 글씨로 한 줄. 「봉 1자루 — 값 없음. 적을 칸이 없어 여기 적음. 서기가 평생 짚고 다님. 이 봉을 장부 위에 탁 올린 해에는 셈이 한 푼도 안 틀렸다는 말이 있으나 장부에 근거는 없음.」 결산 도장은 그 줄을 비켜 찍혀 있다. 서기가 일을 놓은 뒤 장부는 새것으로 바뀌었지만, 누가 새 장부 같은 자리에도 같은 줄을 베껴 적어 두었다. 봉은 관아 벽 그 자리에 그대로 기대어 있다.',
    art: `plain ash quarterstaff, ink-stained one end, dog-chasing scuffs, smooth worn middle grip, mundane, ${STYLE}`,
  },
  {
    key: 'feather_kris',
    slot: 'weapon',
    nameKo: '깃 흘린 크리스',
    region: '타락천사',
    tone: '수수께끼',
    lore: '재고 실사 보고. 「품목: 단검에서 떨어진 검은 깃. 보관: 작은 상자. 1차 셈 100. 3차 셈 97. 5차 셈 102.」 비고: 「넣은 사람도, 뺀 사람도, 손댄 사람도 없음. 상자 봉인 그대로. 셈이 매번 어긋나 실사 종결 못 함.」 담당은 결국 상자를 봉한 채 창고 맨 안쪽으로 옮기고, 보고서에 「실사 보류 — 셀수록 어긋남」이라 적었다. 단검은 그 상자 위에 함께 두었는데, 칼집은 지금도 열 때마다 깃을 딱 한 올씩, 늘 한 올만 떨군다.',
    art: `wavy-bladed kris dagger, rippling pattern-welded steel, dark bound handle, single black feather, mysterious, ${STYLE}`,
  },
  {
    key: 'mistwood_longbow',
    slot: 'weapon',
    nameKo: '안개숲 장궁',
    region: '자유',
    tone: '영웅담',
    lore: '안개숲에서 살아 돌아온 사람들의 이름을 새긴 공덕비가 마을 어귀에 섰다. 마흔에 가까운 이름이 줄줄이 새겨져 있는데, 정작 그 신호 화살을 쏘아 길을 알려 준 순찰자의 이름은 어디에도 없다. 비석을 세운 사람들이 그 이름을 몰랐던 것은 아니다. 다만 본인이 한사코 빼라 했고, 마을은 그 뜻을 거스르지 못해 맨 아래에 빈 줄 하나만 남겨 두었다. 안개 짙은 밤이면 누가 그 빈 줄 앞에 등을 하나 켜 두고 가는데, 누구인지는 매번 다르다.',
    art: `tall slender longbow, pale mist-grey wood, taut string, simple leather grip, vertical, heroic, ${STYLE}`,
  },
  {
    key: 'tunnel_war_pick',
    slot: 'weapon',
    nameKo: '갱도 전투곡괭이',
    region: '자유',
    tone: '일상',
    lore: '구조 기록. 첫날 — 갱도 무너짐. 안에 한 사람 갇힘. 빛도 소리도 끊김. 둘째 날 — 갱 입구에서 낮고 규칙적인 두드림 들림. 곡괭이로 벽을 치는 듯. 간격 일정함. 셋째 날 — 소리 따라 파 들어감. 같은 간격, 한 번도 안 끊김. 셋째 날 저물 무렵 — 그를 파냄. 손에 곡괭이 그대로 쥐고 있었음. 그 뒤로 마을에서 이걸 그냥 광산 연장이라 부르는 사람은 없어졌다. 정작 곡괭이는 그런 대접에 관심 없는 듯, 지금도 돌 깨는 데 제일 잘 든다. 구조 기록은 거기서 끝난다.',
    art: `heavy war pick, single curved spike head, blunt back, rock-scarred iron, sturdy wooden haft, utilitarian, ${STYLE}`,
  },
  {
    key: 'dream_answer_orb_staff',
    slot: 'weapon',
    nameKo: '꿈으로 답하는 구슬홀',
    region: '자유',
    tone: '수수께끼',
    lore: '해몽 봐 주는 노파가 일러 준 것. "이 구슬 홀을 머리맡에 두고 자면, 아침에 답 하나가 또렷이 떠올라 있어. 근데 그게 무슨 물음에 대한 답인지는 안 알려 줘. 그냥 답만 덩그러니 있는 거지. 어떤 사람은 며칠 뒤에 딱 그 답이 맞는 일을 만나. 어떤 사람은 평생 그런 일 안 만나고 답만 품고 늙고. …아니, 물음을 먼저 받고 싶다고? 그건 이 물건이 하는 일이 아니야. 여긴 답이 먼저 와. 물음은 한참 뒤에 오거나, 영영 안 오거나." 노파는 거기까지만 말하고 더 묻는 건 받지 않았다.',
    art: `tall staff, cloudy pale orb cradled at the head, twisted dark shaft, faint inner haze, mysterious, ${STYLE}`,
  },
  {
    key: 'bog_frog_trident',
    slot: 'weapon',
    nameKo: '늪 개구리 작살',
    region: '늪지대',
    tone: '위트',
    lore: '늪 마을엔 이런 얘기가 돈다더라. 개구리잡이 내기에서 제일 많이 잡은 애가 그날 대장이 되는데, 이 세 갈래 작살을 쥔 애만은 평생 한 마리도 못 잡았다더라. 작살은 늘 빗나가고 개구리는 늘 먼저 튀었다더라. 그런데도 그 애가 거의 매번 대장이었다더라. 다른 애들도 그게 이상한 줄은 알았다더라. 그래도 아무도 안 물었다더라 — 한 늙은이 말로는, 그걸 입 밖에 내는 순간 놀이가 통째로 재미없어지는 걸 애들이 본능으로 알았기 때문이라더라. 진짜인지는 그 늙은이도 모른다더라.',
    art: `three-pronged fishing trident, long worn wooden shaft, simple iron tines, marsh wear, playful, ${STYLE}`,
  },
  {
    key: 'jester_morningstar',
    slot: 'weapon',
    nameKo: '광대의 별곤봉',
    region: '자유',
    tone: '위트',
    lore: '"이거? 소품이오, 소품. 웃기려고 들고 다니지. 보쇼, 어깨에 척 걸치고 뒤뚱뒤뚱." …관객이 웃는다. "가시가 왜 진짜냐고? 하하, 그래야 더 웃기지. 휘두른 적은 없소. 한 번도. 진짜요." 그가 며칠 묵은 마을마다 술집 시비랑 골목 다툼이 줄었다는 말이 따라다녔지만, 물으면 그는 늘 딴청을 부렸다. 다만 소품치고 가시 끝이 너무 반들반들 닳아 있었다는 것만큼은, 본 사람들이 굳이 한마디씩 보탰다.',
    art: `spiked ball morningstar on a short haft, jingling tiny bells on the chain, worn grip, ironic playful menace, ${STYLE}`,
  },
  {
    key: 'ashen_nodachi',
    slot: 'weapon',
    nameKo: '잿빛 노다치',
    region: '서쪽 화산',
    tone: '장엄',
    lore: '시연을 구경한 사람이 전한 말. "키보다 긴 칼이라 처음엔 들지도 못할 줄 알았소. 화산 갈라진 틈에 며칠 누여 식혔다더군. 그래서 잿빛 물결무늬가 날 전체에 번진 거고. 한 번 휘두르는데, 그게 어찌나 무거운지 숨 한 번에 딱 한 번. 근데 그 한 번 보고 나니 두 번째가 왜 필요한가 싶더이다. 다들 같은 표정으로 입을 다물었소. 두 번 휘두르라 청하는 건 그 칼한테 좀 무례한 짓 같았다고나 할까." 구경꾼은 거기서 잔을 비웠다.',
    art: `very long two-handed nodachi, slender heat-rippled ash-grey blade, long wrapped grip, sweeping imposing, ${STYLE}`,
  },
  {
    key: 'unsent_letter_dagger',
    slot: 'weapon',
    nameKo: '부치지 못한 편지칼',
    region: '자유',
    tone: '비애',
    lore: '유품을 정리하던 사람이 적어 둔 메모가 남아 있다. "맨 아래 서랍. 편지칼 하나, 봉투 하나. 봉투엔 받는 사람 이름이 또박또박 적혀 있음. 안의 종이는 펼쳐 봐도 백지. 앞뒤 다 봤지만 정말 아무것도 없음. 쓰려다 만 건지, 썼다 지운 건지 알 수 없음. 칼은 봉투 입만 가르던 물건이라 날도 무디다. 그런데 들어 보면 이상하게 묵직함 — 무게를 재 봤는데 보통 편지칼과 다르지 않음. 기분 탓인 듯. 일단 둘을 같이 둠. 따로 떼지 말 것." 그 메모를 쓴 사람도 그 뒤로는 별말을 보태지 않았다.',
    art: `slim letter-opener dagger, thin polished blade, simple bone handle, desk-drawer patina, melancholic, ${STYLE}`,
  },
  {
    key: 'rune_echo_maul',
    slot: 'weapon',
    nameKo: '룬 메아리 큰망치',
    region: '고대 룬 산맥',
    tone: '수수께끼',
    lore: '한 노래 수집가가 적다 만 쪽지. "큰망치 머리에 귀를 대면 낮은 음 하나가 멈추질 않는다. 받아 적으려 했다. 첫 소절: 받아 적음. 둘째 소절: 받아 적는 사이 첫 소절을 잊었다. 다시 들음. 아까와 다른 가락 같다. 이상한 건, 따로 들은 사람들이 흥얼대는 게 다 같은 가락이라는 점이다. 가사는 없다. 배운 데를 댄 사람도 없다. 산 무너지기 전부터 있던 노래라는 노인도 그건 어디서 들었는지 못 댔다. — 채보 포기."',
    art: `heavy stone-headed maul, faint resonant hum lines etched in the rock, banded haft, enigmatic ancient, ${STYLE}`,
  },
  {
    key: 'orc_junk_flail',
    slot: 'weapon',
    nameKo: '오크 잡동사니 도리깨',
    region: '오크 부락',
    tone: '영웅담',
    lore: '"…그래서 그 막내가, 다른 무기 다 잃고 이 잡동사니 도리깨 하나로 어귀를 막았다 이 말이지." (옆에서: 진짜냐?) "끝까지 버텼대두. 냄비 문고리 부딪는 소리가 그날은 물러서지 말라는 북소리로 들렸다더라." (그건 좀 부풀린 거 아니냐?) "부풀리긴. 살아 온 사람들이 다 그 소리 얘길 한다니까. 그 뒤로 아무도 이 도리깨 보고 안 웃어." (…나도 안 웃는다.) 부락에서 이 이야기는 늘 이런 식으로, 누가 토를 달면서 더 길어진다.',
    art: `chain flail, mismatched pot lid and door ring and half-helmet bound at the end, battle-clattered, heroic scrappy, ${STYLE}`,
  },
  {
    key: 'shepherd_sling',
    slot: 'weapon',
    nameKo: '목동의 무릿매',
    region: '자유',
    tone: '일상',
    lore: '"새 무기 자랑은 그만하고 이거나 봐라, 이 가죽 무릿매. 낡았지? 이걸로 짐승 정통으로 맞힌 날, 한 손에 꼽는다. 내 솜씨가 그저 그랬으니까. 근데 들어 봐라 — 돌이 휙 지나가는 소리만으로도 늑대 무리가 비탈 너머로 흩어지더라. 그 한 해, 양 한 마리 안 잃었다. 번쩍이는 새 활? 좋지. 근데 양을 지키는 게 무기 생김새냐, 아니면 늑대가 겁먹느냐다. …알아들었으면 그만 가 봐라." 늙은 양치기는 젊은이만 보면 이 얘기를 꺼낸다.',
    art: `simple leather sling, worn pouch, two braided cords, smooth river stone, humble pastoral, ${STYLE}`,
  },
  {
    key: 'scaled_guard_glaive',
    slot: 'weapon',
    nameKo: '비늘 막은 언월도',
    region: '서쪽 화산',
    tone: '영웅담',
    lore: '그 창병을 만나 이야기를 들으려 한 사람의 기록. "고룡 숨결에 강이 끓던 그 자리에서 끝까지 줄을 안 떠난 분이라 들었다. 어렵게 찾아가 물었다. 그날 어땠습니까. — 답이 없다. 무섭지 않았습니까. — 그는 대답 대신 이 언월도를 꺼내 천천히 닦기 시작했다. 날에 깊은 골이 셋, 자루엔 손이 눌어붙어 그을린 자국. 결국 한마디도 못 들었다. 그 흉터들이 그가 안 한 이야기를 대신 하고 있었다. 더 묻지 않고 일어섰다."',
    art: `polearm glaive, long curved blade with three deep scale-gouges, scorched grip, sturdy shaft, heroic, ${STYLE}`,
  },
  {
    key: 'crossroad_crook',
    slot: 'weapon',
    nameKo: '갈림길 지팡이',
    region: '자유',
    tone: '수수께끼',
    lore: '길 떠나는 이에게 — 이 굽은 지팡이를 가져가거든 알아 둘 것. 평지에서는 그냥 지팡이다. 짚고 다녀도 좋다. 단, 길이 둘로 갈리는 자리에 똑바로 세워 두지는 말 것. 굽은 끝이 한쪽을 가리키는데, 나중에 보면 늘 가지 말았어야 할 쪽이더라는 말이 있다. 시험해 본 사람들은 며칠 뒤 돌아왔고, 무엇을 봤는지는 아무도 말하지 않았다. 그러니 갈림길에서는 그냥 눕혀 둘 것. 길은 네 발로 고르는 게 낫다. — 먼저 다녀온 사람이.',
    art: `long shepherd's crook staff, hooked curved top, pale worn wood, plain banding, quietly uncanny, ${STYLE}`,
  },
  {
    key: 'last_gate_partisan',
    slot: 'weapon',
    nameKo: '마지막 문지기의 파르티잔',
    region: '자유',
    tone: '비애',
    lore: '〈이 자리에 세워 둔 표지〉 — 성문이 무너지던 밤, 한 늙은 위병이 여기서 끝까지 물러서지 않았다. 다른 이들은 명령대로 안으로 들었고, 그가 물러섰어도 누구도 탓하지 않았을 것이다. 그러나 그는 문턱을 한 발도 넘지 않았다. 날이 밝고 거둔 것은 그와 이 폭넓은 창뿐. 날 밑동에 칼끝으로 눌러 쓴 네 글자가 있었다. 이름도 부대명도 아닌, 「여기까지」. 그 글자를 지우지 않기로 했다. 창은 이 자리에 그대로 두고, 새 위병을 그 옆에 세운다.',
    art: `broad-bladed partisan polearm, wide leaf spearhead with side lugs, worn shaft, faint carved words, mournful, ${STYLE}`,
  },
  {
    key: 'dredge_bone_pick',
    slot: 'weapon',
    nameKo: '준설 뼈곡괭이',
    region: '자유',
    tone: '기괴',
    lore: '이웃들이 수군대는 말. "그 준설꾼 말이오, 어느 날 갈퀴에 길고 흰 게 진흙이랑 같이 딸려 올라왔다지." "그걸 안 버리고 곡괭이 자루에 박았다며." "무슨 뼈냐 물으면 한 번도 답을 안 하더라고. 늘 딴 얘기로 돌리고." "곡괭이는 잘만 든답디다, 돌 쪼는 데." "근데 그 양반, 그날 뒤로 그 강엔 발도 안 들이고 강 쪽으로는 집 창도 안 냈잖소." "…그러게 말이오." 거기까지 말하고 이웃들은 대개 입을 다물고 제 갈 길을 갔다.',
    art: `war pick, long pale bone spike as the head, riveted to a plain haft, river silt stains, unsettling, ${STYLE}`,
  },
  {
    key: 'carnival_chakram',
    slot: 'weapon',
    nameKo: '곡예단 차크람',
    region: '자유',
    tone: '위트',
    lore: '〈곡예단, 사람 구함〉 접시돌리기·고리던지기 할 줄 아는 분 환영. 둥근 고리날 다루는 자리 한 명 급함(전임자 사정으로 공석). 잠자리·끼니 제공, 마을마다 옮겨 다님. 무대용 소품이니 위험하지 않음 — 단장 보증. ※작은 글씨: 고리 가장자리는 만지지 말 것. 공연 끝나면 고리 수를 반드시 셀 것, 한 개 모자라면 단장에게 바로 알릴 것(따지지는 말 것). 떠난 마을 일은 묻지 말 것. 그래도 하실 분은 단장 천막으로.',
    art: `flat circular chakram throwing ring, sharpened outer edge, polished steel, small grip wrap, showy ironic, ${STYLE}`,
  },
  {
    key: 'oathline_halberd',
    slot: 'weapon',
    nameKo: '맹세 줄의 할버드',
    region: '자유',
    tone: '영웅담',
    lore: '추도하는 자리에서 누가 이렇게 말했다고 한다. "열두 사람이 어깨를 맞대 방벽을 세웠고, 그 한가운데 이 할버드가 박혀 있었습니다. 그들 약속은 단순했지요. 줄이 안 무너지는 한 이 한 자루도 안 쓰러뜨린다, 이 한 자루가 선 한 줄도 안 물러선다. 서로에게 기대는, 위태로운 맹세였습니다. 그 밤이 다 가도록 줄도 할버드도 끝내 서 있었습니다. 무엇이 무엇을 버티게 했는지… 그건 오늘 여기 모인 우리도 끝내 의견이 갈립니다." 거기서 그는 잔을 내려놓았고, 좌중은 한참 말이 없었다.',
    art: `tall halberd, axe blade with spike and hook, long banded shaft, frayed oath-cord tied below the head, heroic, ${STYLE}`,
  },
  {
    key: 'woodcutter_hatchet',
    slot: 'weapon',
    nameKo: '나무꾼 손도끼',
    region: '자유',
    tone: '담백',
    lore: '한 노인의 유품을 나눌 때 적힌 쪽지에 이런 줄이 있다. "부엌 손도끼 — 막내에게. 날은 너무 갈려 손바닥만 해졌고 자루는 세 번 갈았다. 전장에 나간 적도, 무얼 베어 이름을 남긴 적도 없는 물건이다. 적을 내력이 없으니 길게 안 적는다. 다만 이 도끼가 걸려 있던 동안 그 집 아궁이는 어떤 겨울에도 식은 적이 없었다." 막내가 그것을 받던 날, 늙은 아비는 날을 한 번 더 갈아 손에 쥐여 주고는 끝내 아무 말도 보태지 않았다.',
    art: `small one-handed hatchet, short worn axe head, oft-replaced wooden handle, woodchip nicks, plain, ${STYLE}`,
  },
  {
    key: 'fallen_censer_flail',
    slot: 'weapon',
    nameKo: '타락한 향로 도리깨',
    region: '타락천사',
    tone: '장엄',
    lore: '보관 담당에게 일러두는 다루는 법. 하나, 휘두르지 않아도 향이 천천히 오른다. 불을 댄 적 없으니 끄려 하지 말 것. 둘, 그 연기가 닿은 자리에서는 누구든 잠깐 까닭 없이 고개를 숙인다. 정신 들면 왜 숙였는지 본인도 모른다. 놀라지 말 것. 셋, 무엇 앞에 숙인 것이냐고 묻지 말 것. 향로는 답하지 않고 연기만 올린다. 넷, 이 물건에 대해 길게 캐묻는 사람이 오면 이 쪽지만 보여 줄 것. 그 이상은 담당도 모른다. 이상.',
    art: `chain flail with a great thurible censer at the end, fireless rising incense, tarnished gilt metal, solemn imposing, ${STYLE}`,
  },
  {
    key: 'nightwatch_spear',
    slot: 'weapon',
    nameKo: '야경꾼의 창',
    region: '자유',
    tone: '일상',
    lore: '야경 근무일지에서. "스무날째 밤. 동쪽 골목 이상 없음. 창은 초소 벽에 기대 둠. 졸았음, 솔직히." "스무하루째. 별일 없음. 창 안 겨눔." "스무이틀째. 한 사내가 골목 어귀에서 창 보고 돌아 나감. 따라가지 않음." 일지를 통틀어 창을 실제로 겨눈 밤은 손에 꼽고, 기대 두고 존 밤은 셀 수 없다. 그런데도 그 골목 사람들은 창이 어귀에 서 있다는 것만으로 문단속을 두 번 하지 않고 잤다. 막는 것보다 거기 있다고 믿게 하는 게 더 큰 일을 한 셈이다.',
    art: `plain watchman's spear, simple leaf-shaped head, long worn shaft, leaning-wear scuff, mundane reassuring, ${STYLE}`,
  },
  {
    key: 'rune_needle_rapier',
    slot: 'weapon',
    nameKo: '룬 바늘 레이피어',
    region: '고대 룬 산맥',
    tone: '비애',
    lore: '그 장인을 알던 이웃이 들려준 회상. "옆집 영감 말이오? 평생 똑같은 검만 만들었지. 바늘처럼 가는 찌르기검. 한 자루 끝낼 때마다 그러더이다, 이번 게 제일 낫다고. …그러다 어느 날 죽은 채로 발견됐는데, 마지막 한 자루를 가슴에 꼭 안고 있더란 말이오. 흠도 녹도 없는 검을. 손을 펴려 해도 안 펴져서, 그냥 쥔 채로 묻었소." 이웃은 거기서 한참 담배만 태우다, 그게 영감한테는 제일 나은 끝이었을지도 모른다고 짧게 덧붙였다.',
    art: `extremely slender rapier, needle-thin blade, faint hairline rune lines, fine swept guard, mournful, ${STYLE}`,
  },
  {
    key: 'grandfather_axe',
    slot: 'weapon',
    nameKo: '할아버지의 그 도끼',
    region: '자유',
    tone: '위트',
    lore: '"이게 우리 할아버지가 평생 쓰시던 도끼요." — 그러면 누가 꼭 짚는다. "날은 갈았수?" "두 번 갈았지." "자루는?" "세 번 갈았고." "…그럼 할아버지가 만진 쇠나 나무가 한 조각이라도 남았수?" 거기서 손자는 잠깐 입을 다물었다가, 똑같은 말을 처음부터 다시 한다. "이게 우리 할아버지가 평생 쓰시던 도끼요." 술자리에서 이 문답은 늘 같은 자리에서 막히고, 늘 같은 자리에서 손자가 우긴다. 우기는 쪽이 한 번도 진 적이 없다는 것만은, 마을이 인정한다.',
    art: `well-used one-handed axe, obviously newer head on a re-handled shaft, mismatched wear, homely ironic, ${STYLE}`,
  },
  {
    key: 'silt_anchor_flail',
    slot: 'weapon',
    nameKo: '진흙 닻 도리깨',
    region: '자유',
    tone: '기괴',
    lore: '〈나루터 알림〉 옛 사공이 쓰던 작은 닻 도리깨를 여기 걸어 둔다. 본래는 여울에서 배 떠내려가지 않게 잡던 닻이라, 무기보다 살림에 가깝다. 알아 둘 것 하나 — 어느 날 그 닻이 강바닥에서 뭔가를 함께 끌어 올린 뒤로, 사공은 말수가 줄고 노 젓는 자리를 강 건너로 옮겼다. 다시는 이 여울을 지나지 않았다. 닻은 마르지 않은 진흙을 아직 머금고 있어, 걸어만 둬도 가끔 마른 흙덩이가 저 혼자 툭 떨어진다. 주워서 그 강에 다시 들이지는 말 것.',
    art: `chain flail with a small rusted boat anchor as the head, dried river silt clumps, frayed chain, ominous, ${STYLE}`,
  },
  {
    key: 'herald_banner_poleaxe',
    slot: 'weapon',
    nameKo: '전령의 깃대 폴액스',
    region: '자유',
    tone: '영웅담',
    lore: '전사자 명부 비고란에 이렇게 적혀 있다. "전령. 본디 무기를 들지 않음. 깃발이 쓰러지면 그 깃을 보고 버티던 줄도 무너진다는 것을 알았던 듯. 들고 있던 깃대 끝에 도끼날을 박아 넣고, 소식을 전하는 대신 그 자리를 지킴. 그날 깃천은 화살과 바람에 누더기가 되었으나 깃대는 한 번도 기울지 않았음. 전하려던 마지막 소식의 내용 — 확인 불가, 끝내 닿지 않음. 비고란 더 적을 것 없음." 명부의 다음 줄은 다른 이름으로 이어진다.',
    art: `poleaxe with a banner-pole haft, axe head and top spike, tattered banner remnant near the top, heroic, ${STYLE}`,
  },
  {
    key: 'scorched_reaping_hook',
    slot: 'weapon',
    nameKo: '그을린 거둠낫',
    region: '자유',
    tone: '담백',
    lore: '농사 일지 한 귀퉁이. "불 지나간 밭. 타다 만 그루터기와 그을린 줄기 베어 걷어냄. 손낫 하나로 한 뼘씩. 누가 휘둘렀는지 굳이 안 적음 — 여럿이 번갈아 함." "이듬해 봄. 같은 밭. 푸르게 돋음. 기록해 둠." 그게 전부다. 이 낫에 거창한 사연은 없다. 무엇을 베어 이름을 남긴 적도 없다. 다만 검게 탄 자리를 묵묵히 한 뼘씩 정리한 자리가 다시 푸르렀다는 짧은 두 줄만, 일지에 남아 있다.',
    art: `one-handed reaping hook, short inward-curved blade, soot-darkened edge, plain wooden grip, understated, ${STYLE}`,
  },
  {
    key: 'lullaby_war_fan',
    slot: 'weapon',
    nameKo: '자장가 부르는 철선',
    region: '자유',
    tone: '수수께끼',
    lore: '한 옛것 모으는 이가 적다 만 글. "무쇠 부채. 부챗살마다 가는 날이 숨어 있음. 펴고 접을 때 쇠 스치는 소리 사이로 아주 옅은 가락이 샘. 늙은이들은 입을 모아 오래된 자장가라 하는데, 가사를 기억하는 사람이 없음. 받아 적으려 귀를 대고 있다가, 정신 차려 보니 내가 졸고 있었음. 다시 시도. 또 졺. 누가 이 노래를 차가운 쇠 안에 넣었는지 알 길 없음. 한 가지는 확실함 — 이 소리를 가까이서 듣고 끝까지 안 존 사람을, 나는 아직 못 봤음."',
    art: `folding iron war fan, hidden blade edges on the ribs, faint humming when opened, lacquered dark, mysterious, ${STYLE}`,
  },
  {
    key: 'deserter_shortsword',
    slot: 'weapon',
    nameKo: '탈영병의 단검',
    region: '자유',
    tone: '비애',
    lore: '그 검을 주운 사람이 적은 짧은 일기. "길섶 풀숲에서 멀쩡한 짧은 검 하나를 주웠다. 누가 던져 버린 모양이다. 멀쩡한 걸 버리려면 어지간한 결심이 아니고선 못 한다." "사흘째. 자루 끈 매듭이 반쯤 끊겨 있다. 누가 몹시 급하게 풀려다 만 것 같다." "닷새째. 그 끊긴 매듭을 자꾸 만지작거리게 된다." "이레째. 결국 내 손으로 마저 풀어 새로 묶었다. 던진 사람은 끝내 찾으러 오지 않았다." 일기는 거기서 멈춘다.',
    art: `plain short sword, blade half-buried look, grass-worn finish, hilt cord with a half-cut knot, sorrowful, ${STYLE}`,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// 방어구 (목표 50)
// ─────────────────────────────────────────────────────────────────────────────
const ARMOR: CatalogItem[] = [
  {
    key: 'militia_gambeson',
    slot: 'armor',
    nameKo: '민병대 누비갑옷',
    region: '자유',
    tone: '일상',
    lore: '마을 민병대가 한 벌을 여럿이 돌려 입던 두툼한 누비 상의다. 누가 입었느냐에 따라 품이 늘 어딘가 안 맞았고, 그래서 솔기를 풀었다 다시 박은 자국이 온 데 남았다. 봄 훈련 때 흘린 국물 자국, 가을걷이 끝나고 낀 짚 부스러기, 누군가 떨다 흘린 눈물 자국까지 솔기에 차곡차곡 배었다. 번쩍이는 갑옷도, 이름난 장인의 작품도 아니다. 다만 이 한 벌을 번갈아 껴입은 평범한 사람들이, 그 평범한 어깨로 마을을 몇 번이나 지켜냈다. 갑옷의 값어치는 이따금 그렇게, 입은 사람 쪽에서 매겨진다.',
    art: `quilted padded gambeson coat, faded patched cloth, stitched seams, worn collar, mundane, ${STYLE}`,
  },
  {
    key: 'marsh_reed_cuirass',
    slot: 'armor',
    nameKo: '늪 갈대 흉갑',
    region: '늪지대',
    tone: '담백',
    lore: '늪지대 어부들이 마른 갈대를 겹겹이 엮고 송진으로 굳혀 만든 가벼운 가슴받이다. 묘리랄 것은 단 하나, 물에 푹 젖어도 무거워지지 않게 결을 잡는 법뿐이다. 그 한 가지를 위해 마을의 늙은 어부들이 손주에게 엮는 법을 대를 이어 일러 주었다. 멋이라곤 없고, 가까이서 맡으면 늪 비린내가 제법 난다. 그러나 갑작스레 발이 빠져 가슴까지 잠겨 본 사람은 안다. 그 순간 몸을 끌어올려 주는 것은 번쩍이는 강철이 아니라, 가볍게 떠 주는 이 못난 갈대라는 것을.',
    art: `woven hardened reed cuirass, layered dried marsh reeds, simple cord ties, light, plain, ${STYLE}`,
  },
  {
    key: 'runefall_breastplate',
    slot: 'armor',
    nameKo: '룬 낙석 흉갑',
    region: '고대 룬 산맥',
    tone: '장엄',
    lore: '산이 스스로 일어서던 날, 비탈에서 굴러떨어진 바위판 하나를 사람 가슴 모양으로 끈질기게 깎아낸 흉갑이다. 깎는 동안에도 표면을 가로지른 푸른 룬 균열만은 끝내 메워지지 않아, 그대로 흉갑의 무늬가 되었다. 가벼움 따위는 처음부터 포기한 물건이다. 그러나 이것을 가슴에 두르고 두 발을 땅에 박은 자는, 어떤 충격에도 한 발짝을 밀리지 않는다. 입는다기보다 짊어진다는 말이 맞고, 짊어질 각오가 된 자만이 그 자리에 설 수 있다. 산이 한 사람 몫의 고집을 떼어 준 셈이다.',
    art: `heavy stone-slab breastplate, blue rune cracks across the chest, rough hewn edges, monumental, ${STYLE}`,
  },
  {
    key: 'orc_scrap_harness',
    slot: 'armor',
    nameKo: '오크 고철 갑주',
    region: '오크 부락',
    tone: '비애',
    lore: '돌아오지 못한 전사들의 갑옷에서, 그래도 가장 성한 한 조각씩만 떼어 가죽끈으로 한데 동여 만든 갑주다. 오크 부락에는 오래된 규칙이 하나 있다. 누군가 끝내 돌아오지 못하면, 부락의 가장 어린 전사가 그 사람의 갑옷에서 한 조각을 떼어 이 갑주에 덧댄다. 그렇게 해서 떠난 자를 다음 싸움에도 데려간다고 여겼다. 듣기엔 그럴듯하나, 실상은 이 갑주가 무거워질수록 부락의 빈자리도 꼭 그만큼 늘어 있었다는 뜻이다. 가장 두꺼운 갑옷이 가장 슬픈 갑옷이 되는 일은, 그 부락에서 드물지 않았다.',
    art: `patched scrap-metal harness, mismatched salvaged plates lashed with leather, dull worn, somber, ${STYLE}`,
  },
  {
    key: 'fallen_feather_mantle',
    slot: 'armor',
    nameKo: '깃털 두른 망토',
    region: '타락천사',
    tone: '비애',
    lore: '추락이 있던 자리에 검은 깃이 한겨울 눈처럼 두껍게 쌓였다. 어느 떠돌이가 그것을 그냥 지나치지 못하고 한 아름 주워, 솜씨도 변변치 않은 손으로 어깨망토를 엮었다. 깃을 다 엮고 나서도 그 사이로는 옅은 온기가 좀처럼 가시지 않았다. 이 망토를 두른 이들은 한결같이, 추운 날일수록 등 뒤에서 누군가 나직이 제 이름을 부르는 듯한 기분이 든다고 말한다. 그때마다 돌아보지만 거기엔 늘 아무도 없고, 바람도 없는데 깃만 한 번 천천히 눕는다. 무엇이 떨어진 자리인지 알고 나면, 그 부름이 더는 무섭지만은 않다고도 한다.',
    art: `shoulder mantle cloak, layered black feathers, faded gold-thread trim, pale grey sheen, draped, mournful, ${STYLE}`,
  },
  {
    key: 'ember_slag_cuirass',
    slot: 'armor',
    nameKo: '잉걸 슬래그 흉갑',
    region: '서쪽 화산',
    tone: '장엄',
    lore: '견습에게 남긴다. 이 흉갑 만드는 법이다. 식다 만 용암 슬래그를 골라 다시 녹여 가슴판으로 부어라. 표면에 흐르던 불자국이 저절로 굳어 무늬가 잡히는데, 손대 펴려 하지 마라 — 펴면 부러진다. 한 김만 식혀 두드리고, 다 식기를 기다리지 마라. 한 가지 더 적는다. 이건 한 번 데워지면 잘 안 식는다. 지난 눈보라에 길 잃은 보초가 가슴팍 온기 하나로 밤을 넘겼고, 같은 온기 탓에 그 옆 보초는 졸다 얼어 죽을 뻔했다. 따뜻함이 그만큼 양날이라는 것까지 알아야 한다. 나머지는 만들다 보면 손이 먼저 안다.',
    art: `forged volcanic slag cuirass, swirling fire-grained dark metal, heavy riveted plates, imposing, ${STYLE}`,
  },
  {
    key: 'nightwatch_cloak',
    slot: 'armor',
    nameKo: '야경꾼 망토',
    region: '자유',
    tone: '일상',
    lore: '도시 야경꾼이 비 오는 밤을 어떻게든 버티려고 두르던, 기름을 잔뜩 먹인 망토다. 정직하게 헤아리면, 이 망토가 칼이나 몽둥이를 막아 준 밤보다 빗줄기와 한기를 막아 준 밤이 천 배는 더 많다. 야경이라는 일이 본래 그렇다. 큰일은 어쩌다 한 번이고, 대부분은 그저 젖지 않고 깨어 있는 것이 전부다. 밑단은 늘 한 뼘쯤 축축하고, 천에서는 빨아도 등불 그을음 냄새가 가시지 않는다. 그 냄새를 맡으면 야경꾼들은 이상하게 마음이 놓였다고 한다. 누군가는 깨어 있다는 냄새였기 때문이다.',
    art: `oilcloth watch cloak, dark waxed fabric, frayed wet hem, soot-stained shoulders, mundane, ${STYLE}`,
  },
  {
    key: 'widow_veil_shroud',
    slot: 'armor',
    nameKo: '미망인의 면사 두름',
    region: '자유',
    tone: '비애',
    lore: '상복의 면사를 끝내 벗지 않은 채 전장 한가운데에 선 여인이 두르고 있던, 얇디얇은 천 갑옷이다. 천 두께로 무엇을 막겠다는 물건이 아니다. 실제로 그 얇은 천은 아무것도 막지 못했다. 다만 면사 너머로 흐릿하게 비치던 그 표정 앞에서, 칼을 들었던 자들이 하나같이 손을 멈췄다는 이야기가 두께 대신 남았다. 누구는 그것을 슬픔이라 했고, 누구는 그보다 더한 것이라 했다. 막아 준 것이 천이 아니라 그 앞에 선 사람의 마음이었다면, 이것을 갑옷이라 부르는 일이 과연 틀린 것인지는 쉽게 말하기 어렵다.',
    art: `thin layered veil-shroud over light armor, pale gauzy fabric, mourning grey, draped, sorrowful, ${STYLE}`,
  },
  {
    key: 'graverobber_coat',
    slot: 'armor',
    nameKo: '도굴꾼 외투',
    region: '자유',
    tone: '기괴',
    lore: '안주머니가 유난히 많아, 입으면 사람이 한 뼘쯤 두꺼워 보이는 긴 외투다. 무덤을 파던 도굴꾼이 늘 걸치고 다녔고, 어디에 무엇을 넣어 두었는지는 본인만 알았다. 그가 어느 무덤가에서 차게 식은 채 발견됐을 때, 사람들은 이상한 점을 하나 알아챘다. 외투에 그가 직접 꿰맸을 리 없는 주머니 몇 개가, 안쪽에 새로 늘어 있었던 것이다. 솔기는 분명 사람 손바느질이 아니었다. 그 주머니에 무엇이 들었느냐는 물음에는 답이 제각각이다. 비었다는 사람, 흙뿐이라는 사람, 그리고 끝내 입을 다무는 사람.',
    art: `long many-pocketed coat, dark worn leather, uneven extra-stitched pockets, grimy, unsettling, ${STYLE}`,
  },
  {
    key: 'hero_dented_breastplate',
    slot: 'armor',
    nameKo: '영웅의 찌그러진 흉갑',
    region: '자유',
    tone: '영웅담',
    lore: '심장 바로 위가 주먹이 들어갈 만큼 깊게 움푹 들어간 흉갑이다. 대장장이가 그 자국을 보고 고개를 저었다고 한다. 이만한 한 방이면 안의 사람은 끝났어야 옳다는 것이다. 그런데 끝나지 않았다. 그 사람은 그 한 방을 받고도 일어나 끝까지 싸웠고, 살아 돌아왔다. 사람들은 두고두고 그 이야기를 무용담으로 듣고 싶어 했지만, 정작 본인은 누가 물을 때마다 슬그머니 다른 이야기로 말머리를 돌렸다. 다만 흉갑을 새로 펴 주겠다는 제안만은 한사코 거절하고, 그 움푹한 자국을 평생 그대로 두었다. 그는 갑옷을 벗는 밤에도 늘 그 자국 위에 손바닥을 한 번 얹고서야 끈을 풀었다.',
    art: `steel breastplate with a deep dent over the heart, polished elsewhere, plain straps, heroic, ${STYLE}`,
  },
  {
    key: 'blank_question_helm',
    slot: 'armor',
    nameKo: '물음표 투구',
    region: '자유',
    tone: '수수께끼',
    lore: '눈구멍도, 숨구멍도, 이음매도 없는 한 덩이의 매끈한 투구다. 처음 보는 사람은 누구나 같은 질문을 한다. 이걸 쓰고 어떻게 앞을 보고, 어떻게 숨을 쉬느냐. 그런데 막상 써 본 자들은 하나같이, 평소보다 앞이 더 또렷하게 보였다고 말한다. 숨이 막혔다는 사람은 없다. 그럼 대체 무엇으로 보았느냐고 거듭 물으면, 그들은 잠깐 입을 다물고 허공을 본다. 그러고는 꼭, 전혀 상관없는 다른 이야기를 천천히 꺼내기 시작한다. 그 다른 이야기들 사이에 답이 숨어 있는지, 아니면 그것이 답을 피하는 방식인지조차 분명하지 않다.',
    art: `featureless smooth full helm, no visible eye-slit, polished blank surface, enigmatic, ${STYLE}`,
  },
  {
    key: 'bog_hide_jerkin',
    slot: 'armor',
    nameKo: '늪 가죽 저고리',
    region: '늪지대',
    tone: '영웅담',
    lore: '늪을 통째로 삼킨다는 그 크고 끈적한 것이, 어느 밤 한 정찰대를 통째로 진흙 속으로 끌고 들어갔다. 비명도 길지 않았다고 한다. 다음 날 동틀 무렵, 단 한 사람이 이 가죽 저고리만 걸친 채 진흙 밖으로 손톱이 다 빠지도록 기어 나왔다. 그는 무엇을 보았는지 끝내 말하지 않았고, 어떻게 살았느냐는 물음에는 그저 "운이 좋았다"고만 했다. 저고리에는 길고 깊은 할퀸 자국이 등 쪽에 나란히 나 있다. 그 운이라는 것이 정말 운이었는지, 늪 사람들은 그 뒤로 이 저고리를 누구에게도 가벼이 빌려주지 않는다.',
    art: `short beast-hide jerkin, supple dark leather, deep claw scars, simple lacing, swamp-tanned, heroic, ${STYLE}`,
  },
  {
    key: 'jester_patch_armor',
    slot: 'armor',
    nameKo: '광대 누더기 갑옷',
    region: '자유',
    tone: '위트',
    lore: '색이 안 맞는 천 조각을 일부러 우스꽝스럽게 덧대 기운 광대의 "갑옷"이다. 누가 봐도 공연용 소품이고, 광대 본인도 그렇게 소개하며 일부러 뒤뚱거렸다. 그런데 어느 날 늦은 술집에서 시비가 칼부림으로 번졌을 때, 그 누더기가 정말로 한 번, 들어오던 칼을 받아냈다. 광대도 놀라고 칼을 든 자도 놀랐다. 그 일 이후 광대는 전보다 한층 의기양양해져, 더 큰 소리로 떠들고 더 크게 넘어졌다. 갑옷은 그만큼 더 누더기가 되었지만, 이상하게도 사람들은 그 누더기를 더는 우습게만 보지 않게 되었다.',
    art: `patchwork cloth armor, clashing colorful patches, jingling trim, lopsided padding, comical, ${STYLE}`,
  },
  {
    key: 'rune_hush_helm',
    slot: 'armor',
    nameKo: '룬 침묵 투구',
    region: '고대 룬 산맥',
    tone: '수수께끼',
    lore: '겉은 평범한 쇠투구인데, 안쪽 면에만 산의 돌결을 본뜬 룬이 빼곡히 새겨진 투구다. 머리에 쓰는 순간, 바깥의 모든 소리—발소리, 외침, 쇠가 부딪는 소리—가 한 겹 천을 덧댄 듯 멀어진다. 그 자리를 대신 채우는 것은, 어디서 오는지 알 수 없는 아주 낮은 한 음이다. 처음엔 거슬리지만 차차 그 음에 기대게 된다고 한다. 다만 이 투구를 오래 쓴 자들은 하나같이 말수가 줄었다. 바깥의 말보다 그 한 음이 더 또렷해지면, 굳이 입을 열 이유를 점점 잊는 모양이다.',
    art: `closed helm with inner rune-etched lining, plain stone-grey exterior, muffled aura, mysterious, ${STYLE}`,
  },
  {
    key: 'orc_skull_cap',
    slot: 'armor',
    nameKo: '오크 두개 투구',
    region: '오크 부락',
    tone: '기괴',
    lore: '아주, 사람 머리로는 가늠이 안 될 만큼 큰 무언가의 두개골을 깎고 다듬어 만든 투구다. 오크 부락은 전리품 자랑이라면 빠지지 않는데, 유독 이것이 무엇의 머리였는지에 대해서만은 입을 무겁게 닫는다. 캐물으면 화제를 돌리거나, 자리를 뜬다. 정작 쓰기에도 영 불편하다. 누구의 머리에 얹어도 한 치쯤 헐거워, 그 빈틈으로 가끔 바람이 들고 난다. 그 바람 소리가 어떤 밤에는 꼭 낮게 으르렁대는 것처럼 들린다고, 보초를 선 자들이 마지못해 털어놓곤 한다.',
    art: `helmet carved from a large pale skull, hollow eye-cavities patched, bone-grey, eerie, ${STYLE}`,
  },
  {
    key: 'pilgrim_travel_robe',
    slot: 'armor',
    nameKo: '순례자 여행복',
    region: '자유',
    tone: '일상',
    lore: '밑단이 길의 흙먼지로 늘 거뭇하게 절어 있는 순례자의 겉옷이다. 이 옷은 어지간한 군대보다 더 먼 거리를 걸었다. 그러나 그 먼 길에서 단 한 번도 누구를 벤 적도, 누구에게 들이댄 적도 없다. 순례자는 옷이 헤질 때마다 그 자리에 들른 마을에서 얻은 천을 덧대 기웠다. 그래서 이 옷에는 색도 결도 제각각인 천 조각이 층층이 붙어, 펼쳐 보면 그 자체로 그가 지나온 마을의 수만큼 무늬가 늘어선 지도가 된다. 어느 조각이 어느 마을이었는지는 순례자만 알았고, 그는 그것을 끝내 누구에게도 일러 주지 않았다.',
    art: `long traveler's robe, dust-darkened hem, mismatched cloth patches, rope belt, mundane, ${STYLE}`,
  },
  {
    key: 'ash_evac_veil',
    slot: 'armor',
    nameKo: '잿빛 피난 면포',
    region: '서쪽 화산',
    tone: '비애',
    lore: '서쪽 화산이 깨어나 마을을 통째로 비우던 날, 사람들이 입과 코를 막고 어깨를 덮은 채 잿더미를 헤쳐 빠져나오며 둘렀던 천이다. 같은 천을 두르고 떠난 사람들의 행렬은 길었다. 그 행렬에서 누군가는 무거워진 천을 길에 벗어 두고 갔고, 누군가는 손이 데어 가면서도 끝내 놓지 않았다. 무엇이 그 둘을 갈랐는지는 천도 모른다. 빨고 또 빨아도 천에 밴 잿내만은 끝내 빠지지 않아, 이것을 두른 사람은 바람이 불 때마다 그날의 공기를 한 번씩 다시 들이쉰다.',
    art: `scorched cloth veil-wrap over shoulders, ash-grey fabric, singed edges, draped, mournful, ${STYLE}`,
  },
  {
    key: 'unbroken_line_tabard',
    slot: 'armor',
    nameKo: '무너지지 않은 일선 휘장',
    region: '자유',
    tone: '영웅담',
    lore: '한 줄로 빈틈없이 늘어선 방패병들이 저마다 가슴에 두르던 휘장이다. 같은 문장을 가슴에 단다는 것은, 옆 사람이 무너지면 내 휘장도 한낱 헝겊이 된다는 뜻이기도 했다. 그것이 그들 사이의 말없는 약속이었다. 그날의 줄은 사람을 여럿 잃으면서도 끝내 끊기지 않았고, 마지막까지 한 사람도 등을 보이지 않았다. 살아남은 자가 거둔 휘장은 천 끝이 누더기처럼 다 해져 있었지만, 한가운데 문장만은 이상하리만치 또렷했다. 천을 닳게 한 것과 문장을 지킨 것이 같은 힘이었음을, 거둔 손은 알았다.',
    art: `surcoat tabard over mail, frayed but legible heraldic emblem, battle-worn cloth, heroic, ${STYLE}`,
  },
  {
    key: 'bark_woven_armor',
    slot: 'armor',
    nameKo: '나무껍질 엮음갑',
    region: '자유',
    tone: '담백',
    lore: '숲을 지키며 사는 사람들이, 늙은 나무에서만 벗겨낸 두꺼운 껍질을 비늘처럼 엮어 만든 몸통갑이다. 가까이 가면 송진 냄새가 코를 찌르고, 비를 흠뻑 맞으면 껍질이 물을 머금어 잠깐 더 단단해진다. 강철 갑옷에 견줄 물건은 못 된다. 그런데도 숲에서는 이것을 두른 사람을 누구도 함부로 건드리지 않았다. 그 옷을 입었다는 것은 곧 이 숲을 제 몸처럼 안다는 표였고, 숲에서 길을 아는 자를 적으로 두는 일이 얼마나 어리석은지 다들 알았기 때문이다. 갑옷이 지켜 주는 것은 때로 몸이 아니라 평판이다.',
    art: `woven bark body armor, layered tree-bark scales, resin sheen, cord lacing, plain forest, ${STYLE}`,
  },
  {
    key: 'fallen_choir_robe',
    slot: 'armor',
    nameKo: '타락한 성가복',
    region: '타락천사',
    tone: '담백',
    lore: '추락한 자리에서 거둔 긴 성가복이다. 본래 어떤 자리에서 입던 옷인지 아는 사람은 이제 남아 있지 않다. 천이 두껍고 안쪽에 솜을 덧대 겨울을 나기에 그만이라, 사연을 모르는 이들은 그저 두툼한 겉옷으로 걸친다. 깊은 두건은 목덜미로 드는 바람을 잘 막고, 밑단이 길어 주저앉아 쉴 때 무릎까지 덮인다. 거창한 내력을 기대하고 펼쳐 본 사람들은 처음엔 시시해했지만, 한 철을 입고 난 뒤로는 두말없이 계속 입었다.',
    art: `long thick choir robe with deep hood, faded trim, padded grey cloth, warm worn, plain, ${STYLE}`,
  },
  {
    key: 'tollgate_coat',
    slot: 'armor',
    nameKo: '통행세 외투',
    region: '자유',
    tone: '일상',
    lore: '다리 어귀에서 통행세를 걷던 문지기가 평생 한 벌로 버틴 두꺼운 외투다. 특이한 점은 오른쪽 주머니뿐이다. 오가는 이들에게 받은 동전을 하루에도 수백 번 넣었다 뺐다 하다 보니, 그 주머니만 안감이 닳아 비단처럼 반들거린다. 왼쪽 주머니는 아직 새것 같다. 이 외투가 칼이나 몽둥이 앞을 막아선 밤은 손에 꼽지만, 강바람과 진눈깨비를 막아 준 밤은 헤아릴 수 없다. 문지기가 떠난 뒤 누군가 그 외투를 물려 입었는데, 자기도 모르게 자꾸 오른쪽 주머니에만 손이 갔다고 한다. 옷에도 버릇이 밴다.',
    art: `heavy long coat, coin-worn shiny right pocket, plain dark wool, scuffed buttons, mundane, ${STYLE}`,
  },
  {
    key: 'dragon_scorch_shield',
    slot: 'armor',
    nameKo: '용 그을림 큰방패',
    region: '서쪽 화산',
    tone: '영웅담',
    lore: '한쪽 면이 고룡의 숨결을 정통으로 받아, 쇠가 유리처럼 매끈하게 흘러내린 채 굳은 탑 방패다. 그 숨결이 지나가는 동안, 방패병은 이것을 비스듬히 세우고 그 뒤에 몸을 최대한 작게 웅크렸다. 그는 살았다. 그뿐 아니라 그의 등 뒤로 줄지어 웅크린 사람들까지, 그 한 장의 그늘 안에서 함께 살았다. 녹아내린 면에 손바닥을 대면 아직도 그날의 열기가 어렴풋이 만져진다고들 하는데, 진짜인지 기억이 만든 온기인지는 댄 사람마다 다르게 말한다. 분명한 것은, 그 뜨거움을 한 면으로 다 받아낸 덕에 여러 사람이 다음 날을 봤다는 사실이다.',
    art: `large tower shield, one face melted glass-smooth by heat, scorched rim, sturdy back grip, heroic, ${STYLE}`,
  },
  {
    key: 'riddle_lamellar',
    slot: 'armor',
    nameKo: '수수께끼 찰갑',
    region: '자유',
    tone: '수수께끼',
    lore: '손톱만 한 쇳조각 수백 개를 가죽끈으로 엮어 만든 찰갑이다. 그런데 그 조각마다 한 글자씩이 새겨져 있어, 위에서 아래로 줄을 따라 읽으면 한 줄의 수수께끼가 된다. 갑옷이면서 동시에 풀어야 할 문장인 셈이다. 단, 맨 마지막 자리의 한 조각만은 글자 없이 비어 있다. 그 답을 안다고 큰소리치는 자는 술자리마다 있었지만, 정작 그 빈 조각에 글자를 새겨 끼워 넣은 사람은 아직 아무도 없다. 어떤 이는 답이 너무 뻔해서, 또 어떤 이는 답을 아는 순간 더는 입을 수 없게 될까 봐 비워 둔 거라고 했다. 둘 다 그럴듯하다.',
    art: `lamellar armor of small inscribed plates, one plate slot conspicuously empty, laced rows, enigmatic, ${STYLE}`,
  },
  {
    key: 'marsh_shell_carapace',
    slot: 'armor',
    nameKo: '늪 등딱지 갑',
    region: '늪지대',
    tone: '기괴',
    lore: '늪을 다니던 한 박물가가 적어 둔 대목이다. 가장 깊은 자리에서 사람 몸통만 한 등딱지를 떼어 왔는데, 어느 무리에 넣어야 할지 끝내 분류표에 칸을 잡지 못했다. 다 말렸다 여겼더니 며칠 뒤 손을 대자 안쪽이 또 축축했고, 닦으면 이튿날 도로 그랬다. 그는 그것을 마당 볕에 펴 두고 잠들었다가, 새벽에 등딱지가 처음 둔 자리에서 한 뼘쯤 옮겨 가 있는 것을 보고 그날로 짐을 쌌다. 박물가의 다음 기록은 다른 늪, 다른 표본으로 훌쩍 건너뛴다. 등딱지만 그 집 헛간 구석에 그대로 남아 있다.',
    art: `large shell carapace body armor, ridged chitinous plate, perpetually faintly damp inner side, murky green, eerie, ${STYLE}`,
  },
  {
    key: 'grandmother_quilt_vest',
    slot: 'armor',
    nameKo: '할머니의 누비 조끼',
    region: '자유',
    tone: '비애',
    lore: '한 할머니가 먼 길을 떠나는 손주를 위해, 등잔 심지가 다 닳도록 밤을 새워 한 땀 한 땀 누빈 솜조끼다. 안에 솜을 어찌나 두툼하게 넣었는지, 갑옷이라 부르기엔 누가 봐도 너무 포근하고 둥글다. 손주는 그것이 영 멋쩍어 처음엔 짐 바닥에 처박아 두었다. 그런데 그해 겨울, 어느 길목에서 날아든 화살 하나가 그 두꺼운 솜 어딘가에 박혀 멈췄다는 이야기가, 그 집안에 떠들썩하지 않게, 그러나 끊기지도 않고 전해 내려온다. 할머니가 솜에 무엇을 함께 누벼 넣었는지는 아무도 모른다. 다들 그냥, 정성이라고만 말한다.',
    art: `thick quilted padded vest, hand-stitched patchwork, warm worn cloth, homely, bittersweet, ${STYLE}`,
  },
  {
    key: 'rune_anchor_greaves',
    slot: 'armor',
    nameKo: '룬 닻 정강이받이',
    region: '고대 룬 산맥',
    tone: '위트',
    lore: '산에서 캐낸 돌덩이를 통째로 깎아, 두 다리에 하나씩 채우게 만든 정강이받이다. 무게가 상식을 벗어난다. 이걸 차고 두 발을 디딘 자는, 어떤 거구가 어깨로 들이받아도 한 뼘을 밀리지 않는다. 거기까지는 좋다. 문제는 같은 이유로, 이걸 찬 자는 절대 빨리 달릴 수도, 급히 물러설 수도 없다는 점이다. 사정이 나빠져 슬그머니 후퇴를 시도한 자들의 결말은 부락의 농담거리로 한참 돌았는데, 하나같이 비슷하게 끝나서 더 우스웠다. 버틸 자리에 선 자에게는 더없는 물건이고, 도망칠 셈인 자에게는 더없는 형벌이다.',
    art: `absurdly heavy carved-stone greaves, blue rune seams, oversized footplates, comically immovable, ${STYLE}`,
  },
  {
    key: 'carnival_breastplate',
    slot: 'armor',
    nameKo: '곡예단 흉갑',
    region: '자유',
    tone: '위트',
    lore: '유랑 곡예단의 무대 위에서, 가장 화려한 배역이 입던 번쩍이는 흉갑이다. 멀리서 보면 금빛으로 눈부시고, 두드리면 일부러 요란한 소리가 나도록 만들어졌다. 관객은 그 허풍에 박수를 보냈다. 그런데 분장실에서 칠을 살짝 긁어 본 어린 단원이, 그 아래에서 깊고 오래된 칼자국 여러 개를 발견하고 말문이 막혔다. 단장은 늘 그렇듯 "전부 무대 연출"이라며 웃어넘겼지만, 연출용 흠집치고 그 자국들은 너무 깊고, 너무 정확한 자리에 나 있었다. 그 어린 단원은 그날 이후, 단장이 무대에 오르려 흉갑을 채우는 모습을 전과 같은 눈으로는 보지 못했다.',
    art: `gaudy painted stage breastplate, flaking bright paint, real dents underneath, theatrical ironic, ${STYLE}`,
  },
  {
    key: 'deserter_cloak',
    slot: 'armor',
    nameKo: '탈영병 망토',
    region: '자유',
    tone: '비애',
    lore: '왼쪽 가슴께의 부대 문장이 누군가의 손에 거칠게 뜯겨 나간 망토다. 천을 도려낸 것이 아니라 실을 하나하나 잡아 뜯었기에, 그 자리에는 문장의 윤곽이 실밥 자국으로 또렷이 음각처럼 남았다. 그래서 정작 문장을 떼어냈는데도, 거기 무엇이 있었는지는 보는 사람마다 단번에 알아본다. 떼어낸다고 사라지지 않는 표식이 있다는 것을, 떼어낸 손은 몰랐을 리 없다. 그 문장이 어느 부대였는지, 왜 떠나야 했는지는 망토도, 망토를 두르고 사라진 그 주인도 끝끝내 한마디 하지 않았다. 그 실밥 윤곽은 해가 비스듬히 들 때마다, 떼어낸 적 없다는 듯 도리어 더 또렷이 살아났다.',
    art: `worn travel cloak, torn-off insignia patch leaving a clear thread outline, faded fabric, sorrowful, ${STYLE}`,
  },
  {
    key: 'hide_rain_cowl',
    slot: 'armor',
    nameKo: '가죽 비두건',
    region: '자유',
    tone: '담백',
    lore: '사냥꾼들이 비 오는 날 머리에 푹 뒤집어쓰던, 더없이 단순한 가죽 두건이다. 장식도 문장도, 위엄이라 할 만한 것도 한 점 없다. 만든 사람조차 멋을 낼 생각이 처음부터 없었던 게 분명하다. 이 두건이 하는 일은 딱 하나, 종일 비를 맞고 다녀도 목덜미 한 군데만은 마른 채로 지켜 주는 것이다. 사냥꾼에게는 그 한 가지가 전부였다. 목덜미가 젖으면 그날 사냥은 끝이고, 자칫 다음 사냥도 못 나가기 때문이다. 쓸모란 결국, 누군가에게 꼭 필요한 그 한 가지를 군말 없이 해내는 일이다.',
    art: `plain leather hood cowl, water-darkened edges, simple shoulder cape, drab, understated, ${STYLE}`,
  },
  {
    key: 'fallen_halo_circlet',
    slot: 'armor',
    nameKo: '떨군 후광 고리',
    region: '타락천사',
    tone: '위트',
    lore: '한때는 둥글고 환했다는 얇은 머리 고리. 지금은 한쪽이 푹 눌려, 누가 봐도 더는 후광이라 우기기 어려운 모양새다. 그런데 이걸 쓴 자들은 하나같이 한사코 "원래 이런 모양이다, 요즘은 이게 양식"이라 주장한다. 어찌나 진지하게 말하는지 듣는 쪽이 도리어 머쓱해진다. 아무도 그 말을 믿지 않지만, 정색하고 반박하는 사람도 없다. 덕분에 고리는 찌그러진 채로 여전히 누군가의 머리 위에서 당당하다. 그 우스꽝스러운 당당함을 보고 웃던 사람들도, 자리를 뜰 즈음이면 어느새 제 굽은 어깨를 한 번씩 슬쩍 펴 보곤 했다.',
    art: `thin bent metal circlet, conspicuously dented out of round, dull tarnished gold, worn proudly, ironic, ${STYLE}`,
  },
  {
    key: 'orc_wardrum_rig',
    slot: 'armor',
    nameKo: '오크 전고 멜빵갑',
    region: '오크 부락',
    tone: '장엄',
    lore: '등판에 커다란 전쟁북을 통째로 묶어 멘 갑주다. 이 북이 한 번 울리기 시작하면, 흩어져 싸우던 오크 부락 전체가 거짓말처럼 그 박자에 맞춰 한 덩어리로 움직인다. 그래서 이것을 멘 자에게는 무거운 규칙이 따른다. 가장 먼저 적 앞에 나서야 하고, 가장 늦게 등을 돌려야 한다. 박자가 곧 줄의 목숨이기 때문이다. 그 한 박자가 끊기지 않는 한 어떤 줄도 무너지지 않는다는 것을, 부락은 오래 믿어 왔다. 북을 진 자가 쓰러지는 순간 박자가 멎고, 그 침묵이 패배의 신호가 된다는 것도 함께 믿었다.',
    art: `harness armor with a great war drum on the back, broad leather straps, battle-worn drum, imposing, ${STYLE}`,
  },
  {
    key: 'forge_apron',
    slot: 'armor',
    nameKo: '대장간 가죽 앞치마',
    region: '서쪽 화산',
    tone: '일상',
    lore: '화산 대장간 한 대장장이가 평생을 두르고 모루 앞에 선, 두껍고 뻣뻣한 가죽 앞치마다. 셈해 보면 세상 어떤 방패보다 더 많은 불똥과 쇳가루를 이 한 장이 막아냈을 것이다. 그런데도 그 누구도, 심지어 대장장이 본인조차 이것을 방어구라 부른 적이 없다. 그저 일할 때 입는 옷일 뿐이었다. 그을음이 켜켜이 앉아 본래 색이 무엇이었는지는 이제 짐작도 안 되고, 가죽은 열에 익어 한 군데도 부드러운 데가 없다. 이름 없이 가장 많이 막아낸 것이 가장 덜 불리는 일은, 대장간 밖에서도 흔하다.',
    art: `heavy blacksmith leather apron, layered scorch marks, soot-blackened, simple neck strap, mundane, ${STYLE}`,
  },
  {
    key: 'oath_kite_shield',
    slot: 'armor',
    nameKo: '맹세의 연 방패',
    region: '자유',
    tone: '영웅담',
    lore: '같은 맹세를 나눈 자들이 어깨를 빈틈없이 잇대 세웠던 방패 줄, 그 줄의 한 자리를 책임지던 연 방패다. 겉면은 흔한 전투 흔적뿐이라 특별할 게 없다. 그러나 안쪽으로 돌려 보면, 함께 줄에 섰던 자들의 이름이 못 끝으로 한 글자씩 거칠게 긁혀 있다. 솜씨도 깊이도 제각각인 것은, 새긴 손이 한 사람이 아니었기 때문이다. 그중 몇 개는 글씨가 유난히 흐릿하고 조심스러운데, 줄이 풀린 뒤 살아남은 자가 떠난 이의 이름을 뒤늦게 더해 넣은 것이다. 방패가 막아 준 것은 칼이었고, 방패가 끝내 지킨 것은 그 안쪽의 이름들이었다.',
    art: `kite shield, weathered front, names roughly scratched on the inner face, leather arm straps, heroic, ${STYLE}`,
  },
  {
    key: 'hollow_visor_helm',
    slot: 'armor',
    nameKo: '빈 면갑 투구',
    region: '자유',
    tone: '기괴',
    lore: '면갑의 경첩이 멀쩡한데도, 좀처럼 올린 채로 가만히 있지 않는 투구다. 손으로 끝까지 젖혀 두어도, 한눈을 팔면 어느새 스르르 내려와 닫혀 있다. 그것만으로도 충분히 꺼림한데, 사람들을 진짜 불편하게 만드는 것은 따로 있다. 분명 아무도 쓰고 있지 않은데, 유난히 추운 날이면 닫힌 면갑의 좁은 틈으로 옅은 입김이 한 번씩 하얗게 서린다는 것이다. 닦으면 사라지고, 잊을 만하면 다시 생긴다. 그래서 이 투구를 가진 자들은 대개 그것을 잘 보이는 벽이 아니라, 뚜껑 닫히는 상자 안에 넣어 둔다. 보지 않으면 없는 셈 칠 수 있다고 믿으면서.',
    art: `closed visored helm, visor that won't stay raised, faint breath-fog at the slit, dark steel, unsettling, ${STYLE}`,
  },
  {
    key: 'traveler_patch_coat',
    slot: 'armor',
    nameKo: '여행자 기움 외투',
    region: '자유',
    tone: '일상',
    lore: '천 조각을 덧대 기운 외투라는 점은 흔하지만, 이 외투의 조각에는 규칙이 하나 있다. 모두, 길에서 신세 진 사람이 떼어 준 제 옷의 일부라는 것이다. 하룻밤 재워 준 노파의 앞치마 자락, 강을 건네준 사공의 소맷단, 이름도 못 물어본 누군가의 옷깃. 외투 주인은 빚을 갚는 대신 그 천 한 조각씩을 받아 기웠다. 그래서 이것은 어디를 지났는가가 아니라 누구에게 빚졌는가의 기록이다. 본인은 어느 조각이 누구인지 다 외운다 했고, 한 조각을 짚을 때마다 한 사람 이야기를 길게 풀었다. 외투가 닳을수록 그 이야기 목록은 길어졌다.',
    art: `long coat patched with cloth of many colors, uneven seams, well-worn, mundane, ${STYLE}`,
  },
  {
    key: 'marsh_root_buckler',
    slot: 'armor',
    nameKo: '늪 뿌리 손방패',
    region: '늪지대',
    tone: '비애',
    lore: '늪 바닥에서 캐낸 굵은 뿌리를 둥글게 엮어 만든, 못생기고 가벼운 작은 손방패다. 한 늙은이가 손주에게 늪을 무사히 다니는 법—어디를 디디고 어디를 피하는지—을 가르치며, 그 가르침의 마지막 선물로 직접 엮어 손에 쥐여 주었다. 손주는 그 가르침대로 자라, 마을에서 늪을 가장 잘 아는 사람이 되었다. 정작 그것을 가르친 노인은 어느 안개 짙은 날 늪에 들었다가 끝내 돌아오지 못했다. 방패는 그날 이후 늘 마른 채로 문가에 걸려 있다. 손주는 늪에 나갈 때 그것을 챙기지 않는다. 챙기면, 가르친 사람이 곁에 없다는 사실을 매번 손으로 확인하게 되기 때문이다.',
    art: `small round buckler of woven swamp roots, knotty surface, simple center grip, weathered, mournful, ${STYLE}`,
  },
  {
    key: 'wailing_mail',
    slot: 'armor',
    nameKo: '우는 사슬갑',
    region: '자유',
    tone: '기괴',
    lore: '고리가 닳고 군데군데 벌어진, 아주 오래된 사슬갑이다. 걸어 두기만 해도 바람이 한 줄기 지나가면 그 벌어진 틈 사이로 길고 가느다란 소리가 새어 나온다. 사람에 따라 그것을 다르게 들었다. 어떤 이는 그저 낡은 쇠를 지나는 바람 소리라며 대수롭지 않게 넘겼다. 또 어떤 이는 그 소리를 한 번 듣고는, 그날부터 두 번 다시 그 갑옷 가까이에서 잠들지 않았다. 흥미로운 것은, 그렇게 의견이 갈렸으면서도 두 부류 모두 그 사슬갑을 다시 몸에 걸치지는 않았다는 점이다. 설명할 수 없는 것 앞에서는, 믿는 자와 비웃는 자가 결국 같은 거리를 둔다.',
    art: `old chainmail hauberk, gapped rusted rings, thin whistling through the gaps, grey iron, eerie, ${STYLE}`,
  },
  {
    key: 'dusk_paladin_plate',
    slot: 'armor',
    nameKo: '해 저문 기사 판금',
    region: '자유',
    tone: '영웅담',
    lore: '성한 곳을 찾기가 더 어려운, 온통 찌그러진 전신 판금이다. 그 기사는 단 한 줄을 약속했다. 성문이 닫힐 때까지 이 자리를 비우지 않겠다. 그 약속이 떨어진 뒤로 그는 자리를 한 발도 옮기지 않았고, 해가 뉘엿해질 무렵 성문은 정말로 무겁게 닫혔다. 약속은 글자 그대로 지켜졌다. 사람들이 그를 안으로 들였을 때, 갑옷은 그 하루를 받아낸 충격을 그대로 머금은 채 그 모양으로 굳어 있었다. 대장장이가 펴 주겠다고 했으나, 기사도 사람들도 끝내 그 자국에 손대지 않았다. 갑옷은 성문 안쪽 벽에 그대로 세워졌고, 그 앞을 지나는 사람들은 약속이나 한 듯 한 박자씩 걸음을 늦췄다.',
    art: `full plate harness, many deep dents, dimmed steel, battered pauldrons, plain straps, heroic, ${STYLE}`,
  },
  {
    key: 'rune_echo_shield',
    slot: 'armor',
    nameKo: '룬 메아리 방패',
    region: '고대 룬 산맥',
    tone: '일상',
    lore: '겉면에 산의 돌 한 켜를 덧댄 둥근 방패다. 무게가 상당해 산사람들은 이걸 평소 등에 지고 다니는데, 비탈을 오르다 다리쉼을 할 참이면 바닥에 엎어 깔고 그 위에 털썩 앉는다. 신기한 것은, 그렇게 깔고 앉아 있으면 돌에서 아주 낮은 울림이 엉덩이께로 잔잔히 전해진다는 점이다. 산사람들은 그게 의자 삼기에 제법 듣기 좋다고, 별일 아니라는 듯 말한다. 그러다 보니 이 방패는 평생 무언가를 막아 준 횟수보다, 지친 사람을 쉬게 한 횟수가 압도적으로 많다. 늙은 산사람의 무릎이 성치 않을 무렵이면, 젊은이들이 굳이 말없이 그 방패부터 바닥에 내려 깔아 주었다.',
    art: `round stone-faced shield, blue seam cracks, banded rim, sit-worn back, mundane, ${STYLE}`,
  },
  {
    key: 'child_practice_shield',
    slot: 'armor',
    nameKo: '아이의 연습 방패',
    region: '자유',
    tone: '비애',
    lore: '방패 안쪽 가장자리에 칼끝으로 그은 금이 셋. 맨 아래 「일곱 살 봄」, 그 위 「여덟 살」, 또 그 위 「아홉 살, 한 뼘 더」. 키 잴 때 그어 두는 흔한 눈금이다. 그 위로 금은 없다. 다음 금이 와야 할 자리에는 깊은 칼자국이 어지럽게 겹쳐, 그 한 칸을 통째로 메우고 있다. 지금 그 방패는 같은 집 둘째가 가지고 있다. 둘째는 제 키가 「아홉 살, 한 뼘 더」 줄을 넘긴 봄, 그 위 칼자국 자리에 차마 새 금을 긋지 못하고 방패를 도로 벽에 걸었다. 그러고는 해마다 봄이면 그 줄에 등을 대 보기만 한다.',
    art: `small child-sized wooden practice shield, dense hack marks, scuffed paint, plain grip, sorrowful, ${STYLE}`,
  },
  {
    key: 'fools_brass_cuirass',
    slot: 'armor',
    nameKo: '바보 금 흉갑',
    region: '자유',
    tone: '위트',
    lore: '멀리서도 눈이 부실 만큼 번쩍이는 "황금" 흉갑이다. 다만 사실은, 잘 닦은 놋쇠다. 이 흉갑의 첫 주인은 평생 그것을 진짜 황금이라 굳게 믿었고, 그 믿음으로 늘 가슴을 펴고 다녔다. 사정을 아는 사람이 더러 있었지만, 누구도 굳이 그 사실을 일러 주지 않았다. 알려 줘서 좋을 게 없었기 때문이다. 더 우스운 것은, 그 놋쇠 흉갑이 정작 들어오는 칼은 금이든 놋쇠든 가리지 않고 꼬박꼬박 잘 막아 줬다는 점이다. 그러니 진실이 무엇인지는 끝까지 그다지 중요하지 않았다. 가끔은 잘못된 믿음이, 맞는 사실보다 사람을 더 똑바로 서게 한다.',
    art: `shiny brass cuirass mistaken for gold, bright polished finish, modest dents, ironic, ${STYLE}`,
  },
  {
    key: 'ash_pelt_mantle',
    slot: 'armor',
    nameKo: '잿더미 가죽망토',
    region: '서쪽 화산',
    tone: '담백',
    lore: '서쪽 화산 비탈에 사는, 추위에 유난히 강한 짐승의 가죽으로 만든 두툼한 어깨망토다. 화산 가까운 곳에서 살아온 짐승이라 그런지 가장자리가 본래부터 불에 살짝 그을린 듯 거뭇하고, 아무리 바람을 쐬어도 옅은 연기 냄새가 가시지 않는다. 사연을 캐자면 이쯤에서 끝이다. 더 보탤 신화도, 비밀도 없다. 이 망토에 바랄 수 있는 것은 단 하나, 따뜻하다는 것뿐이다. 그러나 눈보라 속에서 밤을 나 본 사람은 안다. 그 한 가지가 때로는 어떤 굉장한 내력보다 더 절실하다는 것을. 소박한 쓸모에는 굳이 이야기를 덧댈 필요가 없다.',
    art: `thick beast-pelt shoulder mantle, singed edges, smoky brown fur, simple clasp, plain warm, ${STYLE}`,
  },
  {
    key: 'unmarked_grave_plate',
    slot: 'armor',
    nameKo: '무명 무덤 판금',
    region: '자유',
    tone: '비애',
    lore: '비석도 이름도 없는 무덤에서 파낸 가슴판금이다. 흙을 털고 닦아 보니, 땅에 그만큼 누워 있었다는 게 믿기지 않을 만큼 흠도 녹도 한 점 없었다. 그런데 사람들을 더 오싹하게 한 것은 따로 있다. 덩치 큰 자가 입어도, 마른 자가 입어도, 이 판금은 어김없이 몸에 꼭 맞게 조여든다. 마치 입는 사람에 맞춰 누군가 매번 다시 두드려 준 것처럼. 원래 주인이 누구였는지, 왜 표식 없이 묻혔는지는 끝내 알 길이 없다. 다만 이것을 입어 본 자들은 한결같이, 잠깐 동안 자기가 아닌 다른 누군가의 자세로 서 있는 듯한 기분이 들었다고 했다.',
    art: `unearthed steel breastplate, soil-stained then cleaned, oddly flawless, plain fit, melancholic, ${STYLE}`,
  },
  {
    key: 'watchlantern_rig',
    slot: 'armor',
    nameKo: '야경 등 멜빵',
    region: '자유',
    tone: '일상',
    lore: '가슴 한복판에 등을 거는 쇠고리가 달린, 단순한 가죽 멜빵이다. 사실 이걸 방어구라 부르는 건 좀 민망하다. 막아 주는 면적이라곤 멜빵 폭이 전부고, 나머지는 그저 등을 거는 받침일 뿐이다. 그런데 야경꾼들은 새 갑옷을 받으면 으레 이 멜빵부터 챙겼다. 그들 사이에는 오래된 말이 있었다. "캄캄한 골목에서 사람을 살리는 건 두꺼운 쇠가 아니라, 멀리서도 보이는 한 점 불빛이다." 실제로 그 흔들리는 등불을 보고 발길을 돌린 자가, 그 멜빵이 막은 칼보다 훨씬 많았다. 가장 잘 지키는 방어구가 가장 단단한 것은 아니다.',
    art: `leather chest harness with a lantern hook, scuffed straps, soot near the hook, utilitarian mundane, ${STYLE}`,
  },
  {
    key: 'orc_trophy_pauldrons',
    slot: 'armor',
    nameKo: '오크 전리 어깨갑',
    region: '오크 부락',
    tone: '담백',
    lore: '오크 부락의 견갑이다. 그곳에는 한 가지 오랜 풍습이 있다. 싸움에서 무언가를 거두면 그것을 어깨에 매단다는 것. 부러진 칼끝, 적의 투구 장식, 짐승 송곳니 같은 것들이 끈에 줄줄이 늘어진다. 그러니 이 견갑은 곧 그 사람의 이력서이고, 어깨가 무거운 자일수록 더 많은 싸움을 지나온 자다. 깊은 뜻 같은 건 없다. 자랑하고 싶으면 매달면 되고, 무거우면 떼면 된다. 다만 부락에서는 스스로 떼어낸 자를 본 기억이 거의 없다. 사람은 제 어깨가 무거워지는 것을, 생각보다 그리 싫어하지 않는 모양이다.',
    art: `broad shoulder pauldrons hung with trophies, heavy iron plates, rugged, plain, ${STYLE}`,
  },
  {
    key: 'silent_choir_hood',
    slot: 'armor',
    nameKo: '침묵 성가 두건',
    region: '타락천사',
    tone: '영웅담',
    lore: '추락한 성가대가 사방으로 흩어지던 밤, 단 한 사람이 제자리를 뜨지 않고 노래를 이어 갔다. 이 깊은 두건을 쓰면 제 목소리만 한 겹 멀어져, 그는 끝내 자기 노래를 듣지 못한 채 불렀다. 들리지도 않는 노래를 마지막까지 부르는 일이 얼마나 외로운지는 그 사람만 알 것이다. 그러나 흩어지던 자들은 어둠 속에서 그 가느다란 가락을 등불 삼아 길을 찾아 나왔다. 그래서 이 두건을 깊이 쓴 자들은, 노래를 멈추는 법만은 좀처럼 먼저 배우지 못한다.',
    art: `deep cloth hood, faded sacred trim, pale grey, worn solemn, heroic, ${STYLE}`,
  },
  {
    key: 'bog_breath_mask',
    slot: 'armor',
    nameKo: '늪 숨 가리개',
    region: '늪지대',
    tone: '일상',
    lore: '마른 갈대 속을 촘촘히 채워 입과 코에 대도록 만든, 더없이 단순한 가리개다. 늪에는 눈에 보이지 않는 독한 김이 고이는 자리가 있어, 멋모르고 들어선 자는 픽 쓰러진다. 이 가리개를 쓰면 그 김을 한 겹 걸러, 빈손으로 돌아섰을 자리에서 한 뼘 더 깊이 들어갔다가 무사히 나올 수 있었다. 셈해 보면 늪에서 사람을 가장 많이 살린 물건은 어떤 두꺼운 흉갑도 아니고 이 초라한 갈대 가리개다. 그런데도 누구도 이걸 자랑삼아 보여 주지 않는다. 목숨을 가장 많이 구한 물건이 가장 볼품없는 일은, 늪 밖에서도 종종 그렇다.',
    art: `simple reed-filled breathing mask, woven straps, marsh-stained, crude practical, mundane, ${STYLE}`,
  },
  {
    key: 'herald_banner_cloak',
    slot: 'armor',
    nameKo: '전령 깃 망토',
    region: '자유',
    tone: '영웅담',
    lore: '그날 끝까지 땅에 닿지 않은 깃발이 하나 있었다. 싸움이 끝나고 줄이 풀린 뒤, 살아남은 자들은 그 깃발을 그냥 개어 두지 못했다. 그들은 천을 여러 조각으로 잘라, 한 사람이 한 조각씩 어깨망토로 나눠 둘렀다. 화살에 뚫리고 바람에 해진 천이라 조각마다 누더기지만, 펼쳐 맞대면 가운데 문장의 윤곽이 여전히 또렷이 이어진다. 전령은 본래 싸우지 않는다지만, 이 천만은 그날 누구보다 끝까지 그 자리에 서 있었다. 그래서 그것을 나눠 두른 자들은, 무거운 갑옷을 벗는 날에도 이 한 조각만은 좀처럼 내려놓지 못했다.',
    art: `shoulder cloak cut from a tattered war banner, faded heraldic emblem, ragged hem, heroic, ${STYLE}`,
  },
  {
    key: 'late_mirror_shield',
    slot: 'armor',
    nameKo: '묻는 거울 방패',
    region: '자유',
    tone: '수수께끼',
    lore: '거울처럼 한 점 흐림 없이 닦아낸 둥근 방패다. 정면으로 들면 제 얼굴이 또렷이 비친다. 다만 그 얼굴이 늘, 아주 미세하게 한 박자 늦게 따라 움직인다. 손을 들면 거울 속 손이 조금 뒤에 들리고, 눈을 감으면 거울 속 눈이 조금 뒤에 감긴다. 사람들이 진짜로 등골이 서늘해지는 순간은 따로 있다. 그 늦은 한 박자 동안, 거울 속 얼굴이 이쪽이 하지 않은 입 모양을 짓는 것처럼 보일 때다. 무슨 말을 하는지 읽어내려 입술에 눈을 박은 자가 여럿 있었지만, 끝내 알아들었다고 말한 사람은 아직 한 명도 없다. 거울이 늦는 것인지, 이쪽이 빠른 것인지조차 분명하지 않다.',
    art: `round polished mirror-bright shield, reflection lagging a beat, plain rim, eerie enigmatic, ${STYLE}`,
  },
  {
    key: 'worn_road_boots',
    slot: 'armor',
    nameKo: '닳은 길 장화',
    region: '자유',
    tone: '담백',
    lore: '주인을 셋이나 갈아 치우고도 여전히 멀쩡한 가죽 장화다. 첫 주인은 행상이었고, 둘째는 그 행상에게 이걸 받은 짐꾼이었으며, 셋째가 누구인지는 굳이 적혀 있지 않다. 밑창은 닳아 두 번 갈아 댔고, 발등 가죽은 수천 리 길에 길이 들 대로 들어 손바닥처럼 부드럽다. 거창한 사연은 한 줄도 없다. 전장에 나간 적도, 무엇을 막은 적도 없다. 이 장화가 한 일이라곤 그저, 신은 사람을 가고 싶은 곳까지 데려다 놓은 것뿐이다. 그리고 신어 보면 안다. 이 장화는 아직, 다음 사람을 어디로든 더 데려갈 셈인 듯 발에 꼭 감긴다.',
    art: `well-worn leather travel boots, twice-resoled, softened creased leather, plain, understated, ${STYLE}`,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// 장신구 (목표 50)
// ─────────────────────────────────────────────────────────────────────────────
const ACCESSORIES: CatalogItem[] = [
  {
    key: 'marsh_pebble_charm',
    slot: 'accessory',
    nameKo: '늪 조약돌 부적',
    region: '늪지대',
    tone: '담백',
    lore: '늪 마을에서는 아이가 처음 혼자 늪에 다녀오면, 가장 먼저 밟고 돌아온 마른 자리에서 조약돌 하나를 주워 끈에 꿴다. 그게 이 부적의 전부다. 무슨 영험이 있다는 말도, 액을 막는다는 말도 없다. 다만 그 돌을 목에 건 아이는 늪이 어디까지 제 발을 받아 주는지를 한 번 가늠해 본 아이라는 뜻이고, 마을은 그 한 가지만으로 그 아이를 조금 다르게 대했다. 부적의 무게는 돌이 아니라 그 첫걸음에 실린다. 그래서 늙은이들은 새 부적을 받은 아이의 목이 아니라, 그 아이가 늪을 바라보는 눈을 먼저 한 번 살폈다.',
    art: `small smooth river pebble on a worn cord, plain drilled hole, mud-faded, understated, ${STYLE}`,
  },
  {
    key: 'bog_tooth_pendant',
    slot: 'accessory',
    nameKo: '늪 이빨 펜던트',
    region: '늪지대',
    tone: '기괴',
    lore: '솔직히 이걸 왜 아직 차고 다니는지 나도 모르겠다. 늪에서 건졌을 땐 그냥 큼지막한 이빨이라 자랑삼아 보여 주고 다녔다. 그런데 비 길게 오는 철만 되면 이게 살갗에 닿는 데가 미지근하다. 데일 정도는 아니고, 안 그런 척하기엔 분명한 그런 미지근함이다. 무슨 이빨이냐 물으면 나도 모르니 "큰 고기"라 둘러댄다. 그 말 하는 게 해마다 조금씩 덜 웃긴다. 떼서 던져 버리면 그만인데 그게 또 잘 안 된다. 비 오는 철이면 그냥 옷깃 안쪽으로 슬쩍 돌려 차고, 그 얘기는 거기서 그만둔다.',
    art: `long curved tooth on a leather cord, faintly yellowed, swamp-stained binding, eerie, ${STYLE}`,
  },
  {
    key: 'frogcall_whistle',
    slot: 'accessory',
    nameKo: '개구리 호각',
    region: '늪지대',
    tone: '위트',
    lore: '늪 마을 한 노인이 심심풀이로 깎은, 불면 영락없이 개구리 울음소리가 나는 작은 호각이다. 본인은 이걸로 진짜 개구리들을 불러 모을 수 있다 큰소리쳤다. 마을 사람들은 콧방귀를 뀌었지만, 묘하게도 노인이 호각을 불면 늪 어귀가 한동안 유난히 시끄러워지긴 했다. 우연인지 솜씨인지는 끝내 가려지지 않았고, 노인은 그 점을 무척 즐겼다. 목에 걸고 다니면 사람들이 한 번씩 웃는데, 그거면 호각으로서는 충분한 성공이다.',
    art: `tiny carved wooden whistle on a cord, frog-shaped, well-handled patina, playful, ${STYLE}`,
  },
  {
    key: 'drowned_ring',
    slot: 'accessory',
    nameKo: '가라앉은 반지',
    region: '늪지대',
    tone: '비애',
    lore: '한 사람이 늪에 빠져 끝내 나오지 못한 자리에서, 한참 뒤 진흙을 긁다 올라온 반지다. 안쪽에는 둘이 나눠 새겼을 법한 짧은 글자의 절반만 남아 있다. 나머지 절반을 새긴 다른 반지가 어디 있는지는 아무도 모르고, 어쩌면 같은 진흙 속 더 깊은 곳에 있을지도 모른다. 이것을 건진 마을은 주인을 찾지 못해, 결국 늪이 가장 잔잔한 자리에 작은 돌 하나를 세워 두는 것으로 대신했다. 반지는 그 돌 곁에 오래 걸려 있었다.',
    art: `simple band ring, tarnished, half of an inscription inside, silt-darkened, mournful, ${STYLE}`,
  },
  {
    key: 'orc_brag_torc',
    slot: 'accessory',
    nameKo: '오크 자랑 토르크',
    region: '오크 부락',
    tone: '위트',
    lore: '오크 부락에서 가장 허풍이 센 전사가 두르던 굵은 목 고리다. 그는 토르크가 굵을수록 무용이 크다는 부락의 오랜 셈법을 곧이곧대로 믿어, 해마다 제 손으로 고리를 한 겹씩 더 둘렀다. 결국 마지막에는 고개를 옆으로 돌리기도 버거워졌고, 정작 그 무거운 고리 때문에 싸움에서 한 번도 제대로 뒤를 못 돌아봤다. 부락은 그를 가장 용감한 전사로 기억하는데, 사실 그는 도망칠 수가 없어 늘 앞만 봤을 뿐이다. 부락의 아이들은 지금도 이 토르크를 흉내 내며, 고개를 못 돌리는 시늉으로 뻣뻣하게 걷다가 깔깔거린다.',
    art: `thick layered neck torc, crude bronze coils, dented from wear, comically oversized, ${STYLE}`,
  },
  {
    key: 'warband_knuckle_charm',
    slot: 'accessory',
    nameKo: '부락 주먹뼈 부적',
    region: '오크 부락',
    tone: '영웅담',
    lore: '오크 부락에는 어귀를 지키다 끝내 물러서지 않은 자의 주먹뼈를, 다음 어귀지기가 부적으로 받아 차는 풍습이 있다. 그것을 찬 자는 자기가 두 사람 몫의 자리를 지킨다는 뜻이라 여겼다. 이 부적의 끈에는 작은 뼈가 여럿 꿰여 있는데, 그 수는 곧 어귀가 지금까지 몇 번 무너지지 않았는가의 기록이다. 부락 사람들은 이 부적을 찬 자 앞에서는 농을 줄였다. 그 어깨에 누가 얹혀 있는지를 모두가 알았기 때문이다. 새 어귀지기가 이 부적을 받는 날이면, 부락은 까닭을 굳이 말하지 않고도 평소보다 일찍 모닥불을 껐다.',
    art: `cord strung with small worn knuckle bones, bound in sinew, weathered, solemn heroic, ${STYLE}`,
  },
  {
    key: 'orc_ration_tag',
    slot: 'accessory',
    nameKo: '부락 식량패',
    region: '오크 부락',
    tone: '일상',
    lore: '오크 부락에서 하루치 식량을 받을 때 내미는 나무패다. 거칠게 깎은 데다 받은 사람이 제 표식을 더 거칠게 새겨, 패마다 생김이 다 다르다. 싸움 이야기 하나 없는 물건이지만, 부락의 하루가 굴러가게 한 것은 사실 번쩍이는 무기가 아니라 이 손바닥만 한 나무패였다. 끼니가 어긋나면 어떤 줄도 다음 날 서지 못한다는 것을, 부락은 오래전에 배웠다. 그래서 이 패를 잃은 자는, 무기를 잃은 자보다 더 곤란한 하루를 보냈다.',
    art: `small rough wooden tally tag on a cord, crude personal carving, grease-darkened, mundane, ${STYLE}`,
  },
  {
    key: 'chiefs_riddle_bead',
    slot: 'accessory',
    nameKo: '족장의 수수께끼 구슬',
    region: '오크 부락',
    tone: '수수께끼',
    lore: '한 오크 족장이 죽기 전, 다음 족장이 될 자에게 이 나무 구슬 하나를 건네며 한 가지 수수께끼를 냈다고 한다. 답을 맞히면 부락의 진짜 비밀을 알게 된다는 것이었다. 이후로 족장이 여럿 바뀌었지만, 누구도 그 답을 입 밖에 낸 적이 없다. 답을 몰라서인지, 알고도 말하지 않는 것인지조차 분명하지 않다. 구슬은 새 족장의 목으로 옮겨 갈 때마다 조금씩 더 닳았다. 가장 많이 만져진 부분이 정답에 가장 가까운 자리라는 농담만, 부락에 길게 남았다.',
    art: `single dark wooden bead on a thick cord, hand-polished smooth in one spot, enigmatic, ${STYLE}`,
  },
  {
    key: 'runeshard_amulet',
    slot: 'accessory',
    nameKo: '룬 파편 부적',
    region: '고대 룬 산맥',
    tone: '장엄',
    lore: '산이 무너지며 흩어진 룬돌 가운데, 글자 하나가 온전히 남은 파편을 갈아 만든 부적이다. 그 한 글자가 무슨 뜻인지는 산에 오르던 늙은 학자들 사이에서도 끝내 합의되지 않았다. 다만 이것을 목에 건 자는 한결같이, 발밑이 더 단단하게 느껴진다고 했다. 산 하나가 통째로 무너지고도 끝까지 깨지지 않은 한 글자를 지니고 있다는 것은, 그 자체로 사람의 등을 펴게 하는 무게가 있다. 부적이 주는 것은 힘이 아니라, 버틴 것의 곁에 있다는 감각이다.',
    art: `polished rune-stone shard pendant, one clear glyph, faint blue vein, banded setting, monumental, ${STYLE}`,
  },
  {
    key: 'echo_stone_earring',
    slot: 'accessory',
    nameKo: '메아리 돌 귀고리',
    region: '고대 룬 산맥',
    tone: '수수께끼',
    lore: '산에서 캐낸 작은 돌을 깎아 만든 귀고리다. 차고 있으면 가끔, 방금 들은 말이 한 박자 뒤에 아주 작게 한 번 더 들린다. 처음엔 제 귀를 의심하지만, 곧 알게 된다. 두 번째로 들리는 그 말은, 종종 처음과 미세하게 다르다는 것을. 무엇이 진짜 들린 말인지 헷갈리기 시작한 자들은 이 귀고리를 빼서 깊은 서랍에 넣었고, 그러고도 한동안은 남이 한 말을 두 번씩 곱씹는 버릇을 떼지 못했다. 돌은 아무 말도 하지 않는다. 다만 들은 것을 한 번 더 들려줄 뿐이다.',
    art: `small carved stone earring, pale grey with a hairline seam, plain hook, mysterious, ${STYLE}`,
  },
  {
    key: 'carvers_last_ring',
    slot: 'accessory',
    nameKo: '새긴 자의 마지막 반지',
    region: '고대 룬 산맥',
    tone: '비애',
    lore: '산의 룬을 평생 베껴 새기던 한 각자공이 마지막으로 만든 반지다. 그는 산이 무너지기 전, 사라질 글자들을 하나라도 더 남기려 손이 굳도록 새겼다. 이 반지의 안쪽에는 그가 끝내 다 새기지 못한 글자가, 절반에서 끊긴 채로 남아 있다. 끊긴 자리의 칼끝 자국이 유난히 깊은데, 거기서 손을 멈춘 것이 아니라 멈춰진 것임을 사람들은 안다. 다 새겨진 글자보다, 끊긴 글자 하나가 그 사람에 대해 더 많은 것을 말한다.',
    art: `plain stone-set ring, an unfinished glyph cut inside, deep tool-mark at the break, mournful, ${STYLE}`,
  },
  {
    key: 'surveyor_plumb_pendant',
    slot: 'accessory',
    nameKo: '측량추 펜던트',
    region: '고대 룬 산맥',
    tone: '일상',
    lore: '한 측량꾼의 일지에서 옮긴다. "셋째 날. 동쪽 비탈, 추 늘어뜨려 측정. 한 뼘에 손가락 두 마디 기욺 — 수레 못 넘김. 우회선 다시 그음." "스무날째. 추 끈 닳아 교체. 같은 자리 다시 잼, 값 동일." "마흔날째. 능선 평탄, 길 확정. 표식 박음." 일지는 거기서 끊긴다. 산이 한 번 크게 무너졌고, 그 뒤 길을 다시 그으러 나간 사람들이 가장 먼저 챙긴 것이 이런 납추였다는 기록이 다른 일지에 짧게 남아 있을 뿐이다. 추 자체에 대한 묘사는 어느 일지에도 없다.',
    art: `small lead plumb-bob on a knotted cord, scratched measure marks, worn, mundane, ${STYLE}`,
  },
  {
    key: 'ember_bead_string',
    slot: 'accessory',
    nameKo: '잉걸 염주',
    region: '서쪽 화산',
    tone: '위트',
    lore: '화산 대장간 곁에서 저절로 둥글게 굳은 용암 방울을 골라 꿴 염주다. 한 대장장이가 화 잘 내기로 소문난 제 성질을 고쳐 보겠다며, 욱할 때마다 한 알씩 굴리기로 했다. 효과는 있었다—다만 그가 워낙 자주 욱한 탓에, 그 줄의 구슬만 유난히 반들반들 닳았다. 사람들은 그 닳은 정도를 보고 "올해는 좀 참았네" 하고 놀렸다. 정작 본인은 염주를 굴리느라 화낼 타이밍을 놓치는 거라며 끝까지 우겼다. 어느 쪽이든, 그 대장간은 그 줄이 닳는 동안 한결 조용해졌다.',
    art: `string of rounded volcanic-glass beads, one stretch rubbed extra smooth, charred cord, ironic, ${STYLE}`,
  },
  {
    key: 'ashglass_pendant',
    slot: 'accessory',
    nameKo: '잿빛 유리 펜던트',
    region: '서쪽 화산',
    tone: '담백',
    lore: '화산 모래가 열에 녹았다 굳으며 저절로 생긴 잿빛 유리 조각을, 구멍만 뚫어 끈에 꿴 펜던트다. 사람 손이 거의 닿지 않은 물건이라, 모양도 두께도 제각각이고 두 개로 똑같은 것이 없다. 무슨 사연을 기대하면 멋쩍어진다. 화산 마을에서는 그저 길에 흔해 누구나 하나쯤 주워 차고 다녔다. 흔해서 귀하지 않았고, 흔해서 잃어도 서럽지 않았다. 그 가벼움이 화산 곁에 사는 사람들에게는 외려 어울리는 장신구였다. 마을이 비워지던 날에도 사람들은 다른 건 다 챙기면서, 이것만은 길에 흔하다며 줍지도 버리지도 않고 그냥 두고 떠났다.',
    art: `irregular grey volcanic-glass shard pendant, raw drilled hole, plain cord, understated, ${STYLE}`,
  },
  {
    key: 'scorch_medallion',
    slot: 'accessory',
    nameKo: '그을림 훈장',
    region: '서쪽 화산',
    tone: '영웅담',
    lore: '화산 마을이 비워지던 날, 끝까지 남아 사람들을 길로 밀어 보낸 자에게 마을이 뒤늦게 만들어 준 훈장이다. 번듯한 금속이 아니라, 그날 그가 끝내 버리지 못한 문고리를 두드려 편 것이다. 한쪽 면은 열에 검게 그을려 무늬가 다 뭉개졌다. 본인은 받기를 한사코 사양했지만, 마을은 그 그을린 면이야말로 훈장이라 우겼다. 반짝이는 면이 아니라 망가진 면을 자랑으로 삼는 일은 드물지만, 그날 그 자리에 있던 사람들에게는 그게 당연했다.',
    art: `crude hammered medallion from a door-ring, one face heat-blackened, plain ribbon, heroic, ${STYLE}`,
  },
  {
    key: 'cinder_eye_charm',
    slot: 'accessory',
    nameKo: '잿불 눈 부적',
    region: '서쪽 화산',
    tone: '기괴',
    lore: '화산 곁에서 주운, 한가운데에 붉은 점이 박힌 검은 돌을 깎은 부적이다. 그 붉은 점이 꼭 가늘게 뜬 눈을 닮았다 하여 그런 이름이 붙었다. 낮에는 그저 무늬일 뿐인데, 불 곁에서는 그 점이 정말로 불빛을 머금어 한 번씩 깜빡이는 것처럼 보인다. 어느 화부는 이걸 차고부터 화덕 앞에서 늘 누가 어깨 너머로 같이 불을 들여다보는 기분이 든다고 했다. 그는 일을 그만두지는 않았다. 다만 화덕을 등지고 앉는 버릇만은 끝내 고치지 못했다.',
    art: `black stone charm with a red eye-like inclusion, faint glow near fire, plain cord, eerie, ${STYLE}`,
  },
  {
    key: 'feather_locket',
    slot: 'accessory',
    nameKo: '깃 로켓',
    region: '타락천사',
    tone: '비애',
    lore: '추락한 자리에서 주운 검은 깃 한 올을, 작은 쇠 로켓 안에 접어 넣어 다니는 펜던트다. 로켓을 열면 그 깃이 들어 있을 뿐 다른 무엇도 없다. 그런데도 로켓을 가진 자들은 그것을 좀처럼 열지 않는다. 한 번 열어 본 자가 말하길, 닫을 때 깃이 늘 처음 넣은 모양과 미세하게 다르게 접혀 있더라는 것이다. 누가 손댄 흔적은 없다. 그래서 사람들은 그 안의 깃이 아주 천천히, 제 나름의 시간을 살고 있는 것 같다고만 한다.',
    art: `small iron locket on a fine chain, a single folded black feather inside, tarnished, melancholic, ${STYLE}`,
  },
  {
    key: 'fallen_bell_charm',
    slot: 'accessory',
    nameKo: '떨어진 종 부적',
    region: '타락천사',
    tone: '장엄',
    lore: '추락한 성가대가 울리던 종이 깨졌을 때, 그 파편 가운데 가장 맑은 소리가 남은 한 조각을 갈아 만든 작은 부적이다. 손끝으로 가만히 튕기면, 깨진 종의 것이라곤 믿기지 않는 길고 곧은 한 음이 난다. 그 음을 들은 자리에서는 시끄럽던 사람들이 까닭 없이 한순간 조용해진다고 한다. 부서진 것에서 떼어낸 한 조각이, 멀쩡하던 것보다 더 또렷이 울리는 일이 있다. 이 부적이 그렇고, 어쩌면 그 종을 울리던 자도 그랬을 것이다.',
    art: `small ground-down bell-fragment charm, faint clear ring when struck, tarnished gilt, solemn, ${STYLE}`,
  },
  {
    key: 'crooked_halo_pin',
    slot: 'accessory',
    nameKo: '비뚤 후광 핀',
    region: '타락천사',
    tone: '위트',
    lore: '한쪽이 푹 눌린, 비뚠 후광을 본뜬 옷핀이다. 주인이 바뀔 때마다 앞사람이 남긴 쪽지가 한 장씩 늘어 핀 뒤에 끼워진다. 첫 장은 그 눌린 모양을 두고 멋쩍게 변명한다. 둘째 장은 그 변명을 한참 의심하다 그냥 믿기로 했다고 적는다. 셋째 장은 믿고 나니 어쩐지 어깨가 가벼워졌다고, 다음 사람도 그러길 바란다고 적는다. 지금 이 핀을 단 사람은 세 장을 다 읽고, 거울 앞에서 비뚠 후광을 한참 들여다보다 제 굽은 어깨를 슬쩍 한 번 폈다. 그러고는 넷째 쪽지에 딱 한 줄을 적어 끼웠다. 「과연 그렇네요.」 다섯째 장은 아직 백지다.',
    art: `small bent gold halo-ring lapel pin, off-center curve, tarnished sheen, ironic, ${STYLE}`,
  },
  {
    key: 'hollow_prayer_bead',
    slot: 'accessory',
    nameKo: '빈 기도 구슬',
    region: '타락천사',
    tone: '수수께끼',
    lore: '추락한 성가대가 손가락으로 굴리며 기도하던 염주에서 떨어져 나온, 단 한 알의 구슬이다. 다른 구슬과 달리 속이 비어 있어, 흔들면 안에서 무언가 작은 것이 또르르 구른다. 깨 본 자는 없다. 한 사람이 귀에 대고 오래 들었더니, 그 구르는 소리가 어떤 짧은 말의 운율과 꼭 같더라고 했다. 그러나 그게 무슨 기도였는지는 끝내 떠올리지 못했다. 답을 담은 채로 비어 있는 것이 가능하다면, 이 구슬이 바로 그렇다.',
    art: `single hollow prayer bead on a frayed cord, faint rattle inside, worn dark, mysterious, ${STYLE}`,
  },
  {
    key: 'gamblers_lucky_coin',
    slot: 'accessory',
    nameKo: '노름꾼의 행운 동전',
    region: '자유',
    tone: '위트',
    lore: '빚 받으러 다니던 자의 기록. 「대상: 노름꾼. 회수액: 0. 사망 확인. 유품: 동전 하나, 끈에 꿰어 목에 검.」 동전을 장부에 올리려 양면을 확인하다 옆에 적어 둠. 「앞뒤가 같은 그림. 어느 쪽을 불러도 그 그림이 나옴. 본인은 평생 한 판도 안 졌다고 떠들었다는데, 사실로 보임.」 빚은 끝내 못 받았다. 동전은 회수품 상자에 들어갔다가, 다음 빚쟁이가 행운이라며 제 목에 걸고 나갔다. 그자도 한 판을 안 졌고, 그자의 빚도 똑같이 늘어만 갔다.',
    art: `worn old coin on a cord, both faces identical, rubbed-smooth edges, ironic, ${STYLE}`,
  },
  {
    key: 'widowers_band',
    slot: 'accessory',
    nameKo: '홀아비의 반지',
    region: '자유',
    tone: '비애',
    lore: '한 사람이 두 개의 반지를 한 끈에 꿰어 목에 걸고 다녔다. 하나는 제 손가락에 맞고, 다른 하나는 누가 봐도 더 가는 손의 것이다. 그는 가는 쪽 반지에 대해 누가 물으면 말없이 그것을 한 번 만지고는, 다른 이야기를 시작했다. 두 반지는 늘 같은 끈에 함께 있었지만, 한 번도 같은 손가락에 끼워지지는 못했다. 그가 세상을 뜬 뒤에도 사람들은 그 반지를 둘로 나누지 않고, 끈째 그대로 묻었다. 떼어 놓는 것이 더 잔인하다고, 모두가 말없이 동의했다.',
    art: `two band rings of different sizes on one cord, both tarnished, plain, sorrowful, ${STYLE}`,
  },
  {
    key: 'nameless_signet',
    slot: 'accessory',
    nameKo: '무명 인장반지',
    region: '자유',
    tone: '수수께끼',
    lore: '문장이 새겨진 인장반지인데, 그 문장이 어느 가문의 것인지 아는 사람이 한 명도 없다. 오래된 족보를 뒤진 자도, 문장학에 밝다는 노인도 고개를 저었다. 그런데 이 반지를 끼고 봉랍에 찍으면, 받아 본 사람들이 하나같이 잠깐 자세를 고친다고 한다. 무슨 가문인지 모르면서도, 무시하면 안 될 것 같은 기분이 든다는 것이다. 이름이 사라진 문장이 어떻게 아직 무게를 갖는지는 설명되지 않는다. 그 봉랍을 받아 든 사람들은, 누구의 가문인지도 모르면서 답장의 첫 줄을 한 번씩 고쳐 더 정중하게 썼다.',
    art: `signet ring with an unidentifiable crest, worn deep grooves, plain band, enigmatic, ${STYLE}`,
  },
  {
    key: 'grandmas_thimble_charm',
    slot: 'accessory',
    nameKo: '할머니 골무 부적',
    region: '자유',
    tone: '담백',
    lore: '한 집안에서, 바느질을 쥐던 손이 떠나면 그가 쓰던 골무를 끈에 꿰어 다음 사람이 목에 거는 작은 풍습이 있었다. 영험을 바라서가 아니다. 그저 손가락 끝이 닳도록 무언가를 꿰매 준 사람이 있었다는 것을 잊지 않으려는 표식일 뿐이다. 골무는 안쪽이 손가락 모양대로 반들반들 닳아 있어, 끼워 보면 그 사람의 손끝 크기가 그대로 만져진다. 거창한 이야기는 없다. 다만 이걸 건 사람은 단추가 떨어졌을 때 한 번씩, 꿰매 주던 사람을 떠올린다.',
    art: `worn metal thimble strung on thread, inside polished to a fingertip shape, plain, understated, ${STYLE}`,
  },
  {
    key: 'first_tooth_locket',
    slot: 'accessory',
    nameKo: '첫니 로켓',
    region: '자유',
    tone: '비애',
    lore: '아주 작은 쇠 로켓 안에, 더 작은 젖니 하나가 솜에 싸여 들어 있다. 어느 부모가 아이의 첫 이가 빠진 날 그것을 넣어 만든 것이다. 본래는 아이가 크면 웃으며 돌려줄 셈이었다. 그러나 그 아이는 끝내 다음 이가 날 만큼 자라지 못했다. 부모는 그 로켓을 평생 목에서 풀지 않았고, 누구에게도 열어 보여 주지 않았다. 그 안에 무엇이 들었는지를 아는 사람은 손에 꼽고, 로켓은 끝내 한 번도 열리지 않은 채 그 부모가 묻히는 자리에 함께 들어갔다.',
    art: `tiny iron locket on a fine chain, a milk tooth in cotton inside, never opened, mournful, ${STYLE}`,
  },
  {
    key: 'merchants_scale_pendant',
    slot: 'accessory',
    nameKo: '상인의 저울 펜던트',
    region: '자유',
    tone: '일상',
    lore: '한 손바닥에 들어오는 작은 접시저울을 펜던트로 만든 것이다. 떠돌이 상인이 길에서 향료며 은부스러기를 잴 때 쓰다가, 쉴 참엔 그냥 목에 걸어 두었다. 양쪽 접시가 미세하게 안 맞아 늘 한쪽으로 살짝 기우는데, 상인은 그 기운 만큼을 평생 머릿속으로 빼고 셈했다. 한 번도 손님을 속인 적 없다는 그의 자부심은, 사실 이 어긋난 저울을 정직하게 셈하는 수고에서 나온 것이었다. 완벽한 도구보다, 결함을 알고 쓰는 손이 더 믿을 만하다.',
    art: `tiny balance-scale pendant, slightly uneven pans, brass worn bright, mundane, ${STYLE}`,
  },
  {
    key: 'hero_ear_notch',
    slot: 'accessory',
    nameKo: '영웅의 귀고리',
    region: '자유',
    tone: '영웅담',
    lore: '한 변방에서는 큰 싸움에서 사람들을 살린 자에게, 마을이 작은 쇠고리 하나를 귀에 꿰어 주는 풍습이 있었다. 훈장처럼 가슴에 다는 것이 아니라 굳이 귀에 다는 데에는 까닭이 있다. 본인은 잊고 살아도, 그를 마주 본 사람들이 먼저 그 고리를 알아보고 고개를 숙이라는 것이다. 이 고리의 주인은 제 무용담을 한 번도 입에 올리지 않았다고 한다. 올릴 필요가 없었다. 그를 아는 마을의 모든 귀가, 그의 귀에 달린 것을 대신 기억하고 있었으니까.',
    art: `simple iron ear-ring hoop, plain and small, worn smooth, quietly heroic, ${STYLE}`,
  },
  {
    key: 'liars_tongue_pin',
    slot: 'accessory',
    nameKo: '거짓말쟁이 은혀 핀',
    region: '자유',
    tone: '위트',
    lore: '한 이름난 허풍선이가 옷깃에 꽂고 다니던, 작은 혀 모양의 은핀이다. 그는 이 핀을 두고 "내가 거짓말을 하면 이게 검게 변한다"고 떠벌렸다. 사람들은 그 말을 비웃었지만, 정작 누구도 그 핀이 검게 변한 것을 본 적이 없었다. 진실만 말해서가 아니라, 그가 너무 천연덕스러워 무엇이 거짓인지 핀조차 헷갈렸기 때문이라는 농담이 돌았다. 그가 죽은 뒤 핀은 여전히 은빛이다. 그러니 그의 평생이 진실이었거나, 아니면 끝까지 완벽한 거짓이었거나 둘 중 하나다.',
    art: `small silver tongue-shaped lapel pin, polished bright, never tarnished, ironic, ${STYLE}`,
  },
  {
    key: 'quiet_compass_charm',
    slot: 'accessory',
    nameKo: '침묵 나침반 부적',
    region: '자유',
    tone: '수수께끼',
    lore: '바늘이 달린 작은 나침반 부적인데, 그 바늘은 북을 가리키지 않는다. 차고 다니는 사람의 마음이 가장 어지러울 때, 바늘은 한 방향을 천천히 가리켰다가 다시 흔들린다. 그쪽으로 가 본 자들의 말은 제각각이다. 누구는 잊고 있던 사람을 만났다 했고, 누구는 아무것도 없는 들판이었다 했고, 누구는 그 길로 영영 돌아오지 않았다. 그래서 사람들은 이 바늘이 길이 아니라 다른 무언가를 가리킨다고 여긴다. 다만 그것이 무엇인지는, 끝까지 따라가 본 자만 알고 그들은 말이 없다.',
    art: `small compass charm, needle pointing nowhere fixed, dull brass case, mysterious, ${STYLE}`,
  },
  {
    key: 'beekeepers_bell',
    slot: 'accessory',
    nameKo: '양봉가의 종',
    region: '자유',
    tone: '일상',
    lore: '양봉가가 허리에 달고 다니던 아주 작은 놋종이다. 벌통을 살필 때 급한 동작 대신 이 종을 천천히 한 번 울리면, 벌들이 덜 사납게 군다는 것을 그는 평생의 경험으로 알았다. 무기도, 부적도 아니다. 그저 성난 것 앞에서 서두르지 않는 법을 손목으로 익히게 해 주는 물건이다. 양봉가가 떠난 뒤 그 종을 물려받은 젊은이는, 벌이 아니라 화가 난 사람 앞에서도 그 종을 한 번 울리는 버릇이 생겼다. 그러고 나면 대개, 일이 덜 사나워졌다.',
    art: `tiny brass bell on a belt cord, soft worn sheen, faint clear ring, mundane, ${STYLE}`,
  },
  {
    key: 'dueling_garter',
    slot: 'accessory',
    nameKo: '결투의 가터',
    region: '자유',
    tone: '비애',
    lore: '결투에 나서는 자가 상대에게 받아 팔에 묶던 천 띠다. 이긴 자가 그것을 풀어 돌려주는 것이 오랜 예법이었다. 한 사람이 이 가터를 풀어 돌려줄 상대를 끝내 잃고, 그것을 평생 제 팔에 묶은 채 살았다. 이긴 것도 진 것도 아닌 결투가 세상에 있다는 것을, 그 빛바랜 천이 말없이 증언한다. 그가 죽은 뒤 누군가 가터를 풀어 주려 했지만, 매듭이 너무 단단히 굳어 끝내 풀리지 않았다. 사람들은 그것을 묶인 그대로 그와 함께 묻었고, 누구도 마지막까지 그 매듭 쪽으로는 손을 가져가지 않았다.',
    art: `faded cloth arm-garter, knot fused stiff with age, plain weave, sorrowful, ${STYLE}`,
  },
  {
    key: 'fools_crown_brooch',
    slot: 'accessory',
    nameKo: '광대 왕관 브로치',
    region: '자유',
    tone: '위트',
    lore: '끝이 우스꽝스럽게 처진 작은 양철 왕관 모양의 브로치다. 한 광대가 "나는 아무 나라도 다스리지 않는 왕"이라며 가슴에 달고 다녔다. 사람들은 그 농을 웃어넘겼는데, 정작 그가 머문 곳에서는 다투던 자들이 그 앞에서 멋쩍어 화를 거뒀다. 아무것도 다스리지 않는 왕이, 화내는 일만큼은 제법 다스린 셈이다. 그가 떠난 뒤에도 그 브로치를 단 사람은 이상하게 시비에 잘 휘말리지 않았다. 위엄이 없어서 오히려 누구도 적으로 삼지 않은 것이다.',
    art: `small tin crown brooch with droopy points, cheap bright finish, comical, ${STYLE}`,
  },
  {
    key: 'pilgrims_knot_cord',
    slot: 'accessory',
    nameKo: '순례 매듭끈',
    region: '자유',
    tone: '담백',
    lore: '한 가닥의 거친 끈에, 크기도 모양도 제각각인 매듭이 빼곡히 묶여 있다. 어느 순례자가 길에서 무언가를 마음에 새길 만한 일이 있을 때마다 매듭을 하나씩 더 지었다. 좋은 일인지 슬픈 일인지는 매듭만 봐서는 알 수 없다. 본인도 나중에는 어느 매듭이 무엇이었는지 다 잊었다고 했다. 그래도 끈을 손가락으로 훑으면, 잊은 일들이 거기 분명히 있었다는 감각만은 또렷이 만져졌다. 기억은 흐려져도, 그것을 지나왔다는 사실은 손끝에 남는다.',
    art: `single rough cord densely tied with mismatched knots, frayed ends, plain, understated, ${STYLE}`,
  },
  {
    key: 'oathkeeper_token',
    slot: 'accessory',
    nameKo: '맹세지기 표',
    region: '자유',
    tone: '영웅담',
    lore: '둘로 쪼개지는 작은 나무패다. 같은 맹세를 한 두 사람이 한 조각씩 나눠 갖고, 살아 다시 만나는 날 그것을 맞춰 보기로 했다. 이 한 조각의 주인은 약속한 자리에 끝까지 나갔다. 상대가 오지 않을 것을 짐작하면서도, 맞출 일이 없어진 제 조각을 평생 목에 걸고 다녔다. 사람들이 다른 짝을 찾아 주겠다 해도 그는 웃으며 사양했다. 맞지 않게 된 조각을 그대로 지니는 것이, 그가 지킬 수 있는 마지막 맹세였다. 그가 떠난 뒤 그 반쪽 패는, 그가 늘 앉던 문지방 옆 못에 짝 없이 그대로 걸려 있다.',
    art: `half of a split wooden token on a cord, jagged broken edge, worn smooth, heroic solemn, ${STYLE}`,
  },
  {
    key: 'grave_dust_vial',
    slot: 'accessory',
    nameKo: '무덤 먼지 병',
    region: '자유',
    tone: '기괴',
    lore: '엄지만 한 유리병에, 곱고 거뭇한 먼지가 절반쯤 담겨 목에 걸려 있다. 무엇의 먼지냐는 물음에 첫 주인은 끝내 답하지 않았다. 이상한 것은, 병을 아무리 흔들어도 안의 먼지가 늘 같은 자리에 가라앉는다는 점이다. 기울여 두어도 다음 날이면 제자리다. 그것을 본 사람들은 더는 흔들지 않게 되었다. 무언가가 그 안에서 가만히 있고 싶어 한다면, 굳이 깨워 좋을 일이 없다고 여겼기 때문이다. 가진 자도 대개, 병을 옷 안쪽으로 돌려 차고 다닌다.',
    art: `thumb-sized glass vial of dark fine dust on a cord, dust always settled flat, eerie, ${STYLE}`,
  },
  {
    key: 'lullaby_music_charm',
    slot: 'accessory',
    nameKo: '자장가 태엽 부적',
    region: '자유',
    tone: '수수께끼',
    lore: '아주 작은 태엽이 달린 쇠 부적이다. 옆의 손잡이를 감으면 가느다란 가락이 흘러나오는데, 누가 들어도 처음 듣는 곡인데도 끝을 미리 흥얼거릴 수 있다고 한다. 마치 아주 오래전 잊은 노래를 다시 떠올리는 것처럼. 태엽을 끝까지 감아 본 자는 없다. 어느 지점부터는 더 감기지 않고, 그 자리에서 가락이 한 마디를 빼먹은 채 다음으로 넘어간다. 빠진 그 한 마디가 무엇인지 떠올리려 애쓴 사람들은, 하나같이 그날 밤 깊고 이상한 잠을 잤다고 한다.',
    art: `tiny wind-up music charm of iron, small crank, faint tune, missing one note, mysterious, ${STYLE}`,
  },
  {
    key: 'saltworkers_ring',
    slot: 'accessory',
    nameKo: '소금일꾼 반지',
    region: '자유',
    tone: '일상',
    lore: '소금밭에서 평생 일한 사람의 손가락에 맞춰 닳은 무쇠 반지다. 짠물에 종일 잠겨 있던 탓에 표면이 우둘투둘 삭았고, 색도 다 빠졌다. 값나가는 물건은 아니다. 다만 이 반지를 낀 손이 퍼 올린 소금이, 이름 모를 수많은 부엌의 국 맛을 냈다. 화려한 무용담은 끝내 한 줄도 붙지 않았지만, 그 손이 없었다면 싱거웠을 끼니가 헤아릴 수 없이 많았다. 세상을 떠받치는 일은 대개 이렇게, 짜고 무심한 반지 같은 것에서 조용히 이뤄진다.',
    art: `pitted salt-corroded iron band ring, color leached out, worn thin, mundane, ${STYLE}`,
  },
  {
    key: 'last_breath_amulet',
    slot: 'accessory',
    nameKo: '마지막 숨 부적',
    region: '자유',
    tone: '비애',
    lore: '속이 빈 작은 쇠 부적이다. 어느 마을에는 떠나는 사람의 마지막 숨을 이 안에 담아, 남는 이가 목에 거는 풍습이 있었다. 그 안에 정말 무엇이 담겼는지는 누구도 확인할 수 없고, 확인하려 열어 본 자도 없다. 열면 그 한 숨이 끝내 흩어진다고 믿었기 때문이다. 그래서 이 부적은 평생 닫힌 채로만 전해진다. 가진 자는 그것을 열어 무엇이 있나 보는 대신, 추운 날 두 손에 감싸 쥐는 쪽을 택한다. 비어 있을지도 모르는 것을 비어 있지 않다고 믿는 일이, 누군가에게는 살아갈 힘이 된다.',
    art: `small hollow sealed iron amulet, never opened, soft hand-worn sheen, mournful, ${STYLE}`,
  },
  {
    key: 'mummers_false_medal',
    slot: 'accessory',
    nameKo: '가짜 무공 훈장',
    region: '자유',
    tone: '위트',
    lore: '한 떠돌이 연희패가 무대에서 "위대한 장군" 역을 할 때 가슴에 달던, 누가 봐도 가짜인 양철 훈장이다. 그것을 늘 달던 늙은 배우는 진짜 전장에는 한 발도 디딘 적이 없었다. 그런데 그가 그 훈장을 달고 풀어내는 무용담이 어찌나 그럴듯한지, 진짜 노병들조차 술자리에서 그 이야기에 잔을 들곤 했다. 가짜 훈장을 단 가짜 장군이 한 일이라곤 사람들을 한바탕 웃고 울린 것뿐이다. 그런데 그 일을, 진짜 장군 중에도 못 해낸 이가 많았다.',
    art: `cheap tin "war medal", obviously fake, flaking paint, ribbon frayed, ironic, ${STYLE}`,
  },
  {
    key: 'storm_warned_bead',
    slot: 'accessory',
    nameKo: '폭풍 알림 구슬',
    region: '자유',
    tone: '일상',
    lore: '바닷가 마을 어부들이 목에 걸던, 거뭇한 돌을 굴려 만든 구슬이다. 큰 비바람이 오기 하루쯤 전이면 구슬 표면에 자잘한 물기가 맺힌다고 했다. 신통한 점술 같은 것이 아니라, 그 돌이 습기를 잘 머금는 성질일 뿐임을 늙은 어부들도 알았다. 그래도 그들은 매일 아침 그 구슬을 손등으로 한 번 쓸어 보고 배를 띄울지 정했다. 덕분에 그 마을은 폭풍에 배를 잃는 일이 유난히 적었다. 대단한 비밀이 아니라, 매일 한 번 확인하는 작은 습관이 사람을 살린 것이다.',
    art: `dark hygroscopic stone bead on a cord, faint surface beading, plain, mundane, ${STYLE}`,
  },
  {
    key: 'cartographers_eye',
    slot: 'accessory',
    nameKo: '지도장이의 눈',
    region: '자유',
    tone: '수수께끼',
    lore: '한 지도장이가 늘 한쪽 눈에 끼고 다닌 둥근 유리알 펜던트다. 이걸 통해 들여다보면 멀쩡한 지도에 없던 가느다란 길이 하나 더 보인다고 그는 주장했다. 사람들은 노안의 헛것이라 여겼다. 그러나 그가 죽은 뒤 남긴 지도들에는, 실제로 누구도 모르던 지름길이 군데군데 그어져 있었고 그 길들은 모두 옳았다. 유리알을 들여다본 다른 이들 눈에는 끝내 아무것도 보이지 않았다. 어떤 도구는 쥔 사람에게만 한 겹을 더 보여 주고, 그 사람이 떠나면 그 한 겹도 함께 닫힌다.',
    art: `round glass-lens pendant on a chain, faintly clouded, brass rim, mysterious, ${STYLE}`,
  },
  {
    key: 'standardbearer_clasp',
    slot: 'accessory',
    nameKo: '기수의 죔쇠',
    region: '자유',
    tone: '영웅담',
    lore: '깃대를 어깨에 동여매던 가죽끈의 쇠 죔쇠다. 기수는 두 손으로 싸울 수 없다. 깃을 놓는 순간 줄이 흔들리기 때문이다. 그래서 이 죔쇠는 한 번 채우면 본인 손으로는 풀 수 없게 만들어졌다. 깃과 함께 끝까지 가겠다는 뜻이었다. 한 기수가 쓰러진 뒤에도 죔쇠는 끝까지 채워져 있었고, 동료들은 깃을 내리기 위해 그것을 칼로 끊어야 했다. 끊긴 죔쇠는 그 자체로 한 사람의 약속이 어디서 멈췄는지를 보여 준다. 그래서 새 기수는 늘 새 죔쇠를 쓴다. 끊긴 것을 잇는 일은 하지 않는다.',
    art: `iron strap-clasp, cut through cleanly, leather remnant attached, heroic solemn, ${STYLE}`,
  },
  {
    key: 'whispering_keyring',
    slot: 'accessory',
    nameKo: '속삭이는 열쇠고리',
    region: '자유',
    tone: '기괴',
    lore: '낡은 열쇠 여럿이 꿰인 쇠고리다. 그 열쇠들이 어느 문의 것인지는 아무도 모른다. 가진 자가 잠들면 열쇠들이 아주 작게, 저희끼리 부딪는 소리를 낸다고 한다. 바람 한 점 없는 방에서도 그렇다. 한 사람이 그 소리를 흉내 내 보려다, 그게 부딪는 소리가 아니라 무언가 아주 낮게 속삭이는 소리에 더 가깝다는 걸 알아채고는 고리를 멀리 치웠다. 열쇠는 본래 무언가를 여는 물건이다. 그래서 사람들은 이 열쇠들이 무엇을 열고 싶어 하는지를, 차라리 모른 채로 두고 싶어 한다.',
    art: `iron ring of several old mismatched keys, faint clinking, rust-mottled, eerie, ${STYLE}`,
  },
  {
    key: 'plain_iron_band',
    slot: 'accessory',
    nameKo: '무쇠 가락지',
    region: '자유',
    tone: '담백',
    lore: '아무 무늬도, 보석도, 글자도 없는 무쇠 가락지다. 누가 만들었는지, 누구의 것이었는지에 대한 기록이 하나도 없다. 값으로 치면 거의 없는 것과 같다. 그런데도 이것이 손에서 손으로 오래 전해진 이유는 단 하나, 끼면 이상하리만치 손에 잘 맞고 거추장스럽지 않다는 것뿐이다. 화려한 반지는 자랑하느라 자주 빼 두지만, 이 가락지는 낀 사람이 끼고 있다는 것조차 잊는다. 그렇게 잊힌 채로 늘 거기 있는 것이, 어쩌면 장신구가 다다를 수 있는 가장 높은 자리인지도 모른다.',
    art: `utterly plain iron band ring, no markings, comfortably worn, understated, ${STYLE}`,
  },
  {
    key: 'child_string_bracelet',
    slot: 'accessory',
    nameKo: '아이의 실팔찌',
    region: '자유',
    tone: '비애',
    lore: '색실을 어설프게 꼬아 만든 작은 팔찌다. 매듭이 비뚤고 색 배치도 엉망이라, 솜씨라곤 찾아볼 수 없다. 한 아이가 떠나는 누군가의 손목에 직접 묶어 주며 "다시 올 때까지 풀지 마"라고 했다고 한다. 그것을 받은 사람은 그 약속을 글자 그대로 지켰다. 실이 다 삭아 색이 바래고 한 가닥씩 끊어지는 동안에도, 그는 끝내 그것을 풀지 않았다. 잘 만든 보석 팔찌였다면 진작 바꿔 찼을 것이다. 못 만들어서, 오직 그 아이만 그렇게 만들 수 있어서, 그것은 영영 바꿀 수 없는 물건이 되었다.',
    art: `crude frayed colored-thread bracelet, uneven knots, faded colors, sorrowful, ${STYLE}`,
  },
  {
    key: 'lighthouse_keepers_charm',
    slot: 'accessory',
    nameKo: '등대지기 부적',
    region: '자유',
    tone: '영웅담',
    lore: '등대지기가 평생 목에 걸고 있던, 손톱만 한 유리 조각 부적이다. 본래는 깨진 등대 렌즈의 한 귀퉁이라고 한다. 그는 단 하룻밤도 불을 꺼뜨리지 않았다. 폭풍에 손이 찢기고 기름이 떨어진 밤에도, 이 유리 조각을 손에 꼭 쥐고 어떻게든 빛을 살려 두었다. 그 빛을 보고 살아 돌아온 배의 수는 헤아릴 수 없는데, 정작 그 배들의 사람들은 등대지기의 얼굴을 한 번도 보지 못했다. 누군가를 가장 많이 살린 사람이, 그들에게 가장 알려지지 않는 일은 그렇게 흔하다.',
    art: `tiny chipped lighthouse-lens glass shard on a cord, sea-clouded, plain, heroic, ${STYLE}`,
  },
  {
    key: 'mourners_jet_brooch',
    slot: 'accessory',
    nameKo: '상주의 흑옥 브로치',
    region: '자유',
    tone: '담백',
    lore: '윤이 죽은 검은 흑옥을 둥글게 갈아 만든 수수한 브로치다. 상을 당한 사람이 옷깃에 다는 것으로, 화려할 이유가 처음부터 없는 물건이다. 만든 장인도 일부러 빛을 죽여 깎았다. 누가 이 브로치를 단 것을 보면, 사람들은 까닭을 묻는 대신 목소리를 한 톤 낮췄다. 그 작은 검은 점 하나가, 길게 설명하지 않아도 한 사람의 사정을 다 말해 주었기 때문이다. 어떤 장신구는 빛나기 위해서가 아니라, 빛나지 않기 위해 만들어진다. 그 절제가 곧 예의다.',
    art: `plain round matte jet brooch, deliberately unpolished, simple pin, understated, ${STYLE}`,
  },
  {
    key: 'grin_in_glass_pendant',
    slot: 'accessory',
    nameKo: '유리 속 웃음 펜던트',
    region: '자유',
    tone: '기괴',
    lore: '맑은 유리 안에 작은 무언가가 굳어 들어간 펜던트다. 빛에 비춰 들여다보면, 그 안의 형체가 사람이 살짝 웃는 입매를 묘하게 닮았다. 만든 자는 그저 우연히 생긴 기포라고 했다. 그런데 이걸 오래 지닌 사람들이 입을 모으는 말이 하나 있다. 기분이 좋은 날에는 그 웃음이 평범해 보이고, 마음이 가라앉은 날에는 그게 비웃는 것처럼 보인다는 것이다. 유리 속 형체는 변하지 않는다. 변하는 것은 늘 들여다보는 쪽이다. 그것을 깨닫고 나면, 사람들은 대개 그 펜던트를 더 자주 들여다본다.',
    art: `clear glass pendant with a small grin-shaped inclusion, lensing the light, eerie, ${STYLE}`,
  },
  {
    key: 'last_call_tavern_token',
    slot: 'accessory',
    nameKo: '마지막 잔 술집 패',
    region: '자유',
    tone: '일상',
    lore: '어느 술집에서 외상 손님에게 내주던 나무패다. 한 잔 값을 외상으로 달아 두고 받아 가, 갚으면 돌려주는 식이었다. 이 패에는 외상이 끝내 갚아지지 않았다. 주인은 그것을 버리지 않고 술집 벽에 걸어 두었다. 떠난 손님이 언젠가 들러 갚을지도 모른다는 핑계였지만, 사실은 그 사람을 잊지 않으려는 것이었다. 술집이 문을 닫는 날, 주인은 다른 건 다 정리하면서 그 패만은 챙겨 목에 걸었다. 갚이지 않은 한 잔이, 때로는 가장 오래 기억되는 한 잔이 된다.',
    art: `worn wooden tavern tab token on a cord, a tally never settled, ale-stained, mundane, ${STYLE}`,
  },
  {
    key: 'knotted_memory_cord',
    slot: 'accessory',
    nameKo: '기억 매듭끈',
    region: '자유',
    tone: '수수께끼',
    lore: '글을 모르던 한 사람이, 잊고 싶지 않은 일이 생길 때마다 끈에 매듭을 하나씩 지어 기록 대신 삼았다. 매듭의 모양과 간격에 그만의 규칙이 있었다. 그가 떠난 뒤 끈만 남았는데, 매듭은 분명 무언가를 또렷이 적고 있으나 그것을 읽을 수 있는 사람이 세상에 더는 없다. 학자들이 풀이를 시도했지만, 한 매듭을 풀면 그 안의 뜻도 함께 풀려 사라지는 듯했다. 그래서 끈은 묶인 채로 보관된다. 읽지 못하는 기록이라도, 누군가에게 분명히 중요했다는 사실만은 그 매듭들이 끝까지 증언한다.',
    art: `single cord tied with a deliberate sequence of knots, undeciphered, frayed, mysterious, ${STYLE}`,
  },
];

export const CATALOG_ITEMS: CatalogItem[] = [...WEAPONS, ...ARMOR, ...ACCESSORIES];

export const CATALOG_BY_SLOT = (slot: CatalogSlot): CatalogItem[] =>
  CATALOG_ITEMS.filter((c) => c.slot === slot);
