/**
 * 카탈로그 단일 진실 원천 — 아이템 식별/로어/스프라이트.
 *
 * 한 배열이 다음을 모두 공급한다:
 *  - DB 시드 (`scripts/seed-catalog.ts`, `catalogItems`)
 *  - 스프라이트 파이프라인 프롬프트 (`scripts/sprite-pipeline.ts`)
 *  - 도감/인벤토리/공유 UI 표시명
 *  - 확률 공시 슬롯별 종 수
 *
 * 규칙 (GDD §3.1 / docs/LORE.md):
 *  - 등급·희소성·성능 차등 **없음**. 아이템 차이는 외관·도감·로어뿐.
 *  - `key`: 영문 snake. `public/sprites/<slot>/<key>.png` 파일명 = `catalogItems.spriteKey`.
 *  - `lore`: 보스 스토리 톤(장엄·서사·간결, ~60~120자). 등급/성능 표현 금지.
 *  - `art`: Pixellab 64×64 생성 키워드(형태·재질·색·분위기). 글로우/등급 제외(GDD §6 — 코드가 강화 글로우 부여).
 *  - 세계관 연결은 느슨하게(~40%): region 이 5권역이면 보스의 땅과 엮임, '자유'면 권역 무관.
 *
 * 목표: 슬롯당 50종(무기/방어구/장신구 = 150), 이후 가변 추가(GDD §10).
 */

export type CatalogSlot = 'weapon' | 'armor' | 'accessory';

export type CatalogRegion =
  | '늪지대'
  | '오크 부락'
  | '고대 룬 산맥'
  | '서쪽 화산'
  | '타락천사'
  | '자유';

/** 로어 정서 — 배치 내 고르게 분포(한 톤이 슬롯의 ~1/4 초과 금지). docs/LORE.md §1. */
export type CatalogTone =
  | '장엄'
  | '담백'
  | '위트'
  | '비애'
  | '기괴'
  | '일상'
  | '영웅담'
  | '수수께끼';

export interface CatalogItem {
  /** 영문 snake — 스프라이트 파일/스프라이트키 식별자. 전역 유니크. */
  key: string;
  slot: CatalogSlot;
  /** 한국어 표시명 (도감/인벤토리/공유). */
  nameKo: string;
  region: CatalogRegion;
  /** 로어 정서(다양성 강제용). docs/LORE.md §1. */
  tone: CatalogTone;
  /** 한국어 로어 (~120~260자, 2~4문장). 아이템마다 고유 사연·개성. 등급/성능 언급 금지. */
  lore: string;
  /** Pixellab 64×64 생성 키워드 (영문, 글로우/등급 제외). */
  art: string;
}

const STYLE = 'clean readable silhouette, fantasy RPG pixel art inventory icon, transparent background';

/** 슬롯별 묶음을 합쳐 단일 export. 배치(슬롯)별로 확장한다. */

// ─────────────────────────────────────────────────────────────────────────────
// 무기 (목표 50) — 배치 1/약4
// ─────────────────────────────────────────────────────────────────────────────
const WEAPONS: CatalogItem[] = [
  {
    key: 'marsh_rusted_blade',
    slot: 'weapon',
    nameKo: '녹슨 늪칼',
    region: '늪지대',
    tone: '담백',
    lore: '늪 마을 대장간이 한철에 수십 자루씩 똑같은 모양으로 찍어내던 보급용 한손검이다. 자루를 감은 가죽도, 날의 두께도 옆에 놓인 칼과 구분되지 않는다. 마른 우물을 치우던 인부가 진흙 더미에서 한 자루를 건져 올렸는데, 점액에 오래 절어 날이 검붉게 삭아 있었다. 버리려다 한번 닦아 보니 이 빠진 데 하나 없이 멀쩡히 들었고, 인부는 그것을 그냥 허리에 찼다. 이름을 붙인 적도, 누구에게 물려준 적도 없다. 그저 쓸 만해서 오래 쓰였을 뿐, 더 보탤 이야기가 없다.',
    art: `plain one-handed sword, pitted reddish-rusted iron blade, dried swamp mud, leather-wrapped grip, simple crossguard, understated, ${STYLE}`,
  },
  {
    key: 'ashfall_obsidian_dagger',
    slot: 'weapon',
    nameKo: '화산재 흑요석 단검',
    region: '서쪽 화산',
    tone: '기괴',
    lore: '끓는 강 가장자리에서 식다 만 흑요석을 깎아낸 단검이다. 칼날이 거울처럼 검고 매끄러워 들여다보면 제 얼굴이 비치는데, 그 얼굴이 가끔 이쪽이 짓지 않은 표정을 짓는다고 본 사람들은 입을 모은다. 고룡의 숨결을 너무 가까이서 쬔 유리가 무언가를 본 채로 굳어 버린 것이라는 말도 있다. 들여다본 자는 많았고, 두 번 들여다본 자는 드물었으며, 오래 들여다본 자는 끝내 없었다. 칼집에 넣어 두면 안쪽에서 아주 가끔, 유리를 천천히 긁는 듯한 소리가 샌다.',
    art: `short dagger, glassy black obsidian blade, faint distorted reflection, fractured razor edge, charred bone handle, eerie, ${STYLE}`,
  },
  {
    key: 'runescar_warhammer',
    slot: 'weapon',
    nameKo: '룬흉터 전쟁망치',
    region: '고대 룬 산맥',
    tone: '장엄',
    lore: '산이 스스로 몸을 일으키던 날, 무너진 비탈에서 떨어져 나온 한 덩이를 머리 삼아 박은 전쟁망치다. 표면을 가로지른 푸른 룬 균열은 식지 않아, 내려칠 때마다 결을 따라 잠깐 살아났다가 다시 잠든다. 산이 제 분노의 한 줌을 떼어 자루 끝에 묶어 둔 셈이라, 드는 일조차 함부로 할 수 없다. 휘두른 자리에는 한동안 낮은 울림이 땅에 남고, 그 울림이 가실 때까지 곁의 누구도 입을 열지 않는다. 가벼이 들 물건이 아니라는 것을, 다른 누구보다 그것을 든 자가 가장 먼저 깨닫는다.',
    art: `massive two-handed warhammer, grey carved-stone head, vivid blue rune cracks, iron-banded oak haft, monumental, ${STYLE}`,
  },
  {
    key: 'orcfang_cleaver',
    slot: 'weapon',
    nameKo: '오크 송곳니 도끼',
    region: '오크 부락',
    tone: '위트',
    lore: '오크 족장이 손수 만들었다고 두고두고 자랑하던 외날 도끼다. 자루에 제 부러진 어금니를 직접 박아 넣고는, 둘러앉은 부락민에게 "이빨이 둘이면 무는 힘도 둘"이라는 명언을 남겼다고 전한다. 그 말의 앞뒤를 끝내 이해한 자는 부락에 한 명도 없었으나, 족장의 표정이 워낙 진지해 누구도 되묻지 못했다. 박아 넣은 어금니가 무엇을 보탰는지는 알 길이 없지만, 도끼 자체가 부정할 수 없이 잘 든다는 점만은 분명하다. 그 한 가지에 대해서만큼은 족장도, 도끼도 거짓말을 하지 않은 셈이다.',
    art: `one-handed broad cleaver axe, chipped crescent iron blade, large tusk wedged into haft, crude lashings, rugged, ${STYLE}`,
  },
  {
    key: 'fallen_grace_rapier',
    slot: 'weapon',
    nameKo: '타락한 은총의 레이피어',
    region: '타락천사',
    tone: '비애',
    lore: '추락한 자리에 부러져 흩어진 검 조각을 모아, 누군가 그것을 다시 가늘게 두들겨 편 찌르기검이다. 한 날 안에서 신성과 저주가 한데 섞여 흐른다. 휘두르면 아주 잠깐 깃털이 스치는 소리가 나는데, 베인 쪽보다 쥔 쪽이 먼저 그 소리에 손을 멈춘다고 한다. 멈춘 사이 무엇을 떠올리는지는 사람마다 다르지만, 떠올린 뒤의 표정만은 한결같이 닮아 있다. 그래서 이 검을 오래 지닌 자일수록, 점점 그것을 덜 뽑게 된다.',
    art: `slender thrusting rapier, pale silver blade, tarnished gold swept hilt, faint black feather etching, somber elegant, ${STYLE}`,
  },
  {
    key: 'iron_field_sword',
    slot: 'weapon',
    nameKo: '무쇠 야전검',
    region: '자유',
    tone: '일상',
    lore: '병참 창고에 천 자루씩 같은 모양으로 포개져 있던 보급용 한손검이다. 이가 나가면 숫돌에 갈고, 자루 가죽이 닳으면 그 자리에서 새로 감았다. 누구의 것도 아니었으므로, 그날 당번이 집어 든 칼이 그날의 칼이 되었다. 한 자루가 부러지면 다음 자루를 꺼냈고, 부러진 쪽을 두고 멈춰 선 사람은 없었다. 그렇게 수없이 쥐어졌다 놓인 칼이라, 무용담이라 부를 만한 것이 한 줄도 들러붙지 못했다. 이 검에 대해 정직하게 할 수 있는 이야기는 거기까지다.',
    art: `standard-issue one-handed arming sword, straight iron blade, re-wrapped worn grip, plain pommel, utilitarian, ${STYLE}`,
  },
  {
    key: 'wanderer_oak_staff',
    slot: 'weapon',
    nameKo: '방랑자의 떡갈나무 지팡이',
    region: '자유',
    tone: '수수께끼',
    lore: '어느 노인이 평생을 짚고 다녔다는 떡갈나무 지팡이다. 머리에 박힌 흐린 돌은 빛도, 열도, 마법의 기척도 한 번 내보인 적이 없다. 다만 그 노인이 며칠 묵어 간 마을마다 이상하리만치 그해 농사가 잘되었다는 이야기가, 길을 따라 드문드문 남아 있다. 노인은 그 말을 들으면 늘 슬그머니 화제를 돌렸고, 돌이 무엇이냐 물으면 그저 "주워 온 돌"이라고만 했다. 우연이 너무 길게 이어지면 더는 우연이라 부르기 어려워지지만, 그렇다고 다른 이름을 댈 수도 없다. 지팡이는 끝까지 아무 말도 하지 않는다.',
    art: `tall wooden wizard staff, gnarled oak shaft, smooth hand-worn grip, dull clouded stone at crown, enigmatic, ${STYLE}`,
  },
  {
    key: 'hunter_greenwood_bow',
    slot: 'weapon',
    nameKo: '푸른숲 사냥활',
    region: '자유',
    tone: '영웅담',
    lore: '늑대 떼가 마을 외양간을 노리던 그 겨울, 한 사냥꾼이 사흘 밤을 눈밭에 엎드린 끝에 이 활로 우두머리를 잡았다. 마을 사람들은 그를 영웅이라 불렀지만, 정작 그는 활을 손질하며 "운이 좋았고, 마침 추웠을 뿐"이라고만 했다. 시위는 그 사흘 동안 두 번이나 갈렸고, 활대는 그만큼 손에 깊이 익었다. 봄이 와 눈이 다 녹은 뒤에도 시위에서는 그 겨울의 송진 냄새가 좀처럼 가시지 않았다. 사냥꾼은 그 뒤로 활을 벽에 걸어 두기만 했는데, 마을 아이들은 지금도 그 앞을 지날 때 까닭 없이 목소리를 낮춘다.',
    art: `curved wooden recurve shortbow, taut sinew bowstring, frost-pale wood grain, worn grip wrap, vertical, heroic, ${STYLE}`,
  },
  {
    key: 'marsh_reed_spear',
    slot: 'weapon',
    nameKo: '늪 갈대창',
    region: '늪지대',
    tone: '일상',
    lore: '늪 마을에선 집집마다 갈대창 한 자루씩을 문가에 세워 둔다. 아침이면 물뱀을 쫓는 데 쓰고, 한낮엔 늘어진 빨랫줄을 받치는 데 쓰고, 비 오는 밤엔 그냥 처마 밑에 서 있다. 자루는 점액에 오래 절어 검푸르게 굳어, 어지간한 손아귀로는 휘어지지도 않는다. 큰 싸움에 들렸다는 기록은 손에 꼽지만, 빨래를 받친 날만 헤아려도 한 사람의 평생을 넘긴다. 늪에서는 무기와 살림 도구의 경계가 본래 이렇게 흐릿하고, 누구도 그 흐릿함을 굳이 따지지 않는다.',
    art: `long thrusting spear, dark hardened reed shaft, narrow leaf-shaped iron head, doorway-leaning wear, mundane, ${STYLE}`,
  },
  {
    key: 'emberforged_greatsword',
    slot: 'weapon',
    nameKo: '잉걸불 대검',
    region: '서쪽 화산',
    tone: '장엄',
    lore: '화산 대장간에서 가장 깊은 화덕에 넣었다 빼낸 양손 대검이다. 식는 동안 잿빛 결이 날 안쪽으로 강물처럼 굳어, 들어 올리면 그 무늬가 멈춰 버린 불길의 잔영을 닮았다. 한 번 휘두르면 칼이 지나간 자리의 공기가 잠깐 일렁이며 데워진다고, 곁에서 본 자들은 한결같이 말한다. 무겁고 길어 한 호흡에 한 번밖에 휘두를 수 없지만, 그 한 번을 본 자들은 두 번째를 굳이 기다리지 않았다. 칼을 든 쪽도, 마주 선 쪽도 그 한 번이 무슨 뜻인지 같은 순간에 알아챈다.',
    art: `large two-handed greatsword, broad heat-grained steel blade, deep ash river streaks, long wrapped grip, imposing, ${STYLE}`,
  },
  {
    key: 'glass_question_scepter',
    slot: 'weapon',
    nameKo: '물음의 유리홀',
    region: '자유',
    tone: '수수께끼',
    lore: '머리에 속이 빈 유리구가 얹힌 짧은 홀이다. 구 안에는 분명 아무것도 들어 있지 않은데, 가만히 흔들면 무언가 또르르 굴러다니는 소리가 또렷이 난다. 만든 장인도, 오래 쥐었던 주인도, 끝내 그것을 부숴 본 자도, 그 소리의 정체만은 한 사람도 입에 올리지 못했다. 부순 자는 깨진 유리 안에서 끝내 아무것도 찾지 못했고, 그 뒤로 부쩍 말수가 줄었다고 한다. 이 홀은 답을 건네는 물건이 아니라, 질문 하나를 손에 쥐여 주고 정작 답은 가져가 버리는 물건에 가깝다.',
    art: `short ornate scepter, hollow clear glass orb at head, faint something-inside rattle, banded silver shaft, mysterious, ${STYLE}`,
  },
  {
    key: 'orc_bonk_maul',
    slot: 'weapon',
    nameKo: '오크 박치기 둔기',
    region: '오크 부락',
    tone: '위트',
    lore: '오크 부락에서 가장 머리가 나쁜 전사가 "이러면 안 깨지겠지"라며 굵은 관절뼈를 통째로 가죽끈에 동여 만든 둔기다. 모두가 한 번 휘두르면 부서질 거라 장담했는데, 놀랍게도 둔기는 멀쩡했다. 더 놀랍게도 그 전사 본인은 같은 날 전혀 다른 일로 비탈을 굴러 죽었다. 부락에서는 그 일을 두고 한동안 "둔기가 주인보다 튼튼했다"는 말이 농담처럼 돌았다. 둔기는 지금도 흠 하나 없이 멀쩡한 채로, 자기보다는 약할 게 분명한 다음 주인을 느긋이 기다리고 있다.',
    art: `crude heavy bludgeon, single huge joint-bone head, thick leather lashings, lopsided, comically brutal, ${STYLE}`,
  },
  {
    key: 'parted_twin_daggers',
    slot: 'weapon',
    nameKo: '엇갈린 쌍단검',
    region: '자유',
    tone: '비애',
    lore: '본래 한 쌍이었다. 두 자매가 하나씩 나눠 가졌고, 길이 갈라지던 날 언젠가 다시 두 자루를 맞대기로 약속했다. 지금 남은 것은 한 자루뿐이다. 짝을 잃은 칼은 무게중심이 미세하게 어긋나 있어, 쥔 손이 자꾸만 비어 있는 다른 손을 찾는다. 그 어긋남에 익숙해질 무렵이면, 사람은 대개 약속도 함께 잊는다. 나머지 한 자루가 지금 어느 손에 있는지, 혹은 어느 흙 속에 있는지는 이 칼도 알지 못한다.',
    art: `single curved dagger, faint mark where a twin once paired, dark wrapped handle, slightly off-balance, lonesome, ${STYLE}`,
  },
  {
    key: 'tollkeeper_glaive',
    slot: 'weapon',
    nameKo: '통행세 받던 언월도',
    region: '자유',
    tone: '일상',
    lore: '다리 어귀에서 통행세를 걷던 늙은 문지기가 평생 곁에 둔 언월도다. 실제로 휘두른 날은 한 손에 꼽을 정도고, 대부분의 세월은 그저 초소 벽에 비스듬히 기대 세워져 있었다. 날에 앉은 흙먼지가 칼날 두께보다 두껍다는 농담이 다리 마을에 오래 돌았다. 그래도 다리를 건넌 누구도, 아무리 급하고 험한 자라도, 그 칼 앞에서 떼를 쓰거나 셈을 속이지는 못했다. 문지기가 떠난 뒤에도 그 버릇만은 마을에 남았다.',
    art: `polearm glaive, long worn wooden shaft, single curved blade thick with road dust, leaning-post wear, mundane, ${STYLE}`,
  },
  {
    key: 'fallen_feather_scythe',
    slot: 'weapon',
    nameKo: '깃 떨군 낫',
    region: '타락천사',
    tone: '기괴',
    lore: '추락한 자리에 검은 깃이 눈처럼 두껍게 쌓였고, 누군가 그 깃과 부러진 날개뼈를 모아 낫자루를 칭칭 감았다. 이 낫으로 풀을 베면, 베어 넘긴 자리에서 가끔 검은 깃털 한두 올이 풀과 함께 떨어진다—깃 같은 것을 심은 적 없는 자리에서도. 그 깃이 어디서 오는지 캐물은 자는 며칠 잠을 설쳤고, 그래서 늦게 배운 이들은 거두는 동안 발밑을 굳이 내려다보지 않는 법을 먼저 익힌다. 그것이 무엇의 깃인지는, 묻지 않을수록 오래 쓴다.',
    art: `war scythe, long curved blade, black feather-bound shaft, pale wing-bone fittings, unsettling, ${STYLE}`,
  },
  {
    key: 'butcher_falchion',
    slot: 'weapon',
    nameKo: '푸줏간 팔치온',
    region: '자유',
    tone: '위트',
    lore: '원래는 시장통 푸줏간에서 뼈마디를 끊던 넓적칼이다. 주인이 밀린 외상값을 받으러 나갔다가 영영 돌아오지 않은 뒤로, 칼은 손에서 손으로 여럿을 거쳤다. 무기로 쓰기엔 너무 둔하고 무겁다는 평이 따라다녔는데, 묘하게도 그 평을 입에 올린 자들은 하나같이 나중에 그 둔한 칼에 한 번씩 혼쭐이 났다. 어떤 물건은 잘 드는 것보다 만만해 보이는 쪽이 더 무섭다. 이 칼이 딱 그렇다.',
    art: `wide heavy falchion, broad cleaver-like steel blade, nicked edge, plain wooden grip, butcher-tool origin, ${STYLE}`,
  },
  {
    key: 'dawn_charge_saber',
    slot: 'weapon',
    nameKo: '여명 돌격 사브르',
    region: '자유',
    tone: '영웅담',
    lore: '안개가 채 걷히지 않은 새벽, 스무 기의 기병이 이 사브르를 맨 앞에 세우고 세 배가 넘는 적진 한가운데를 가로질러 갈랐다. 돌격이 끝났을 때 안장에 다시 앉은 자는 절반이었으나, 그들이 지키던 깃발만은 끝내 땅에 닿지 않았다. 살아남은 기병들은 그날 일을 거의 입에 올리지 않았고, 다만 이 사브르를 손질할 때면 평소보다 한참을 더 닦았다. 곡선진 날을 빛에 비추면, 닦아도 지워지지 않는 그날의 흙빛이 결을 따라 얇게 남아 있다.',
    art: `curved cavalry saber, slender single-edged blade, brass knuckle-guard, faded ribbon on hilt, heroic, ${STYLE}`,
  },
  {
    key: 'marsh_hook_sickle',
    slot: 'weapon',
    nameKo: '늪 갈고리 낫',
    region: '늪지대',
    tone: '기괴',
    lore: '뱀장어잡이가 진흙 구멍에 던져 넣고 잡아채던 갈고리 낫이다. 손맛이 오면 단번에 끌어올리는 것이 이 일의 전부였고, 그는 그 손맛을 누구보다 잘 알았다. 그런데 어느 밤부터, 분명 비어 있어야 할 구멍에서도 줄이 팽팽해지며 무언가가 마주 잡아당기기 시작했다. 끌어올리면 갈고리에는 늘 아무것도 없었다. 어부는 결국 낫을 그 자리에 박아 둔 채 늪을 떠났고, 낫은 지금도 가끔, 바람도 없는 밤에 저 혼자 천천히 흔들린다고 한다.',
    art: `hooked sickle, curved barbed iron hook, mud-caked short handle, frayed pull-cord, eerie swamp, ${STYLE}`,
  },
  {
    key: 'orc_horn_club',
    slot: 'weapon',
    nameKo: '오크 뿔나팔 곤봉',
    region: '오크 부락',
    tone: '일상',
    lore: '오크 부락 신호병이 매일 새벽 가장 먼저 들고 나가던 곤봉이다. 끝에 동여맨 뿔나팔로 교대 시각을 알리고, 단단한 자루로는 밤사이 헐거워진 천막 말뚝을 다시 박았다. 부락의 하루는 이 곤봉 소리로 열려, 같은 곤봉 소리로 닫혔다. 신호병이 셋이나 바뀌는 동안에도 그 순서만은 한 번도 어긋난 적이 없다. 휘둘러 적을 친 기억보다 말뚝을 박은 기억이 압도적으로 많은, 그저 부락의 평범한 하루 같은 물건이다.',
    art: `crude wooden club, horn trumpet lashed to the head, stake-driving wear, leather wrap, mundane, ${STYLE}`,
  },
  {
    key: 'rune_split_longsword',
    slot: 'weapon',
    nameKo: '룬으로 갈라진 장검',
    region: '고대 룬 산맥',
    tone: '기괴',
    lore: '날 한가운데가 룬의 결을 따라 길게 갈라진 장검이다. 갈라졌는데도 부러지지 않고, 그 틈이 닫히지도 않는다. 빛에 비춰 그 틈을 들여다보면, 분명 손가락 두 마디 두께의 칼인데 한참 더 깊은 어딘가까지 시선이 빨려 들어간다. 오래 들여다본 자는 거기서 무언가가 이쪽을 마주 보고 있었다고 했고, 그 말을 한 자 중 누구도 두 번째로 들여다보지 않았다. 칼은 멀쩡히 잘 든다. 다만 사람들은 그 틈 쪽으로는 좀처럼 손을 가져가지 않는다.',
    art: `long straight longsword, deep crack splitting the blade lengthwise, unnaturally deep gap, stone-grey temper, eerie, ${STYLE}`,
  },
  {
    key: 'widow_estoc',
    slot: 'weapon',
    nameKo: '미망인의 에스톡',
    region: '자유',
    tone: '비애',
    lore: '결투로 남편을 잃은 여인이, 그 빚을 갚기 위한 다음 결투를 앞두고 손에 쥐었던 가늘고 곧은 찌르기검이다. 그 결투에서 그가 이겼는지 졌는지, 살아 돌아왔는지조차 어디에도 기록이 남지 않았다. 검만이 한참 뒤에 한 고물상의 궤짝에서 발견됐다. 검집 안쪽에는 칼끝으로 눌러 쓴 듯한 글씨 한 줄이 있었는데, "이번이 마지막"이라는 다섯 글자였다. 그 말이 결투를 가리킨 것인지, 결혼을 가리킨 것인지는 이제 아무도 묻지 못한다.',
    art: `long rigid estoc, narrow needle-like thrusting blade, plain dark hilt, worn engraved scabbard motif, mournful, ${STYLE}`,
  },
  {
    key: 'ember_falx',
    slot: 'weapon',
    nameKo: '잉걸 팔크스',
    region: '서쪽 화산',
    tone: '장엄',
    lore: '안으로 휘어든 한날의 팔크스다. 대장장이는 흘러내리던 용암이 식으며 땅에 파 놓은 골을 그대로 거푸집 삼아 이 칼을 부어 만들었다고 한다. 그래서 날 안쪽 곡선에는 불이 흐르던 결이 영원히 굳은 채 박혀 있고, 빛을 받으면 그 곡면을 따라 시선이 자꾸 미끄러진다. 곧게 내려치는 칼이 아니라, 휜 안쪽으로 상대를 끌어당겨 가르는 칼이다. 한 번 걸리면 빠져나가는 쪽이 더 깊이 베인다는 것을, 마주 서 본 자들이 뒤늦게 깨닫는다.',
    art: `inward-curved falx blade, single hooked edge, fire-grained dark steel, long two-handed grip, imposing, ${STYLE}`,
  },
  {
    key: 'ledger_quarterstaff',
    slot: 'weapon',
    nameKo: '장부 지팡이',
    region: '자유',
    tone: '일상',
    lore: '세금을 걷으러 마을마다 도는 서기가 평생 짚고 다닌 물푸레 봉이다. 한쪽 끝에는 잉크병을 매달아 다니던 끈이 닳긴 자국이, 반대쪽 끝에는 길에서 달려드는 개를 쫓느라 생긴 흠집이 잔뜩 남았다. 누구도 이 봉을 무기라 부른 적은 없다. 그런데도 마을 사람들은 이 봉이 장부 위에 탁 놓이는 순간만큼은, 어쩐 일인지 셈을 한 푼도 속이지 못했다. 서기가 늙어 일을 놓은 뒤에도, 그 봉이 기대 서 있던 관아 벽 자리만은 한참 비워져 있었다.',
    art: `plain ash quarterstaff, ink-stained one end, dog-chasing scuffs, smooth worn middle grip, mundane, ${STYLE}`,
  },
  {
    key: 'feather_kris',
    slot: 'weapon',
    nameKo: '깃 흘린 크리스',
    region: '타락천사',
    tone: '수수께끼',
    lore: '날이 물결처럼 여러 번 굽이친 단검이다. 칼집을 열 때마다 검은 깃 한 올이 어디선가, 늘 한 올씩만 떨어진다. 한 수집가가 그 깃을 하루도 빠짐없이 작은 상자에 모았다. 한 해가 지나 세어 보니 깃은 분명 가지런히 쌓여 있는데, 며칠 뒤 다시 세면 그 수가 늘 달라져 있었다. 더 넣은 적도, 빼낸 적도, 누가 손댄 적도 없다. 그는 결국 세는 일을 그만두었고, 상자도 더는 열지 않았다. 단검만은 여전히, 열 때마다 한 올씩이다.',
    art: `wavy-bladed kris dagger, rippling pattern-welded steel, dark bound handle, single black feather, mysterious, ${STYLE}`,
  },
  {
    key: 'mistwood_longbow',
    slot: 'weapon',
    nameKo: '안개숲 장궁',
    region: '자유',
    tone: '영웅담',
    lore: '국경의 안개숲을 혼자 지키던 순찰자의 장궁이다. 짙은 안개 속에서 길을 잃은 행상들을 향해, 그는 방향만 알려 주는 신호 화살을 쏘아 올렸다. 그렇게 살아 돌아온 사람의 수가 마흔이라는 이야기가 마을마다 조금씩 다르게—어디선 서른여덟, 어디선 마흔둘—전해진다. 정작 순찰자 본인은 어느 숫자도 한 번 바로잡지 않았다. 셈이 중요한 게 아니라고 여겼거나, 혹은 자기도 정확히는 몰랐을 것이다. 시위를 당기는 소리만은 안개 너머에서도 또렷이 들렸다고, 살아 온 자들은 입을 모은다.',
    art: `tall slender longbow, pale mist-grey wood, taut string, simple leather grip, vertical, heroic, ${STYLE}`,
  },
  {
    key: 'tunnel_war_pick',
    slot: 'weapon',
    nameKo: '갱도 전투곡괭이',
    region: '자유',
    tone: '일상',
    lore: '광부가 막장에서 돌을 쪼던 곡괭이다. 갱이 무너진 날, 그것으로 벽을 두드려 사흘 만에 구조 신호를 보냈다. 이후로 누구도 그걸 광구 도구라 부르지 않았지만, 정작 곡괭이는 여전히 돌 깨는 데 가장 잘 든다.',
    art: `heavy war pick, single curved spike head, blunt back, rock-scarred iron, sturdy wooden haft, utilitarian, ${STYLE}`,
  },
  {
    key: 'dream_answer_orb_staff',
    slot: 'weapon',
    nameKo: '꿈으로 답하는 구슬홀',
    region: '자유',
    tone: '수수께끼',
    lore: '머리에 탁한 구슬을 얹은 홀. 들고 잔 사람은 다음 날 아침, 묻지 않은 질문의 답을 알고 깬다고 한다. 정작 그 답이 무슨 질문에 대한 것인지는 끝내 모른다. 답이 먼저 오고 질문이 나중에 온다.',
    art: `tall staff, cloudy pale orb cradled at the head, twisted dark shaft, faint inner haze, mysterious, ${STYLE}`,
  },
  {
    key: 'bog_frog_trident',
    slot: 'weapon',
    nameKo: '늪 개구리 작살',
    region: '늪지대',
    tone: '위트',
    lore: '늪 마을 아이들이 개구리 잡기 내기를 하던 세 갈래 작살. 가장 많이 잡은 아이가 그날의 대장이 되는 규칙이었다. 정작 이 작살의 주인은 평생 한 마리도 못 잡았는데, 어쩐 일인지 늘 대장이었다. 아무도 그 이유는 캐묻지 않았다.',
    art: `three-pronged fishing trident, long worn wooden shaft, simple iron tines, marsh wear, playful, ${STYLE}`,
  },
  {
    key: 'jester_morningstar',
    slot: 'weapon',
    nameKo: '광대의 별곤봉',
    region: '자유',
    tone: '위트',
    lore: '떠돌이 광대가 "웃기려고" 들고 다니던 가시 박힌 별곤봉. 공연에선 한 번도 휘두르지 않았고, 늘 들고만 다녔다. 그런데 그 광대가 머문 마을에서는 이상하게 시비가 줄었다. 소품이라기엔 가시가 너무 진짜였다.',
    art: `spiked ball morningstar on a short haft, jingling tiny bells on the chain, worn grip, ironic playful menace, ${STYLE}`,
  },
  {
    key: 'ashen_nodachi',
    slot: 'weapon',
    nameKo: '잿빛 노다치',
    region: '서쪽 화산',
    tone: '장엄',
    lore: '키를 넘는 길이로 벼린 대태도. 화산 열기에 식히는 동안 날 전체에 잿빛 물결무늬가 번져, 휘두르면 그 무늬가 따라 흐르는 듯 보인다. 한 호흡에 한 번밖에 휘두를 수 없으나, 그 한 번이면 충분하다고들 했다.',
    art: `very long two-handed nodachi, slender heat-rippled ash-grey blade, long wrapped grip, sweeping imposing, ${STYLE}`,
  },
  {
    key: 'unsent_letter_dagger',
    slot: 'weapon',
    nameKo: '부치지 못한 편지칼',
    region: '자유',
    tone: '비애',
    lore: '본래 편지 봉투를 가르던 가느다란 칼이다. 주인이 끝내 부치지 못한 편지 한 장과 함께 서랍에서 발견됐다. 편지는 백지였다. 칼날은 한 번도 종이 말고 다른 것을 가른 적 없는데, 이상하게 손에 들면 무겁다.',
    art: `slim letter-opener dagger, thin polished blade, simple bone handle, desk-drawer patina, melancholic, ${STYLE}`,
  },
  {
    key: 'rune_echo_maul',
    slot: 'weapon',
    nameKo: '룬 메아리 큰망치',
    region: '고대 룬 산맥',
    tone: '수수께끼',
    lore: '머리를 산의 돌로 깎은 큰망치. 내려치지 않아도, 귀를 대면 아주 낮은 한 음이 끝없이 울린다. 그 음을 따라 흥얼거린 자들은 하나같이 같은 가락을 떠올렸다는데, 누구도 그 노래를 배운 적이 없다.',
    art: `heavy stone-headed maul, faint resonant hum lines etched in the rock, banded haft, enigmatic ancient, ${STYLE}`,
  },
  {
    key: 'orc_junk_flail',
    slot: 'weapon',
    nameKo: '오크 잡동사니 도리깨',
    region: '오크 부락',
    tone: '영웅담',
    lore: '냄비며 문고리를 사슬 끝에 매단 볼품없는 도리깨. 부락 어귀가 뚫리던 날, 가장 어린 전사가 이것 하나로 무너진 틈을 메우고 끝까지 버텼다. 잡동사니가 부딪는 소리가 그날따라 물러서지 말라는 북소리처럼 들렸다고, 살아남은 자들은 입을 모은다.',
    art: `chain flail, mismatched pot lid and door ring and half-helmet bound at the end, battle-clattered, heroic scrappy, ${STYLE}`,
  },
  {
    key: 'shepherd_sling',
    slot: 'weapon',
    nameKo: '목동의 무릿매',
    region: '자유',
    tone: '일상',
    lore: '양치기 소년이 늑대를 쫓던 가죽 무릿매. 짐승을 맞힌 적은 손에 꼽지만, 돌이 휙 날아가는 소리만으로 무리를 흩어 놓기엔 충분했다. 양 한 마리 잃지 않고 한 해를 넘긴 도구치고는, 너무 소박하게 생겼다.',
    art: `simple leather sling, worn pouch, two braided cords, smooth river stone, humble pastoral, ${STYLE}`,
  },
  {
    key: 'scaled_guard_glaive',
    slot: 'weapon',
    nameKo: '비늘 막은 언월도',
    region: '서쪽 화산',
    tone: '영웅담',
    lore: '고룡의 숨결 앞에 마지막까지 줄을 지킨 창병의 언월도. 날에는 비늘에 긁힌 깊은 골이 셋, 자루에는 그날 잡았던 손자국이 그을려 남았다. 창병은 살아남았고, 언월도는 그 이야기를 대신 짊어졌다.',
    art: `polearm glaive, long curved blade with three deep scale-gouges, scorched grip, sturdy shaft, heroic, ${STYLE}`,
  },
  {
    key: 'crossroad_crook',
    slot: 'weapon',
    nameKo: '갈림길 지팡이',
    region: '자유',
    tone: '수수께끼',
    lore: '끝이 갈고리처럼 굽은 양치기 지팡이. 평지에서는 멀쩡하나 갈림길에 세워 두면 굽은 끝이 늘 가지 말아야 할 길을 가리킨다고 한다. 그 말을 시험한 자들은 돌아와 아무 말도 하지 않았다.',
    art: `long shepherd's crook staff, hooked curved top, pale worn wood, plain banding, quietly uncanny, ${STYLE}`,
  },
  {
    key: 'last_gate_partisan',
    slot: 'weapon',
    nameKo: '마지막 문지기의 파르티잔',
    region: '자유',
    tone: '비애',
    lore: '성문이 무너지던 밤, 끝까지 자리를 뜨지 않은 늙은 위병의 폭넓은 창. 다른 이들은 모두 안쪽으로 물러섰고, 그는 문턱을 한 발도 넘지 않았다. 날 밑동에 짧게 새겨진 글자는 이름이 아니라 "여기까지"였다.',
    art: `broad-bladed partisan polearm, wide leaf spearhead with side lugs, worn shaft, faint carved words, mournful, ${STYLE}`,
  },
  {
    key: 'dredge_bone_pick',
    slot: 'weapon',
    nameKo: '준설 뼈곡괭이',
    region: '자유',
    tone: '기괴',
    lore: '강바닥을 긁어 올리던 준설꾼이, 진흙에서 함께 딸려 온 길고 흰 것을 자루에 박아 만든 곡괭이. 그게 무슨 뼈인지 묻는 사람에게 그는 늘 화제를 돌렸다. 곡괭이는 잘 들었고, 준설꾼은 다시는 그 강에 들어가지 않았다.',
    art: `war pick, long pale bone spike as the head, riveted to a plain haft, river silt stains, unsettling, ${STYLE}`,
  },
  {
    key: 'carnival_chakram',
    slot: 'weapon',
    nameKo: '곡예단 차크람',
    region: '자유',
    tone: '위트',
    lore: '유랑 곡예단에서 접시 대신 돌리던 둥근 고리날. 단장이 "이건 묘기용"이라 우겼지만, 가장자리는 접시를 자를 일이 없을 만큼 날카로웠다. 곡예가 끝나면 늘 한 개씩 사라졌고, 단장은 그 이야기를 꺼내면 표정이 굳었다.',
    art: `flat circular chakram throwing ring, sharpened outer edge, polished steel, small grip wrap, showy ironic, ${STYLE}`,
  },
  {
    key: 'oathline_halberd',
    slot: 'weapon',
    nameKo: '맹세 줄의 할버드',
    region: '자유',
    tone: '영웅담',
    lore: '같은 맹세를 한 열두 명이 어깨를 맞대고 세웠던 방벽, 그 한가운데에 박혀 있던 할버드. 줄이 무너지지 않는 한 이 한 자루도 쓰러지지 않는다는 약속이 있었다. 줄은 그날 끝까지 무너지지 않았다.',
    art: `tall halberd, axe blade with spike and hook, long banded shaft, frayed oath-cord tied below the head, heroic, ${STYLE}`,
  },
  {
    key: 'woodcutter_hatchet',
    slot: 'weapon',
    nameKo: '나무꾼 손도끼',
    region: '자유',
    tone: '담백',
    lore: '겨울 땔감을 패던 손도끼. 날은 자주 갈려 손바닥만큼 작아졌고, 자루는 세 번 갈아 끼웠다. 큰일을 해낸 적은 없다. 다만 그 집 아궁이는 어느 겨울에도 식은 적이 없었다.',
    art: `small one-handed hatchet, short worn axe head, oft-replaced wooden handle, woodchip nicks, plain, ${STYLE}`,
  },
  {
    key: 'fallen_censer_flail',
    slot: 'weapon',
    nameKo: '타락한 향로 도리깨',
    region: '타락천사',
    tone: '장엄',
    lore: '추락한 성가대가 받들던 향로를 사슬 끝에 매단 도리깨. 휘두르면 불 없이 향이 피어오르고, 그 연기가 닿은 자리에서는 아주 잠깐 모두가 까닭 없이 고개를 숙인다고 한다. 무엇 앞에 숙이는지는 누구도 묻지 않는다.',
    art: `chain flail with a great thurible censer at the end, fireless rising incense, tarnished gilt metal, solemn imposing, ${STYLE}`,
  },
  {
    key: 'nightwatch_spear',
    slot: 'weapon',
    nameKo: '야경꾼의 창',
    region: '자유',
    tone: '일상',
    lore: '도시 야경꾼이 골목을 돌 때 들던 평범한 창. 실전에 쓴 밤보다 벽에 비스듬히 기대 둔 밤이 훨씬 많았다. 그래도 그 창이 골목 어귀에 서 있는 한, 그 동네 사람들은 등을 켜 두지 않고 잤다.',
    art: `plain watchman's spear, simple leaf-shaped head, long worn shaft, leaning-wear scuff, mundane reassuring, ${STYLE}`,
  },
  {
    key: 'rune_needle_rapier',
    slot: 'weapon',
    nameKo: '룬 바늘 레이피어',
    region: '고대 룬 산맥',
    tone: '비애',
    lore: '산의 돌결을 따라 바늘처럼 가늘게 벼린 찌르기검. 이것을 벼린 장인은 마지막 한 자루를 끝내 누구에게도 넘기지 않고 끌어안은 채 발견됐다. 검에는 흠 하나 없었고, 장인의 손은 펴지지 않았다.',
    art: `extremely slender rapier, needle-thin blade, faint hairline rune lines, fine swept guard, mournful, ${STYLE}`,
  },
  {
    key: 'grandfather_axe',
    slot: 'weapon',
    nameKo: '할아버지의 그 도끼',
    region: '자유',
    tone: '위트',
    lore: '손자는 이것을 "할아버지가 쓰시던 도끼"라며 자랑한다. 다만 날은 두 번, 자루는 세 번 갈아 끼웠다. 따지자면 할아버지가 손댄 부분은 단 한 군데도 남지 않은 셈이다. 그런데도 손자에게 이것은, 여전히 변함없이 할아버지의 도끼다.',
    art: `well-used one-handed axe, obviously newer head on a re-handled shaft, mismatched wear, homely ironic, ${STYLE}`,
  },
  {
    key: 'silt_anchor_flail',
    slot: 'weapon',
    nameKo: '진흙 닻 도리깨',
    region: '자유',
    tone: '기괴',
    lore: '강 사공이 작은 닻을 사슬에 매어 휘두르던 도리깨. 어느 날 그 닻이 바닥에서 끌어 올린 것을 본 뒤로, 사공은 노 젓는 자리를 옮겼다. 닻은 아직 진흙을 머금고 있고, 가끔 마른 진흙이 저 혼자 떨어진다.',
    art: `chain flail with a small rusted boat anchor as the head, dried river silt clumps, frayed chain, ominous, ${STYLE}`,
  },
  {
    key: 'herald_banner_poleaxe',
    slot: 'weapon',
    nameKo: '전령의 깃대 폴액스',
    region: '자유',
    tone: '영웅담',
    lore: '전령은 본래 싸우지 않는다. 그러나 깃발이 쓰러지면 줄도 무너지기에, 이 전령은 깃대 끝에 도끼날을 박고 끝까지 그 자리에 섰다. 깃천은 누더기가 되었어도 깃대는 한 번도 기울지 않았다.',
    art: `poleaxe with a banner-pole haft, axe head and top spike, tattered banner remnant near the top, heroic, ${STYLE}`,
  },
  {
    key: 'scorched_reaping_hook',
    slot: 'weapon',
    nameKo: '그을린 거둠낫',
    region: '자유',
    tone: '담백',
    lore: '불 지나간 밭에서 타다 만 그루터기를 베어 정리하던 한손 낫. 화려한 사연은 없다. 다만 그 밭은 이듬해 다시 푸르렀고, 낫은 그 일을 묵묵히 거들었을 뿐이다.',
    art: `one-handed reaping hook, short inward-curved blade, soot-darkened edge, plain wooden grip, understated, ${STYLE}`,
  },
  {
    key: 'lullaby_war_fan',
    slot: 'weapon',
    nameKo: '자장가 부르는 철선',
    region: '자유',
    tone: '수수께끼',
    lore: '살에 날을 숨긴 무쇠 부채. 펴고 접을 때 아주 희미한 가락이 새는데, 늙은이들은 그게 아주 오래된 자장가라 했다. 누가 그 노래를 부채에 넣었는지는 모른다. 듣고 졸지 않은 사람도 아직 없다.',
    art: `folding iron war fan, hidden blade edges on the ribs, faint humming when opened, lacquered dark, mysterious, ${STYLE}`,
  },
  {
    key: 'deserter_shortsword',
    slot: 'weapon',
    nameKo: '탈영병의 단검',
    region: '자유',
    tone: '비애',
    lore: '더는 싸우지 않으려고 누군가 길섶에 던져 버린 짧은 검. 던진 손은 끝내 돌아오지 않았고, 검은 풀숲에서 다음 사람을 기다렸다. 칼자루의 끈은 누가 급히 풀어낸 듯 매듭이 반쯤 끊겨 있다.',
    art: `plain short sword, blade half-buried look, grass-worn finish, hilt cord with a half-cut knot, sorrowful, ${STYLE}`,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// 방어구 (목표 50)
// ─────────────────────────────────────────────────────────────────────────────
const ARMOR: CatalogItem[] = [
  {
    key: 'militia_gambeson',
    slot: 'armor',
    nameKo: '민병대 누비갑옷',
    region: '자유',
    tone: '일상',
    lore: '마을 민병대가 돌려 입던 두툼한 누비 상의. 봄에는 누가 흘린 국물이, 가을에는 짚 부스러기가 솔기에 박혀 있다. 화려한 방어구는 아니지만, 이걸 입은 사람들이 마을을 몇 번이나 지켰다.',
    art: `quilted padded gambeson coat, faded patched cloth, stitched seams, worn collar, mundane, ${STYLE}`,
  },
  {
    key: 'marsh_reed_cuirass',
    slot: 'armor',
    nameKo: '늪 갈대 흉갑',
    region: '늪지대',
    tone: '담백',
    lore: '늪지대 어부들이 갈대를 겹겹이 엮어 굳힌 가벼운 가슴받이. 물에 젖어도 무거워지지 않게 만든 게 전부의 묘리다. 멋은 없고, 비린내가 좀 난다. 그래도 늪에서 그만한 게 없다.',
    art: `woven hardened reed cuirass, layered dried marsh reeds, simple cord ties, light, plain, ${STYLE}`,
  },
  {
    key: 'runefall_breastplate',
    slot: 'armor',
    nameKo: '룬 낙석 흉갑',
    region: '고대 룬 산맥',
    tone: '장엄',
    lore: '산이 일어서던 날 굴러떨어진 바위판을 가슴 모양으로 깎아낸 흉갑이다. 표면을 가로지른 푸른 룬 균열은 닫히지 않으나, 그 무게를 견디고 선 자는 한 발도 밀리지 않는다. 입는 것이 아니라 짊어지는 갑옷이다.',
    art: `heavy stone-slab breastplate, blue rune cracks across the chest, rough hewn edges, monumental, ${STYLE}`,
  },
  {
    key: 'orc_scrap_harness',
    slot: 'armor',
    nameKo: '오크 고철 갑주',
    region: '오크 부락',
    tone: '비애',
    lore: '돌아오지 못한 전사들의 갑옷에서 가장 성한 조각만 떼어 한데 묶은 갑주. 부락에서는 누군가 쓰러질 때마다 그 한 조각을 여기 더한다. 그래서 이 갑주가 무거워질수록, 부락의 빈자리도 꼭 그만큼 늘어 있었다.',
    art: `patched scrap-metal harness, mismatched salvaged plates lashed with leather, dull worn, somber, ${STYLE}`,
  },
  {
    key: 'fallen_feather_mantle',
    slot: 'armor',
    nameKo: '깃털 두른 망토',
    region: '타락천사',
    tone: '비애',
    lore: '추락한 자리에 검은 깃이 눈처럼 쌓였고, 누군가 그것을 주워 어깨망토로 엮었다. 깃 사이로 옅은 온기가 아직 돌아, 두른 이들은 종종 등 뒤에서 누가 부르는 듯한 기분이 든다고 한다. 돌아보면 아무도 없다.',
    art: `shoulder mantle cloak, layered black feathers, faded gold-thread trim, pale grey sheen, draped, mournful, ${STYLE}`,
  },
  {
    key: 'ember_slag_cuirass',
    slot: 'armor',
    nameKo: '잉걸 슬래그 흉갑',
    region: '서쪽 화산',
    tone: '장엄',
    lore: '용암이 식다 만 슬래그를 다시 녹여 가슴판으로 벼린 흉갑. 표면에 불의 흐름이 그대로 굳어, 들어 올리면 무늬가 천천히 일렁이는 듯 보인다. 한 번 데워지면 좀처럼 식지 않아, 한겨울에도 가슴팍이 미지근하다.',
    art: `forged volcanic slag cuirass, swirling fire-grained dark metal, heavy riveted plates, imposing, ${STYLE}`,
  },
  {
    key: 'nightwatch_cloak',
    slot: 'armor',
    nameKo: '야경꾼 망토',
    region: '자유',
    tone: '일상',
    lore: '도시 야경꾼이 비 오는 밤을 견디려 두르던 기름 먹인 망토. 칼을 막은 밤보다 비를 막은 밤이 천 배는 많았다. 밑단이 늘 축축하고, 등불 그을음 냄새가 가시지 않는다.',
    art: `oilcloth watch cloak, dark waxed fabric, frayed wet hem, soot-stained shoulders, mundane, ${STYLE}`,
  },
  {
    key: 'widow_veil_shroud',
    slot: 'armor',
    nameKo: '미망인의 면사 두름',
    region: '자유',
    tone: '비애',
    lore: '상복의 면사를 벗지 않은 채 전장에 선 여인이 둘렀던 얇은 천 갑옷. 두께로 막는 것이 아니라, 그 앞에 선 자가 차마 손을 못 댔다는 이야기가 더 많이 남았다.',
    art: `thin layered veil-shroud over light armor, pale gauzy fabric, mourning grey, draped, sorrowful, ${STYLE}`,
  },
  {
    key: 'graverobber_coat',
    slot: 'armor',
    nameKo: '도굴꾼 외투',
    region: '자유',
    tone: '기괴',
    lore: '안주머니가 유난히 많은 긴 외투. 도굴꾼이 죽은 뒤 발견됐을 때, 그가 직접 꿰맨 적 없는 주머니 몇 개가 더 늘어 있었다고 한다. 그 안에 무엇이 들었는지는, 입은 사람마다 다르게 말한다.',
    art: `long many-pocketed coat, dark worn leather, uneven extra-stitched pockets, grimy, unsettling, ${STYLE}`,
  },
  {
    key: 'hero_dented_breastplate',
    slot: 'armor',
    nameKo: '영웅의 찌그러진 흉갑',
    region: '자유',
    tone: '영웅담',
    lore: '심장 바로 위가 깊게 움푹 들어간 흉갑. 그 한 방이면 끝났어야 했는데, 끝나지 않았다. 본인은 무용담을 묻는 사람마다 화제를 돌렸지만, 그 자국만큼은 끝내 펴지 않고 그대로 두었다.',
    art: `steel breastplate with a deep dent over the heart, polished elsewhere, plain straps, heroic, ${STYLE}`,
  },
  {
    key: 'blank_question_helm',
    slot: 'armor',
    nameKo: '물음표 투구',
    region: '자유',
    tone: '수수께끼',
    lore: '눈구멍도 숨구멍도 없는 매끈한 투구. 그런데 쓴 자들은 하나같이 앞이 더 또렷이 보인다고 했다. 무엇으로 보는지를 물으면, 그들은 잠깐 말이 없다가 다른 이야기를 시작한다.',
    art: `featureless smooth full helm, no visible eye-slit, polished blank surface, enigmatic, ${STYLE}`,
  },
  {
    key: 'bog_hide_jerkin',
    slot: 'armor',
    nameKo: '늪 가죽 저고리',
    region: '늪지대',
    tone: '영웅담',
    lore: '늪을 통째로 삼킨다는 그 큰 것이 한 정찰대를 진흙 속으로 끌고 들어간 밤, 단 한 사람이 이 가죽 저고리만 걸친 채 기어 나왔다. 본인은 운이었다고만 했다. 그 뒤로 늪 사람들은 이 저고리를 아무에게나 빌려주지 않는다.',
    art: `short beast-hide jerkin, supple dark leather, deep claw scars, simple lacing, swamp-tanned, heroic, ${STYLE}`,
  },
  {
    key: 'jester_patch_armor',
    slot: 'armor',
    nameKo: '광대 누더기 갑옷',
    region: '자유',
    tone: '위트',
    lore: '천 조각을 우스꽝스럽게 기워 붙인 광대의 "갑옷". 공연 소품인 줄 알았는데, 어느 날 술집 시비에서 진짜로 칼 한 번을 막았다. 그 뒤로 광대는 더 의기양양해졌고, 갑옷은 더 누더기가 되었다.',
    art: `patchwork cloth armor, clashing colorful patches, jingling trim, lopsided padding, comical, ${STYLE}`,
  },
  {
    key: 'rune_hush_helm',
    slot: 'armor',
    nameKo: '룬 침묵 투구',
    region: '고대 룬 산맥',
    tone: '수수께끼',
    lore: '안쪽에 룬 결이 새겨진 투구. 쓰는 순간 바깥의 모든 소리가 한 겹 멀어지고, 대신 아주 낮은 한 음이 머릿속에 깔린다. 그 음을 오래 들은 자들은 말수가 줄었다.',
    art: `closed helm with inner rune-etched lining, plain stone-grey exterior, muffled aura, mysterious, ${STYLE}`,
  },
  {
    key: 'orc_skull_cap',
    slot: 'armor',
    nameKo: '오크 두개 투구',
    region: '오크 부락',
    tone: '기괴',
    lore: '아주 큰 무언가의 두개골을 깎아 만든 투구. 오크들도 정확히 무엇의 머리였는지는 말을 아낀다. 누가 써도 한 치쯤 헐겁고, 그 빈 한 치에서 가끔 바람 새는 소리가 난다.',
    art: `helmet carved from a large pale skull, hollow eye-cavities patched, bone-grey, eerie, ${STYLE}`,
  },
  {
    key: 'pilgrim_travel_robe',
    slot: 'armor',
    nameKo: '순례자 여행복',
    region: '자유',
    tone: '일상',
    lore: '밑단이 길의 흙으로 늘 거뭇한 순례자의 겉옷. 어떤 군대보다 멀리 걸었지만, 한 번도 누구를 벤 적은 없다. 헤진 자리마다 다른 색 천이 덧대어져 지나온 마을 수만큼 무늬가 늘었다.',
    art: `long traveler's robe, dust-darkened hem, mismatched cloth patches, rope belt, mundane, ${STYLE}`,
  },
  {
    key: 'ash_evac_veil',
    slot: 'armor',
    nameKo: '잿빛 피난 면포',
    region: '서쪽 화산',
    tone: '비애',
    lore: '화산 마을이 비워지던 날, 사람들이 입과 어깨를 가리고 잿더미를 빠져나오며 둘렀던 천. 누군가는 두고 갔고, 누군가는 끝까지 손에서 놓지 않았다. 천에 밴 잿내는 빨아도 빠지지 않는다.',
    art: `scorched cloth veil-wrap over shoulders, ash-grey fabric, singed edges, draped, mournful, ${STYLE}`,
  },
  {
    key: 'unbroken_line_tabard',
    slot: 'armor',
    nameKo: '무너지지 않은 일선 휘장',
    region: '자유',
    tone: '영웅담',
    lore: '한 줄로 늘어선 방패병들이 가슴에 둘렀던 휘장. 줄이 무너지면 휘장도 의미를 잃는다는 약속이 있었고, 그날 줄은 끝까지 무너지지 않았다. 천 끝이 다 해졌어도 문장은 또렷이 남았다.',
    art: `surcoat tabard over mail, frayed but legible heraldic emblem, battle-worn cloth, heroic, ${STYLE}`,
  },
  {
    key: 'bark_woven_armor',
    slot: 'armor',
    nameKo: '나무껍질 엮음갑',
    region: '자유',
    tone: '담백',
    lore: '숲을 지키는 사람들이 두꺼운 나무껍질을 엮어 만든 몸통갑. 송진 냄새가 진하고, 비를 맞으면 잠깐 더 단단해진다. 대단한 물건은 아니지만, 숲에서는 이걸 입은 사람을 함부로 건드리지 않았다.',
    art: `woven bark body armor, layered tree-bark scales, resin sheen, cord lacing, plain forest, ${STYLE}`,
  },
  {
    key: 'fallen_choir_robe',
    slot: 'armor',
    nameKo: '타락한 성가복',
    region: '타락천사',
    tone: '담백',
    lore: '추락한 자리에서 거둔 긴 성가복이다. 본래 어떤 자리에서 입던 옷인지 아는 사람은 이제 남아 있지 않다. 천이 두껍고 안쪽에 솜을 덧대 겨울을 나기에 그만이라, 사연을 모르는 이들은 그저 두툼한 겉옷으로 걸친다. 깊은 두건은 목덜미로 드는 바람을 잘 막고, 밑단이 길어 주저앉아 쉴 때 무릎까지 덮인다. 거창한 내력을 기대하고 펼쳐 본 사람들은 처음엔 시시해했지만, 한 철을 입고 난 뒤로는 두말없이 계속 입었다.',
    art: `long thick choir robe with deep hood, faded trim, padded grey cloth, warm worn, plain, ${STYLE}`,
  },
  {
    key: 'tollgate_coat',
    slot: 'armor',
    nameKo: '통행세 외투',
    region: '자유',
    tone: '일상',
    lore: '다리 어귀 문지기가 평생 입은 두꺼운 외투. 오른쪽 주머니만 동전에 쓸려 안감이 반들반들하다. 무기 앞을 막은 적보다 찬바람을 막은 밤이 훨씬 많았던, 그런 외투다.',
    art: `heavy long coat, coin-worn shiny right pocket, plain dark wool, scuffed buttons, mundane, ${STYLE}`,
  },
  {
    key: 'dragon_scorch_shield',
    slot: 'armor',
    nameKo: '용 그을림 큰방패',
    region: '서쪽 화산',
    tone: '영웅담',
    lore: '한쪽 면이 고룡의 숨결에 닿아 매끈하게 녹아내린 탑 방패. 그 면 뒤에 웅크렸던 자는 살았고, 옆 사람들도 그 그늘에 살았다. 녹은 면에는 아직 그날의 열이 손바닥으로 만져진다고들 한다.',
    art: `large tower shield, one face melted glass-smooth by heat, scorched rim, sturdy back grip, heroic, ${STYLE}`,
  },
  {
    key: 'riddle_lamellar',
    slot: 'armor',
    nameKo: '수수께끼 찰갑',
    region: '자유',
    tone: '수수께끼',
    lore: '작은 쇳조각마다 한 글자씩 새겨, 줄지어 엮으면 한 줄 수수께끼가 되는 찰갑. 단 마지막 한 조각이 비어 있다. 답을 안다는 사람은 많았지만, 빈 조각을 채워 넣은 사람은 아직 없다.',
    art: `lamellar armor of small inscribed plates, one plate slot conspicuously empty, laced rows, enigmatic, ${STYLE}`,
  },
  {
    key: 'marsh_shell_carapace',
    slot: 'armor',
    nameKo: '늪 등딱지 갑',
    region: '늪지대',
    tone: '기괴',
    lore: '늪에 사는 아주 큰 무언가의 등딱지를 통째로 떼어 만든 몸통갑. 다 마른 줄 알았는데, 안쪽이 늘 미세하게 축축하다. 늪 사람들은 그 갑옷을 햇볕에 오래 두지 말라고만 일러 준다.',
    art: `large shell carapace body armor, ridged chitinous plate, perpetually faintly damp inner side, murky green, eerie, ${STYLE}`,
  },
  {
    key: 'grandmother_quilt_vest',
    slot: 'armor',
    nameKo: '할머니의 누비 조끼',
    region: '자유',
    tone: '비애',
    lore: '한 할머니가 떠나는 손주를 위해 밤새 누벼 만든 솜조끼. 갑옷이라 부르기엔 너무 포근하다. 그런데 그해 겨울, 그 조끼가 어느 화살을 한 번 막았다는 이야기가 집안에 조용히 전해 온다.',
    art: `thick quilted padded vest, hand-stitched patchwork, warm worn cloth, homely, bittersweet, ${STYLE}`,
  },
  {
    key: 'rune_anchor_greaves',
    slot: 'armor',
    nameKo: '룬 닻 정강이받이',
    region: '고대 룬 산맥',
    tone: '위트',
    lore: '산의 돌을 통째로 깎아 만든 정강이받이. 어찌나 무거운지 신은 자는 절대 떠밀리지 않는다. 동시에 절대 도망치지도 못한다. 이걸 신고 후퇴를 시도한 자들의 최후는, 대체로 서로 비슷했다.',
    art: `absurdly heavy carved-stone greaves, blue rune seams, oversized footplates, comically immovable, ${STYLE}`,
  },
  {
    key: 'carnival_breastplate',
    slot: 'armor',
    nameKo: '곡예단 흉갑',
    region: '자유',
    tone: '위트',
    lore: '유랑 곡예단의 무대 의상이던 번쩍이는 흉갑. 칠을 벗겨 보면 그 아래 진짜 칼자국이 여럿이다. 단장은 "전부 연출"이라 했지만, 연출치고는 너무 깊었다.',
    art: `gaudy painted stage breastplate, flaking bright paint, real dents underneath, theatrical ironic, ${STYLE}`,
  },
  {
    key: 'deserter_cloak',
    slot: 'armor',
    nameKo: '탈영병 망토',
    region: '자유',
    tone: '비애',
    lore: '부대 문장이 급히 뜯겨 나간 망토. 뜯긴 자리에 실밥 윤곽만 또렷이 남아, 무엇이 거기 있었는지 누구나 알아본다. 정작 그 문장이 어느 부대였는지는, 망토도 그 주인도 끝내 말하지 않았다.',
    art: `worn travel cloak, torn-off insignia patch leaving a clear thread outline, faded fabric, sorrowful, ${STYLE}`,
  },
  {
    key: 'hide_rain_cowl',
    slot: 'armor',
    nameKo: '가죽 비두건',
    region: '자유',
    tone: '담백',
    lore: '사냥꾼들이 비를 피하려 뒤집어쓰던 단순한 가죽 두건. 멋도 위엄도 없다. 다만 종일 비를 맞아도 목덜미가 마른 채로 있게 해 줬고, 그거면 충분했다.',
    art: `plain leather hood cowl, water-darkened edges, simple shoulder cape, drab, understated, ${STYLE}`,
  },
  {
    key: 'fallen_halo_circlet',
    slot: 'armor',
    nameKo: '떨군 후광 고리',
    region: '타락천사',
    tone: '위트',
    lore: '한때는 둥글고 환했다는 얇은 머리 고리. 지금은 한쪽이 푹 눌려, 누가 봐도 더는 후광이라 우기기 어려운 모양새다. 그런데 이걸 쓴 자들은 하나같이 한사코 "원래 이런 모양이다, 요즘은 이게 양식"이라 주장한다. 어찌나 진지하게 말하는지 듣는 쪽이 도리어 머쓱해진다. 아무도 그 말을 믿지 않지만, 정색하고 반박하는 사람도 없다. 덕분에 고리는 찌그러진 채로 여전히 누군가의 머리 위에서 당당하다.',
    art: `thin bent metal circlet, conspicuously dented out of round, dull tarnished gold, worn proudly, ironic, ${STYLE}`,
  },
  {
    key: 'orc_wardrum_rig',
    slot: 'armor',
    nameKo: '오크 전고 멜빵갑',
    region: '오크 부락',
    tone: '장엄',
    lore: '등에 멘 전쟁북이 울리면 부락 전체가 한 박자로 움직인다. 북을 진 자는 가장 앞에 서고, 가장 늦게 물러서야 한다. 그 한 박자가 끊기지 않는 한 줄도 무너지지 않는다는 것이, 부락의 오랜 믿음이다.',
    art: `harness armor with a great war drum on the back, broad leather straps, battle-worn drum, imposing, ${STYLE}`,
  },
  {
    key: 'forge_apron',
    slot: 'armor',
    nameKo: '대장간 가죽 앞치마',
    region: '서쪽 화산',
    tone: '일상',
    lore: '화산 대장간에서 평생 불똥을 받아낸 두꺼운 가죽 앞치마. 어떤 방패보다 많은 불꽃을 막았지만, 누구도 그걸 방어구라 부르지 않았다. 그을음이 켜켜이 앉아 색을 잃은 지 오래다.',
    art: `heavy blacksmith leather apron, layered scorch marks, soot-blackened, simple neck strap, mundane, ${STYLE}`,
  },
  {
    key: 'oath_kite_shield',
    slot: 'armor',
    nameKo: '맹세의 연 방패',
    region: '자유',
    tone: '영웅담',
    lore: '같은 맹세를 한 자들이 어깨를 잇대 세웠던 방패 줄, 그 한 자리를 메우던 연 방패. 안쪽에는 함께 섰던 이름들이 못 끝으로 거칠게 새겨져 있다. 그중 몇 개는 줄이 풀린 뒤 더해진 것이다.',
    art: `kite shield, weathered front, names roughly scratched on the inner face, leather arm straps, heroic, ${STYLE}`,
  },
  {
    key: 'hollow_visor_helm',
    slot: 'armor',
    nameKo: '빈 면갑 투구',
    region: '자유',
    tone: '기괴',
    lore: '면갑이 좀처럼 열린 채로 있지 않는 투구. 아무도 쓰지 않았는데도, 추운 날이면 면갑 틈으로 옅은 입김이 서린다고 한다. 보관하는 자들은 대체로 그것을 벽이 아니라 상자 안에 둔다.',
    art: `closed visored helm, visor that won't stay raised, faint breath-fog at the slit, dark steel, unsettling, ${STYLE}`,
  },
  {
    key: 'traveler_patch_coat',
    slot: 'armor',
    nameKo: '여행자 기움 외투',
    region: '자유',
    tone: '일상',
    lore: '지나온 마을마다 한 조각씩 천을 얻어 기운 외투. 색도 무늬도 제각각이라, 펼쳐 보면 그게 곧 여정 지도다. 어느 조각이 어느 마을인지는 입은 사람만 안다.',
    art: `long coat patched with cloth of many colors, uneven seams, well-worn, mundane, ${STYLE}`,
  },
  {
    key: 'marsh_root_buckler',
    slot: 'armor',
    nameKo: '늪 뿌리 손방패',
    region: '늪지대',
    tone: '비애',
    lore: '늪 바닥 뿌리를 엮어 만든 작은 손방패. 한 노인이 늪 다니는 법을 가르치며 손주에게 직접 엮어 주었다. 손주는 끝내 늪을 능숙하게 다니게 되었고, 노인은 그 늪에서 돌아오지 못했다. 방패만 마른 채로 문가에 남았다.',
    art: `small round buckler of woven swamp roots, knotty surface, simple center grip, weathered, mournful, ${STYLE}`,
  },
  {
    key: 'wailing_mail',
    slot: 'armor',
    nameKo: '우는 사슬갑',
    region: '자유',
    tone: '기괴',
    lore: '오래된 사슬갑인데, 바람이 통하면 낡은 고리 틈에서 길고 가는 소리가 샌다. 누군가는 그게 그냥 바람 소리라 했고, 누군가는 더는 그 옆에서 자지 않았다. 둘 다 그 갑옷을 다시 입지는 않았다.',
    art: `old chainmail hauberk, gapped rusted rings, thin whistling through the gaps, grey iron, eerie, ${STYLE}`,
  },
  {
    key: 'dusk_paladin_plate',
    slot: 'armor',
    nameKo: '해 저문 기사 판금',
    region: '자유',
    tone: '영웅담',
    lore: '온통 찌그러진 전신 판금. 그 기사는 성문이 닫힐 때까지 자리를 지키겠다 했고, 해가 질 무렵 정말로 문은 닫혔다. 갑옷은 그 약속의 모양 그대로 굳어, 누구도 그 자국을 펴려 하지 않았다.',
    art: `full plate harness, many deep dents, dimmed steel, battered pauldrons, plain straps, heroic, ${STYLE}`,
  },
  {
    key: 'rune_echo_shield',
    slot: 'armor',
    nameKo: '룬 메아리 방패',
    region: '고대 룬 산맥',
    tone: '일상',
    lore: '산의 돌을 댄 둥근 방패. 산사람들은 이걸 등에 지고 다니다 쉴 참엔 바닥에 엎어 깔고 앉는다. 낮게 울리는 소리가 의자 삼기엔 제법 듣기 좋다고들 한다. 막는 일보다 깔고 앉는 일에 더 자주 쓰였다.',
    art: `round stone-faced shield, blue seam cracks, banded rim, sit-worn back, mundane, ${STYLE}`,
  },
  {
    key: 'child_practice_shield',
    slot: 'armor',
    nameKo: '아이의 연습 방패',
    region: '자유',
    tone: '비애',
    lore: '아이 손에 맞춘 작은 나무 방패. 온통 칼자국투성이인데, 정작 그 아이는 다음 치수의 방패를 끝내 들지 못했다. 누가 그 칼자국을 냈는지는 묻지 않는 편이 좋다.',
    art: `small child-sized wooden practice shield, dense hack marks, scuffed paint, plain grip, sorrowful, ${STYLE}`,
  },
  {
    key: 'fools_brass_cuirass',
    slot: 'armor',
    nameKo: '바보 금 흉갑',
    region: '자유',
    tone: '위트',
    lore: '번쩍번쩍한 "황금" 흉갑. 사실은 놋쇠다. 입은 자는 평생 그걸 진짜 금이라 믿었고, 아무도 굳이 알려 주지 않았다. 놀랍게도 칼은 가리지 않고 막아 줬으므로, 진실은 그다지 중요하지 않았다.',
    art: `shiny brass cuirass mistaken for gold, bright polished finish, modest dents, ironic, ${STYLE}`,
  },
  {
    key: 'ash_pelt_mantle',
    slot: 'armor',
    nameKo: '잿더미 가죽망토',
    region: '서쪽 화산',
    tone: '담백',
    lore: '화산 비탈의 짐승 가죽으로 만든 두툼한 어깨망토. 가장자리가 불에 살짝 그을렸고, 연기 냄새가 가시지 않는다. 따뜻하다. 그게 이 망토에 바랄 수 있는 거의 전부다.',
    art: `thick beast-pelt shoulder mantle, singed edges, smoky brown fur, simple clasp, plain warm, ${STYLE}`,
  },
  {
    key: 'unmarked_grave_plate',
    slot: 'armor',
    nameKo: '무명 무덤 판금',
    region: '자유',
    tone: '비애',
    lore: '표식 없는 무덤에서 파낸 가슴판금. 닦아 보니 흠 하나 없이 멀쩡했고, 더 이상한 건 누가 입어도 몸에 꼭 맞는다는 점이다. 원래 주인이 누구였는지는 비석이 없어 알 길이 없다.',
    art: `unearthed steel breastplate, soil-stained then cleaned, oddly flawless, plain fit, melancholic, ${STYLE}`,
  },
  {
    key: 'watchlantern_rig',
    slot: 'armor',
    nameKo: '야경 등 멜빵',
    region: '자유',
    tone: '일상',
    lore: '가슴 앞에 등을 거는 고리가 달린 가죽 멜빵. 방어구라기보다 등받이에 가깝다. 야경꾼들은 갑옷보다 이 불빛이 먼저라 했고, 실제로 어두운 골목에서 사람을 더 많이 살린 건 쪽이었다.',
    art: `leather chest harness with a lantern hook, scuffed straps, soot near the hook, utilitarian mundane, ${STYLE}`,
  },
  {
    key: 'orc_trophy_pauldrons',
    slot: 'armor',
    nameKo: '오크 전리 어깨갑',
    region: '오크 부락',
    tone: '담백',
    lore: '오크 견갑. 어깨마다 전리품을 매다는 것이 부락의 오랜 풍습이라, 많이 싸운 자일수록 어깨가 무겁다. 장식이 곧 그 사람의 이력이다. 그뿐, 더 깊은 뜻은 없다.',
    art: `broad shoulder pauldrons hung with trophies, heavy iron plates, rugged, plain, ${STYLE}`,
  },
  {
    key: 'silent_choir_hood',
    slot: 'armor',
    nameKo: '침묵 성가 두건',
    region: '타락천사',
    tone: '영웅담',
    lore: '추락한 성가대가 사방으로 흩어지던 밤, 단 한 사람이 제자리를 뜨지 않고 노래를 이어 갔다. 이 깊은 두건을 쓰면 제 목소리만 한 겹 멀어져, 그는 끝내 자기 노래를 듣지 못한 채 불렀다. 들리지도 않는 노래를 마지막까지 부르는 일이 얼마나 외로운지는 그 사람만 알 것이다. 그러나 흩어지던 자들은 어둠 속에서 그 가느다란 가락을 등불 삼아 길을 찾아 나왔다. 두건은 그 밤 이후로 늘 조금 무겁다고, 써 본 이들은 입을 모은다.',
    art: `deep cloth hood, faded sacred trim, pale grey, worn solemn, heroic, ${STYLE}`,
  },
  {
    key: 'bog_breath_mask',
    slot: 'armor',
    nameKo: '늪 숨 가리개',
    region: '늪지대',
    tone: '일상',
    lore: '갈대 속을 채워 만든 단순한 입가리개. 이걸 쓰면 늪에 한 뼘 더 깊이 들어갈 수 있었다. 어떤 흉갑보다 많은 늪 사람을 살린 물건인데, 정작 생긴 건 더없이 초라하다.',
    art: `simple reed-filled breathing mask, woven straps, marsh-stained, crude practical, mundane, ${STYLE}`,
  },
  {
    key: 'herald_banner_cloak',
    slot: 'armor',
    nameKo: '전령 깃 망토',
    region: '자유',
    tone: '영웅담',
    lore: '끝까지 쓰러지지 않은 깃발을, 줄이 풀린 뒤 잘라 만든 어깨망토. 누더기가 된 천에도 문장의 윤곽이 또렷하다. 전령은 싸우지 않는다지만, 이 천만큼은 그날 끝까지 그 자리에 있었다.',
    art: `shoulder cloak cut from a tattered war banner, faded heraldic emblem, ragged hem, heroic, ${STYLE}`,
  },
  {
    key: 'late_mirror_shield',
    slot: 'armor',
    nameKo: '묻는 거울 방패',
    region: '자유',
    tone: '수수께끼',
    lore: '거울처럼 닦인 둥근 방패. 비친 제 모습이 늘 한 박자 늦게 움직인다. 그 늦은 한 박자 동안 거울 속 얼굴이 무슨 말을 하는 듯 보일 때가 있는데, 알아들었다는 사람은 아직 없다.',
    art: `round polished mirror-bright shield, reflection lagging a beat, plain rim, eerie enigmatic, ${STYLE}`,
  },
  {
    key: 'worn_road_boots',
    slot: 'armor',
    nameKo: '닳은 길 장화',
    region: '자유',
    tone: '담백',
    lore: '주인을 셋 갈아 치우고도 멀쩡한 가죽 장화. 밑창은 두 번 갈았고, 발등 가죽은 길이 들어 부드럽다. 사연이랄 게 없다. 그저 많이 걸었고, 아직 더 걸을 수 있다.',
    art: `well-worn leather travel boots, twice-resoled, softened creased leather, plain, understated, ${STYLE}`,
  },
];

const ACCESSORIES: CatalogItem[] = [];

export const CATALOG_ITEMS: CatalogItem[] = [...WEAPONS, ...ARMOR, ...ACCESSORIES];

export const CATALOG_BY_SLOT = (slot: CatalogSlot): CatalogItem[] =>
  CATALOG_ITEMS.filter((c) => c.slot === slot);
