/**
 * 새 catalog (이미지-우선 워크플로).
 * Pixellab로 sprite 먼저 생성 → 사용자 선택 → 한국어 nameKo·lore 작성.
 *
 * 점진적 append (5종씩 batch). 150 완성 후 catalog.ts와 swap.
 * sprite 위치: public/sprites-next/<slot>/<key>.png
 *
 * lore 가이드 (memory: lore-shorter-shape-first):
 *  - 한 문단, 약 80~150자
 *  - 형태 묘사 우선 + 사연 녹임
 *  - "[장소/사람 도입] → [형태 핵심] → [그 형태가 어떻게 보이는지]" 흐름
 */

import type { CatalogItem } from './catalog';

export const CATALOG_NEXT: CatalogItem[] = [
  // ── batch 1: 늪지대 weapon × 5 (다양한 tone) ──
  {
    key: 'marsh_frog_leaf_dirk',
    slot: 'weapon',
    nameKo: '개구리 잎 단검',
    region: '늪지대',
    tone: '위트',
    lore: '늪의 한 어린아이가 첫 비 오는 새벽에 잎 한 장을 접어 만든 단검이다. 끝에 작은 개구리 머리가 가만히 앉아 있는데, 새벽마다 옆자리의 잎이 한 줄씩 더 자라난다. 아이는 단검을 자기 키만큼 자랐을 때 어른에게 넘기겠다고 한 줄을 자루에 작은 글씨로 적어 두었다.',
    art: 'humorous quirky charming silly marsh swamp fantasy dagger weapon item icon, green folded leaf blade with a small frog head perched at the tip, single inanimate game loot object on transparent background',
  },
  {
    key: 'marsh_dry_root_blade',
    slot: 'weapon',
    nameKo: '마른 뿌리의 검',
    region: '늪지대',
    tone: '비애',
    lore: '늪에 묻혀 있던 검을 한 늙은 마부가 자기 마차 옆에 세워 두고 떠난 자리다. 검은 자루 위로 마른 뿌리 한 줌이 죽은 채로 감겨 있고, 뿌리 끝은 검신을 향해 한 방향으로 굽어 있다. 마부가 누구를 묻고 왔는지는 마차의 다음 손님도 묻지 않았다.',
    art: 'mournful melancholy somber sad marsh swamp fantasy sword weapon item icon, slim black blade with dried root tendrils wrapped around the crossguard curving toward the blade, single inanimate game loot object on transparent background',
  },
  {
    key: 'marsh_skull_drip_axe',
    slot: 'weapon',
    nameKo: '점액 흐르는 도끼',
    region: '늪지대',
    tone: '기괴',
    lore: '늪 깊은 자리에서 한 사냥꾼이 들고 나온 도끼다. 자루 위 사람 머리뼈가 칼날을 가만히 내려다보는 자세로 박혀 있고, 칼날엔 짙은 녹색 점액이 한 줄로 천천히 흐른다. 사냥꾼은 도끼를 누구에게도 보여 주지 않고 자기 천막 안쪽에만 세워 두었다.',
    art: 'uncanny eerie creepy unsettling marsh swamp fantasy axe weapon item icon, a human skull mounted at the haft top looking down at the blade with thick green slime dripping along the iron axe head, single inanimate game loot object on transparent background',
  },
  {
    key: 'marsh_lantern_wand',
    slot: 'weapon',
    nameKo: '안개 등롱 wand',
    region: '늪지대',
    tone: '수수께끼',
    lore: '늪 가장 깊은 안개 안쪽에서 한 길잡이가 들고 다닌 wand다. 끝의 작은 등롱 안에 청록 룬 보석이 한 알 박혀 있고, 길이 어디로 굽었는지에 따라 보석의 빛이 한 박자 늦게 한 방향으로 기운다. 등롱은 길잡이가 자기 집에 두고 떠난 새벽에도 가만히 켜져 있었다.',
    art: 'mysterious enigmatic cryptic marsh swamp fantasy magic staff wand item icon, dark wand with a small iron lantern at the tip housing a glowing teal rune gemstone inside, single inanimate game loot object on transparent background',
  },
  {
    key: 'marsh_old_god_polearm',
    slot: 'weapon',
    nameKo: '늪 옛 신의 폴암',
    region: '늪지대',
    tone: '장엄',
    lore: '늪의 가장 오랜 신을 마지막으로 모셨던 자가 자기 자리에 세워 두고 떠난 폴암이다. 끝에 어둠 같은 보라색 꽃이 한 송이 굵게 피어 있고, 자루 가시 사이로 옅은 향이 한 새벽에 한 번 새어 나온다. 그 향을 맡은 늪 사람은 그날 자기 집 문 앞을 비질하지 않고 잠든다.',
    art: 'grand majestic legendary mythic ancient marsh swamp fantasy polearm weapon item icon, dark thorn-wrapped polearm shaft with a single large dark purple flower bloom at the top, single inanimate game loot object on transparent background',
  },

  // ── batch 2: 오크 부락 weapon × 5 ──
  {
    key: 'orc_tooth_band_club',
    slot: 'weapon',
    nameKo: '이빨 띠 곤봉',
    region: '오크 부락',
    tone: '위트',
    lore: '부락의 어린 오크가 처음 짐승을 잡았을 때 그 짐승의 이빨을 띠로 엮어 자기 곤봉 가운데에 둘러 박은 것이다. 곤봉의 둘레가 다 차도록 이빨이 늘어나면 어른 오크들이 그를 한 번 부락 가운데 자리에 서게 한다.',
    art: 'humorous boastful orcish tribal fantasy club bludgeon weapon item icon, crude wooden club with a band of carved fangs wrapped around its middle section, single inanimate game loot object on transparent background',
  },
  {
    key: 'orc_two_feather_sabre',
    slot: 'weapon',
    nameKo: '두 깃의 곡검',
    region: '오크 부락',
    tone: '비애',
    lore: '한 오크 전사가 자기 동무 둘을 잃은 새벽에 두 동무의 화살에서 깃을 하나씩 빼어 자기 곡검의 grip에 묶은 것이다. 깃 사이에 누덕한 천 한 자락이 검신을 향해 늘어져 있고, 천에는 두 동무의 이름이 한 자씩 박혀 있다.',
    art: 'mournful sorrowful orcish tribal fantasy curved sabre weapon item icon, dark curved blade with two feathers tied to the grip and a ragged cloth strip hanging toward the blade, single inanimate game loot object on transparent background',
  },
  {
    key: 'orc_spine_whip',
    slot: 'weapon',
    nameKo: '척추 채찍',
    region: '오크 부락',
    tone: '기괴',
    lore: '어느 짐승의 척추를 통째 꿰어 한 줄로 묶어 만든 채찍이다. 마디마다 한 알의 뼈가 가시처럼 굽어 있어 휘두를 때 자기들끼리 가는 소리를 낸다. 그 소리를 가까이서 들은 부락의 강아지는 사흘간 자기 천막 밖으로 나오지 않았다.',
    art: 'uncanny eerie unsettling orcish tribal fantasy bone whip weapon item icon, a chain whip made entirely of curved animal spine vertebrae linked together, single inanimate game loot object on transparent background',
  },
  {
    key: 'orc_horn_grown_axe',
    slot: 'weapon',
    nameKo: '뿔 자란 도끼',
    region: '오크 부락',
    tone: '수수께끼',
    lore: '부락의 가장 늙은 양 한 마리가 자기 뿔이 떨어지던 새벽 부락 가장자리에 와 그 뿔을 가만히 놓고 돌아갔다. 부락의 대장장이가 그 뿔을 자기 도끼의 머리 위에 굽혀 박았더니, 뿔이 마치 도끼 위에서 한 번 더 자라난 모양이 되었다.',
    art: 'mysterious enigmatic ritual orcish tribal fantasy ceremonial axe weapon item icon, axe head fused with a curled ram horn arching over the blade with tribal glyphs engraved, single inanimate game loot object on transparent background',
  },
  {
    key: 'orc_oldchief_maul',
    slot: 'weapon',
    nameKo: '옛 부족장의 망치',
    region: '오크 부락',
    tone: '장엄',
    lore: '부락의 가장 옛 부족장이 자기 마지막 새벽까지 어깨에 메고 다닌 망치다. 머리에 두른 황금 띠 위로 부락의 첫 일곱 부족장 이름이 한 줄로 새겨져 있고, 띠가 시작되는 자리는 정확히 그가 자기 손가락 끝으로 짚어 두었던 자리다.',
    art: 'grand legendary ancient orcish tribal fantasy chieftain two-handed maul weapon item icon, massive black stone head wrapped with a gold band engraved with seven names, single inanimate game loot object on transparent background',
  },

  // ── batch 3: 고대 룬 산맥 weapon × 5 ──
  {
    key: 'rune_chime_wand',
    slot: 'weapon',
    nameKo: '종 달린 wand',
    region: '고대 룬 산맥',
    tone: '위트',
    lore: '룬 학원의 한 견습이 자기 wand 끝에 작은 종을 하나 매달았다. 종에 새긴 룬은 "조용"이라는 한 글자였는데, 흔들 때마다 정확히 한 번씩 가는 소리를 냈다. 견습은 그 한 박자에 자기 호흡을 맞춰 룬을 외웠다고 한 줄로 일기에 적었다.',
    art: 'humorous whimsical mountain rune ancient fantasy wand weapon item icon, dark slender wand with a small brass bell carved with a rune hanging at the tip, single inanimate game loot object on transparent background',
  },
  {
    key: 'rune_three_shard_blade',
    slot: 'weapon',
    nameKo: '세 조각의 검',
    region: '고대 룬 산맥',
    tone: '비애',
    lore: '룬 산맥의 한 검사가 마지막 새벽 자기 검을 산문 돌에 한 번 내리쳐 세 조각으로 부순 자리다. 세 조각은 부서진 자리를 한 줄로 그대로 두고 누구도 다시 잇지 못하게 했고, 가운데 조각의 룬만 한 줄로 끊긴 채 남아 있다.',
    art: 'mournful broken mountain rune ancient fantasy shard sword weapon item icon, broken stone blade fractured into three pieces lined up with carved runes interrupted at the breaks, single inanimate game loot object on transparent background',
  },
  {
    key: 'rune_watching_dirk',
    slot: 'weapon',
    nameKo: '보는 단검',
    region: '고대 룬 산맥',
    tone: '기괴',
    lore: '룬 산맥의 옛 신전 가장 안쪽에서 한 학자가 챙겨 온 단검이다. 자루 가운데에 살아 있는 한 눈이 박혀 있고, 그 눈의 동공은 단검을 든 사람이 어느 방향으로 돌리든 정면을 향해 한 박자 늦게 따라온다.',
    art: 'uncanny eerie mountain rune ancient fantasy stone-eye dagger weapon item icon, dark stone dagger with a single living red-pupil eye set in the crossguard, single inanimate game loot object on transparent background',
  },
  {
    key: 'rune_book_chained_wand',
    slot: 'weapon',
    nameKo: '돌책 매단 wand',
    region: '고대 룬 산맥',
    tone: '수수께끼',
    lore: '룬 학원의 한 사관이 자기 wand 옆에 작은 돌책을 사슬로 매달아 다녔다. 돌책엔 룬 일곱 줄이 새겨져 있는데, 사관은 그 일곱 줄을 평생 다 읽지 못했다. 마지막 새벽 그가 그 책을 펼친 자리는 정확히 네 번째 줄에서 멈춰 있었다.',
    art: 'mysterious cryptic mountain rune ancient fantasy book-bound staff weapon item icon, dark staff with a small chained stone book engraved with seven rune lines hanging at the side, single inanimate game loot object on transparent background',
  },
  {
    key: 'rune_first_thunder_hammer',
    slot: 'weapon',
    nameKo: '첫 천둥의 망치',
    region: '고대 룬 산맥',
    tone: '장엄',
    lore: '룬 산맥의 첫 천둥이 친 새벽 한 장인이 그 천둥을 자기 망치 머리 안에 봉인한 것이라 한다. brass 띠 두 줄이 stone 머리를 양쪽에서 한 번씩 묶었고, 머리 안쪽에선 새벽이 깊을 때마다 한 박자 늦은 우르릉 소리가 손바닥으로 전해진다.',
    art: 'grand legendary mythic mountain rune ancient fantasy first thunder warhammer weapon item icon, massive pale stone hammer head bound with two brass bands and carved runes, single inanimate game loot object on transparent background',
  },

  // ── batch 4: 서쪽 화산 weapon × 5 ──
  {
    key: 'volcano_pan_cleaver',
    slot: 'weapon',
    nameKo: '프라이팬 칼',
    region: '서쪽 화산',
    tone: '위트',
    lore: '서쪽 화로 옆 부엌의 한 견습이 자기가 가장 자주 떨군 식칼과 프라이팬을 화로 안에 같이 던져 한 덩이로 굳혀 버린 것이다. 두 자루가 한 손잡이로 붙은 채 굳었고, 칼날 둘레로 화로 불의 작은 자국이 평생 사라지지 않는다.',
    art: 'humorous comical volcanic forge fire fantasy frying-pan cleaver kitchen weapon item icon, blackened iron pan-cleaver crossbreed weapon with sparks, single inanimate game loot object on transparent background',
  },
  {
    key: 'volcano_widow_ribbon_hammer',
    slot: 'weapon',
    nameKo: '리본의 망치',
    region: '서쪽 화산',
    tone: '비애',
    lore: '서쪽 마을이 잿더미가 된 새벽 한 과부가 자기 남편의 대장간 망치 grip에 그가 한때 자기에게 선물한 머리 리본을 한 줄로 묶어 놓은 자리다. 리본의 옅은 색은 그 새벽의 잿빛에 한 번 덮였다가 다시 한 색만 옅게 떠올랐다.',
    art: 'mournful sorrowful ashen volcanic forge fire fantasy widow blacksmith hammer weapon item icon, scorched hammer with a single faded ribbon tied at the grip, single inanimate game loot object on transparent background',
  },
  {
    key: 'volcano_molten_eye_dirk',
    slot: 'weapon',
    nameKo: '용암 눈의 단검',
    region: '서쪽 화산',
    tone: '기괴',
    lore: '화로 가장 깊은 자리에서 한 풀무지기가 끄집어낸 단검이다. 자루 끝에 박힌 한 알의 보석이 새벽마다 한쪽으로 슬쩍 도는데, 그 보석 안쪽엔 식지 않은 용암 한 방울이 작은 눈동자처럼 굳어 있다. 칼날의 균열은 그 눈이 도는 방향으로만 한 줄로 자란다.',
    art: 'uncanny eerie volcanic forge fire fantasy molten-eye dagger weapon item icon, dark dagger with a glowing molten orange eye gemstone at the pommel and lava cracks branching along the blade, single inanimate game loot object on transparent background',
  },
  {
    key: 'volcano_ember_rune_blade',
    slot: 'weapon',
    nameKo: '잉걸 룬의 검',
    region: '서쪽 화산',
    tone: '수수께끼',
    lore: '화로의 한 학자가 자기 검의 빈 fuller에 잉걸 한 알을 한 글자 모양으로 굳혀 넣은 것이다. 자루의 가시는 그 글자를 누구도 쥐지 않게 하려고 함께 굳힌 자리인데, 가시 한 줄에 한 새벽씩 옅은 빨간 빛이 한 박자 늦게 한 번 흐른다.',
    art: 'mysterious cryptic volcanic forge fire fantasy ember rune longsword weapon item icon, dark steel blade with a glowing ember rune line down the fuller and a thorned grip, single inanimate game loot object on transparent background',
  },
  {
    key: 'volcano_dragon_rune_axe',
    slot: 'weapon',
    nameKo: '용 화로의 도끼',
    region: '서쪽 화산',
    tone: '장엄',
    lore: '서쪽 화산의 가장 깊은 화로에서 한 장인이 평생 한 자루만 두드린 도끼다. 머리 가운데에 황금 한 알이 룬 모양으로 박혀 있고, 그 룬을 가로질러 한 줄의 용암 균열이 검은 머리에 한 박자 늦은 박동으로 짙어졌다 옅어진다.',
    art: 'grand legendary mythic volcanic forge fire fantasy dragon-forged greataxe weapon item icon, massive blackened axe head with a single gold rune at center and molten lava cracks branching across, single inanimate game loot object on transparent background',
  },

  // ── batch 5: 타락천사 weapon × 5 ──
  {
    key: 'fallen_cherub_resting_rapier',
    slot: 'weapon',
    nameKo: '케르빔이 안 떠난 검',
    region: '타락천사',
    tone: '위트',
    lore: '추락한 자가 떠난 새벽 신전 빈자리에 남은 가는 검이다. 검신 가운데에 어린 케르빔 한 명이 자기 침대인 양 두 다리를 펴고 누워 가만히 자고 있는데, 누가 검을 들어 올려도 케르빔은 한 번도 자기 자세를 흩뜨리지 않는다.',
    art: 'humorous mischievous cherub fallen angel divine fantasy thin rapier weapon item icon, slender silver rapier with a small chubby cherub baby lying playfully across the blade, single inanimate game loot object on transparent background',
  },
  {
    key: 'fallen_black_feather_blade',
    slot: 'weapon',
    nameKo: '검은 깃의 검',
    region: '타락천사',
    tone: '비애',
    lore: '추락한 자가 마지막으로 자기 깃을 한 가닥 떨어뜨린 자리에 한 신관이 자기 검의 crossguard에 그 깃을 묶어 둔 것이다. 깃의 검은색은 신관이 검을 닦아도 닦이지 않고, 자루 위 흰 천은 그 깃을 가리려 매번 한 줄로 더 감긴다.',
    art: 'mournful sorrowful fallen angel divine fantasy longsword weapon item icon, dark silver blade with a single black feather tied at the crossguard and a torn ivory cloth wrapped around the grip, single inanimate game loot object on transparent background',
  },
  {
    key: 'fallen_decay_wing_scythe',
    slot: 'weapon',
    nameKo: '썩은 날개의 낫',
    region: '타락천사',
    tone: '기괴',
    lore: '추락한 자의 두 날개가 부패해 떨어진 자리에 한 신관이 그 깃들을 한 줄로 묶어 자기 낫의 양쪽에 박아 넣은 것이다. 날개 가운데에는 신관이 자기 손가락 끝으로 박아 둔 한 알의 보석이 한 박자 늦은 박동으로 짙어졌다 옅어진다.',
    art: 'uncanny eerie corrupted decaying fallen angel divine fantasy scythe weapon item icon, dark scythe with two large rotting feathered wings spread on each side and a single glowing gemstone at the center, single inanimate game loot object on transparent background',
  },
  {
    key: 'fallen_veiled_wand',
    slot: 'weapon',
    nameKo: '베일을 쓴 wand',
    region: '타락천사',
    tone: '수수께끼',
    lore: '추락한 자의 신부가 자기 베일을 한 자락 떼어 한 wand 끝에 한 번 둘러 묶은 것이다. 베일은 wand 안쪽에 무엇이 박혀 있는지 누구도 들춰 보지 못하게 한 줄로 가리고 있고, 새벽마다 한 호흡씩 옅게 떨린다.',
    art: 'mysterious cryptic veiled fallen angel divine fantasy wand weapon item icon, slim ivory wand topped with a sheer white bridal veil draped completely over the tip hiding what is underneath, single inanimate game loot object on transparent background',
  },
  {
    key: 'fallen_seraph_glaive',
    slot: 'weapon',
    nameKo: '세라프의 글레이브',
    region: '타락천사',
    tone: '장엄',
    lore: '한 세라프가 추락하기 전 마지막으로 자기 자리에 세워 두고 떠난 글레이브다. 검신 뒤로 한 줄의 황금 후광이 동심원으로 굳어 있고, 양 옆엔 그 세라프가 떨어뜨린 두 깃이 한 번도 식지 않은 채 굳어 있어 새벽 햇살이 그 자리에서 한 박자 더 머문다.',
    art: 'grand legendary mythic seraphic celestial fallen angel divine fantasy glaive weapon item icon, tall pale silver curved glaive blade with concentric gold halo arcs behind and two large white feathers framing the head, single inanimate game loot object on transparent background',
  },

  // ── batch 6: 일반 region weapon × 5 ──
  {
    key: 'common_clover_dirk',
    slot: 'weapon',
    nameKo: '행운의 단검',
    region: '일반',
    tone: '위트',
    lore: '시장의 한 노점상이 자기 단검의 grip에 자기 어머니가 들에서 가져다 준 네잎 클로버 한 잎을 한 줄로 묶어 두었다. 그 자리 옆에 한 잎이 더 마르지 않는 자리가 있어, 노점상은 늘 그 자리에 손가락을 한 번씩 짚어 본 뒤 거래를 시작한다.',
    art: 'humorous lucky charming fantasy traveler dagger weapon item icon, simple steel dagger with a small four-leaf clover charm tied at the grip with a cord, single inanimate game loot object on transparent background',
  },
  {
    key: 'common_widow_veil_blade',
    slot: 'weapon',
    nameKo: '과부의 검',
    region: '일반',
    tone: '비애',
    lore: '한 과부가 자기 남편의 검을 마차 옆에 세워 두면서 자기 베일을 한 자락 떼어 crossguard에 한 줄로 묶은 자리다. 검은 베일은 검신을 따라 한 호흡 늦게 흔들렸고, 마차의 다음 손님이 그 흔들림을 한 번 짚어 보고는 자기 머리도 한 번 숙였다.',
    art: 'mournful sorrowful widow fantasy human village longsword weapon item icon, plain steel blade with a black mourning veil tied at the crossguard hanging down along the blade, single inanimate game loot object on transparent background',
  },
  {
    key: 'common_gravedigger_pick',
    slot: 'weapon',
    nameKo: '묘지기의 곡괭이',
    region: '일반',
    tone: '기괴',
    lore: '마을 끝 묘지의 한 묘지기가 평생 한 자루만 들고 들어간 곡괭이다. 자루의 끈은 그가 자기 손가락 끝으로 한 번 더 묶은 자리에서 끊긴 채 그대로 매여 있고, 끈 사이로 묻지 못한 흙 한 알이 매년 한 알씩 더 끼어 들어간다.',
    art: 'uncanny eerie gravedigger fantasy human village pickaxe weapon item icon, brown wooden pickaxe with simple binding cord wrapped around the haft, single inanimate game loot object on transparent background',
  },
  {
    key: 'common_scribe_quill_wand',
    slot: 'weapon',
    nameKo: '사관의 깃촉 wand',
    region: '일반',
    tone: '수수께끼',
    lore: '한 사관이 평생 자기 옆구리에 차고 다닌 깃촉 wand다. 가운데에 박힌 푸른 보석이 그가 한 줄을 새겨 들어갈 때마다 한 박자 늦은 빛으로 답해 주었는데, 보석의 한 박자가 흐릿한 새벽엔 사관은 그날의 줄을 쓰지 않았다.',
    art: 'mysterious cryptic chronicler fantasy human scholar quill wand weapon item icon, slim writing-quill-shaped wand with an ink-stained nib at the bottom, a single small blue gem at the center, and two white feathered barbs at the top, single inanimate game loot object on transparent background',
  },
  {
    key: 'common_hero_greatsword',
    slot: 'weapon',
    nameKo: '영웅의 대검',
    region: '일반',
    tone: '장엄',
    lore: '한 영웅이 자기 평생의 길 끝에 자기 마을의 광장 한가운데에 세워 두고 떠난 대검이다. crossguard에서 굳은 두 황금 날개가 가운데 푸른 보석 한 알을 양쪽에서 가만히 받치고 있고, 보석 안쪽엔 그가 마지막 새벽까지 한 번 더 휘두를 자리가 한 줄로 새겨져 있다.',
    art: 'grand legendary heroic fantasy human village hero two-handed greatsword weapon item icon, massive shining steel blade with golden winged crossguard and a single blue gemstone at the center, single inanimate game loot object on transparent background',
  },

  // ── batch 7 (부분, 담백/일상 제외 후 영웅담 2종만 유지) ──
  {
    key: 'orc_first_hunt_broken_axe',
    slot: 'weapon',
    nameKo: '부서진 첫 사냥의 도끼',
    region: '오크 부락',
    tone: '영웅담',
    lore: '부락의 한 어린 오크가 자기 첫 사냥에서 그 짐승의 송곳니에 자기 도끼 칼날 한쪽이 부서지자, 부서진 자리에 그 송곳니를 한 줄로 꿰어 매단 자리다. 부락의 늙은 전사는 그 부서진 자리를 깎아 다듬지 말라고 한 줄로 어린 오크의 자루에 적어 주었다.',
    art: 'heroic epic orcish tribal fantasy first hunt axe weapon item icon, dark iron axe with one chipped broken blade edge and a yellowed tusk hanging from the haft on a cord, single inanimate game loot object on transparent background',
  },
  {
    key: 'volcano_first_ember_hammer',
    slot: 'weapon',
    nameKo: '첫 잉걸의 망치',
    region: '서쪽 화산',
    tone: '영웅담',
    lore: '서쪽 화로의 첫 잉걸 한 알을 그 화로의 첫 풀무지기가 자기 망치 머리 안에 봉인한 것이라 한다. 망치를 두드리면 잉걸의 빛이 가운데에서 한 박자 늦게 한 번 짙어졌다 옅어지고, 그 한 박자에 다른 화로의 풀무지기들도 한 호흡을 맞춰 두드린다.',
    art: 'heroic epic volcanic forge fire fantasy first ember blacksmith hammer weapon item icon, large dark hammer with a single glowing orange ember sealed in the center of the head, single inanimate game loot object on transparent background',
  },
];
