/**
 * 새 catalog (이미지-우선 워크플로).
 * Pixellab로 sprite 먼저 생성 → 사용자 선택 → 한국어 nameKo·lore 작성.
 *
 * 점진적 append (5종씩 batch). 150 완성 후 catalog.ts와 swap.
 * sprite 위치: public/sprites-next/<slot>/<key>.png
 *
 * lore 가이드 (memory: lore-shorter-shape-first):
 *  - 한 문단, 약 80~150자
 *  - 형태 묘사 우선 + 사연 녹임
 *  - "[장소/사람 도입] → [형태 핵심] → [그 형태가 어떻게 보이는지]" 흐름
 */

import type { CatalogItem } from './catalog';

export const CATALOG_NEXT: CatalogItem[] = [
  // ── batch 1: 늪지대 weapon × 5 (다양한 tone) ──
  {
    key: 'marsh_frog_leaf_dirk',
    slot: 'weapon',
    nameKo: '개구리 잎 단검',
    region: '늪지대',
    tone: '위트',
    lore: '늪의 한 어린아이가 첫 비 오는 새벽에 잎 한 장을 접어 만든 단검이다. 끝에 작은 개구리 머리가 가만히 앉아 있는데, 새벽마다 옆자리의 잎이 한 줄씩 더 자라난다. 아이는 단검을 자기 키만큼 자랐을 때 어른에게 넘기겠다고 한 줄을 자루에 작은 글씨로 적어 두었다.',
    art: 'humorous quirky charming silly marsh swamp fantasy dagger weapon item icon, green folded leaf blade with a small frog head perched at the tip, single inanimate game loot object on transparent background',
  },
  {
    key: 'marsh_dry_root_blade',
    slot: 'weapon',
    nameKo: '마른 뿌리의 검',
    region: '늪지대',
    tone: '비애',
    lore: '늪에 묻혀 있던 검을 한 늙은 마부가 자기 마차 옆에 세워 두고 떠난 자리다. 검은 자루 위로 마른 뿌리 한 줌이 죽은 채로 감겨 있고, 뿌리 끝은 검신을 향해 한 방향으로 굽어 있다. 마부가 누구를 묻고 왔는지는 마차의 다음 손님도 묻지 않았다.',
    art: 'mournful melancholy somber sad marsh swamp fantasy sword weapon item icon, slim black blade with dried root tendrils wrapped around the crossguard curving toward the blade, single inanimate game loot object on transparent background',
  },
  {
    key: 'marsh_skull_drip_axe',
    slot: 'weapon',
    nameKo: '점액 흐르는 도끼',
    region: '늪지대',
    tone: '기괴',
    lore: '늪 깊은 자리에서 한 사냥꾼이 들고 나온 도끼다. 자루 위 사람 머리뼈가 칼날을 가만히 내려다보는 자세로 박혀 있고, 칼날엔 짙은 녹색 점액이 한 줄로 천천히 흐른다. 사냥꾼은 도끼를 누구에게도 보여 주지 않고 자기 천막 안쪽에만 세워 두었다.',
    art: 'uncanny eerie creepy unsettling marsh swamp fantasy axe weapon item icon, a human skull mounted at the haft top looking down at the blade with thick green slime dripping along the iron axe head, single inanimate game loot object on transparent background',
  },
  {
    key: 'marsh_lantern_wand',
    slot: 'weapon',
    nameKo: '안개 등롱 wand',
    region: '늪지대',
    tone: '수수께끼',
    lore: '늪 가장 깊은 안개 안쪽에서 한 길잡이가 들고 다닌 wand다. 끝의 작은 등롱 안에 청록 룬 보석이 한 알 박혀 있고, 길이 어디로 굽었는지에 따라 보석의 빛이 한 박자 늦게 한 방향으로 기운다. 등롱은 길잡이가 자기 집에 두고 떠난 새벽에도 가만히 켜져 있었다.',
    art: 'mysterious enigmatic cryptic marsh swamp fantasy magic staff wand item icon, dark wand with a small iron lantern at the tip housing a glowing teal rune gemstone inside, single inanimate game loot object on transparent background',
  },
  {
    key: 'marsh_old_god_polearm',
    slot: 'weapon',
    nameKo: '늪 옛 신의 폴암',
    region: '늪지대',
    tone: '장엄',
    lore: '늪의 가장 오랜 신을 마지막으로 모셨던 자가 자기 자리에 세워 두고 떠난 폴암이다. 끝에 어둠 같은 보라색 꽃이 한 송이 굵게 피어 있고, 자루 가시 사이로 옅은 향이 한 새벽에 한 번 새어 나온다. 그 향을 맡은 늪 사람은 그날 자기 집 문 앞을 비질하지 않고 잠든다.',
    art: 'grand majestic legendary mythic ancient marsh swamp fantasy polearm weapon item icon, dark thorn-wrapped polearm shaft with a single large dark purple flower bloom at the top, single inanimate game loot object on transparent background',
  },

  // ── batch 2: 오크 부락 weapon × 5 ──
  {
    key: 'orc_tooth_band_club',
    slot: 'weapon',
    nameKo: '이빨 띠 곤봉',
    region: '오크 부락',
    tone: '위트',
    lore: '부락의 어린 오크가 처음 짐승을 잡았을 때 그 짐승의 이빨을 띠로 엮어 자기 곤봉 가운데에 둘러 박은 것이다. 곤봉의 둘레가 다 차도록 이빨이 늘어나면 어른 오크들이 그를 한 번 부락 가운데 자리에 서게 한다.',
    art: 'humorous boastful orcish tribal fantasy club bludgeon weapon item icon, crude wooden club with a band of carved fangs wrapped around its middle section, single inanimate game loot object on transparent background',
  },
  {
    key: 'orc_two_feather_sabre',
    slot: 'weapon',
    nameKo: '두 깃의 곡검',
    region: '오크 부락',
    tone: '비애',
    lore: '한 오크 전사가 자기 동무 둘을 잃은 새벽에 두 동무의 화살에서 깃을 하나씩 빼어 자기 곡검의 grip에 묶은 것이다. 깃 사이에 누덕한 천 한 자락이 검신을 향해 늘어져 있고, 천에는 두 동무의 이름이 한 자씩 박혀 있다.',
    art: 'mournful sorrowful orcish tribal fantasy curved sabre weapon item icon, dark curved blade with two feathers tied to the grip and a ragged cloth strip hanging toward the blade, single inanimate game loot object on transparent background',
  },
  {
    key: 'orc_spine_whip',
    slot: 'weapon',
    nameKo: '척추 채찍',
    region: '오크 부락',
    tone: '기괴',
    lore: '어느 짐승의 척추를 통째 꿰어 한 줄로 묶어 만든 채찍이다. 마디마다 한 알의 뼈가 가시처럼 굽어 있어 휘두를 때 자기들끼리 가는 소리를 낸다. 그 소리를 가까이서 들은 부락의 강아지는 사흘간 자기 천막 밖으로 나오지 않았다.',
    art: 'uncanny eerie unsettling orcish tribal fantasy bone whip weapon item icon, a chain whip made entirely of curved animal spine vertebrae linked together, single inanimate game loot object on transparent background',
  },
  {
    key: 'orc_horn_grown_axe',
    slot: 'weapon',
    nameKo: '뿔 자란 도끼',
    region: '오크 부락',
    tone: '수수께끼',
    lore: '부락의 가장 늙은 양 한 마리가 자기 뿔이 떨어지던 새벽 부락 가장자리에 와 그 뿔을 가만히 놓고 돌아갔다. 부락의 대장장이가 그 뿔을 자기 도끼의 머리 위에 굽혀 박았더니, 뿔이 마치 도끼 위에서 한 번 더 자라난 모양이 되었다.',
    art: 'mysterious enigmatic ritual orcish tribal fantasy ceremonial axe weapon item icon, axe head fused with a curled ram horn arching over the blade with tribal glyphs engraved, single inanimate game loot object on transparent background',
  },
  {
    key: 'orc_oldchief_maul',
    slot: 'weapon',
    nameKo: '옛 부족장의 망치',
    region: '오크 부락',
    tone: '장엄',
    lore: '부락의 가장 옛 부족장이 자기 마지막 새벽까지 어깨에 메고 다닌 망치다. 머리에 두른 황금 띠 위로 부락의 첫 일곱 부족장 이름이 한 줄로 새겨져 있고, 띠가 시작되는 자리는 정확히 그가 자기 손가락 끝으로 짚어 두었던 자리다.',
    art: 'grand legendary ancient orcish tribal fantasy chieftain two-handed maul weapon item icon, massive black stone head wrapped with a gold band engraved with seven names, single inanimate game loot object on transparent background',
  },

  // ── batch 3: 고대 룬 산맥 weapon × 5 ──
  {
    key: 'common_bard_lute_with_blade',
    slot: 'weapon',
    nameKo: '음유시인의 비밀 류트',
    region: '일반',
    tone: '위트',
    lore: '한 광장의 음유시인이 자기 마지막 새벽 자기 류트 안쪽에 한 알의 칼날을 한 번 더 깎아 넣고 자기 자리를 떠난 자리다. 류트의 줄 옆에 매달린 파란 ribbon은 그가 자기 자리에서 한 번 더 자기 노래의 마지막 줄을 한 번 더 흥얼거린 결이다.',
    art: 'humorous quirky fantasy traveling bard lute with hidden blade weapon item icon, dark wooden pear-shaped lute instrument with strings, a blue ribbon tied at the neck, and a small concealed blade extending from the bottom tip, single inanimate game loot object on transparent background',
  },
  {
    key: 'rune_three_shard_blade',
    slot: 'weapon',
    nameKo: '세 조각의 검',
    region: '고대 룬 산맥',
    tone: '비애',
    lore: '룬 산맥의 한 검사가 마지막 새벽 자기 검을 산문 돌에 한 번 내리쳐 세 조각으로 부순 자리다. 세 조각은 부서진 자리를 한 줄로 그대로 두고 누구도 다시 잇지 못하게 했고, 가운데 조각의 룬만 한 줄로 끊긴 채 남아 있다.',
    art: 'mournful broken mountain rune ancient fantasy shard sword weapon item icon, broken stone blade fractured into three pieces lined up with carved runes interrupted at the breaks, single inanimate game loot object on transparent background',
  },
  {
    key: 'rune_watching_dirk',
    slot: 'weapon',
    nameKo: '보는 단검',
    region: '고대 룬 산맥',
    tone: '기괴',
    lore: '룬 산맥의 옛 신전 가장 안쪽에서 한 학자가 챙겨 온 단검이다. 자루 가운데에 살아 있는 한 눈이 박혀 있고, 그 눈의 동공은 단검을 든 사람이 어느 방향으로 돌리든 정면을 향해 한 박자 늦게 따라온다.',
    art: 'uncanny eerie mountain rune ancient fantasy stone-eye dagger weapon item icon, dark stone dagger with a single living red-pupil eye set in the crossguard, single inanimate game loot object on transparent background',
  },
  {
    key: 'common_chef_giant_skillet',
    slot: 'weapon',
    nameKo: '거대 프라이팬',
    region: '일반',
    tone: '위트',
    lore: '한 여관의 가장 무뚝뚝한 셰프가 자기 평생 한 번도 자기 프라이팬을 화로 밖으로 한 번 더 내려놓지 않은 결을 그 자루의 무게로 한 번 더 굳혀 두고 떠난 자리다. 안쪽에 가만히 들러붙어 굳은 계란 한 알은 셰프가 자기 마지막 새벽까지 자기 자리에서 한 번 더 부치다 만 결이다.',
    art: 'humorous quirky fantasy chef giant cast-iron skillet smashing weapon item icon, big round black cast-iron frying pan with a long sturdy handle and a single fried egg still stuck inside, single inanimate game loot object on transparent background',
  },
  {
    key: 'rune_first_thunder_hammer',
    slot: 'weapon',
    nameKo: '첫 천둥의 망치',
    region: '고대 룬 산맥',
    tone: '장엄',
    lore: '룬 산맥의 첫 천둥이 친 새벽 한 장인이 그 천둥을 자기 망치 머리 안에 봉인한 것이라 한다. brass 띠 두 줄이 stone 머리를 양쪽에서 한 번씩 묶었고, 머리 안쪽에선 새벽이 깊을 때마다 한 박자 늦은 우르릉 소리가 손바닥으로 전해진다.',
    art: 'grand legendary mythic mountain rune ancient fantasy first thunder warhammer weapon item icon, massive pale stone hammer head bound with two brass bands and carved runes, single inanimate game loot object on transparent background',
  },

  // ── batch 4: 서쪽 화산 weapon × 5 ──
  {
    key: 'volcano_pan_cleaver',
    slot: 'weapon',
    nameKo: '프라이팬 칼',
    region: '서쪽 화산',
    tone: '위트',
    lore: '서쪽 화로 옆 부엌의 한 견습이 자기가 가장 자주 떨군 식칼과 프라이팬을 화로 안에 같이 던져 한 덩이로 굳혀 버린 것이다. 두 자루가 한 손잡이로 붙은 채 굳었고, 칼날 둘레로 화로 불의 작은 자국이 평생 사라지지 않는다.',
    art: 'humorous comical volcanic forge fire fantasy frying-pan cleaver kitchen weapon item icon, blackened iron pan-cleaver crossbreed weapon with sparks, single inanimate game loot object on transparent background',
  },
  {
    key: 'common_royal_archer_longbow',
    slot: 'weapon',
    nameKo: '왕실 궁수의 황금 장궁',
    region: '일반',
    tone: '화려',
    lore: '한 왕국의 첫 궁수가 자기 평생 자기 활시위를 한 번도 줄여 박지 않은 결을 자기 활 grip 가운데에 한 알의 큰 푸른 보석으로 한 번 더 굳혀 박아 둔 자리다. 활의 양 끝의 filigree는 그가 자기 평생 한 번씩 더 짚어 본 결을 따라 한 줄씩 더 둘러져 있다.',
    art: 'ornate flamboyant gilded fantasy royal archer recurve longbow weapon item icon, elegant gold-inlaid wooden recurve longbow with intricate filigree carvings, a sapphire gemstone at the grip, and a single nocked golden arrow, single inanimate game loot object on transparent background',
  },
  {
    key: 'volcano_molten_eye_dirk',
    slot: 'weapon',
    nameKo: '용암 눈의 단검',
    region: '서쪽 화산',
    tone: '기괴',
    lore: '화로 가장 깊은 자리에서 한 풀무지기가 끄집어낸 단검이다. 자루 끝에 박힌 한 알의 보석이 새벽마다 한쪽으로 슬쩍 도는데, 그 보석 안쪽엔 식지 않은 용암 한 방울이 작은 눈동자처럼 굳어 있다. 칼날의 균열은 그 눈이 도는 방향으로만 한 줄로 자란다.',
    art: 'uncanny eerie volcanic forge fire fantasy molten-eye dagger weapon item icon, dark dagger with a glowing molten orange eye gemstone at the pommel and lava cracks branching along the blade, single inanimate game loot object on transparent background',
  },
  {
    key: 'volcano_ember_rune_blade',
    slot: 'weapon',
    nameKo: '잉걸 룬의 검',
    region: '서쪽 화산',
    tone: '수수께끼',
    lore: '화로의 한 학자가 자기 검의 빈 fuller에 잉걸 한 알을 한 글자 모양으로 굳혀 넣은 것이다. 자루의 가시는 그 글자를 누구도 쥐지 않게 하려고 함께 굳힌 자리인데, 가시 한 줄에 한 새벽씩 옅은 빨간 빛이 한 박자 늦게 한 번 흐른다.',
    art: 'mysterious cryptic volcanic forge fire fantasy ember rune longsword weapon item icon, dark steel blade with a glowing ember rune line down the fuller and a thorned grip, single inanimate game loot object on transparent background',
  },
  {
    key: 'volcano_dragon_rune_axe',
    slot: 'weapon',
    nameKo: '용 화로의 도끼',
    region: '서쪽 화산',
    tone: '장엄',
    lore: '서쪽 화산의 가장 깊은 화로에서 한 장인이 평생 한 자루만 두드린 도끼다. 머리 가운데에 황금 한 알이 룬 모양으로 박혀 있고, 그 룬을 가로질러 한 줄의 용암 균열이 검은 머리에 한 박자 늦은 박동으로 짙어졌다 옅어진다.',
    art: 'grand legendary mythic volcanic forge fire fantasy dragon-forged greataxe weapon item icon, massive blackened axe head with a single gold rune at center and molten lava cracks branching across, single inanimate game loot object on transparent background',
  },

  // ── batch 5: 타락천사 weapon × 5 ──
  {
    key: 'fallen_cherub_resting_rapier',
    slot: 'weapon',
    nameKo: '케르빔이 안 떠난 검',
    region: '타락천사',
    tone: '위트',
    lore: '추락한 자가 떠난 새벽 신전 빈자리에 남은 가는 검이다. 검신 가운데에 어린 케르빔 한 명이 자기 침대인 양 두 다리를 펴고 누워 가만히 자고 있는데, 누가 검을 들어 올려도 케르빔은 한 번도 자기 자세를 흩뜨리지 않는다.',
    art: 'humorous mischievous cherub fallen angel divine fantasy thin rapier weapon item icon, slender silver rapier with a small chubby cherub baby lying playfully across the blade, single inanimate game loot object on transparent background',
  },
  {
    key: 'fallen_black_feather_blade',
    slot: 'weapon',
    nameKo: '검은 깃의 검',
    region: '타락천사',
    tone: '비애',
    lore: '추락한 자가 마지막으로 자기 깃을 한 가닥 떨어뜨린 자리에 한 신관이 자기 검의 crossguard에 그 깃을 묶어 둔 것이다. 깃의 검은색은 신관이 검을 닦아도 닦이지 않고, 자루 위 흰 천은 그 깃을 가리려 매번 한 줄로 더 감긴다.',
    art: 'mournful sorrowful fallen angel divine fantasy longsword weapon item icon, dark silver blade with a single black feather tied at the crossguard and a torn ivory cloth wrapped around the grip, single inanimate game loot object on transparent background',
  },
  {
    key: 'fallen_decay_wing_scythe',
    slot: 'weapon',
    nameKo: '썩은 날개의 낫',
    region: '타락천사',
    tone: '기괴',
    lore: '추락한 자의 두 날개가 부패해 떨어진 자리에 한 신관이 그 깃들을 한 줄로 묶어 자기 낫의 양쪽에 박아 넣은 것이다. 날개 가운데에는 신관이 자기 손가락 끝으로 박아 둔 한 알의 보석이 한 박자 늦은 박동으로 짙어졌다 옅어진다.',
    art: 'uncanny eerie corrupted decaying fallen angel divine fantasy scythe weapon item icon, dark scythe with two large rotting feathered wings spread on each side and a single glowing gemstone at the center, single inanimate game loot object on transparent background',
  },
  {
    key: 'common_warrior_chakram',
    slot: 'weapon',
    nameKo: '전사의 차크람',
    region: '일반',
    tone: '전설',
    lore: '한 무명 전사가 자기 평생 한 번도 자기 손에서 떨어뜨리지 않은 결을 자기 강철 ring의 가장자리에 한 줄로 새긴 자리다. 둘레의 글리프는 그 전사가 자기 평생 한 번씩 더 짚어 본 적의 자국이고, 가운데에 한 줄 더 둘러진 가죽 grip은 그가 자기 손가락 끝으로 한 번 더 묶어 둔 자리다.',
    art: 'legendary mythic ancient fantasy warrior chakram throwing disc weapon item icon, sharp gold-trimmed steel ring blade with engraved ancient warrior glyphs along the rim and a small leather grip wrap at the bottom, single inanimate game loot object on transparent background',
  },
  {
    key: 'fallen_seraph_glaive',
    slot: 'weapon',
    nameKo: '세라프의 글레이브',
    region: '타락천사',
    tone: '장엄',
    lore: '한 세라프가 추락하기 전 마지막으로 자기 자리에 세워 두고 떠난 글레이브다. 검신 뒤로 한 줄의 황금 후광이 동심원으로 굳어 있고, 양 옆엔 그 세라프가 떨어뜨린 두 깃이 한 번도 식지 않은 채 굳어 있어 새벽 햇살이 그 자리에서 한 박자 더 머문다.',
    art: 'grand legendary mythic seraphic celestial fallen angel divine fantasy glaive weapon item icon, tall pale silver curved glaive blade with concentric gold halo arcs behind and two large white feathers framing the head, single inanimate game loot object on transparent background',
  },

  // ── batch 6: 일반 region weapon × 5 ──
  {
    key: 'common_clover_dirk',
    slot: 'weapon',
    nameKo: '행운의 단검',
    region: '일반',
    tone: '위트',
    lore: '시장의 한 노점상이 자기 단검의 grip에 자기 어머니가 들에서 가져다 준 네잎 클로버 한 잎을 한 줄로 묶어 두었다. 그 자리 옆에 한 잎이 더 마르지 않는 자리가 있어, 노점상은 늘 그 자리에 손가락을 한 번씩 짚어 본 뒤 거래를 시작한다.',
    art: 'humorous lucky charming fantasy traveler dagger weapon item icon, simple steel dagger with a small four-leaf clover charm tied at the grip with a cord, single inanimate game loot object on transparent background',
  },
  {
    key: 'common_widow_veil_blade',
    slot: 'weapon',
    nameKo: '과부의 검',
    region: '일반',
    tone: '비애',
    lore: '한 과부가 자기 남편의 검을 마차 옆에 세워 두면서 자기 베일을 한 자락 떼어 crossguard에 한 줄로 묶은 자리다. 검은 베일은 검신을 따라 한 호흡 늦게 흔들렸고, 마차의 다음 손님이 그 흔들림을 한 번 짚어 보고는 자기 머리도 한 번 숙였다.',
    art: 'mournful sorrowful widow fantasy human village longsword weapon item icon, plain steel blade with a black mourning veil tied at the crossguard hanging down along the blade, single inanimate game loot object on transparent background',
  },
  {
    key: 'common_acrobat_fan_blade',
    slot: 'weapon',
    nameKo: '곡예사의 칼 부채',
    region: '일반',
    tone: '위트',
    lore: '한 광장에서 평생 자기 부채로 사람들의 웃음을 풀어 둔 한 곡예사가 마지막 새벽에 자기 부채의 spoke 끝마다 한 알의 칼날을 박아 둔 자리다. 그 칼날들은 부채를 흔드는 새벽에 한 박자 늦은 빛으로 한 번씩 더 가만히 흔들린다.',
    art: 'humorous quirky fantasy acrobat folding fan blade weapon item icon, ornate red and gold half-opened folding fan with sharp steel blades along each spoke, single inanimate game loot object on transparent background',
  },
  {
    key: 'common_scribe_quill_wand',
    slot: 'weapon',
    nameKo: '사관의 깃촉 wand',
    region: '일반',
    tone: '수수께끼',
    lore: '한 사관이 평생 자기 옆구리에 차고 다닌 깃촉 wand다. 가운데에 박힌 푸른 보석이 그가 한 줄을 새겨 들어갈 때마다 한 박자 늦은 빛으로 답해 주었는데, 보석의 한 박자가 흐릿한 새벽엔 사관은 그날의 줄을 쓰지 않았다.',
    art: 'mysterious cryptic chronicler fantasy human scholar quill wand weapon item icon, slim writing-quill-shaped wand with an ink-stained nib at the bottom, a single small blue gem at the center, and two white feathered barbs at the top, single inanimate game loot object on transparent background',
  },
  {
    key: 'common_hero_greatsword',
    slot: 'weapon',
    nameKo: '영웅의 대검',
    region: '일반',
    tone: '장엄',
    lore: '한 영웅이 자기 평생의 길 끝에 자기 마을의 광장 한가운데에 세워 두고 떠난 대검이다. crossguard에서 굳은 두 황금 날개가 가운데 푸른 보석 한 알을 양쪽에서 가만히 받치고 있고, 보석 안쪽엔 그가 마지막 새벽까지 한 번 더 휘두를 자리가 한 줄로 새겨져 있다.',
    art: 'grand legendary heroic fantasy human village hero two-handed greatsword weapon item icon, massive shining steel blade with golden winged crossguard and a single blue gemstone at the center, single inanimate game loot object on transparent background',
  },

  // ── batch 7 (부분, 담백/일상 제외 후 영웅담 2종만 유지) ──
  {
    key: 'orc_first_hunt_broken_axe',
    slot: 'weapon',
    nameKo: '부서진 첫 사냥의 도끼',
    region: '오크 부락',
    tone: '영웅담',
    lore: '부락의 한 어린 오크가 자기 첫 사냥에서 그 짐승의 송곳니에 자기 도끼 칼날 한쪽이 부서지자, 부서진 자리에 그 송곳니를 한 줄로 꿰어 매단 자리다. 부락의 늙은 전사는 그 부서진 자리를 깎아 다듬지 말라고 한 줄로 어린 오크의 자루에 적어 주었다.',
    art: 'heroic epic orcish tribal fantasy first hunt axe weapon item icon, dark iron axe with one chipped broken blade edge and a yellowed tusk hanging from the haft on a cord, single inanimate game loot object on transparent background',
  },
  {
    key: 'volcano_first_ember_hammer',
    slot: 'weapon',
    nameKo: '첫 잉걸의 망치',
    region: '서쪽 화산',
    tone: '영웅담',
    lore: '서쪽 화로의 첫 잉걸 한 알을 그 화로의 첫 풀무지기가 자기 망치 머리 안에 봉인한 것이라 한다. 망치를 두드리면 잉걸의 빛이 가운데에서 한 박자 늦게 한 번 짙어졌다 옅어지고, 그 한 박자에 다른 화로의 풀무지기들도 한 호흡을 맞춰 두드린다.',
    art: 'heroic epic volcanic forge fire fantasy first ember blacksmith hammer weapon item icon, large dark hammer with a single glowing orange ember sealed in the center of the head, single inanimate game loot object on transparent background',
  },

  // ── batch 8: 영웅담 1종 ──
  {
    key: 'marsh_ferry_harpoon',
    slot: 'weapon',
    nameKo: '뱃사공의 작살',
    region: '늪지대',
    tone: '영웅담',
    lore: '늪 한가운데서 큰 손 하나가 물 아래로 끌어내려 한 자루를 잠시 멈추게 한 뱃사공이 자기 자리로 돌아온 새벽에 자기 작살의 자루에 그 자국이 가시처럼 남았다. 자루에 감긴 한 줄의 코일은 그 새벽에 그가 묶어 둔 자리 그대로다.',
    art: 'heroic epic marsh swamp fantasy ferryman harpoon weapon item icon, dark harpoon with thorn-marked shaft and a single iron coiled rope wrapping, single inanimate game loot object on transparent background',
  },

  // ── batch 9: 전설 2종 ──
  {
    key: 'orc_ancestor_twin_tusk_axe',
    slot: 'weapon',
    nameKo: '조상의 양날 도끼',
    region: '오크 부락',
    tone: '전설',
    lore: '부락의 첫 조상이 자기 두 손에 한 자루의 양날 도끼를 들고 부락의 첫 자리를 열었다고 전해 내려오는 도끼다. 두 칼날 위로 그 조상이 길에 잡은 짐승들의 송곳니 두 개가 솟아 있고, 자루 둘레의 가시는 부락 사람이 한 세대마다 한 줄씩 더 깎아 박는다.',
    art: 'legendary mythic ancient orcish tribal ancestor fantasy two-handed twin-edged axe weapon item icon, massive twin-bladed iron axe with two protruding tusks and a thorned haft, single inanimate game loot object on transparent background',
  },
  {
    key: 'volcano_dragon_bone_blade',
    slot: 'weapon',
    nameKo: '용뼈의 검',
    region: '서쪽 화산',
    tone: '전설',
    lore: '서쪽 화산이 식기 전 그 안에서 잠든 용의 등뼈 한 토막으로 깎아 낸 검이다. 검신 가운데를 한 줄로 흐르는 용암 균열은 그 용이 식다가 한 박자 더 숨을 내쉰 자리이고, 검을 휘두를 때마다 그 한 박자가 손바닥으로 한 번 더 전해진다.',
    art: 'legendary mythic ancient volcanic dragon fantasy dragonbone longsword weapon item icon, blade carved from a single curved dragon vertebra with a glowing molten crack running down the center, single inanimate game loot object on transparent background',
  },

  // ── batch 10: 화려 5종 ──
  {
    key: 'marsh_gemwoven_wand',
    slot: 'weapon',
    nameKo: '보석 그물 wand',
    region: '늪지대',
    tone: '화려',
    lore: '늪 깊은 자리의 한 마녀가 자기 wand 둘레에 길어 올린 청록 보석들을 황금 그물로 한 줄로 엮어 박은 자리다. 보석 알 하나하나는 그 마녀가 늪에서 만난 사람의 새벽 하나씩을 끌어와 굳힌 것이라 한다.',
    art: 'ornate flamboyant lavishly decorated gilded marsh swamp fantasy jeweled wand weapon item icon, wand with multiple teal gemstones woven into a gold mesh net wrapping along the shaft, single inanimate game loot object on transparent background',
  },
  {
    key: 'orc_totem_chief_axe',
    slot: 'weapon',
    nameKo: '조상 얼굴의 도끼',
    region: '오크 부락',
    tone: '화려',
    lore: '부락의 부족장이 자기 도끼 머리를 자기 조상의 얼굴 모양으로 깎고, 그 이마 가운데에 첫 사냥에서 얻은 큰 빨간 보석을 한 알 박아 둔 것이다. 자루 아래로 늘어진 두 줄의 깃털은 부족장이 마지막 새벽까지 떠날 때마다 한 줄씩 손가락 끝으로 짚어 본 자리다.',
    art: 'ornate flamboyant gilded orcish tribal chieftain fantasy totem axe weapon item icon, iron axe head carved into an ancestor face with a large red gemstone in the forehead and two feather strands hanging from the haft, single inanimate game loot object on transparent background',
  },
  {
    key: 'common_grand_executioner_halberd',
    slot: 'weapon',
    nameKo: '처형인의 미늘창',
    region: '일반',
    tone: '장엄',
    lore: '한 왕국의 첫 처형인이 자기 평생 한 번도 자기 손가락 끝을 떨지 않은 결을 자기 미늘창의 곡선 칼날에 한 번 더 굳혀 박아 둔 자리다. 양 옆의 옅은 빛은 처형인이 자기 자리에서 한 번 더 자기 결정을 미룬 새벽마다 한 줄씩 더 옅어진다.',
    art: 'grand majestic imposing fantasy royal executioner halberd weapon item icon, tall heavy iron halberd with a curved axe blade, a long spike on top, a small back hook, and a dark wood haft with faint glow at the sides, single inanimate game loot object on transparent background',
  },
  {
    key: 'volcano_phoenix_blade',
    slot: 'weapon',
    nameKo: '불사조의 검',
    region: '서쪽 화산',
    tone: '화려',
    lore: '서쪽 화산이 한 번 다 식고 한 번 다시 태어났다는 새벽에 그 불사조의 깃을 떨어뜨린 자리에서 한 장인이 그 깃의 모양 그대로 자기 검의 crossguard를 깎아 낸 자리다. 검신 위로 한 줄의 빨간 룬이 그 새벽의 한 박자를 지금도 한 번씩 더 그어 준다.',
    art: 'ornate flamboyant gilded volcanic fire phoenix fantasy ornate longsword weapon item icon, golden blade with red rune line down the fuller and ornate phoenix wing crossguard with red gemstone, single inanimate game loot object on transparent background',
  },
  {
    key: 'fallen_golden_glaive',
    slot: 'weapon',
    nameKo: '황금 깃의 글레이브',
    region: '타락천사',
    tone: '화려',
    lore: '한 세라프가 추락하기 전 자기 깃 두 개를 자기 글레이브의 양 옆에 황금으로 덮어 굳혀 둔 자리다. 자루의 가시는 그 세라프가 자기 손가락이 떨지 않게 한 줄로 박아 둔 자리이고, 가운데 보석은 그가 마지막 새벽 한 번 더 잡으려 한 자리에 한 알이 박혀 있다.',
    art: 'ornate flamboyant gilded fallen angel divine seraphic fantasy ornate glaive weapon item icon, golden curved glaive blade with two small golden wings on each side and a single gemstone at the center, single inanimate game loot object on transparent background',
  },

  // ── batch 11: 일반 region 새 톤 보충 + 추가 전설 ──
  {
    key: 'common_knight_lance',
    slot: 'weapon',
    nameKo: '기사의 lance',
    region: '일반',
    tone: '영웅담',
    lore: '한 늙은 기사가 마지막 진영 앞에 자기 lance를 한 번 더 들고 섰다. 자루 끝에 묶인 황금 깃발은 그가 평생 들고 다닌 자기 가문의 마지막 한 자락이고, 자루의 가시는 그가 살아온 길에서 한 번씩 적을 멈추게 한 자리에 한 줄씩 박은 것이다.',
    art: 'heroic epic fantasy human knight lance weapon item icon, brown sturdy lance with a golden cloth pennant tied near the tip and small thorn-marks along the shaft, single inanimate game loot object on transparent background',
  },
  {
    key: 'common_anointed_sabre',
    slot: 'weapon',
    nameKo: '기름 부음의 검',
    region: '일반',
    tone: '전설',
    lore: '한 늙은 왕이 마지막 새벽 자기 후계자에게 기름을 부으면서 그 후계자의 어깨에 한 번 가만히 내려놓은 검이다. 황금 swept guard에는 첫 일곱 후계자의 이름이 한 줄로 새겨져 있고, 새 이름을 더할 자리는 그 일곱 자리 옆에 한 줄로 남아 있다.',
    art: 'legendary mythic ancient storied fantasy anointed kings sabre weapon item icon, slim curved sword with ornate gold swept guard engraved with royal names, single inanimate game loot object on transparent background',
  },
  {
    key: 'common_twin_dragon_scepter',
    slot: 'weapon',
    nameKo: '두 용의 scepter',
    region: '일반',
    tone: '화려',
    lore: '한 왕국의 첫 왕이 자기 즉위 새벽에 두 용의 머리를 자기 scepter의 양 옆에 황금으로 굳혀 박은 것이다. 두 용의 시선이 마주 보는 자리에 가운데 한 알의 큰 진주가 박혀 있어, 왕이 자기 결정을 한 번 더 미루는 새벽엔 그 진주의 빛이 한 박자 늦게 옅어진다.',
    art: 'ornate flamboyant gilded fantasy royal twin-dragon kings scepter weapon item icon, gold scepter with two dragon-wing dragon-head ornaments flanking a single large central pearl, single inanimate game loot object on transparent background',
  },
  {
    key: 'rune_first_chronicler_pen',
    slot: 'weapon',
    nameKo: '첫 사관의 깃촉',
    region: '고대 룬 산맥',
    tone: '전설',
    lore: '룬 산맥의 첫 사관이 자기 손가락 끝으로 청록 깃 한 가닥을 산문 돌 위에서 한 번 흔든 자리에 한 자루 펜이 굳어 떨어졌다. 그 깃촉은 사관이 자기 마지막 새벽까지 한 줄도 잘못 쓰지 않은 자루이고, nib 끝엔 그 새벽의 한 알의 잉크가 그대로 굳어 있다.',
    art: 'legendary mythic ancient storied mountain rune fantasy first scribe quill pen weapon item icon, tall teal feather quill pen with a single silver-nib tip and a small drop of ink frozen at the tip, single inanimate game loot object on transparent background',
  },
  {
    key: 'fallen_starhead_flail',
    slot: 'weapon',
    nameKo: '별 형상의 flail',
    region: '타락천사',
    tone: '전설',
    lore: '한 대천사가 자기 손에 별의 모양을 한 번 굳혀 박아 두고 추락한 자리다. 별의 한 끝에 검은 깃 한 가닥이 체인의 끝에서 한 박자 늦게 흔들리고 있고, 별의 가운데 자리는 그 대천사가 마지막 새벽까지 자기 자리로 다시 돌아오지 않은 빈 자리 그대로다.',
    art: 'legendary mythic ancient fallen angel archangel divine fantasy starhead flail weapon item icon, silver star-shaped flail head with a single black feather hanging from the chain, single inanimate game loot object on transparent background',
  },

  // ── batch 12: weapon 마지막 5종 (weapon 50/50 완성) ──
  {
    key: 'common_two_handed_morningstar',
    slot: 'weapon',
    nameKo: '양손 모닝스타',
    region: '일반',
    tone: '장엄',
    lore: '한 왕국의 첫 흑기사가 자기 평생 한 번도 자기 두 손으로 자기 자루를 한 번 더 놓지 않은 결을 자기 모닝스타의 가시 한 알 한 알에 한 번 더 박아 둔 자리다. 가시 한 알이 한 번 떨어지는 새벽은 그 흑기사가 자기 자리에서 한 번 더 누군가의 결정을 한 번 더 막은 자리다.',
    art: 'grand majestic imposing fantasy two-handed morningstar mace weapon item icon, long dark steel haft with a massive spiked iron ball at the top with many sharp short spikes radiating outward, single inanimate game loot object on transparent background',
  },
  {
    key: 'common_emperor_naginata',
    slot: 'weapon',
    nameKo: '황제의 나기나타',
    region: '일반',
    tone: '화려',
    lore: '한 황제가 자기 즉위 새벽에 자기 평생 한 번도 자기 자리에서 들어 본 적 없는 나기나타를 자기 등 뒤에 한 번 더 세워 두고 떠난 자리다. 칼날에 새겨진 학 무늬는 그 황제가 자기 자리에서 한 번 더 자기 자리로 돌아오지 않은 결대로 굳어 있고, 아래 빨간 술은 그 새벽의 첫 빛이 한 번 더 매달려 굳은 자리다.',
    art: 'ornate flamboyant gilded fantasy emperor ceremonial naginata polearm weapon item icon, long gold-inlaid lacquered wood pole with a curved single-edged blade engraved with crane patterns and a red silk tassel below the blade, single inanimate game loot object on transparent background',
  },
  {
    key: 'orc_warband_cleaver',
    slot: 'weapon',
    nameKo: '워밴드의 도끼',
    region: '오크 부락',
    tone: '영웅담',
    lore: '부락의 한 전사 대장이 자기 일곱 동무의 첫 사냥에서 가져온 짐승 두개골을 자기 도끼 자루에 한 줄로 엮어 둔 자리다. 두 깃털은 그가 마지막 새벽까지 자기 동무 둘이 떠나지 못한 자리에 남긴 표식이고, 도끼 머리의 가시는 그 둘의 자리를 대신해 그가 한 번씩 더 휘둘러 박은 자국이다.',
    art: 'heroic epic orcish tribal warband fantasy cleaver axe weapon item icon, dark iron cleaver-axe with small skulls and cord tied along the haft and two feathers hanging at the grip, single inanimate game loot object on transparent background',
  },
  {
    key: 'marsh_witch_queen_staff',
    slot: 'weapon',
    nameKo: '늪 여왕의 staff',
    region: '늪지대',
    tone: '전설',
    lore: '늪의 가장 깊은 자리에 한 번 살았다고 전해 내려오는 마녀 여왕이 자기 자리에 세워 두고 떠난 staff다. 끝에 굳은 청록 orb는 여왕이 늪의 한 호흡을 자기 손바닥 안에 굳혀 박은 자리이고, orb를 감싼 root는 그 새벽 이후로도 매해 한 가닥씩 더 자라 올라온다.',
    art: 'legendary mythic ancient marsh swamp witch queen fantasy staff weapon item icon, tall gnarled black staff with a large dark teal orb cradled at the top by curled root claws, single inanimate game loot object on transparent background',
  },
  {
    key: 'common_jester_lollipop_mace',
    slot: 'weapon',
    nameKo: '광대의 막대사탕 mace',
    region: '일반',
    tone: '위트',
    lore: '한 왕실의 광대가 자기 평생 한 번도 자기 손에서 떨어뜨리지 않은 거대 막대사탕이다. 빨강·흰 소용돌이는 광대가 자기 자리에서 한 번 더 자기 농담을 한 줄로 더 풀어 놓을 때마다 한 박자 늦은 색으로 한 번씩 더 자기 결을 둘러 박은 자리다.',
    art: 'humorous quirky whimsical fantasy court jester giant lollipop mace weapon item icon, oversized round candy lollipop with red and white swirl pattern on a sturdy wooden stick, single inanimate game loot object on transparent background',
  },

  // ═══════ armor 50종 ═══════
  // ── batch 13: armor 시작 5종 ──
  {
    key: 'marsh_lily_dress',
    slot: 'armor',
    nameKo: '백합의 드레스',
    region: '늪지대',
    tone: '아름다운',
    lore: '늪의 한 마녀가 자기 손바닥 위에 한 송이 백합을 한 번 들여다본 새벽에 그 백합의 결대로 자기 dress를 한 자락 짜 내려놓은 것이다. 가슴께에 가만히 자라난 청록 보석은 백합이 자기 결을 dress 안쪽에 한 번 더 박아 둔 자리다.',
    art: 'beautiful elegant graceful marsh swamp witch fantasy lily dress robe armor item icon, slender pale flowing dress with a single teal lily-shaped gemstone at the chest, single inanimate game loot object on transparent background',
  },
  {
    key: 'orc_palm_print_vest',
    slot: 'armor',
    nameKo: '손바닥 자국 가죽 vest',
    region: '오크 부락',
    tone: '위트',
    lore: '부락의 한 어린 오크가 자기 첫 사냥 새벽에 그 짐승을 한 번 잡은 자기 손바닥을 자기 가죽 vest에 한 번 더 찍어 둔 자리다. 손바닥 자국 아래로 그 사냥의 송곳니 두 개가 한 줄로 매달려 있고, 그 어린 오크는 그 자국이 옅어질 때까지 vest를 한 번도 벗지 않았다.',
    art: 'humorous orcish tribal fantasy leather warpaint vest armor item icon, brown leather chest vest with a single red palm-print smear and two tusks hanging from the chest cord, single inanimate game loot object on transparent background',
  },
  {
    key: 'rune_single_curve_stone_plate',
    slot: 'armor',
    nameKo: '한 줄 곡선의 stone plate',
    region: '고대 룬 산맥',
    tone: '기괴',
    lore: '룬 산맥의 한 새김장이가 자기 stone breastplate 가슴께에 한 줄의 곡선만 한 번 더 깊이 그어 둔 자리다. 그 곡선이 어떤 룬인지는 그 새김장이도 자기 마지막 새벽까지 답하지 않았는데, 한 번씩 보는 사람마다 그 곡선이 한 번씩 다른 모양으로 보인다고 한다.',
    art: 'uncanny eerie mountain rune ancient fantasy stone breastplate armor item icon, dark gray stone breastplate with a single deep curved rune line carved across the chest, single inanimate game loot object on transparent background',
  },
  {
    key: 'volcano_ember_embroidered_cloak',
    slot: 'armor',
    nameKo: '잉걸 자수의 cloak',
    region: '서쪽 화산',
    tone: '수수께끼',
    lore: '서쪽 화로 옆 마을의 한 자수가가 자기 cloak 한 자락에 잉걸 한 알을 한 줄로 박아 넣은 자리다. cloak 안쪽에서 한 번씩 옅게 흘러나오는 작은 빛은 그 자수가가 자기 손가락 끝으로 그 잉걸의 가장자리에 한 줄씩 더 박아 둔 결을 따라 한 박자 늦게 흘러간다.',
    art: 'mysterious cryptic volcanic forge fire fantasy ashen hooded cloak armor item icon, dark gray hooded cloak with glowing ember embroidery along the hem and a small sealed rune at the collar, single inanimate game loot object on transparent background',
  },
  {
    key: 'fallen_seraph_dark_breastplate',
    slot: 'armor',
    nameKo: '추락한 자의 흉갑',
    region: '타락천사',
    tone: '장엄',
    lore: '한 세라프가 추락하기 전 자기 흉갑 가운데에 자기 후광을 한 번 더 황금으로 굳혀 박아 두고 떠난 자리다. 양 옆에 굳은 두 검은 날개는 그 세라프가 자기 자리를 한 번 더 안 돌아본다는 약속처럼 펴진 채 굳었고, 후광의 동심원은 한 새벽에 한 줄씩 옅어진다.',
    art: 'grand majestic legendary fallen angel seraphic divine fantasy dark seraph breastplate armor item icon, dark chest plate with concentric gold halo embossed at the center and two dark feathered wing pauldrons, single inanimate game loot object on transparent background',
  },

  // ── batch 14: armor 두 번째 5종 ──
  {
    key: 'common_imperial_dragon_robe',
    slot: 'armor',
    nameKo: '황제의 용 robe',
    region: '일반',
    tone: '화려',
    lore: '한 황제가 자기 즉위 새벽에 자기 가슴에 한 마리의 용을 한 번 더 자기 silk robe 위로 황금으로 굳혀 자수한 자리다. 용의 비늘 하나하나는 황제가 자기 평생 한 번씩 더 짚어 본 자기 광맥의 결을 따라 한 자국씩 더 깊어졌고, jade buttons는 그가 자기 자리에서 한 번도 풀지 않은 결대로 한 알씩 더 가만히 박혀 있다.',
    art: 'ornate flamboyant gilded fantasy imperial dragon robe armor item icon, long flowing red and gold silk robe with embroidered gold dragon coiling across the chest, jade jewel buttons, and wide ornate sleeves, single inanimate game loot object on transparent background',
  },
  {
    key: 'common_knight_chainmail_hauberk',
    slot: 'armor',
    nameKo: '기사의 사슬갑옷',
    region: '일반',
    tone: '장엄',
    lore: '한 왕국의 첫 기사가 자기 평생 한 번도 자기 자리에서 한 줄도 풀지 않은 결을 자기 사슬갑옷의 한 알 한 알에 한 번 더 박아 둔 자리다. 가슴께의 가죽 벨트는 그가 자기 손가락 끝으로 한 번 더 묶은 자리에서 한 번도 풀린 적 없고, collar에 굳어진 사슬 coif는 기사가 자기 머리 위로 한 번 더 올려 본 결대로 가만히 늘어져 있다.',
    art: 'grand majestic imposing fantasy knight chainmail hauberk armor item icon, full grey chainmail armor with interlocking rings, a sturdy leather belt at the waist, and a small mail coif draped at the collar, single inanimate game loot object on transparent background',
  },
  {
    key: 'rune_guardian_brass_helm',
    slot: 'armor',
    nameKo: '수호자의 brass 투구',
    region: '고대 룬 산맥',
    tone: '영웅담',
    lore: '룬 산맥의 산문을 자기 평생의 자리로 삼은 한 보초가 자기 brass 투구의 이마 가운데에 보호의 룬을 한 글자 더 깊이 박아 둔 자리다. 그 글자가 한 번 빛을 머금는 새벽엔 산문 앞에 다가오던 발자국 하나가 그 자리에서 한 박자 멈춰 섰다.',
    art: 'heroic epic mountain rune ancient fantasy guardian brass helm armor item icon, polished brass full helm with a single deep protective rune carved on the brow, single inanimate game loot object on transparent background',
  },
  {
    key: 'volcano_phoenix_robe',
    slot: 'armor',
    nameKo: '불사조의 robe',
    region: '서쪽 화산',
    tone: '화려',
    lore: '서쪽 화산의 한 자수가가 자기 robe 전체에 불사조 한 마리를 한 번 펼쳐 박아 넣은 자리다. robe의 두 옷자락은 그 불사조의 날개가 그대로 펴진 모양으로 굳어 있고, 가슴께의 황금 깃은 그 불사조가 자기 가슴을 한 번 더 안에서 보여 준 자국이다.',
    art: 'ornate flamboyant gilded volcanic phoenix fire fantasy ornate robe armor item icon, deep red flowing robe with massive embroidered phoenix wings spread across the sleeves and golden phoenix feathers at the chest, single inanimate game loot object on transparent background',
  },
  {
    key: 'fallen_white_silk_robe',
    slot: 'armor',
    nameKo: '흰 silk의 robe',
    region: '타락천사',
    tone: '아름다운',
    lore: '한 천사가 추락하지 않으려 자기 손가락 끝으로 한 가닥 흰 silk를 자기 robe의 가운데에 한 줄로 길게 늘여 놓은 자리다. 그 한 줄 trim 위로 한 가닥씩 옅게 떠 있는 깃털 자수는 그 천사가 자기 깃 하나를 한 번 더 자기 자리에 남겨 두려 한 표식이다.',
    art: 'beautiful elegant graceful fallen angel divine fantasy long silk robe armor item icon, long flowing pale ivory silk robe with a single gold trim line down the center and delicate feather embroidery along the sleeves, single inanimate game loot object on transparent background',
  },

  // ── batch 15: armor 세 번째 5종 ──
  {
    key: 'marsh_frog_nest_hat',
    slot: 'armor',
    nameKo: '개구리 둥지 모자',
    region: '늪지대',
    tone: '위트',
    lore: '늪의 한 아이가 자기 손바닥 위에 한 마리 개구리를 한 번 들어 보고는 자기 모자 가운데에 그 자리를 한 줄로 비워 두었다. 모자 둘레의 잎과 잔가지는 그 개구리가 한 번 더 앉으러 올 자리를 한 호흡 만큼 더 크게 짠 자국이다.',
    art: 'humorous whimsical marsh swamp fantasy frog nest leaf hat armor item icon, wide green leaf hat woven from twigs with a small live green frog sitting in the center nest, single inanimate game loot object on transparent background',
  },
  {
    key: 'orc_ribcage_chest',
    slot: 'armor',
    nameKo: '갈비뼈 가슴갑',
    region: '오크 부락',
    tone: '기괴',
    lore: '부락의 한 늙은 사냥꾼이 평생 자기 손에 잡힌 짐승들의 갈비뼈를 한 줄씩 자기 가슴갑 가죽 위에 한 자리씩 더 박아 둔 것이다. 갈비뼈 한 가닥 한 가닥은 사냥꾼이 자기 호흡을 그 짐승의 마지막 호흡 위에 한 번씩 더 얹어 본 자리다.',
    art: 'uncanny eerie unsettling orcish tribal fantasy bone chest armor item icon, dark leather chest piece covered with sewn-together animal ribcage bones forming a second rib pattern, single inanimate game loot object on transparent background',
  },
  {
    key: 'rune_high_priest_crown',
    slot: 'armor',
    nameKo: '룬 산맥 대제사장의 관',
    region: '고대 룬 산맥',
    tone: '장엄',
    lore: '룬 산맥의 일곱 산문 안쪽에서 평생 한 번도 자기 자리를 벗어나지 않은 한 대제사장이 자기 마지막 새벽에 자기 관과 망토를 한 자리에 같이 벗어 두고 떠난 자리다. 관 가운데에 새겨진 룬은 그가 평생 한 번도 그 산문 안쪽에서 입 밖으로 꺼낸 적 없는 한 글자다.',
    art: 'grand majestic imposing mountain rune ancient fantasy high priest crown with mantle armor item icon, dark iron crown engraved with a single carved rune at the front and a long dark blue mantle flowing down, single inanimate game loot object on transparent background',
  },
  {
    key: 'volcano_blacksmith_apron',
    slot: 'armor',
    nameKo: '대장간의 가죽 앞치마',
    region: '서쪽 화산',
    tone: '영웅담',
    lore: '서쪽 화로 가장 안쪽 자리의 한 장인이 평생 한 자루의 망치를 자기 가죽 앞치마의 한 pocket에만 넣어 두고 두드린 자리다. 앞치마 가슴께의 어두운 자국은 그 망치가 한 번씩 더 자기 자리로 돌아온 새벽마다 한 줄씩 더 깊어졌다.',
    art: 'heroic epic volcanic forge fire fantasy blacksmith leather apron armor item icon, brown scorched leather apron with iron rivets and a single small chest pocket, single inanimate game loot object on transparent background',
  },
  {
    key: 'common_court_jester_motley',
    slot: 'armor',
    nameKo: '광대의 motley 튜닉',
    region: '일반',
    tone: '위트',
    lore: '한 왕실의 광대가 자기 평생 자기 몸에 한 번도 다른 색을 두르지 않은 결을 자기 튜닉의 네 자락에 한 번 더 네 가지 색으로 갈라 박은 자리다. hem 둘레의 작은 종은 광대가 자기 자리에서 한 번 더 농담을 끝낸 새벽마다 한 알씩 더 가만히 매달려 있다.',
    art: 'humorous quirky whimsical fantasy court jester motley patchwork tunic armor item icon, brightly colored four-quadrant patchwork tunic in red, yellow, green, and blue with small bells hanging from the hem and a striped collar, single inanimate game loot object on transparent background',
  },

  // ── batch 16: armor 네 번째 5종 ──
  {
    key: 'common_legendary_relic_breastplate',
    slot: 'armor',
    nameKo: '영웅 새김의 흉갑',
    region: '일반',
    tone: '전설',
    lore: '한 왕국의 첫 일곱 영웅이 자기 자리에서 한 번 더 자기 결을 같이 모으던 새벽에, 그들 중 한 명이 자기 흉갑의 가슴께에 그 일곱의 얼굴을 한 자리씩 더 깊이 새겨 둔 자리다. 가운데 박힌 한 알의 루비는 그 일곱이 자기 한 호흡을 한 자리에 모으던 결을 따라 한 번 더 굳어진 자리다.',
    art: 'legendary mythic ancient fantasy hero relic breastplate armor item icon, weathered bronze breastplate with three engraved ancient hero faces across the chest and a single embedded ruby gem at the heart, single inanimate game loot object on transparent background',
  },
  {
    key: 'common_pope_mitre_crown',
    slot: 'armor',
    nameKo: '교황의 미터',
    region: '일반',
    tone: '장엄',
    lore: '한 신성한 도시의 첫 교황이 자기 즉위 새벽에 자기 머리 위에 한 알의 흰·황금 미터를 한 번 더 박아 두고 자기 자리에 한 번 더 가만히 앉은 자리다. 미터 가운데에 굳어 박힌 황금 십자는 교황이 자기 평생 한 번도 자기 시선을 떼지 않은 결대로 굳어 있다.',
    art: 'grand majestic imposing fantasy pope high priest mitre crown armor item icon, tall pointed white and gold ceremonial mitre headpiece with an embroidered cross at the front and two narrow fanons hanging at the back, single inanimate game loot object on transparent background',
  },
  {
    key: 'volcano_drake_lord_helm',
    slot: 'armor',
    nameKo: '용 영주의 투구',
    region: '서쪽 화산',
    tone: '전설',
    lore: '서쪽 화산이 한 번 다 잠든 새벽에 그 화산의 가장 깊은 자리에서 잠들지 않은 용 한 마리가 자기 머리뼈를 한 풀무지기에게 자기 자리 대신 맡겨 둔 자리다. 두 빨간 눈은 그 용이 자기 자리로 한 번 더 돌아오는 날 안쪽에서 한 박자 더 짙어진다.',
    art: 'legendary mythic ancient volcanic dragon fantasy drake lord helm armor item icon, dark iron helm shaped like a snarling dragon head with two large curving horns and glowing red eyes, single inanimate game loot object on transparent background',
  },
  {
    key: 'fallen_archangel_gold_wings',
    slot: 'armor',
    nameKo: '대천사의 황금 두 깃',
    region: '타락천사',
    tone: '화려',
    lore: '한 대천사가 자기 두 깃을 마지막 새벽에 자기 양 어깨 위에 황금으로 한 번 더 굳혀 박아 두고 떠난 자리다. 두 깃 가운데에 박힌 푸른 보석은 그가 자기 자리로 한 번 더 돌아올 새벽까지 가만히 한 박자 늦은 빛을 머금고 기다린다.',
    art: 'ornate flamboyant gilded fallen angel archangel divine fantasy ornate wing pauldrons shoulder armor item icon, two large golden feathered wing pauldrons with a single blue sapphire set at the center, single inanimate game loot object on transparent background',
  },
  {
    key: 'common_king_cross_helm',
    slot: 'armor',
    nameKo: '왕의 십자 투구',
    region: '일반',
    tone: '장엄',
    lore: '한 왕국의 첫 왕이 자기 즉위 새벽에 자기 투구의 이마 가운데에 한 줄의 황금 십자를 한 번 더 깊이 박아 두고, 그 가운데에 자기 왕국 첫 광맥에서 가져온 푸른 보석 한 알을 박아 두었다. 그 십자는 다음 왕이 새 줄을 그 위에 한 번 더 더 그을 자리로 비워져 있다.',
    art: 'grand majestic imposing fantasy king crown war helm armor item icon, polished silver helm with a golden cross inlaid at the brow, a single blue sapphire at the center, and gold trim along the rim, single inanimate game loot object on transparent background',
  },

  // ── batch 17: armor 다섯 번째 5종 ──
  {
    key: 'orc_jester_hood',
    slot: 'armor',
    nameKo: '어릿광대의 모자',
    region: '오크 부락',
    tone: '위트',
    lore: '부락의 한 젊은 오크가 자기 동무들 앞에서 자기 사냥의 사연을 한 번 더 부풀려 늘어놓을 때마다 자기 모자 끝 종 한 알이 한 번씩 같이 울렸다. 그 종은 그가 자기 사연이 한 자국 더 부풀어 오를 때마다 한 박자 늦은 소리로 동무들 사이에 웃음을 한 줄로 더 풀어 놓아 주었다.',
    art: 'humorous orcish tribal fantasy jester two-tone mask hood armor item icon, green and brown jester hood with a single white jester face mask at the front and small bells on the ear flaps, single inanimate game loot object on transparent background',
  },
  {
    key: 'marsh_lord_robe',
    slot: 'armor',
    nameKo: '늪 영주의 robe',
    region: '늪지대',
    tone: '장엄',
    lore: '늪의 가장 깊은 자리에 살았다는 한 영주가 자기 자리에 두고 떠난 robe다. 어깨의 잎과 깃털 collar는 늪의 식물들이 한 번씩 자기 결을 robe 위에 묶어 둔 결이고, 가슴께의 큰 보석은 영주가 마지막 새벽 자기 손가락으로 한 번 더 짚어 본 자리다.',
    art: 'grand majestic imposing marsh swamp fantasy swamp lord robe armor item icon, dark teal flowing robe with leaf and feather shoulder collar and a single large dark gemstone clasp at the throat, single inanimate game loot object on transparent background',
  },
  {
    key: 'rune_silver_diadem',
    slot: 'armor',
    nameKo: '은빛 diadem',
    region: '고대 룬 산맥',
    tone: '아름다운',
    lore: '룬 산맥의 한 새김장이가 자기 평생의 연인이 한 번 자기 곁에 머무를 새벽을 위해 한 가닥 은을 자기 손가락 끝으로 한 줄로 펴 둔 것이다. 가운데에 박힌 청록 보석은 그 연인이 자기 자리에서 한 번 더 돌아본 새벽에 그 자리에 굳어 떨어진 한 알이다.',
    art: 'beautiful elegant graceful mountain rune ancient fantasy silver diadem armor item icon, delicate slim silver diadem with curling vine etchings and a single small teal teardrop gem at the center brow, single inanimate game loot object on transparent background',
  },
  {
    key: 'volcano_corrupted_mask',
    slot: 'armor',
    nameKo: '굳은 가면',
    region: '서쪽 화산',
    tone: '기괴',
    lore: '서쪽 화로 안쪽에서 한 번 식다가 다시 굳어진 한 가면이다. 두 눈자리 둘레로 한 줄씩 새어 나오던 오렌지 잉걸이 마지막 새벽에 가면의 가장자리에서 굳었고, 그 자리 너머로 가면 안쪽에 한 번 더 식지 않은 호흡 한 가닥이 가만히 들어 있다.',
    art: 'uncanny eerie unsettling volcanic forge fire fantasy corrupted face mask armor item icon, dark iron face mask with faint orange embers solidified around the eye sockets, single inanimate game loot object on transparent background',
  },
  {
    key: 'fallen_paladin_breastplate',
    slot: 'armor',
    nameKo: '팰러딘의 흉갑',
    region: '타락천사',
    tone: '영웅담',
    lore: '한 팰러딘이 자기 평생 한 번도 자기 자리에서 등 돌리지 않은 흉갑이다. 가슴께의 황금 해의 얼굴은 그가 마지막 새벽까지 자기 시선을 한 박자 늦추지 않은 결대로 굳어 있고, 가장자리의 황금 trim은 그가 자기 길에 두고 온 흠을 한 번 더 둘러 박은 자리다.',
    art: 'heroic epic fallen angel divine paladin fantasy breastplate armor item icon, polished silver breastplate with a golden sun face emblem at the center and gold trim along the rim, single inanimate game loot object on transparent background',
  },

  // ── batch 18: 희망 톤 시범 5종 ──
  {
    key: 'common_emperor_jade_crown',
    slot: 'armor',
    nameKo: '황제의 옥관',
    region: '일반',
    tone: '화려',
    lore: '한 황제가 자기 즉위 새벽에 자기 머리에 한 알의 큰 빨간 보석과 그 둘레의 푸른 jade를 한 번 더 황금 crown 위에 박아 둔 자리다. 양 옆에서 늘어진 jade bead strand는 황제가 자기 자리에서 한 번씩 더 자기 시선을 옮길 때마다 한 박자 늦은 결로 한 번씩 더 가만히 흔들린다.',
    art: 'ornate flamboyant gilded fantasy emperor jade crown armor item icon, ornate gold crown set with multiple polished green jade discs, dangling jade bead strands hanging from each side, and a large central red jewel, single inanimate game loot object on transparent background',
  },
  {
    key: 'orc_sunrise_tabard',
    slot: 'armor',
    nameKo: '일출 tabard',
    region: '오크 부락',
    tone: '희망',
    lore: '부락의 한 어린 오크가 자기 첫 사냥 새벽의 일출 자리를 자기 가슴 한 가운데에 한 번 더 작게 박아 둔 가죽 tabard다. 어깨와 가슴께의 황금 detail은 그 어린 오크가 자기 동무들과 같은 새벽을 한 번 더 함께 본다는 약속처럼 한 줄씩 더 둘러져 있다.',
    art: 'hopeful radiant warm orcish tribal fantasy sunrise tabard armor item icon, brown leather chest tabard with a small embroidered orange sunrise at the center chest and warm gold detail trim across shoulders, single inanimate game loot object on transparent background',
  },
  {
    key: 'rune_morning_light_cloak',
    slot: 'armor',
    nameKo: '새벽빛의 cloak',
    region: '고대 룬 산맥',
    tone: '희망',
    lore: '룬 산맥의 한 새벽 보초가 자기 망토의 collar 가운데에 새벽의 첫 sun-rune을 한 자만 더 박아 둔 자리다. 망토의 옷자락 둘레로 한 줄씩 흐르는 작은 빛 자수는 그가 자기 보초 자리에서 처음 본 새벽의 결을 한 새벽씩 더 따라 적어 둔 자리다.',
    art: 'hopeful radiant warm mountain rune fantasy morning light cloak armor item icon, pale sky-blue hooded cloak with a small gold sun-rune at the collar and warm light embroidery along the hem, single inanimate game loot object on transparent background',
  },
  {
    key: 'volcano_first_spark_apron',
    slot: 'armor',
    nameKo: '첫 불씨의 앞치마',
    region: '서쪽 화산',
    tone: '희망',
    lore: '서쪽 화로의 한 어린 풀무지기가 자기 첫 불씨 한 알을 자기 가죽 앞치마 pocket 한가운데에 한 번 더 옮겨 두고 자기 자리로 돌아온 자리다. 그 한 알은 풀무지기가 다음 새벽 자기 화로를 다시 켜기 전까지 한 박자 늦은 빛으로 가만히 자기 자리를 지킨다.',
    art: 'hopeful radiant warm volcanic forge fire fantasy first spark apron armor item icon, warm brown leather apron with a single bright orange spark glowing inside the chest pocket, single inanimate game loot object on transparent background',
  },
  {
    key: 'fallen_dawn_wing_chest',
    slot: 'armor',
    nameKo: '새벽 깃의 흉갑',
    region: '타락천사',
    tone: '희망',
    lore: '한 천사가 추락하지 않은 자기 동료의 새벽 깃 두 가닥을 자기 흉갑 양 옆에 한 번 더 황금으로 굳혀 박아 둔 자리다. 가운데에 박힌 sun 모양 보석은 그 동료가 자기 자리에서 다시 한 번 더 자기 새벽을 맞이한 결대로 가만히 빛을 머금고 있다.',
    art: 'hopeful radiant warm blessed fallen angel divine fantasy dawn wings chest armor item icon, oval gold chest plate with two small white feather wings on each side and a sun-shaped gemstone at the center, single inanimate game loot object on transparent background',
  },

  // ── batch 19: armor 다양 톤 5종 ──
  {
    key: 'marsh_big_lilypad_hat',
    slot: 'armor',
    nameKo: '큰 연잎 모자',
    region: '늪지대',
    tone: '위트',
    lore: '늪 가운데 가장 큰 연잎 한 장이 한 새벽에 자기 자리에서 한 번 더 위로 솟아 한 아이의 손바닥 위에 가만히 한 송이 모자처럼 내려앉은 자리다. 잎 가운데에 굳은 진주 한 알은 그 아이가 자기 손가락 끝으로 한 번 더 짚어 본 새벽 이슬이 그대로 굳은 자리다.',
    art: 'humorous quirky marsh swamp fantasy big lilypad hat armor item icon, wide round dark green lily-pad hat with a single dewdrop pearl at the center and curled leaf edges, single inanimate game loot object on transparent background',
  },
  {
    key: 'common_aristocrat_lace_dress',
    slot: 'armor',
    nameKo: '귀족 영애의 레이스 드레스',
    region: '일반',
    tone: '아름다운',
    lore: '한 귀족 영애가 자기 평생 자기 한 자루의 dress 위에 한 번 더 자기 손가락 끝으로 한 자국씩 더 레이스를 풀어 짠 자리다. 가슴께의 작은 진주 단추 한 알 한 알은 영애가 자기 자리에서 한 번도 풀지 않은 결대로 한 번 더 가만히 박혀 있다.',
    art: 'beautiful elegant graceful fantasy aristocrat Victorian lace dress armor item icon, slender pale cream lace dress with delicate floral lace patterns, a tight bodice, and small pearl buttons down the front, single inanimate game loot object on transparent background',
  },
  {
    key: 'rune_seer_hood',
    slot: 'armor',
    nameKo: 'seer의 hood',
    region: '고대 룬 산맥',
    tone: '수수께끼',
    lore: '룬 산맥의 가장 깊은 자리에 살았다는 seer가 자기 평생 한 번도 자기 눈을 직접 드러내지 않았다고 한다. 그가 자기 머리에 두른 hood의 이마 가운데에 한 줄로 새겨진 룬 원은 그가 한 번씩 꺼내 보던 다른 사람의 다음 새벽 한 자리를 적어 둔 자리다.',
    art: 'mysterious cryptic veiled mountain rune fantasy seer hood armor item icon, dark indigo hooded shawl with a single rune circle on the brow and a thin veil across the face, single inanimate game loot object on transparent background',
  },
  {
    key: 'volcano_glass_flame_crown',
    slot: 'armor',
    nameKo: '유리 화염의 crown',
    region: '서쪽 화산',
    tone: '아름다운',
    lore: '서쪽 화로의 유리 장인이 자기 마지막 작업 새벽에 한 줄기 유리 화염을 그대로 굳혀 둔 자리에 한 알의 빨간 보석을 가만히 박아 둔 자리다. 화염의 곡선은 식다가도 한 번도 자기 결을 흩뜨리지 않고 가만히 한 알을 둘러싼 채 굳어 있다.',
    art: 'beautiful elegant graceful volcanic glasswork fantasy glass flame crown armor item icon, slender dark curving glass flame circlet with a single small red gem at the center brow, single inanimate game loot object on transparent background',
  },
  {
    key: 'fallen_celestial_gold_chest',
    slot: 'armor',
    nameKo: '천상의 황금 흉갑',
    region: '타락천사',
    tone: '화려',
    lore: '한 천상의 사관이 자기 평생 적은 첫 일곱 새벽의 빛을 자기 흉갑 가운데에 한 알의 황금 해로 한 번 더 박아 두고 떠난 자리다. 양옆의 빨간 보석들은 그 일곱 새벽 사이마다 사관이 자기 손가락 끝으로 한 번 더 짚어 본 자리에 한 알씩 굳어 있다.',
    art: 'ornate flamboyant gilded fallen angel celestial divine fantasy ornate gold chest plate armor item icon, polished gold breastplate with a sun emblem at the center and multiple red rubies inlaid along the sides, single inanimate game loot object on transparent background',
  },

  // ── batch 20: armor 균등화 5종 ──
  {
    key: 'marsh_drowned_pirate_tricorne',
    slot: 'armor',
    nameKo: '익사한 해적의 모자',
    region: '늪지대',
    tone: '전설',
    lore: '늪 가장 깊은 자리에 가라앉은 한 해적의 모자가 한 새벽에 자기 자리에서 떠올라 어부의 손에 잡힌 자리다. 가운데 다발의 진주는 해적이 마지막까지 가슴에 안고 있던 한 줌의 알이고, 가장자리의 거미 무늬는 늪의 풀들이 모자 위에 한 줄로 적어 둔 결이다.',
    art: 'legendary mythic ancient marsh swamp drowned pirate fantasy tricorne hat armor item icon, dark teal tricorne pirate hat with a cluster of pearls at the front and spider-like leaf etchings along the brim, single inanimate game loot object on transparent background',
  },
  {
    key: 'orc_blood_brother_horn_pauldrons',
    slot: 'armor',
    nameKo: '두 뿔의 어깨갑',
    region: '오크 부락',
    tone: '영웅담',
    lore: '부락의 두 형제 전사가 자기 첫 사냥에서 같이 잡은 짐승의 뿔을 한 쪽씩 자기 어깨갑 위에 한 번 더 박아 두고, 그 두 뿔 사이를 한 줄의 빨간 cord로 자기들 사이를 묶어 둔 자리다. cord의 한 끝이 흔들리는 새벽엔 다른 쪽 형제의 어깨도 같이 한 박자 늦게 한 번 흔들린다.',
    art: 'heroic epic orcish tribal warband fantasy twin horned pauldrons armor item icon, two matching dark iron shoulder plates with a single large horn on each top joined by a red blood-cord across the chest, single inanimate game loot object on transparent background',
  },
  {
    key: 'rune_high_lord_gauntlets',
    slot: 'armor',
    nameKo: '고룬 영주의 황금 장갑',
    region: '고대 룬 산맥',
    tone: '화려',
    lore: '룬 산맥의 한 고대 영주가 자기 두 손에 한 번도 같은 룬을 두 번 박지 않은 황금 장갑이다. 각 장갑의 손등에 새겨진 룬은 영주가 자기 평생 가장 자주 짚어 본 결이고, 손목의 빨간 보석은 그가 자기 결정을 한 번 더 잡아 두려 한 번씩 더 짚어 본 자리에 한 알씩 굳어 있다.',
    art: 'ornate flamboyant gilded mountain rune ancient fantasy high lord gauntlets armor item icon, two ornate gold brass gauntlets with engraved runes on the back of the hand and a red gem at each wrist, single inanimate game loot object on transparent background',
  },
  {
    key: 'volcano_widow_smith_apron',
    slot: 'armor',
    nameKo: '과부의 대장간 앞치마',
    region: '서쪽 화산',
    tone: '비애',
    lore: '서쪽 화로의 한 장인이 마지막 새벽에 자기 앞치마를 화로 옆 못에 한 번 더 걸어 두고 떠난 자리다. 그 장인의 부인이 다음 새벽 그 앞치마를 자기 등으로 묶은 끈은 한 번도 풀린 적이 없고, pocket 안쪽엔 장인이 마지막으로 만진 망치의 자국이 한 자리 그대로 패여 있다.',
    art: 'mournful sorrowful volcanic forge fire fantasy widow smith apron armor item icon, dark scorched leather apron with a tied bow at the back and a single empty front pocket, single inanimate game loot object on transparent background',
  },
  {
    key: 'common_traveler_star_hat',
    slot: 'armor',
    nameKo: '여행자의 별 모자',
    region: '일반',
    tone: '위트',
    lore: '한 여행자가 자기 평생 자기 머리에 한 번 더 얹어 둔 뾰족 모자다. 모자 끝에 달린 작은 별 charm은 여행자가 자기 자리에서 한 번 더 자기 길을 떠올릴 때마다 한 박자 늦은 작은 소리로 자기 가슴 쪽으로 한 번씩 흔들려 와 준다.',
    art: 'humorous quirky whimsical fantasy traveler witch pointed hat armor item icon, tall dark blue pointed wizard hat with a wide brim, a yellow ribbon band, and a small star charm hanging from the tip, single inanimate game loot object on transparent background',
  },

  // ── batch 21: armor 5종 ──
  {
    key: 'common_first_paladin_oath_chestplate',
    slot: 'armor',
    nameKo: '첫 팰러딘의 서약 흉갑',
    region: '일반',
    tone: '전설',
    lore: '한 왕국의 첫 팰러딘이 자기 평생 자기 가슴 가운데에 한 줄의 서약을 한 번 더 자기 흉갑의 결대로 새겨 둔 자리다. 가슴 가운데에 굳어 박힌 작은 검은 팰러딘이 자기 자리에서 한 번도 자기 시선을 떼지 않은 결을 한 알의 emblem으로 한 번 더 굳혀 둔 자리다.',
    art: 'legendary mythic ancient fantasy first paladin oath chest plate armor item icon, polished silver breastplate with a single sworn-oath scroll engraved across the chest and a small upright sword embossed at the heart, single inanimate game loot object on transparent background',
  },
  {
    key: 'orc_first_chief_armor',
    slot: 'armor',
    nameKo: '첫 부족장의 갑옷',
    region: '오크 부락',
    tone: '전설',
    lore: '부락의 첫 부족장이 자기 평생 한 번도 자기 등을 자기 부락에서 돌리지 않은 갑옷이다. 가슴께에 굳은 녹색 글리프는 부락의 첫 일곱 사람이 자기 손가락 끝으로 한 자씩 더 새긴 자리이고, 어깨의 송곳니는 부족장이 자기 첫 사냥에서 가져온 그대로 박혀 있다.',
    art: 'legendary mythic ancient storied orcish tribal first chieftain fantasy chest armor item icon, weathered dark leather chest piece with a green tribal glyph at the center and a single tusk attached at the shoulder, single inanimate game loot object on transparent background',
  },
  {
    key: 'rune_arch_priest_robe',
    slot: 'armor',
    nameKo: '대주교의 robe',
    region: '고대 룬 산맥',
    tone: '장엄',
    lore: '룬 산맥의 일곱 산문 가장 안쪽에서 평생 자기 자리를 한 번도 떠나지 않은 한 대주교가 자기 robe의 가슴께를 한 번 더 황금 룬으로 둘러 박은 자리다. 큰 깃 collar는 그가 자기 산문 안쪽의 한 박자 더 깊은 정적을 자기 어깨 둘레로 한 번 더 감싸 둔 결이다.',
    art: 'grand majestic imposing mountain rune ancient fantasy arch priest robe armor item icon, dark purple flowing robe with gold rune embroidery down the front and a tall stiff collar, single inanimate game loot object on transparent background',
  },
  {
    key: 'volcano_lava_pup_helm',
    slot: 'armor',
    nameKo: '도롱뇽 새끼 helm',
    region: '서쪽 화산',
    tone: '위트',
    lore: '서쪽 화로 가장자리에서 자라난 한 도롱뇽 새끼가 자기 첫 새벽에 한 화로 장인의 머리 위로 자기 자리를 옮겨 가만히 한 번 앉아 있다 떠난 자리에 그 모양 그대로 굳혀진 helm이다. 두 빨간 눈은 도롱뇽이 자기 자리를 한 번 더 들여다본 결대로 가만히 한 새벽씩 더 짙어진다.',
    art: 'humorous quirky whimsical volcanic fire fantasy lava pup salamander helm armor item icon, dark leather helm shaped like a cute round salamander head with two small orange ember eyes and small dragon ears, single inanimate game loot object on transparent background',
  },
  {
    key: 'fallen_dusk_short_robe',
    slot: 'armor',
    nameKo: '노을의 짧은 robe',
    region: '타락천사',
    tone: '희망',
    lore: '한 천사가 자기 마지막 새벽이 노을빛으로 깊어진 결을 자기 robe의 분홍 자락에 한 줄로 적어 둔 자리다. 어깨의 황금 armor는 그 노을의 가장 짙은 자리를 단단히 감싸 둔 결이고, 짧은 자락의 옅은 분홍빛은 천사가 떠나지 않은 새벽마다 한 번씩 더 옅게 깜빡인다.',
    art: 'hopeful radiant warm serene fallen angel divine fantasy dusk short robe armor item icon, short pink silk robe with golden brass shoulder pauldrons and warm sunset glow trim along the hem, single inanimate game loot object on transparent background',
  },

  // ── batch 22: armor 마지막 5종 (armor 50/50 완성) ──
  {
    key: 'marsh_drowned_pearl_cape',
    slot: 'armor',
    nameKo: '익사한 자의 진주 cape',
    region: '늪지대',
    tone: '비애',
    lore: '늪 가장 깊은 자리에 가라앉은 한 여인의 cape가 한 새벽에 자기 자리에서 위로 떠올라 어부의 손에 잡힌 자리다. cape의 너덜한 hem 둘레로 한 알씩 진주가 박힌 자리는 그 여인이 자기 마지막 호흡마다 한 알씩 자기 가슴에 굳혀 박아 둔 결이다.',
    art: 'mournful sorrowful marsh swamp drowned widow fantasy pearl cape armor item icon, dark teal short cape with a wide collar, multiple pearls along the ragged hem, and a single small pearl clasp at the throat, single inanimate game loot object on transparent background',
  },
  {
    key: 'orc_oracle_hood',
    slot: 'armor',
    nameKo: '오라클의 hood',
    region: '오크 부락',
    tone: '수수께끼',
    lore: '부락의 한 oracle이 자기 평생 한 번도 자기 양쪽 눈을 동시에 뜨지 않았다고 한다. 그가 자기 머리에 두른 hood의 이마 가운데에 박혀 있는 빨간 눈은 그가 다른 사람의 다음 새벽을 한 번씩 더 들여다본 자리에 한 알씩 더 짙어진 자리다.',
    art: 'mysterious cryptic orcish tribal oracle fantasy hood armor item icon, dark brown leather hood with a single red eye-rune at the brow and a trim of bone beads along the edge, single inanimate game loot object on transparent background',
  },
  {
    key: 'rune_apprentice_satchel',
    slot: 'armor',
    nameKo: '견습생의 책가방',
    region: '고대 룬 산맥',
    tone: '위트',
    lore: '룬 산맥 학원의 한 어린 견습이 자기 평생 자기 어깨에 한 번 더 메고 다닌 책가방이다. 옆 pocket에 한 자루씩 더 꽂혀 있는 깃펜과 두루마리는 그 어린 견습이 자기 자리에 앉기 전에 한 번씩 더 짚어 본 자국이고, 가방 위의 잉크 자국은 그가 한 번씩 더 흘린 결이다.',
    art: 'humorous quirky mountain rune ancient fantasy apprentice scholar satchel armor item icon, brown leather shoulder satchel with a feather quill and small rolled scroll tucked into side pockets and ink-stain blots across the flap, single inanimate game loot object on transparent background',
  },
  {
    key: 'volcano_master_smith_chest',
    slot: 'armor',
    nameKo: '명장의 흉갑',
    region: '서쪽 화산',
    tone: '영웅담',
    lore: '서쪽 화로의 한 명장이 자기 평생 한 번도 자기 자리를 떠나지 않은 흉갑이다. 가슴께에 박힌 망치 emblem은 그가 자기 첫 망치질을 한 번 더 본 결대로 굳어 있고, 양 옆의 빨간 잉걸은 그 새벽 그 망치질이 화로 안쪽으로 한 알씩 떨군 자국 그대로다.',
    art: 'heroic epic volcanic forge fire fantasy master smith chest armor item icon, dark steel breastplate with a hammer-shaped emblem at the center, glowing red ember inlays on each side, and a leather strap across the shoulder, single inanimate game loot object on transparent background',
  },
  {
    key: 'common_golden_rose_shield',
    slot: 'armor',
    nameKo: '황금 장미 방패',
    region: '일반',
    tone: '화려',
    lore: '한 왕국의 첫 왕비가 자기 신혼 새벽에 자기 남편의 방패 가운데에 한 송이 황금 장미를 한 번 더 박아 두고 자기 자리로 돌아온 자리다. 가장자리의 황금 leaf trim은 그 새벽 이후로 새 왕비가 한 번씩 더 자기 손가락 끝으로 짚어 본 결을 따라 한 줄씩 더 둘러져 있다.',
    art: 'ornate flamboyant gilded fantasy royal golden rose kite shield armor item icon, pale ivory kite shield with a large golden rose embossed at the center and intricate gold leaf filigree along the rim, single inanimate game loot object on transparent background',
  },

  // ═══════ accessory 50종 ═══════
  // ── batch 23: accessory 첫 5종 ──
  {
    key: 'marsh_lily_amulet',
    slot: 'accessory',
    nameKo: '연꽃 amulet',
    region: '늪지대',
    tone: '아름다운',
    lore: '늪의 한 어부가 자기 누이에게 자기 평생 가장 깊은 자리에서 길어 올린 한 송이 청록 연꽃을 한 알의 진주와 함께 silver 한 가닥으로 한 번 더 묶어 둔 자리다. 누이는 그 amulet을 자기 가슴 가운데에 한 번 더 짚어 본 결대로 한 자리에 가만히 걸어 두었다.',
    art: 'beautiful elegant graceful marsh swamp fantasy lily amulet accessory item icon, slender silver chain holding a single small teal lily blossom pendant with a pearl at the center, single inanimate game loot object on transparent background',
  },
  {
    key: 'common_witty_clockwork_pocket_watch',
    slot: 'accessory',
    nameKo: '톱니바퀴 회중시계',
    region: '일반',
    tone: '위트',
    lore: '한 시계공이 자기 평생 한 자루의 회중시계를 한 번도 자기 손에서 떨어뜨리지 않은 결을 자기 시계의 톱니바퀴 안쪽에 한 번 더 굳혀 박아 둔 자리다. chain에 매달린 작은 gear charm은 시계공이 자기 자리에서 한 번 더 자기 시간을 흘려보낸 결을 따라 한 번씩 더 가만히 흔들린다.',
    art: 'humorous quirky whimsical fantasy clockwork pocket watch accessory item icon, brass round pocket watch with intricate cogwheels visible through the glass face, a small chain with a tiny gear charm hanging beside it, single inanimate game loot object on transparent background',
  },
  {
    key: 'rune_listening_rune_ring',
    slot: 'accessory',
    nameKo: '엿듣는 룬 반지',
    region: '고대 룬 산맥',
    tone: '수수께끼',
    lore: '룬 산맥의 한 새김장이가 자기 평생 한 번도 자기 입으로 말하지 않은 한 줄의 룬을 자기 반지의 양 옆에 한 자씩 더 새겨 둔 자리다. 가운데에 박힌 푸른 보석은 새김장이가 자기 손가락 끝으로 한 번씩 더 짚어 본 자리에 한 알이 굳어 있다.',
    art: 'mysterious cryptic mountain rune ancient fantasy listening rune ring accessory item icon, dark silver band ring with a single small blue gem at the center and tiny carved runes on each side, single inanimate game loot object on transparent background',
  },
  {
    key: 'volcano_phoenix_eye_amulet',
    slot: 'accessory',
    nameKo: '불사조의 눈 amulet',
    region: '서쪽 화산',
    tone: '장엄',
    lore: '서쪽 화산의 가장 깊은 자리에 잠든 불사조가 자기 잠들기 전 자기 한 눈을 한 알의 보석으로 한 번 더 굳혀 자기 자리에 두고 떠난 자리다. amulet 가운데에 박힌 오렌지 보석은 그 불사조가 자기 자리에서 다시 한 번 더 깨어나는 새벽까지 한 박자 늦은 빛으로 가만히 보고 있다.',
    art: 'grand majestic imposing volcanic phoenix fire fantasy phoenix eye amulet accessory item icon, gold brass amulet pendant with a large round orange phoenix-eye gemstone at the center and small flame embossing around the rim, single inanimate game loot object on transparent background',
  },
  {
    key: 'fallen_morning_sun_charm',
    slot: 'accessory',
    nameKo: '아침 해의 부적',
    region: '타락천사',
    tone: '희망',
    lore: '한 천사가 자기 평생 자기 가슴께에 매달아 두고 다닌 부적이다. 가운데에 황금으로 굳어 박힌 큰 해는 천사가 자기 자리에서 한 번 더 본 첫 새벽의 결대로 굳어 있고, 옆에 가만히 매달린 흰 깃은 그 새벽의 첫 빛이 자기 결을 깃에 한 번 더 적어 둔 자리다.',
    art: 'hopeful radiant warm blessed fallen angel divine fantasy morning sun charm accessory item icon, gold chain holding a large radiant gold sun pendant with a small white feather hanging beside it, single inanimate game loot object on transparent background',
  },

  // ── batch 24: accessory 두 번째 5종 ──
  {
    key: 'marsh_frog_ring',
    slot: 'accessory',
    nameKo: '개구리 반지',
    region: '늪지대',
    tone: '위트',
    lore: '늪의 한 아이가 자기 손가락 끝에 한 마리 작은 개구리를 한 번 더 올려 본 새벽에 그 개구리가 그 자리에서 한 박자 늦게 앉아 한 번 더 가만히 있었다. 그 모양 그대로 한 자루의 silver가 자기 결을 한 번 더 둘러 굳혀 박힌 자리가 이 반지다.',
    art: 'humorous quirky marsh swamp fantasy frog ring accessory item icon, silver band ring with a tiny cheerful green frog perched on top, single inanimate game loot object on transparent background',
  },
  {
    key: 'orc_chieftain_twin_tusk_necklace',
    slot: 'accessory',
    nameKo: '두 송곳니의 부족장 목걸이',
    region: '오크 부락',
    tone: '장엄',
    lore: '부락의 한 부족장이 자기 첫 사냥에서 한 짐승의 두 송곳니를 한 알씩 자기 목 둘레에 한 번 더 묶어 둔 자리다. 두 송곳니 사이에 가만히 매달린 두 깃털은 그 부족장이 자기 자리에서 한 번 더 떠올린 자기 두 동무의 자리에 한 줄씩 박혀 있다.',
    art: 'grand majestic imposing orcish tribal chieftain fantasy twin tusk necklace accessory item icon, brown leather cord with two large curved tusks hanging at the center wrapped with sinew and two small feathers between them, single inanimate game loot object on transparent background',
  },
  {
    key: 'rune_warden_wing_seal',
    slot: 'accessory',
    nameKo: '수호자의 날개 인장',
    region: '고대 룬 산맥',
    tone: '영웅담',
    lore: '룬 산맥의 산문을 자기 자리로 삼은 한 보초가 자기 평생 한 번도 자기 자리에서 등 돌리지 않은 결을 자기 인장 brooch의 양 옆에 두 짝 날개로 한 번 더 굳혀 박은 자리다. 가운데 shield 위에 새겨진 한 줄은 그 보초가 자기 자리에서 한 번 더 본 새벽의 결이다.',
    art: 'heroic epic mountain rune ancient fantasy warden wing seal brooch accessory item icon, silver round brooch with a small shield emblem at the center and two engraved wings flanking it, single inanimate game loot object on transparent background',
  },
  {
    key: 'volcano_glass_ember_earring',
    slot: 'accessory',
    nameKo: '유리 물방울 ember 귀걸이',
    region: '서쪽 화산',
    tone: '아름다운',
    lore: '서쪽 화로의 유리 장인이 자기 첫 잉걸 한 알을 한 방울의 유리 안에 한 번 더 굳혀 박아 둔 자리다. 그 잉걸의 빛은 한 박자 늦은 빛으로 유리 안쪽에서 가만히 흔들리는데, 귀걸이가 한 번 흔들릴 때마다 그 안쪽의 잉걸도 한 번 더 같이 흔들린다.',
    art: 'beautiful elegant graceful volcanic glasswork fantasy glass drop ember earring accessory item icon, dangling teardrop earring of clear glass with a large orange ember glowing inside and a gold hook, single inanimate game loot object on transparent background',
  },
  {
    key: 'fallen_four_wing_pinwheel_brooch',
    slot: 'accessory',
    nameKo: '네 깃의 풍차 brooch',
    region: '타락천사',
    tone: '화려',
    lore: '한 세라프가 추락하기 전 자기 네 깃을 자기 손가락 끝으로 한 자리에 한 번 더 모아 둔 결대로 굳어진 brooch다. 네 깃이 가운데를 향해 한 박자 늦게 도는 결을 따라 박힌 진주 한 알은 그 세라프가 자기 자리에서 한 번 더 떠올린 새벽의 결이다.',
    art: 'ornate flamboyant gilded fallen angel seraphic divine fantasy four-wing pinwheel brooch accessory item icon, large gold brooch with four feathered wings arranged in a pinwheel around a single central pearl, single inanimate game loot object on transparent background',
  },

  // ── batch 25: accessory 5종 (다양 모티프) ──
  {
    key: 'marsh_winged_slime_charm',
    slot: 'accessory',
    nameKo: '날개 슬라임 부적',
    region: '늪지대',
    tone: '위트',
    lore: '늪의 한 새벽이 가장 옅어진 자리에서 한 슬라임이 자기 결을 한 번 더 위로 펴 보려 자기 양 옆에 한 짝 작은 날개를 한 번 더 자라난 채 떠 있다 그 자리에 가만히 떨어진 자리다. 그 슬라임은 자기 자리에서 한 번도 자기 날개로 다시 떠올라 본 적이 없다.',
    art: 'humorous quirky whimsical marsh swamp fantasy winged slime charm accessory item icon, silver chain holding a small green slime blob with two tiny pale blue feathered wings on each side, single inanimate game loot object on transparent background',
  },
  {
    key: 'orc_first_hunt_tooth_ring',
    slot: 'accessory',
    nameKo: '첫 사냥의 송곳니 반지',
    region: '오크 부락',
    tone: '영웅담',
    lore: '부락의 한 어린 오크가 자기 첫 사냥의 송곳니를 자기 손가락 둘레의 검은 ring 가운데에 한 번 더 박아 두고, 그 양 옆에 자기 부락의 첫 룬 두 글자를 한 자씩 더 새겨 둔 자리다. 그 어린 오크는 자기 자리에서 한 번도 그 반지를 다시 빼 본 적이 없다.',
    art: 'heroic epic orcish tribal warband fantasy first hunt tooth ring accessory item icon, dark iron band ring with a small gold detail at the center holding a single yellowed tooth and two tribal runes carved on each side, single inanimate game loot object on transparent background',
  },
  {
    key: 'rune_first_letter_amulet',
    slot: 'accessory',
    nameKo: '첫 글자 amulet',
    region: '고대 룬 산맥',
    tone: '전설',
    lore: '룬 산맥의 첫 새김장이가 자기 첫 룬을 산문 돌 대신 자기 가슴께 amulet의 한 가운데에 한 자만 더 깊이 박아 둔 자리다. 그 한 글자가 한 번 빛을 머금는 새벽엔 산맥 안쪽에 잠든 다른 룬 한 자리도 같이 한 박자 옅게 떨린다.',
    art: 'legendary mythic ancient mountain rune fantasy first letter amulet accessory item icon, dark chain holding a round dark stone amulet with a single deep blue glowing rune letter carved at the center, single inanimate game loot object on transparent background',
  },
  {
    key: 'volcano_leaf_ember_locket',
    slot: 'accessory',
    nameKo: '잎의 잉걸 locket',
    region: '서쪽 화산',
    tone: '비애',
    lore: '서쪽 화로 곁의 한 잎 모양 잿더미에서 한 부인이 자기 남편의 마지막 호흡 한 알을 잉걸로 굳혀 자기 amulet 안에 박아 둔 자리다. 잎 가장자리의 갈라진 검은 자국은 그 부인이 손가락 끝으로 한 번씩 더 짚어 본 결을 따라 한 줄씩 더 패여 들어간 자리다.',
    art: 'mournful sorrowful volcanic forge fire fantasy leaf ember locket accessory item icon, dark blackened leaf-shaped locket on a chain with a single large orange ember inside and cracked black details along the edges, single inanimate game loot object on transparent background',
  },
  {
    key: 'common_king_lion_signet_ring',
    slot: 'accessory',
    nameKo: '왕의 사자 signet ring',
    region: '일반',
    tone: '장엄',
    lore: '한 왕국의 첫 왕이 자기 즉위 새벽에 자기 손가락 둘레에 한 알의 큰 푸른 보석을 한 번 더 박고, 그 양 옆에 자기 왕국의 두 수호 사자를 한 짝씩 더 새겨 둔 자리다. 사자 두 짝은 그 왕이 자기 결정을 한 번 더 미루는 새벽엔 가운데 보석을 한 박자 늦게 한 번 더 가만히 본다.',
    art: 'grand majestic imposing fantasy royal king signet ring accessory item icon, heavy gold signet ring with a large blue sapphire at the top engraved with a royal crown emblem and two engraved lions flanking the band, single inanimate game loot object on transparent background',
  },

  // ── batch 26: accessory 5종 ──
  {
    key: 'marsh_root_eye_pendant',
    slot: 'accessory',
    nameKo: '뿌리에 둘러싸인 눈의 pendant',
    region: '늪지대',
    tone: '기괴',
    lore: '늪 가장 깊은 자리에서 한 자루의 medallion이 어부의 그물에 한 번 더 걸려 올라온 자리다. 가운데에 박힌 청록의 눈은 그 medallion을 가져온 뱃사공이 자기 자리로 한 번 더 돌리지 못한 자리이고, 둘레의 뿌리들은 늪 바닥의 풀들이 자기 결을 한 번 더 medallion 위에 한 줄씩 감아 둔 결이다.',
    art: 'uncanny eerie marsh swamp drowned fantasy root-wrapped eye pendant accessory item icon, brown round medallion with a single staring teal eye at the center and dark twisted roots wrapping around the rim, single inanimate game loot object on transparent background',
  },
  {
    key: 'common_royal_fan_brooch',
    slot: 'accessory',
    nameKo: '왕실 부채 브로치',
    region: '일반',
    tone: '화려',
    lore: '한 왕국의 첫 황후가 자기 즉위 새벽에 자기 가슴께에 한 알의 황금 부채 브로치를 한 번 더 박아 둔 자리다. 부채의 보석꽃잎 한 알 한 알은 황후가 자기 자리에서 한 번 더 자기 시선을 옮긴 결을 따라 한 번씩 더 짙어졌고, 가운데 진주는 그 새벽의 한 호흡이 한 알로 굳어진 자리다.',
    art: 'ornate flamboyant gilded fantasy royal court fan brooch accessory item icon, gold brooch shaped like an open fan with red and pink jewel-petals and a small pearl at the pivot, single inanimate game loot object on transparent background',
  },
  {
    key: 'rune_starlight_crown',
    slot: 'accessory',
    nameKo: '별빛의 silver crown',
    region: '고대 룬 산맥',
    tone: '장엄',
    lore: '룬 산맥의 가장 높은 자리에서 자기 평생 자기 등으로 별을 한 번 더 본 한 보초가 자기 머리띠 가운데에 그 별의 결을 한 알의 보석으로 한 번 더 굳혀 박아 둔 자리다. 가장자리의 가시는 별빛이 자기 결을 보초의 머리띠 위에 한 줄씩 더 그어 둔 자국이다.',
    art: 'grand majestic imposing mountain rune ancient fantasy starlight crown accessory item icon, silver crown with sharp star-shaped spikes along the rim, a single large star-cut gemstone at the brow, and small star engravings between the spikes, single inanimate game loot object on transparent background',
  },
  {
    key: 'common_phoenix_egg_pendant',
    slot: 'accessory',
    nameKo: '봉황 알 펜던트',
    region: '일반',
    tone: '전설',
    lore: '한 어느 자리에 떨어진 한 알의 황금 알이 자기 자리에서 한 번 더 깨지지 않은 채로 한 사관의 그릇에 한 번 더 옮겨진 자리다. 알의 안쪽에서 한 박자 늦은 ember 빛이 가만히 머무는 결은 그 안에 잠든 한 봉황이 자기 자리에서 한 번 더 깨어날 새벽을 기다리는 자국이다.',
    art: 'legendary mythic ancient fantasy phoenix egg pendant accessory item icon, dark chain holding a single golden egg pendant with cracking shell revealing warm ember glow inside, single inanimate game loot object on transparent background',
  },
  {
    key: 'fallen_three_feather_anklet',
    slot: 'accessory',
    nameKo: '세 깃의 silver anklet',
    region: '타락천사',
    tone: '아름다운',
    lore: '한 천사가 자기 발걸음의 첫 일곱 새벽을 자기 발목 둘레에 한 줄의 silver로 한 번 더 둘러 둔 자리다. 매달린 세 깃은 그 천사가 자기 자리에서 한 번 더 떠올린 자기 첫 세 동료의 자리에 한 가닥씩 박혀 있고, 가운데 진주는 일곱 새벽이 한 알로 굳어진 자리다.',
    art: 'beautiful elegant graceful fallen angel divine fantasy silver feather anklet accessory item icon, delicate slim silver anklet with three small dangling feather charms and a tiny single pearl at the clasp, single inanimate game loot object on transparent background',
  },

  // ── batch 27: accessory 4종 (volcano_witty_baby_dragon_pendant 배경 재생성으로 제외) ──
  {
    key: 'marsh_drowned_queen_circlet',
    slot: 'accessory',
    nameKo: '익사한 여왕의 circlet',
    region: '늪지대',
    tone: '전설',
    lore: '늪 가장 깊은 자리에 한 번 자리를 잡은 여왕이 자기 자리를 떠나지 않은 채 늪 바닥에 가만히 그대로 굳어 가는 동안 늪의 뿌리들이 그 여왕의 circlet을 한 줄씩 더 자기 결로 감싸 안은 자리다. 가운데 청록 보석은 여왕이 자기 마지막 새벽까지 자기 시선을 한 번도 떼지 않은 자리다.',
    art: 'legendary mythic ancient marsh swamp drowned queen fantasy root-wrapped circlet accessory item icon, tarnished bronze circlet entwined with dark twisted swamp roots and a single teal gem at the center, single inanimate game loot object on transparent background',
  },
  {
    key: 'orc_chief_gold_collar',
    slot: 'accessory',
    nameKo: '부족장의 황금 collar',
    region: '오크 부락',
    tone: '화려',
    lore: '부락의 한 부족장이 자기 즉위 새벽에 자기 평생 잡은 짐승들의 첫 송곳니를 황금으로 굳혀 자기 목 둘레 collar에 한 줄로 박아 둔 자리다. 가운데 박힌 큰 빨간 보석은 부족장이 자기 부락 첫 광맥에서 가져온 한 알이고, swirl 패턴은 그가 손가락 끝으로 한 줄씩 더 그어 둔 결이다.',
    art: 'ornate flamboyant gilded orcish tribal chieftain fantasy gold collar accessory item icon, wide gold neck collar with ornate swirl patterns and a single large red ruby at the center flanked by smaller rubies, single inanimate game loot object on transparent background',
  },
  {
    key: 'rune_hex_riddle_ring',
    slot: 'accessory',
    nameKo: '여섯 결 룬 반지',
    region: '고대 룬 산맥',
    tone: '수수께끼',
    lore: '룬 산맥의 한 새김장이가 자기 평생 한 번도 풀지 못한 한 줄의 룬을 자기 반지의 가운데에 여섯 결의 면으로 한 번 더 새겨 둔 자리다. 그 한 줄을 풀려 시도한 자는 자기 자리에서 한 번도 답을 찾지 못한 채 그 반지를 한 번 더 가만히 끼고 있는다.',
    art: 'mysterious cryptic enigmatic mountain rune ancient fantasy hexagon riddle ring accessory item icon, dark silver band ring with a six-sided hexagonal silver plate at the top engraved with a single rune line, single inanimate game loot object on transparent background',
  },
  {
    key: 'common_pilgrim_knot_charm',
    slot: 'accessory',
    nameKo: '순례자의 매듭 부적',
    region: '일반',
    tone: '희망',
    lore: '한 순례자가 자기 평생 자기 가슴께에 한 번 더 매달아 두고 다닌 부적이다. cord의 매듭은 그가 자기 첫 길의 자리에 한 번 더 짚어 본 결대로 한 번씩 더 묶인 자국이고, medallion 가운데에 굳어 박힌 sun은 순례자가 자기 첫 새벽에 자기 자리에서 본 결대로 굳어 있다.',
    art: 'hopeful radiant warm serene fantasy pilgrim travel knot charm accessory item icon, brown cord with a single decorative knot above a small wooden round medallion engraved with a warm gold sun at the center, single inanimate game loot object on transparent background',
  },

  // ── batch 28: accessory 5종 (volcano dragon v2 채택) ──
  {
    key: 'volcano_baby_dragon_pendant',
    slot: 'accessory',
    nameKo: '잠든 새끼 용 pendant',
    region: '서쪽 화산',
    tone: '위트',
    lore: '서쪽 화산의 한 새끼 용이 자기 첫 새벽에 자기 둥지에서 한 번 더 잠들어 가만히 한 자리에 굳어 있다가 한 어린 풀무지기의 손에 한 번 더 옮겨진 자리다. 둥근 안쪽에서 새끼 용은 자기 꼬리를 한 번 더 자기 몸에 둘러 잠든 채로 한 번도 자기 자세를 흩뜨리지 않는다.',
    art: 'humorous quirky volcanic fantasy baby dragon pendant accessory item icon, gold chain holding a round medallion with a tiny curled sleeping pale dragon figurine inside, single inanimate game loot object on transparent background',
  },
  {
    key: 'marsh_swamp_god_eye_amulet',
    slot: 'accessory',
    nameKo: '늪의 신의 눈 amulet',
    region: '늪지대',
    tone: '장엄',
    lore: '늪의 가장 깊은 자리에 한 번 자리를 잡은 신이 자기 한 눈을 한 알의 보석으로 한 번 더 굳혀 자기 자리에 두고 잠든 자리다. amulet 가장자리의 가시는 신이 자기 자리를 한 번도 떠나지 않은 결대로 늪의 풀들이 한 줄로 더 둘러 둔 자국이다.',
    art: 'grand majestic imposing marsh swamp god ancient fantasy eye amulet accessory item icon, brown chain holding a round amulet with a large staring deep green divine eye at the center and small thorn details along the rim, single inanimate game loot object on transparent background',
  },
  {
    key: 'orc_blood_pact_skull_brooch',
    slot: 'accessory',
    nameKo: '혈맹의 두개골 brooch',
    region: '오크 부락',
    tone: '전설',
    lore: '부락의 두 형제 전사가 자기 첫 사냥에서 같이 잡은 짐승의 두개골 위에 자기 두 단검을 한 번 더 교차해 박고, 가운데에 자기 두 사람의 첫 핏방울을 한 알의 보석으로 굳혀 둔 자리다. 양 옆 두 황금 뿔은 두개골이 한 번 더 일어나지 않게 못 박힌 결이다.',
    art: 'legendary mythic ancient orcish tribal blood pact fantasy skull brooch accessory item icon, animal skull with two golden horns on each side and two crossed tribal daggers in front of it with a single red blood gemstone at the crossing, single inanimate game loot object on transparent background',
  },
  {
    key: 'rune_quartz_droplet_earring',
    slot: 'accessory',
    nameKo: '수정 물방울 귀걸이',
    region: '고대 룬 산맥',
    tone: '아름다운',
    lore: '룬 산맥의 한 새김장이가 자기 누이의 귀에 자기 첫 깃 한 가닥을 한 알의 수정으로 한 번 더 굳혀 매달아 둔 자리다. 위쪽 작은 황금 wing은 그 깃의 결을 한 번 더 적어 둔 자리다.',
    art: 'beautiful elegant graceful mountain rune ancient fantasy quartz droplet earring accessory item icon, slender silver hook holding a large clear quartz crystal teardrop with a tiny single gold wing detail at the top, single inanimate game loot object on transparent background',
  },
  {
    key: 'fallen_archangel_halo_crown',
    slot: 'accessory',
    nameKo: '대천사의 후광 crown',
    region: '타락천사',
    tone: '장엄',
    lore: '한 대천사가 자기 평생 자기 머리 둘레에 두 줄의 후광을 한 번 더 굳혀 박아 두고, 그 가운데에 자기 첫 깃 한 가닥과 자기 첫 검을 한 번 더 함께 박아 둔 자리다. 두 후광의 한 박자 늦은 빛은 그 검과 깃이 자기 결을 한 번 더 적어 둔 결을 따라 옅어진다.',
    art: 'grand majestic imposing fallen angel archangel divine fantasy halo crown accessory item icon, two concentric pale gold halo arcs forming a crown shape with a single white feather and a small upright sword rising at the center, single inanimate game loot object on transparent background',
  },

  // ── batch 29: accessory 5종 ──
  {
    key: 'volcano_salamander_ring',
    slot: 'accessory',
    nameKo: '도롱뇽의 반지',
    region: '서쪽 화산',
    tone: '위트',
    lore: '서쪽 화로의 가장자리에 살던 한 도롱뇽이 자기 자리에서 한 번 더 떠나기 전 자기 한 새끼를 한 알의 반지 위에 가만히 한 번 더 두고 떠난 자리다. 그 새끼 도롱뇽은 자기 자리에서 한 박자 늦게 한 번씩 더 자기 발자국을 ring 위에 한 번 더 박는다.',
    art: 'humorous quirky volcanic fire fantasy salamander ring accessory item icon, dark band ring with a bright orange salamander wrapped around the top and a small ember gem at the center, single inanimate game loot object on transparent background',
  },
  {
    key: 'marsh_lily_pad_anklet',
    slot: 'accessory',
    nameKo: '연꽃잎 발찌',
    region: '늪지대',
    tone: '희망',
    lore: '늪의 한 신부가 자기 결혼 새벽에 자기 발목 둘레에 세 잎의 연꽃잎을 한 번 더 매달고, 그 끝에 한 송이 분홍 연꽃을 한 번 더 매달아 둔 자리다. 그 신부가 자기 발걸음을 한 박자 늦게 옮길 때마다 세 잎은 한 번씩 더 가만히 같이 흔들린다.',
    art: 'hopeful radiant warm serene marsh swamp fantasy lily pad anklet accessory item icon, pale silver anklet with three small green lily pad charms hanging and a pink lily blossom at the clasp, single inanimate game loot object on transparent background',
  },
  {
    key: 'orc_grinning_beard_bead',
    slot: 'accessory',
    nameKo: '웃는 얼굴의 턱수염 구슬',
    region: '오크 부락',
    tone: '위트',
    lore: '부락의 한 부족장이 자기 평생 자기 턱수염 끝에 한 알의 wooden bead를 한 번 더 묶어 매달고 다닌 자리다. bead 가운데에 한 번 더 새겨진 grinning 얼굴은 부족장이 자기 자리에 한 번 더 웃어 본 결대로 굳어 있고, 양 옆 송곳니는 그가 자기 첫 사냥에서 가져온 자국이다.',
    art: 'humorous quirky orcish tribal chief fantasy beard braid bead accessory item icon, single large dark wooden bead carved with a comical grinning tribal face and two small dangling tooth charms, single inanimate game loot object on transparent background',
  },
  {
    key: 'rune_two_chisel_charm',
    slot: 'accessory',
    nameKo: '두 끌의 십자 부적',
    region: '고대 룬 산맥',
    tone: '영웅담',
    lore: '룬 산맥의 첫 두 새김장이가 자기 평생 한 번도 자기 자리를 떠나지 않은 결을 자기 두 끌을 한 번 더 십자로 교차해 자기 가슴께에 한 줄로 매달아 둔 자리다. 두 끌이 한 자리에 한 번 더 만나는 가운데는 그들이 같이 새긴 첫 룬이 한 자 더 깊이 박혀 있다.',
    art: 'heroic epic mountain rune ancient fantasy two chisel cross charm accessory item icon, silver chain holding two miniature stone-carver chisels crossed in an X with a small rune mark at the crossing point, single inanimate game loot object on transparent background',
  },
  {
    key: 'common_butterfly_wing_earring',
    slot: 'accessory',
    nameKo: '나비 날개의 귀걸이',
    region: '일반',
    tone: '아름다운',
    lore: '한 곤충학자가 자기 평생 자기 손바닥 위에 가만히 한 마리 나비를 한 번 더 들여다본 결을 자기 누이의 귀에 한 알의 날개로 한 번 더 굳혀 매달아 둔 자리다. 날개의 결은 그 나비가 자기 자리에서 한 번 더 흔든 결을 따라 한 박자 늦은 푸른빛으로 한 번씩 더 가만히 머문다.',
    art: 'beautiful elegant graceful fantasy butterfly wing earring accessory item icon, slender silver hook holding a single iridescent enamel butterfly wing pendant in pale blue and silver, single inanimate game loot object on transparent background',
  },

  // ── batch 30: accessory 5종 ──
  {
    key: 'marsh_swamp_hand_bone_knot_charm',
    slot: 'accessory',
    nameKo: '늪 손 뼈의 매듭 부적',
    region: '늪지대',
    tone: '기괴',
    lore: '늪 가장 깊은 자리에서 한 어부의 그물에 한 번 더 걸려 올라온 한 손 뼈를 그 어부가 자기 매듭 cord 끝에 한 번 더 묶어 자기 자리에 가만히 매달아 둔 자리다. 손 뼈의 가시는 늪의 풀들이 그 손가락 끝마다 한 줄씩 더 자라난 결이다.',
    art: 'uncanny eerie marsh swamp fantasy hand bone knot charm accessory item icon, dark endless knot cord holding a pale hand bone with green moss patches and small thorn growths along the finger joints, single inanimate game loot object on transparent background',
  },
  {
    key: 'common_emperor_signet_chain',
    slot: 'accessory',
    nameKo: '황제의 인장 사슬',
    region: '일반',
    tone: '장엄',
    lore: '한 황제가 자기 즉위 새벽에 자기 가슴께에 한 줄의 두꺼운 황금 chain을 한 번 더 두르고, 그 chain의 가운데에 자기 왕국의 사자 인장을 한 알의 plate로 한 번 더 굳혀 박아 둔 자리다. 사자 인장은 황제가 자기 자리에서 한 번도 자기 시선을 떼지 않은 결대로 굳어 있다.',
    art: 'grand majestic imposing fantasy emperor signet chain accessory item icon, heavy gold thick chain holding a large rectangular gold signet plate engraved with a stylized lion seal, single inanimate game loot object on transparent background',
  },
  {
    key: 'rune_sunrise_medallion',
    slot: 'accessory',
    nameKo: '일출의 medallion',
    region: '고대 룬 산맥',
    tone: '희망',
    lore: '룬 산맥의 가장 높은 자리에서 평생 자기 첫 새벽의 일출을 한 번도 놓치지 않은 한 보초가 자기 medallion 가운데에 그 일출의 결을 한 번 더 황금으로 굳혀 박아 둔 자리다. 가운데 박힌 작은 진주는 보초가 마지막 새벽에 손가락 끝으로 한 번 더 짚어 본 자리다.',
    art: 'hopeful radiant warm serene mountain rune fantasy sunrise medallion accessory item icon, silver chain holding a round gold medallion with an embossed warm sunrise emblem and a small pearl at the center, single inanimate game loot object on transparent background',
  },
  {
    key: 'volcano_smith_hammer_pin',
    slot: 'accessory',
    nameKo: '대장간의 망치 pin',
    region: '서쪽 화산',
    tone: '영웅담',
    lore: '서쪽 화로의 한 대장장이가 자기 평생 한 번도 자기 자리를 떠나지 않은 망치와 모루를 자기 가슴께에 한 번 더 작은 pin으로 한 번 더 굳혀 박아 둔 자리다. 가운데 작은 잉걸은 그가 자기 첫 새벽에 처음 두드린 잉걸이 한 번 더 그 자리에 굳어 있는 결이다.',
    art: 'heroic epic volcanic forge fire fantasy blacksmith hammer anvil pin accessory item icon, dark iron pin shaped like a small upright hammer and anvil with a single glowing ember at the center, single inanimate game loot object on transparent background',
  },
  {
    key: 'fallen_pearl_feather_choker',
    slot: 'accessory',
    nameKo: '진주 깃 choker',
    region: '타락천사',
    tone: '아름다운',
    lore: '한 천사가 자기 누이의 목 둘레에 한 줄의 흰 진주를 한 번 더 감아 두고, 그 가운데에 자기 첫 깃 한 가닥을 한 번 더 silver로 굳혀 매달아 둔 자리다. 진주 한 알 한 알은 천사가 자기 누이를 한 번씩 더 떠올린 새벽마다 한 알씩 더 굳어진 결이다.',
    art: 'beautiful elegant graceful fallen angel divine fantasy pearl feather choker accessory item icon, slender white pearl strand choker with a single silver feather pendant hanging at the front, single inanimate game loot object on transparent background',
  },

  // ── batch 31: accessory 5종 ──
  {
    key: 'marsh_wisp_lantern_charm',
    slot: 'accessory',
    nameKo: '도깨비불의 lantern',
    region: '늪지대',
    tone: '위트',
    lore: '늪의 한 아이가 자기 첫 새벽에 자기 손바닥 안에 한 알의 청록 도깨비불을 한 번 더 굳혀 둔 자리에 한 자루의 작은 lantern이 그 자리 그대로 자기 결을 한 번 더 둘러 굳어진 자리다. lantern 안쪽의 wisp는 자기 자리에서 한 박자 늦게 한 번씩 더 옅게 깜빡인다.',
    art: 'humorous quirky marsh swamp will-o-wisp fantasy tiny lantern charm accessory item icon, silver chain holding a small silver teardrop lantern pendant with a teal wisp flame glowing inside, single inanimate game loot object on transparent background',
  },
  {
    key: 'orc_lost_brother_token',
    slot: 'accessory',
    nameKo: '잃은 형제의 token',
    region: '오크 부락',
    tone: '비애',
    lore: '부락의 한 어린 오크가 자기 동무 한 명을 자기 첫 사냥에서 잃은 새벽에, 그 동무의 마지막 손바닥 자국을 자기 가슴께 token에 한 번 더 굳혀 박아 둔 자리다. cord의 매듭은 그 어린 오크가 한 번도 그 동무의 이름을 다시 부르지 않은 결대로 한 번 더 묶여 있다.',
    art: 'mournful sorrowful orcish tribal fantasy lost brother token accessory item icon, brown leather cord with a single knot above a small carved bone token engraved with a red handprint and a single rune mark, single inanimate game loot object on transparent background',
  },
  {
    key: 'rune_high_archon_crown',
    slot: 'accessory',
    nameKo: '대제관의 crown',
    region: '고대 룬 산맥',
    tone: '장엄',
    lore: '룬 산맥의 가장 안쪽 산문을 자기 자리로 삼은 한 대제관이 자기 평생 한 번도 자기 자리에서 일어나지 않은 결을 자기 머리띠 가운데에 한 알의 큰 푸른 보석으로 한 번 더 굳혀 박아 둔 자리다. 양 옆에 새겨진 룬은 그 대제관이 자기 자리에서 한 번씩 더 짚어 본 결의 자국이다.',
    art: 'grand majestic imposing mountain rune ancient fantasy high archon crown accessory item icon, tall heavy dark silver crown with three sharp peaks engraved with ancient runes and a large central blue sapphire, single inanimate game loot object on transparent background',
  },
  {
    key: 'volcano_ash_phoenix_feather',
    slot: 'accessory',
    nameKo: '잿빛 불사조의 깃',
    region: '서쪽 화산',
    tone: '전설',
    lore: '서쪽 화산이 한 번 다 식고 한 번 다시 태어났다는 새벽에 그 불사조가 자기 자리에 한 줄 떨어뜨린 깃 한 가닥을 한 풀무지기가 자기 가슴께에 한 번 더 묶어 둔 자리다. 깃 끝에 가만히 머문 ember 한 알은 그 불사조가 자기 자리에서 한 번 더 깨어나는 새벽까지 한 박자 늦은 빛으로 남아 있다.',
    art: 'legendary mythic ancient storied volcanic phoenix fire fantasy ash feather charm accessory item icon, dark chain holding a single grey ash-colored phoenix feather pendant with a small ember glow burning at the tip, single inanimate game loot object on transparent background',
  },
  {
    key: 'common_kingsguard_medal',
    slot: 'accessory',
    nameKo: '왕실 근위의 medal',
    region: '일반',
    tone: '영웅담',
    lore: '한 왕국의 첫 근위 기사가 자기 평생 자기 왕의 자리 옆을 한 번도 떠나지 않은 결을 자기 medal에 한 번 더 굳혀 박아 둔 자리다. 가운데 황금으로 새겨진 검과 왕관은 그 근위가 마지막 새벽에 손가락 끝으로 한 번 더 짚어 본 자리에 깊이 새겨졌다.',
    art: 'heroic epic fantasy kingsguard medal accessory item icon, gold bow ribbon holding a round silver medal with a gold crowned sword emblem at the center, single inanimate game loot object on transparent background',
  },

  // ── batch 32: accessory 마지막 5종 ──
  {
    key: 'common_silver_rose_locket',
    slot: 'accessory',
    nameKo: '은 장미 locket',
    region: '일반',
    tone: '아름다운',
    lore: '한 신부가 자기 결혼 새벽에 자기 가슴께에 한 알의 은 locket을 한 번 더 매달고, 그 locket의 가운데에 자기 평생 한 번 더 짚어 본 한 송이 장미를 한 번 더 새겨 둔 자리다. locket은 그 신부가 자기 자리에서 한 번도 다시 열어 본 적이 없는 채로 가만히 한 자리에 굳어 있다.',
    art: 'beautiful elegant graceful fantasy silver rose locket accessory item icon, silver chain holding a small heart-shaped polished silver locket with a single rose etched on the front, single inanimate game loot object on transparent background',
  },
  {
    key: 'marsh_dawn_lotus_charm',
    slot: 'accessory',
    nameKo: '새벽 연꽃 부적',
    region: '늪지대',
    tone: '희망',
    lore: '늪의 한 신부가 자기 결혼 새벽 첫 일출 자리에 한 송이 분홍 연꽃을 한 번 더 가만히 두고 떠난 자리에 한 자루의 은 체인이 그 결을 그대로 두른 자리다. 꽃 가운데에 굳어 박힌 작은 황금 sun은 그 신부가 자기 결혼 새벽에 한 번 더 본 첫 빛이 한 알로 굳어진 자리다.',
    art: 'hopeful radiant warm serene marsh swamp fantasy dawn lotus charm accessory item icon, silver chain holding a pink lotus blossom pendant with a small warm gold sun rising behind the petals, single inanimate game loot object on transparent background',
  },
  {
    key: 'orc_first_kin_braid',
    slot: 'accessory',
    nameKo: '첫 친족의 매듭 팔찌',
    region: '오크 부락',
    tone: '희망',
    lore: '부락의 한 어린 오크가 자기 첫 친족 셋과 함께 한 새벽에 자기 손목 둘레에 한 줄의 가죽을 한 번 더 매듭으로 두르고, 세 알의 wooden bead에 각자의 결을 한 자씩 더 새겨 둔 자리다. 매듭은 그 어린 오크가 자기 자리에서 한 번도 풀지 않은 결대로 한 번 더 묶여 있다.',
    art: 'hopeful radiant warm orcish tribal fantasy first kin braid bracelet accessory item icon, braided brown leather bracelet with three small wooden beads carved with warm family tribal marks, single inanimate game loot object on transparent background',
  },
  {
    key: 'rune_apprentice_inkwell',
    slot: 'accessory',
    nameKo: '견습생의 잉크병 부적',
    region: '고대 룬 산맥',
    tone: '위트',
    lore: '룬 산맥 학원의 한 어린 견습이 자기 평생 가장 자주 떨군 잉크병을 자기 가슴께에 한 번 더 작은 부적으로 한 번 더 매달아 둔 자리다. 잉크병 옆에 박혀 있는 깃펜과 둘레의 잉크 자국 세 알은 그 견습이 자기 자리에서 한 번씩 더 떨군 결이다.',
    art: 'humorous quirky mountain rune fantasy apprentice inkwell charm accessory item icon, silver chain holding a small dark inkwell pendant with a feather quill leaning into it and three ink splatter dots around, single inanimate game loot object on transparent background',
  },
  {
    key: 'fallen_cherub_brooch',
    slot: 'accessory',
    nameKo: 'cherub의 brooch',
    region: '타락천사',
    tone: '위트',
    lore: '한 천사가 자기 어린 케르빔 동무 한 명을 자기 자리에 한 번 더 두고 떠난 새벽에, 그 케르빔이 자기 자리에서 한 번 더 가만히 웃어 본 결을 한 알의 황금으로 한 번 더 굳혀 brooch로 박아 둔 자리다. 양 옆 두 작은 날개와 머리 위의 후광은 케르빔이 자기 자세를 한 번 더 흩뜨리지 않은 결대로 굳어 있다.',
    art: 'humorous quirky whimsical fallen angel divine fantasy cherub brooch accessory item icon, small gold brooch shaped like a chubby smiling cherub face with two tiny wings on each side and a small halo above, single inanimate game loot object on transparent background',
  },
];
