/** 카탈로그 모티프(개념+색) — scripts/_gen-motifs.ts 로 art에서 추출. 형태·tone 제외. */
export const ITEM_MOTIFS: Record<string, string> = {
  "marsh_frog_leaf_dirk": "frog, green",
  "marsh_dry_root_blade": "root, black",
  "marsh_skull_drip_axe": "skull, green",
  "marsh_lantern_wand": "lantern, teal",
  "marsh_old_god_polearm": "flower, purple",
  "orc_tooth_band_club": "fang, bone",
  "orc_two_feather_sabre": "feather, dark",
  "orc_spine_whip": "spine, bone",
  "orc_horn_grown_axe": "horn, dark",
  "orc_oldchief_maul": "stone, gold, black",
  "common_bard_lute_with_blade": "lute, blue",
  "rune_three_shard_blade": "rune, stone",
  "rune_watching_dirk": "eye, rune, red",
  "common_chef_giant_skillet": "egg, black",
  "rune_first_thunder_hammer": "rune, stone, gold",
  "volcano_pan_cleaver": "fire, black",
  "common_royal_archer_longbow": "gold, sapphire",
  "volcano_molten_eye_dirk": "eye, orange",
  "volcano_ember_rune_blade": "rune, ember",
  "volcano_dragon_rune_axe": "dragon, gold",
  "fallen_cherub_resting_rapier": "cherub, silver",
  "fallen_black_feather_blade": "feather, silver, black",
  "fallen_decay_wing_scythe": "wing, feather, dark",
  "common_warrior_chakram": "warrior, gold",
  "fallen_seraph_glaive": "seraph, silver, gold, white",
  "common_clover_dirk": "clover, steel",
  "common_widow_veil_blade": "veil, black",
  "common_acrobat_fan_blade": "fan, red, gold",
  "common_scribe_quill_wand": "quill, blue, white",
  "common_hero_greatsword": "hero, gold, blue",
  "orc_first_hunt_broken_axe": "tusk, bone",
  "volcano_first_ember_hammer": "ember, orange",
  "marsh_ferry_harpoon": "thorn, dark",
  "orc_ancestor_twin_tusk_axe": "tusk, iron",
  "volcano_dragon_bone_blade": "dragon, bone",
  "marsh_gemwoven_wand": "gem, teal, gold",
  "orc_totem_chief_axe": "totem, face, red",
  "common_grand_executioner_halberd": "iron, dark",
  "volcano_phoenix_blade": "phoenix, gold, red",
  "fallen_golden_glaive": "angel, wing, gold",
  "common_knight_lance": "knight, gold",
  "common_anointed_sabre": "royal, gold",
  "common_twin_dragon_scepter": "dragon, gold, pearl",
  "rune_first_chronicler_pen": "rune, teal, silver",
  "fallen_starhead_flail": "star, silver, black",
  "common_two_handed_morningstar": "spike, iron",
  "common_emperor_naginata": "crane, gold, red",
  "orc_warband_cleaver": "skull, iron",
  "marsh_witch_queen_staff": "root, teal, black",
  "common_jester_lollipop_mace": "candy, red, white",
  "marsh_lily_dress": "lily, teal",
  "orc_palm_print_vest": "orc, red",
  "rune_single_curve_stone_plate": "rune, gray",
  "volcano_ember_embroidered_cloak": "ember, gray",
  "fallen_seraph_dark_breastplate": "seraph, gold",
  "common_imperial_dragon_robe": "dragon, red, gold",
  "common_knight_chainmail_hauberk": "chainmail, gray",
  "rune_guardian_brass_helm": "rune, brass",
  "volcano_phoenix_robe": "phoenix, red, gold",
  "fallen_white_silk_robe": "angel, white, gold",
  "marsh_frog_nest_hat": "frog, green",
  "orc_ribcage_chest": "bone, dark",
  "rune_high_priest_crown": "rune, blue",
  "volcano_blacksmith_apron": "forge, brown",
  "common_court_jester_motley": "jester, multicolor",
  "common_legendary_relic_breastplate": "hero, bronze, red",
  "common_pope_mitre_crown": "cross, white, gold",
  "volcano_drake_lord_helm": "dragon, red",
  "fallen_archangel_gold_wings": "angel, gold, blue",
  "common_king_cross_helm": "cross, silver, gold",
  "orc_jester_hood": "jester, green",
  "marsh_lord_robe": "leaf, teal",
  "rune_silver_diadem": "rune, silver, teal",
  "volcano_corrupted_mask": "ember, orange",
  "fallen_paladin_breastplate": "sun, silver, gold",
  "common_emperor_jade_crown": "jade, gold, red",
  "orc_sunrise_tabard": "sunrise, orange",
  "rune_morning_light_cloak": "sun-rune, gold",
  "volcano_first_spark_apron": "spark, orange",
  "fallen_dawn_wing_chest": "angel, gold, white",
  "marsh_big_lilypad_hat": "lily, green",
  "common_aristocrat_lace_dress": "flower, cream",
  "rune_seer_hood": "rune, indigo",
  "volcano_glass_flame_crown": "flame, red",
  "fallen_celestial_gold_chest": "sun, gold, red",
  "marsh_drowned_pirate_tricorne": "pearl, teal",
  "orc_blood_brother_horn_pauldrons": "horn, red",
  "rune_high_lord_gauntlets": "rune, gold, red",
  "volcano_widow_smith_apron": "forge, black",
  "common_traveler_star_hat": "star, blue, yellow",
  "common_first_paladin_oath_chestplate": "sword, silver",
  "orc_first_chief_armor": "glyph, green",
  "rune_arch_priest_robe": "rune, purple, gold",
  "volcano_lava_pup_helm": "salamander, orange",
  "fallen_dusk_short_robe": "angel, pink, gold",
  "marsh_drowned_pearl_cape": "pearl, teal",
  "orc_oracle_hood": "rune, red",
  "rune_apprentice_satchel": "rune, brown",
  "volcano_master_smith_chest": "hammer, red",
  "common_golden_rose_shield": "rose, gold",
  "marsh_lily_amulet": "lily, teal, silver",
  "common_witty_clockwork_pocket_watch": "clockwork, brass",
  "rune_listening_rune_ring": "rune, blue, silver",
  "volcano_phoenix_eye_amulet": "phoenix, orange, gold",
  "fallen_morning_sun_charm": "angel, sun, gold, white",
  "marsh_frog_ring": "frog, green, silver",
  "orc_chieftain_twin_tusk_necklace": "orc, tusk, brown",
  "rune_warden_wing_seal": "rune, wing, silver",
  "volcano_glass_ember_earring": "ember, orange, gold",
  "fallen_four_wing_pinwheel_brooch": "angel, wing, gold",
  "marsh_winged_slime_charm": "slime, wing, green, blue",
  "orc_first_hunt_tooth_ring": "orc, tooth, gold, iron",
  "rune_first_letter_amulet": "rune, blue, dark",
  "volcano_leaf_ember_locket": "leaf, ember, orange, black",
  "common_king_lion_signet_ring": "lion, gold, blue",
  "marsh_root_eye_pendant": "eye, root, teal, brown",
  "common_royal_fan_brooch": "fan, gold, red, pink",
  "rune_starlight_crown": "rune, star, silver, blue",
  "common_phoenix_egg_pendant": "phoenix, gold, ember",
  "fallen_three_feather_anklet": "angel, feather, silver",
  "marsh_drowned_queen_circlet": "marsh, root, teal, bronze",
  "orc_chief_gold_collar": "orc, gold, red",
  "rune_hex_riddle_ring": "rune, hexagon, silver",
  "common_pilgrim_knot_charm": "sun, gold, brown",
  "volcano_baby_dragon_pendant": "dragon, gold, pale",
  "marsh_swamp_god_eye_amulet": "eye, god, green, brown",
  "orc_blood_pact_skull_brooch": "orc, skull, gold, red",
  "rune_quartz_droplet_earring": "rune, quartz, silver, gold",
  "fallen_archangel_halo_crown": "angel, halo, gold, white",
  "volcano_salamander_ring": "salamander, orange, dark",
  "marsh_lily_pad_anklet": "lily, lily pad, green, pink, silver",
  "orc_grinning_beard_bead": "orc, dark, wood",
  "rune_two_chisel_charm": "rune, chisel, silver",
  "common_butterfly_wing_earring": "butterfly, blue, silver",
  "marsh_swamp_hand_bone_knot_charm": "bone, hand, green, dark",
  "common_emperor_signet_chain": "lion, gold",
  "common_witty_three_needle_compass": "compass, brass",
  "volcano_smith_hammer_pin": "hammer, anvil, iron, orange",
  "common_kingsguard_shield_brooch": "lion, shield, silver, gold",
  "marsh_wisp_lantern_charm": "wisp, lantern, teal, silver",
  "common_first_forge_ring": "ember, orange, iron",
  "rune_high_archon_crown": "rune, silver, blue",
  "volcano_ash_phoenix_feather": "phoenix, feather, grey, orange",
  "common_kingsguard_medal": "sword, gold, silver",
  "common_ornate_ruby_diadem": "ruby, gold, red",
  "marsh_dawn_lotus_charm": "lotus, sun, pink, gold, silver",
  "orc_first_kin_braid": "orc, brown, wood",
  "rune_apprentice_inkwell": "rune, inkwell, silver, dark",
  "fallen_cherub_brooch": "angel, cherub, gold",
  "common_silver_swan_pendant": "swan, silver"
};
