// 길드 에러 코드 → 사용자 메시지(클라이언트). 서버 액션의 { code }와 1:1.
const MAP: Record<string, string> = {
  ALREADY_IN_GUILD: '이미 길드에 소속되어 있습니다.',
  NOT_IN_GUILD: '길드에 소속되어 있지 않습니다.',
  NAME_INVALID: '길드 이름은 2~8자여야 합니다.',
  NAME_CHARSET: '길드 이름은 한글·영문·숫자만 사용할 수 있어요 (공백·특수문자·이모지 불가).',
  NAME_TAKEN: '이미 사용 중인 길드 이름입니다.',
  PROFANITY: '사용할 수 없는 단어가 포함되어 있습니다.',
  INSUFFICIENT_DIAMOND: '다이아가 부족합니다.',
  GUILD_NOT_FOUND: '길드를 찾을 수 없습니다.',
  GUILD_FULL: '길드 정원이 가득 찼습니다.',
  REJOIN_LOCKED: '탈퇴 후 24시간이 지나야 가입할 수 있습니다.',
  NOT_LEADER: '길드장만 할 수 있습니다.',
  LEADER_MUST_TRANSFER: '길드장은 위임하거나 해산해야 탈퇴할 수 있습니다.',
  DONATION_CAP_REACHED: '오늘 기부를 모두 했습니다.',
  TARGET_NOT_IN_GUILD: '대상이 같은 길드원이 아닙니다.',
  INVALID_TARGET: '대상이 올바르지 않습니다.',
  ZONE_NOT_FOUND: '구역을 찾을 수 없습니다.',
  NOT_EXECUTOR: '해당 구역의 집행관이 아닙니다.',
  COLLECT_COOLDOWN: '아직 수금 할 수 없습니다.',
  NOTHING_TO_COLLECT: '수금할 다이아가 없습니다.',
  NOTHING_TO_DISTRIBUTE: '분배할 다이아가 없습니다.',
  DISTRIBUTE_OVER_POOL: '분배 총액이 세금을 초과합니다.',
  ZONE_NOT_OWNED: '자기 길드 소유 구역만 수비할 수 있습니다.',
  CANNOT_ATTACK_OWN: '자기 길드 구역은 공격할 수 없습니다.',
  NOT_ADJACENT: '내 길드 영토에 인접한 구역만 공격할 수 있습니다.',
  IS_EXECUTOR: '집행관은 자동 방어 중이라 배치할 수 없습니다.',
  BATTLE_IN_PROGRESS: '점령전 진행 중에는 배치를 변경할 수 없습니다. 점령전 종료 후 한 시간 뒤부터 변경 가능합니다.',
  TARGET_ALREADY_EXECUTOR: '이미 다른 구역의 집행관입니다.',
  NOT_OFFICER: '길드장·부길드장만 할 수 있습니다.',
  FORBIDDEN: '권한이 없습니다.',
  NO_JOIN_REQUEST: '처리할 가입 신청이 없습니다.',
  VICE_LIMIT: '부길드장은 최대 5명까지 임명할 수 있습니다.',
  EMBLEM_INVALID: '문양은 모양·색상 각 1개, 키워드 1~2개를 선택하세요.',
  EMBLEM_MAX: '문양은 최대 5개까지 보관할 수 있어요. 하나를 삭제한 뒤 생성하세요.',
  EMBLEM_MIN: '문양은 최소 1개는 남겨야 해요.',
  EMBLEM_NOT_FOUND: '문양을 찾을 수 없습니다.',
  OPENCHAT_INVALID: '카카오 오픈채팅 링크(https://open.kakao.com/o/…)만 등록할 수 있습니다.',
  UNAUTHENTICATED: '로그인이 필요합니다.',
  RATE_LIMITED: '요청이 너무 빠릅니다. 잠시 후 다시 시도해 주세요.',
  MAINTENANCE: '서버 점검 중입니다. 잠시 후 다시 시도해 주세요.',
  UNKNOWN: '오류가 발생했습니다.',
};

export function guildErrMsg(code: string): string {
  return MAP[code] ?? MAP.UNKNOWN!;
}
