// public/sprites/{ui,hub,og,boss}/* — content 8자 hash 맵 빌드 → lib/asset-versions.generated.ts.
// raw <img src> client/server 어디서나 import 해 사용. 파일 변경 시 hash 갱신
// → 모바일 포함 브라우저 캐시 자동 무효화(강력 새로고침 불필요).
//
// ⚠ content 해시 필수(mtime 금지) — 빌드가 Vercel에서도 이 스크립트를 실행하는데,
//   git clone은 mtime을 체크아웃 시각으로 새로 찍어 mtime 해시는 **배포마다 전 자산
//   캐시를 무효화**시켰다(2026-07-10 감사 발견). content 해시는 파일이 실제로 바뀔
//   때만 변한다(재현 가능·로컬/CI 동일).
//
// item sprite(/sprites/{weapon,armor,accessory}/*)는 양 많고 거의 안 변경 →
// atlas.webp가 단일 자산이므로 atlas만 포함. 개별 PNG는 양 많아 생략.
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { createHash } from 'node:crypto';

const PUB = join(process.cwd(), 'public');

// 자주 변경되는 자산 폴더. 자산 추가 시 여기 path 추가.
const SCAN_DIRS = ['sprites/ui', 'sprites/hub', 'sprites/boss', 'sprites/characters', 'sprites/shop', 'sprites/checkin', 'sprites/guild', 'sprites/guild-menu', 'sprites/anim', 'og'];
// atlas 단일 자산도 포함(원자적 갱신).
const SCAN_FILES = ['sprites/atlas.webp'];

function listRecursive(rel: string): string[] {
  const abs = join(PUB, rel);
  let entries: string[];
  try {
    entries = readdirSync(abs);
  } catch {
    return [];
  }
  const out: string[] = [];
  for (const e of entries) {
    const sub = join(abs, e);
    const subRel = `${rel}/${e}`;
    try {
      const st = statSync(sub);
      if (st.isDirectory()) {
        out.push(...listRecursive(subRel));
      } else if (st.isFile()) {
        out.push(subRel);
      }
    } catch {
      // skip
    }
  }
  return out;
}

const map: Record<string, string> = {};
let count = 0;
function contentHash(absPath: string): string {
  return createHash('sha1').update(readFileSync(absPath)).digest('hex').slice(0, 8);
}
for (const d of SCAN_DIRS) {
  for (const rel of listRecursive(d)) {
    try {
      map[`/${rel}`] = contentHash(join(PUB, rel));
      count++;
    } catch {
      // skip
    }
  }
}
for (const f of SCAN_FILES) {
  try {
    map[`/${f}`] = contentHash(join(PUB, f));
    count++;
  } catch {
    // skip
  }
}

const out = `// AUTO-GENERATED by scripts/build-asset-versions.ts — 수정 금지.
// content 8자 hash 맵. assetUrl()이 import 후 path → '?v=<hash>' 첨부.
export const ASSET_VERSIONS: Record<string, string> = ${JSON.stringify(map, null, 2)};
`;
const dst = join(process.cwd(), 'lib', 'asset-versions.generated.ts');
writeFileSync(dst, out);
console.log(`asset-versions: ${count} entries → ${dst}`);
