// 신규 120종 아바타-코디 카탈로그 작업 데이터(docs/ITEMS.md). 배치 단위로 채워 나간다.
// 워크플로: ①컨셉·이름·프롬프트 검수 → ②이미지(객체) 생성·검수 → ③이미지 보고 로어 작성.
// 프롬프트 원칙(memory pixellab-item-prompt-balance):
//   - 최대한 디테일·특색(아이템마다 애정 생기게). 형태/구성 디테일 자세히.
//   - 지역이 왕국이어도 '로열+보석'으로 도배 금지 — 아이템마다 재질·역할·캐릭터를 제각각.
//     보석은 그게 진짜 컨셉인 것만. 화려함은 다양한 장인적 재질(강철·실크·라커·호두나무·은각인 등)로.
//   - 무기: large·diagonal·clean/straight(가드는 칼날에 수직), 두꺼운 타입 적극.
export type ItemV2 = {
  key: string;
  slot: 'weapon' | 'armor' | 'accessory';
  nameKo: string;
  region: string;
  tone: string;
  concept: string;
  art: string; // 컨셉-온리 프롬프트 조각 "a <종류> — <역할·무드>"(외형묘사 X). buildArt가 품질 tail을 덧붙임.
  wornDesc: string;
  lore: string;
  keeper?: boolean; // 사용자가 고른 확정 이미지(생성 스킵·잠금)
};

import { EXTRA_ITEMS } from './items-extra';
import { WEAPONS_90, ARMOR_90, ACCESSORIES_90 } from './items90';

const INLINE_ITEMS: ItemV2[] = [
  // ── 왕국 · 무기 (10) · 아이템마다 다른 재질·캐릭터 ───────────────────────────
  {
    key: 'kingdom_ribbon_rapier',
    slot: 'weapon',
    nameKo: '푸른 매듭',
    region: '왕국',
    tone: '화려',
    concept: '파란 실크 리본의 결투용 레이피어',
    art: 'an ornate royal rapier with a flowing ribbon, elegant and splendid, large, pixel art',
    wornDesc: 'a slim golden rapier with an ornate guard and a trailing blue ribbon',
    lore: '',
  },
  {
    key: 'kingdom_coronation_greatsword',
    slot: 'weapon',
    nameKo: '왕관의 무게',
    region: '왕국',
    tone: '영웅담',
    concept: '크라운 폼멜의 묵직한 강철 대검',
    art: 'a grand ornate royal two-handed greatsword, majestic and splendid, premium game-art, isolated object, plain background, large, pixel art',
    wornDesc: 'a magnificent heroic greatsword with a broad gleaming steel blade and a golden crown-shaped pommel, rested over one shoulder',
    lore: '',
  },
  {
    key: 'kingdom_court_twinblades',
    slot: 'weapon',
    nameKo: '마주 든 한 쌍',
    region: '왕국',
    tone: '화려',
    concept: 'X자 교차·자개 라커 손잡이 쌍곡검',
    art: 'two slim curved court sabers crossed in a big X shape, black lacquered hilts inlaid with mother-of-pearl and hanging silk tassels, lavishly ornate in a fantasy anime style, graceful and exotic, isolated object, plain background, large, pixel art',
    wornDesc: 'a pair of slim curved sabers with black lacquered, pearl-inlaid hilts, one per hand',
    lore: '',
  },
  {
    key: 'kingdom_coronation_spear',
    slot: 'weapon',
    nameKo: '즉위를 알린 창',
    region: '왕국',
    tone: '영웅담',
    concept: '긴 물푸레 자루에 왕실 깃발 단 의장창',
    art: 'a very long slender processional spear, a tall finely polished shaft with gold fittings, a gleaming steel head, a rich royal banner streaming from below the blade, ceremonial and majestic, full length, pixel art',
    wornDesc: 'a long processional spear with a pale wooden shaft, a steel head and a royal banner below the blade',
    lore: '',
  },
  {
    key: 'kingdom_jewel_longsword',
    slot: 'weapon',
    nameKo: '보석을 삼킨 날',
    region: '왕국',
    tone: '화려',
    concept: '자수정이 박힌 넓은 의장 장검(보석이 컨셉)',
    art: 'a magnificent fantasy longsword, a broad ornate blade set with a glittering row of amethyst gems, an elaborate gilded guard and a large amethyst gem pommel, lavishly jeweled in a fantasy anime JRPG style, gorgeous and splendid, clean and straight with the guard perpendicular to the blade, large, pixel art',
    wornDesc: 'a broad longsword with a row of amethyst gems along the blade and a gilded hilt',
    lore: '',
  },
  {
    key: 'kingdom_guard_halberd',
    slot: 'weapon',
    nameKo: '문 앞의 맹세',
    region: '왕국',
    tone: '영웅담',
    concept: '왕실 정문을 지키는 화려한 의장 할버드',
    art: 'a magnificent fantasy royal halberd, a long ornate shaft with a large gold-engraved axe blade and a spike, lavishly ornate in a fantasy anime style, splendid and grand, isolated object, plain background, full length, pixel art',
    wornDesc: 'an ornate royal halberd with a long shaft and a large gold-engraved axe blade',
    lore: '',
  },
  {
    key: 'kingdom_cane_sword',
    slot: 'weapon',
    nameKo: '지팡이 속 한 줄',
    region: '왕국',
    tone: '수수께끼',
    concept: '호두나무·놋쇠 손잡이 지팡이검',
    art: "an exquisite fantasy gentleman's cane, lustrous dark wood with elaborate gold scrollwork and a jeweled bird-head handle, concealing a thin hidden blade, luxurious in a fantasy anime style, refined and splendid, large, pixel art",
    wornDesc: 'a polished dark-walnut cane with a brass bird-head handle that conceals a thin blade',
    lore: '',
  },
  {
    key: 'kingdom_duel_pistol',
    slot: 'weapon',
    nameKo: '정중한 한 발',
    region: '왕국',
    tone: '화려',
    concept: '은각인 호두나무 플린트락 결투 권총',
    art: 'an exquisite flintlock dueling pistol, a fine dark walnut stock with chased silver scrollwork and gold inlay, a long engraved barrel, refined and elegant, large, pixel art',
    wornDesc: 'an antique flintlock dueling pistol with a dark walnut stock and chased silver scrollwork',
    lore: '',
  },
  {
    key: 'kingdom_scepter_mace',
    slot: 'weapon',
    nameKo: '보석을 인 홀',
    region: '왕국',
    tone: '전설',
    concept: '거대한 루비가 얹힌 황금 왕홀(보석이 컨셉)',
    art: 'a golden royal scepter-mace crowned with one enormous ruby, ornate gold flanges, lavishly regal and gorgeous, large, pixel art',
    wornDesc: 'an ornate golden scepter-mace topped with one enormous ruby',
    lore: '',
  },
  {
    key: 'kingdom_ribbon_whip',
    slot: 'weapon',
    nameKo: '풀린 리본의 춤',
    region: '왕국',
    tone: '아름다운',
    concept: '강철 비늘 박힌 크림슨 실크 리본 채찍',
    art: 'a long flowing ribbon-whip of crimson silk lined with tiny steel scales, an ornate grip, graceful and beautiful, large, pixel art',
    wornDesc: 'a long crimson silk ribbon-whip lined with tiny steel scales and an ornate grip',
    lore: '',
  },

  // ── 새 방식(종류+컨셉+스타일) 테스트 — 신전·늪지 ──────────────────────────
  {
    key: 'temple_frostvein_rifle',
    slot: 'weapon',
    nameKo: '첫눈을 겨눈 총신',
    region: '신전',
    tone: '영웅담',
    concept: '성스러운 설산 사냥꾼의 의식용 장총',
    art: 'a long fantasy flintlock musket (a snow-temple hunter who aims at the first snowfall) — a splendid, gorgeous, lavishly detailed premium visual pixel-art game item, dazzling frost-touched fantasy game art, no telescopic scope, isolated object, plain background, large, pixel art',
    wornDesc: 'a long ornate hunting rifle, white-silver with frost-rune accents and fur trim, held one-handed at rest',
    lore: '',
  },
  {
    key: 'swamp_petal_dress',
    slot: 'armor',
    nameKo: '요정의 첫 꽃잎',
    region: '늪지대',
    tone: '아름다운',
    concept: '어린 늪요정의 첫 비행 꽃잎 드레스',
    art: 'a layered petal fairy dress — the first-flight gown of a young bog-fairy, woven from dawn-dewed flower petals with gossamer wings, light and joyful — drawn in a cute charming fantasy-anime style, soft luminous pastel pink and mint, a graceful slender silhouette, isolated object, plain background, pixel art',
    wornDesc: 'a layered pastel-pink-and-mint petal fairy dress with sheer gossamer wings',
    lore: '',
  },
];

// 재설계: 새 90종(items90)을 카탈로그로 사용. 이전 120종은 보류 — 삭제하지 않고
// HELD_ITEMS로 보존(나머지 30을 여기서 골라 추가할 풀). 현재 무기 30만 작성됨(방어구·장신구 추가 예정).
export const HELD_ITEMS: ItemV2[] = [...INLINE_ITEMS, ...EXTRA_ITEMS];


// ── V4 확장 14종 · 4차(2026-08-02) — 3차에서 장미 채찍검 1종 채택(+2차 임프 날개).
//    채택작의 공통 결: 흐르는 실루엣·단일 색 이야기·형태 자체가 컨셉. 넓은 날에 장식을
//    박는 방식(트럼프·태엽 대검류)을 버리고 전체 형태가 컨셉인 12종으로 재설계.
export const V4_ITEMS: ItemV2[] = [
  // ── 무기 8/8 확정 ──
  {
    key: 'general_twin_flintlocks',
    slot: 'weapon',
    nameKo: '두 발의 대답',
    region: '일반',
    tone: '화려',
    concept: '금 세공 쌍발 플린트락 권총',
    art: 'a pair of ornate flintlock pistols crossed — polished black barrels with swirling gold engravings and ruby-set grips, dashing and elegant, clearly pistol weapons, no text, no letters, no labels, large, diagonal',
    wornDesc: 'a crossed pair of black-and-gold flintlock pistols with ruby grips',
    lore: '',
    keeper: true,
  },
  {
    key: 'general_spiral_lance',
    slot: 'weapon',
    nameKo: '나선을 그리는 끝',
    region: '일반',
    tone: '영웅담',
    concept: '흑금 나선 세공의 기사 랜스',
    art: 'a black and gold spiral-fluted knight lance tapering to a piercing point, dramatic and imposing, clearly a lance weapon, large, diagonal',
    wornDesc: 'a black-and-gold spiral-fluted lance tapering to a fine point',
    lore: '',
    keeper: true,
  },
  {
    key: 'general_starfield_blade',
    slot: 'weapon',
    nameKo: '밤하늘을 벼린 날',
    region: '일반',
    tone: '수수께끼',
    concept: '별과 별자리 선이 흐르는 심야 검신',
    art: 'a longsword forged of the night sky — a deep midnight-blue translucent blade filled with tiny stars and glowing gold constellation lines, a dark silver hilt with a star-shaped pommel, mystical and elegant, clearly a sword weapon, large, diagonal',
    wornDesc: 'a midnight-blue blade filled with tiny stars and gold constellation lines',
    lore: '',
    keeper: true,
  },
  {
    key: 'general_kintsugi_katana',
    slot: 'weapon',
    nameKo: '금으로 기운 상처',
    region: '일반',
    tone: '아름다운',
    concept: '깨졌던 자리를 금으로 이은 킨츠기 카타나',
    art: 'a magnificent kintsugi katana — a long jet-black blade once shattered and rejoined with luminous molten-gold veins branching like lightning across the steel, warm gold light softly leaking from the seams, an ornate engraved gold tsuba and a black-and-gold silk-wrapped hilt, breathtaking and resolute, clearly a katana sword weapon, large, diagonal',
    wornDesc: 'a jet-black katana with bright gold veins mending old cracks along the blade',
    lore: '',
    keeper: true,
  },
  {
    key: 'fallen_half_blade',
    slot: 'weapon',
    nameKo: '절반의 추락',
    region: '타락천사',
    tone: '수수께끼',
    concept: '세로로 갈라진 반빛·반흑 대검 — 검은 깃털',
    art: 'a half-fallen greatsword — a blade split lengthwise, one half radiant white-gold and the other jet-black with falling dark feathers, a wing-shaped guard half gold half black, dramatic and tragic, clearly a greatsword weapon, large, diagonal',
    wornDesc: 'a greatsword split lengthwise into radiant gold and jet-black halves, dark feathers falling',
    lore: '',
    keeper: true,
  },
  { key: 'temple_icicle_longbow', slot: 'weapon', nameKo: '고드름을 당기다', region: '신전', tone: '아름다운',
    concept: '고드름이 자란 백은 장궁',
    art: 'an icicle longbow — a tall pale silver bow with clusters of clear icicles growing along its limbs, a shimmering frost-blue string, cold mist drifting from the grip, elegant and freezing, clearly a longbow weapon, no text, large, diagonal',
    wornDesc: 'a tall silver longbow with icicles growing along its limbs', lore: '', keeper: true },
  { key: 'fallen_pinion_twinblades', slot: 'weapon', nameKo: '한 쌍의 깃', region: '타락천사', tone: '전설',
    concept: '흰 깃·검은 깃의 쌍검',
    art: 'a pair of pinion twinblades — two curved wing-shaped blades crossed in an X, one white-gold with radiant feather etching and one jet-black with dark feather etching, matching hilts, dualistic and striking, clearly twin sword weapons, no text, large, diagonal',
    wornDesc: 'two crossed wing-shaped blades, one white-gold and one jet-black', lore: '', keeper: true },
  { key: 'fallen_grace_greatbow', slot: 'weapon', nameKo: '반쯤 남은 은총', region: '타락천사', tone: '전설',
    concept: '한쪽은 금빛·한쪽은 흑빛인 대궁',
    art: 'a magnificent fallen grace greatbow — a tall elegant bow with a deep recurve, its upper limb sculpted as a radiant white-gold angel wing with layered luminous feathers, its lower limb as a charred jet-black wing with ragged dark feathers, an ornate gilded center grip with fine filigree and a single pale gem, a taut string of pale light, a few loose feathers drifting, majestic and tragic, no halo, no ring, clearly a longbow weapon, no text, large, diagonal',
    wornDesc: 'a tall bow with one radiant gold limb and one charred black limb', lore: '', keeper: true },
  // ── 장신구 2/4 확정 ──
  {
    key: 'general_star_eyepatch',
    slot: 'accessory',
    nameKo: '감아 둔 왼눈',
    region: '일반',
    tone: '수수께끼',
    concept: '금 별 장식의 검은 가죽 안대',
    art: 'a black leather eyepatch over the left eye with a slim strap and a small gold star stud, roguish and stylish',
    wornDesc: 'a black leather eyepatch with a gold star stud over the left eye',
    lore: '',
    keeper: true,
  },
  {
    key: 'general_imp_wings',
    slot: 'accessory',
    nameKo: '등에 돋은 장난',
    region: '일반',
    tone: '희망',
    concept: '작은 악마의 박쥐 날개 한 쌍',
    art: 'a small pair of imp bat wings — two little glossy crimson-and-black bat wings with cute rounded tips and gold wing-claws, sized to sit on the upper back, charming and mischievous, not large dragon wings',
    wornDesc: 'small crimson bat wings perched on the upper back',
    lore: '',
    keeper: true,
  },
  // ── 미확정(방어구 2 · 장신구 2 자리) — 후보, 채택 대기 ──
  {
    key: 'general_kintsugi_armor',
    slot: 'armor',
    nameKo: '깨진 적 있는 갑옷',
    region: '일반',
    tone: '영웅담',
    concept: '금맥으로 기운 흑칠 킨츠기 갑주',
    art: 'a kintsugi armor — a sleek black lacquered plate armor mended with branching veins of bright gold across the chest and pauldrons, warm gold light in the cracks, a dark sash, resolute and beautiful, a single garment floating on a plain empty background, no buildings',
    wornDesc: 'black lacquered plate armor mended with branching veins of bright gold',
    lore: '',
  },
  {
    key: 'general_rosevine_dress',
    slot: 'armor',
    nameKo: '가시로 지은 옷',
    region: '일반',
    tone: '화려',
    concept: '가시 넝쿨로 짠 장미 아머드 드레스',
    art: 'an armored dress of living rose vines — a fitted bodice woven from dark green thorned vines with deep red roses blooming at the shoulder and waist, thorn-plated skirt layers, elegant and dangerous, a single garment floating on a plain empty background, no buildings',
    wornDesc: 'a bodice of dark thorned vines with deep red roses at the shoulder and waist',
    lore: '',
  },
  {
    key: 'general_hero_scarf',
    slot: 'accessory',
    nameKo: '바람을 기억하는 머플러',
    region: '일반',
    tone: '영웅담',
    concept: '바람에 길게 휘날리는 진홍 머플러',
    art: 'a long crimson hero scarf — a deep red muffler wrapped once around the neck with both ends streaming dramatically in the wind, frayed tips and gold-stitched edges, heroic and free, isolated object on a plain background',
    wornDesc: 'a deep red muffler with both ends streaming dramatically behind',
    lore: '',
  },
  {
    key: 'general_guardian_daggers',
    slot: 'accessory',
    nameKo: '주인을 지키는 세 자루',
    region: '일반',
    tone: '수수께끼',
    concept: '등 뒤에 부유하는 호위 소검 세 자루',
    art: 'three small guardian daggers floating in formation — ornate silver-and-gold daggers hovering in a fan arrangement with faint magic glow trails, vigilant and mysterious, isolated objects on a plain background, no text',
    wornDesc: 'three ornate daggers floating in a fan formation behind the back',
    lore: '',
  },
];



// ── V4 후보 풀 30종(2026-08-02, key1 대량 생성) — 사용자가 2/2/2 선별 예정.
export const V4_POOL30: ItemV2[] = [
  { key: 'kingdom_heraldic_bastard', slot: 'weapon', nameKo: '문장을 새긴 날', region: '왕국', tone: '영웅담',
    concept: '청금 문장이 새겨진 은강 바스타드소드',
    art: 'a heraldic bastard sword — a broad polished silver blade with a royal-blue enamel heraldic crest inlaid at the ricasso, a straight gold crossguard and a blue-wrapped grip with a lion pommel, noble and disciplined, clearly a bastard sword weapon, no text, large, diagonal',
    wornDesc: 'a silver bastard sword with a blue enamel crest and gold crossguard', lore: '' },
  { key: 'kingdom_lily_halberd', slot: 'weapon', nameKo: '백합이 핀 도끼날', region: '왕국', tone: '화려',
    concept: '백합 투각의 은빛 할버드',
    art: 'a royal lily halberd — a wide silver axe head pierced with an openwork fleur-de-lis pattern, a slim spike above and a pale ash shaft with gold rings, stately and ornamental, clearly a halberd polearm weapon, no text, large, diagonal',
    wornDesc: 'a silver halberd with an openwork lily-pattern axe head', lore: '' },
  { key: 'kingdom_swan_rapier', slot: 'weapon', nameKo: '백조가 접은 가드', region: '왕국', tone: '아름다운',
    concept: '백조 날개 형상의 은백 레이피어',
    art: 'a swan rapier — a slender white-silver blade with a swept guard shaped like two folded swan wings in white enamel and silver filigree, a pearl pommel, graceful and refined, clearly a rapier sword weapon, no text, large, diagonal',
    wornDesc: 'a slender silver rapier with a guard of folded white swan wings', lore: '' },
  { key: 'kingdom_royal_warhammer', slot: 'weapon', nameKo: '조례를 끝내는 소리', region: '왕국', tone: '전설',
    concept: '청 에나멜·금장의 왕실 워해머',
    art: 'a royal warhammer — a squared steel hammer head faced with deep blue enamel panels and gold filigree edging, a back spike, a long white-wrapped haft with gold bands, ceremonial and heavy, clearly a warhammer weapon, no text, large, diagonal',
    wornDesc: 'a blue-enamel and gold warhammer with a white-wrapped haft', lore: '' },
  { key: 'kingdom_duelist_smallsword', slot: 'weapon', nameKo: '한 뼘의 예절', region: '왕국', tone: '수수께끼',
    concept: '다이아 세공 손잡이의 결투용 스몰소드',
    art: 'a duelist smallsword — a very slender triangular blade with a small shell guard of chased silver, a grip wound in twisted silver wire set with tiny diamonds, elegant and precise, clearly a smallsword weapon, no text, large, diagonal',
    wornDesc: 'a very slender smallsword with a chased silver shell guard and wire grip', lore: '' },
  { key: 'swamp_bogsteel_falchion', slot: 'weapon', nameKo: '늪이 삼켰던 칼', region: '늪지대', tone: '수수께끼',
    concept: '녹청 슨 늪철 팔시온 — 이끼가 낀 날',
    art: 'a bog-steel falchion — a heavy single-edged blade of verdigris-green corroded steel with patches of moss and dried silt clinging to it, a rough wrapped grip with a bone pommel, grim and weathered, clearly a falchion sword weapon, no text, large, diagonal',
    wornDesc: 'a heavy verdigris falchion with moss clinging to the corroded blade', lore: '' },
  { key: 'swamp_lilypad_spear', slot: 'weapon', nameKo: '수련이 감은 창', region: '늪지대', tone: '아름다운',
    concept: '수련잎과 줄기가 감긴 녹빛 장창',
    art: 'a water-lily spear — a long spear with a leaf-shaped green-tinged blade, lily pads and coiling stems wrapping the upper shaft, a white lotus blooming just below the head, serene and wild, clearly a spear weapon, no text, large, diagonal',
    wornDesc: 'a long spear with a leaf-shaped blade and lily pads coiling the shaft', lore: '' },
  { key: 'swamp_witchlight_staff', slot: 'weapon', nameKo: '불빛을 따라오지 말 것', region: '늪지대', tone: '수수께끼',
    concept: '도깨비불이 맺힌 뒤틀린 나무 지팡이',
    art: 'a witchlight staff — a gnarled twisted bog-wood staff whose crooked top cradles a hovering pale green wisp flame, smaller wisps drifting around it, hanging moss and a bone charm, eerie and beautiful, clearly a staff weapon, no text, large, diagonal',
    wornDesc: 'a twisted bogwood staff cradling a pale green wisp flame', lore: '' },
  { key: 'swamp_serpent_whip', slot: 'weapon', nameKo: '물을 가르는 비늘', region: '늪지대', tone: '화려',
    concept: '늪뱀 비늘의 녹흑 채찍',
    art: 'a serpent-scale whip — a long segmented whip of dark green overlapping snake scales tapering to a fanged tip, an ornate bronze grip shaped like a snake head with amber eyes, sinuous and dangerous, clearly a whip weapon, no text, large, diagonal',
    wornDesc: 'a long dark-green scaled whip with a bronze snake-head grip', lore: '' },
  { key: 'swamp_toxin_shortbow', slot: 'weapon', nameKo: '시위에 맺힌 독', region: '늪지대', tone: '수수께끼',
    concept: '독액이 맺힌 늪나무 단궁',
    art: 'a toxin shortbow — a compact bow of dark swamp wood bound with green sinew, viscous poison beading along the string and dripping from the limb tips, small vials tied at the grip, sinister and practical, clearly a shortbow weapon, no text, large, diagonal',
    wornDesc: 'a dark swampwood shortbow with poison beading along the string', lore: '' },
  { key: 'volcano_obsidian_odachi', slot: 'weapon', nameKo: '유리로 벼린 큰칼', region: '화산', tone: '전설',
    concept: '붉은 균열이 흐르는 흑요석 오다치',
    art: 'an obsidian odachi — an enormous glassy black blade with glowing red magma cracks running through its depth, a charred wrapped hilt with an ember-lit tsuba, heat shimmer along the edge, imposing and volcanic, clearly a long sword weapon, no text, large, diagonal',
    wornDesc: 'an enormous black glass odachi with glowing red magma cracks', lore: '' },
  { key: 'volcano_magma_maul', slot: 'weapon', nameKo: '산이 내려친 자리', region: '화산', tone: '영웅담',
    concept: '현무암 덩어리를 얹은 용암 대망치',
    art: 'a magma maul — a huge rough basalt block hammer head veined with flowing orange lava, glowing chunks breaking loose at the edges, a thick iron-banded haft, brutal and elemental, clearly a maul weapon, no text, large, diagonal',
    wornDesc: 'a huge basalt maul head veined with flowing orange lava', lore: '' },
  { key: 'volcano_ashfall_scimitar', slot: 'weapon', nameKo: '재가 내린 뒤', region: '화산', tone: '수수께끼',
    concept: '잿빛 재가 흩날리는 회흑 시미터',
    art: 'an ashfall scimitar — a curved smoke-grey blade with a matte ashen finish, fine grey ash constantly sifting off its edge, a charcoal-black grip with a dull ember gem, desolate and elegant, clearly a scimitar sword weapon, no text, large, diagonal',
    wornDesc: 'a curved ash-grey scimitar shedding fine grey ash from its edge', lore: '' },
  { key: 'volcano_emberfang_daggers', slot: 'weapon', nameKo: '두 개의 불티', region: '화산', tone: '화려',
    concept: '잉걸이 박힌 흑철 쌍단검',
    art: 'a pair of ember-fang daggers — two short blackened fang-shaped blades with glowing orange ember veins along their spines, crossed in an X, wrapped grips with small ember beads, fierce and compact, clearly dagger weapons, no text, large, diagonal',
    wornDesc: 'two blackened fang daggers with glowing ember veins, crossed', lore: '' },
  { key: 'volcano_cinder_greataxe', slot: 'weapon', nameKo: '불티를 뿌리는 도끼', region: '화산', tone: '전설',
    concept: '불티가 날리는 진홍 대도끼',
    art: 'a cinder greataxe — a massive crescent axe head of dark iron glowing crimson along its cutting edge, sparks and cinders trailing off it, a long haft bound in scorched leather, mighty and blazing, clearly a greataxe weapon, no text, large, diagonal',
    wornDesc: 'a massive dark axe head glowing crimson with cinders trailing', lore: '' },
  { key: 'temple_snowlily_glaive', slot: 'weapon', nameKo: '눈 속에 핀 것', region: '신전', tone: '아름다운',
    concept: '설련이 새겨진 백은 글레이브',
    art: 'a snow-lily glaive — a long curved silver-white blade etched with a blooming lily motif, frost creeping along the etching, a pale birch shaft with a white silk cord, pure and cold, clearly a glaive polearm weapon, no text, large, diagonal',
    wornDesc: 'a curved silver-white glaive etched with a frost-covered lily motif', lore: '' },
  { key: 'temple_sanctus_mace', slot: 'weapon', nameKo: '기도가 굳은 무게', region: '신전', tone: '전설',
    concept: '스테인드글라스 보석을 문 백금 메이스',
    art: 'a sanctus mace — a white-gold flanged mace head holding a glowing stained-glass gem between its flanges, fine scripture-like engraving on the flanges, a white-wrapped haft, sacred and weighty, clearly a mace weapon, no text, large, diagonal',
    wornDesc: 'a white-gold mace holding a glowing stained-glass gem', lore: '' },
  { key: 'temple_frostbell_flail', slot: 'weapon', nameKo: '울리면 얼어붙는다', region: '신전', tone: '수수께끼',
    concept: '서리 맺힌 은종의 플레일',
    art: 'a frost-bell flail — a silver temple bell head rimed with frost hanging from a short chain on a pale shaft, tiny icicles along the bell rim, a soft ringing shimmer, solemn and chilling, clearly a flail weapon, no text, large, diagonal',
    wornDesc: 'a frost-rimed silver bell flail on a short chain', lore: '' },
  { key: 'temple_vow_greatsword', slot: 'weapon', nameKo: '서원의 무게', region: '신전', tone: '영웅담',
    concept: '백금 각인의 서원 대검',
    art: 'a vow greatsword — a broad white-gold blade with a pale blue fuller and delicate engraved patterns, a wide winged crossguard set with a clear crystal, soft holy light along the edge, resolute and radiant, clearly a greatsword weapon, no text, large, diagonal',
    wornDesc: 'a broad white-gold greatsword with a winged crossguard and crystal', lore: '' },
  { key: 'temple_icicle_longbow', slot: 'weapon', nameKo: '고드름을 당기다', region: '신전', tone: '아름다운',
    concept: '고드름이 자란 백은 장궁',
    art: 'an icicle longbow — a tall pale silver bow with clusters of clear icicles growing along its limbs, a shimmering frost-blue string, cold mist drifting from the grip, elegant and freezing, clearly a longbow weapon, no text, large, diagonal',
    wornDesc: 'a tall silver longbow with icicles growing along its limbs', lore: '' },
  { key: 'fallen_halo_chakram', slot: 'weapon', nameKo: '떨어진 고리', region: '타락천사', tone: '수수께끼',
    concept: '금이 간 후광을 벼린 차크람',
    art: 'a broken-halo chakram — a large golden ring blade cracked along one arc with dark feathers caught in the fracture, faint gold light bleeding from the crack, engraved feather patterns, tragic and sharp, clearly a chakram ring weapon, no text, large, diagonal',
    wornDesc: 'a cracked golden ring blade with dark feathers caught in the fracture', lore: '' },
  { key: 'fallen_blackfeather_rapier', slot: 'weapon', nameKo: '검은 깃의 예의', region: '타락천사', tone: '화려',
    concept: '검은 깃털 가드의 흑금 레이피어',
    art: 'a black-feather rapier — a slender dark blade with a guard formed of layered black metal feathers gilded at the tips, a single loose feather drifting free, a black wire grip, elegant and fallen, clearly a rapier sword weapon, no text, large, diagonal',
    wornDesc: 'a slender dark rapier with a guard of gilded black metal feathers', lore: '' },
  { key: 'fallen_pinion_twinblades', slot: 'weapon', nameKo: '한 쌍의 깃', region: '타락천사', tone: '전설',
    concept: '흰 깃·검은 깃의 쌍검',
    art: 'a pair of pinion twinblades — two curved wing-shaped blades crossed in an X, one white-gold with radiant feather etching and one jet-black with dark feather etching, matching hilts, dualistic and striking, clearly twin sword weapons, no text, large, diagonal',
    wornDesc: 'two crossed wing-shaped blades, one white-gold and one jet-black', lore: '' },
  { key: 'fallen_censer_flail', slot: 'weapon', nameKo: '향이 끊긴 자리', region: '타락천사', tone: '수수께끼',
    concept: '검은 연기가 새는 향로 플레일',
    art: 'a censer flail — an ornate pierced golden censer on a long chain, black smoke pouring from its vents and trailing behind, tarnished gold and soot streaks, ritual and ominous, clearly a chained flail weapon, no text, large, diagonal',
    wornDesc: 'an ornate golden censer flail trailing black smoke', lore: '' },
  { key: 'fallen_grace_greatbow', slot: 'weapon', nameKo: '반쯤 남은 은총', region: '타락천사', tone: '전설',
    concept: '한쪽은 금빛·한쪽은 흑빛인 대궁',
    art: 'a magnificent fallen grace greatbow — a tall elegant bow with a deep recurve, its upper limb sculpted as a radiant white-gold angel wing with layered luminous feathers, its lower limb as a charred jet-black wing with ragged dark feathers, an ornate gilded center grip with fine filigree and a single pale gem, a taut string of pale light, a few loose feathers drifting, majestic and tragic, no halo, no ring, clearly a longbow weapon, no text, large, diagonal',
    wornDesc: 'a tall bow with one radiant gold limb and one charred black limb', lore: '' },
  { key: 'orc_scrapiron_cleaver', slot: 'weapon', nameKo: '주워 모은 쇠', region: '오크 부락', tone: '영웅담',
    concept: '고철을 덧대 만든 거대 대도',
    art: 'a scrap-iron cleaver — a massive crude blade forged from mismatched riveted iron plates with uneven edges and rust patches, a haft bound in frayed leather and rope, savage and improvised, clearly a heavy cleaver weapon, no text, large, diagonal',
    wornDesc: 'a massive crude cleaver of riveted mismatched iron plates', lore: '' },
  { key: 'orc_bonecrush_maul', slot: 'weapon', nameKo: '한 번이면 충분해', region: '오크 부락', tone: '전설',
    concept: '거대 뼈머리를 얹은 대망치',
    art: 'a bone-crusher maul — an enormous hammer head made from a thick knotted beast skull-bone bound with iron straps and spikes, a heavy timber haft wrapped in hide, crushing and primal, clearly a maul weapon, no text, large, diagonal',
    wornDesc: 'an enormous bone maul head bound with iron straps and spikes', lore: '' },
  { key: 'orc_warhorn_axe', slot: 'weapon', nameKo: '뿔피리를 겸한 도끼', region: '오크 부락', tone: '화려',
    concept: '전투뿔을 자루에 단 흑철 도끼',
    art: 'a war-horn axe — a broad chipped black iron axe head with crimson war-paint stripes, a curved beast horn lashed along the haft as a signal horn, feathers and beads hanging, tribal and loud, clearly an axe weapon, no text, large, diagonal',
    wornDesc: 'a broad black axe with war-paint stripes and a horn lashed to the haft', lore: '' },
  { key: 'orc_hidebound_spear', slot: 'weapon', nameKo: '가죽으로 묶은 결의', region: '오크 부락', tone: '영웅담',
    concept: '가죽끈으로 감은 흑철 장창',
    art: 'a hide-bound spear — a long spear with a wide leaf-shaped iron head pitted from use, the shaft tightly wound in rough hide strips with bone rings and hanging fangs, rugged and ready, clearly a spear weapon, no text, large, diagonal',
    wornDesc: 'a long spear with a pitted iron head and hide-wrapped shaft', lore: '' },
  { key: 'orc_twinfang_daggers', slot: 'weapon', nameKo: '물어뜯는 두 개', region: '오크 부락', tone: '수수께끼',
    concept: '거수 엄니를 깎은 쌍단검',
    art: 'a pair of twin-fang daggers — two curved daggers carved from pale beast tusks with jagged edges, bound with sinew and crimson cord at the grips, crossed in an X, feral and quick, clearly dagger weapons, no text, large, diagonal',
    wornDesc: 'two curved tusk daggers bound with sinew, crossed', lore: '' },
];

export const ITEMS_V2: ItemV2[] = [...WEAPONS_90, ...ARMOR_90, ...ACCESSORIES_90, ...V4_ITEMS, ...V4_POOL30];

// 컨셉-온리 확정 방식(2026-06-27): art = "a <종류> — <역할·무드>"(외형묘사 X). buildArt가 슬롯별 품질 tail만 덧붙임.
// 자유를 줄수록 결과가 좋다(사용자 검증). 아바타가 일본 애니메 미소년/미소녀라 톤은 밝고 깔끔한 애니/JRPG.
const TAIL: Record<string, string> = {
  weapon: 'a beautiful clean fantasy anime RPG gacha-game weapon, bright and stylish, not gothic, a single isolated object on a plain flat empty background, large, pixel art',
  armor: 'a beautiful clean fantasy anime RPG gacha-game outfit, bright and stylish, not gothic, shown as the worn outfit on its own with no head and no neck, a slim full-length figure, a single isolated object on a plain flat empty background, pixel art',
  accessory: 'a beautiful clean fantasy anime RPG gacha-game item, bright and stylish, not gothic, a single isolated object on a plain flat empty background, pixel art',
};
export function buildArt(it: ItemV2): string {
  if (it.art.includes('pixel art')) return it.art; // 이미 완성된 프롬프트면 그대로
  return `${it.art}, ${TAIL[it.slot] ?? TAIL.accessory}`;
}
