// 새 90종 카탈로그(2026-06-27 재설계) — 검증된 미니멀 골격 + 밝은 애니/JRPG 미감.
// 6지역×5/슬롯 = 슬롯당 30. 지역색은 art 머리에 색·소재 한두 단어로만 가볍게(도배 금지).
// ⚠ buildArt는 art의 '첫 쉼표/대시 앞 머리'만 사용 → art는 쉼표 없이 한 구절로(형태+시그니처 다 살게).
//    wornDesc는 아바타 합성용이라 쉼표 OK.
// 무기 타입: 손에 쥐는 인상적 타입만(건틀릿·곤봉·차크람 금지), 총은 전체 ≤4, 두꺼운 타입 섞어 캔버스 채움.
import type { ItemV2 } from './items-v2';

export const WEAPONS_90: ItemV2[] = [
  // ── 왕국 · 무기(5) — 정제된 왕실, 재질 제각각 ───────────────────────────────
  { key: 'kingdom_winged_coronation_sword', slot: 'weapon', nameKo: '즉위의 깃', region: '왕국', tone: '영웅담', concept: '즉위식에 바쳐진 날개 가드의 의례 장검', art: 'a regal fantasy longsword with a golden winged crossguard and a sky-blue gem in the hilt', wornDesc: 'a gleaming longsword with a golden winged guard, a crown-shaped pommel and a sky-blue gem', lore: '' },
  { key: 'kingdom_ribbon_rapier', slot: 'weapon', nameKo: '푸른 매듭', region: '왕국', tone: '화려', concept: '결투를 즐기는 귀족의 리본 레이피어', art: 'a slender royal rapier with a swept silver guard and a trailing blue ribbon', wornDesc: 'a slim silver rapier with a swept ornate guard and a trailing blue ribbon', lore: '' },
  { key: 'kingdom_court_twin_sabers', slot: 'weapon', nameKo: '마주 든 한 쌍', region: '왕국', tone: '화려', concept: 'X자로 맞물리는 궁정 쌍곡검', art: 'a pair of slim curved court sabers crossed in an X with golden tasseled hilts', wornDesc: 'a pair of slim curved sabers with golden hilts and silk tassels, one per hand', lore: '' },
  { key: 'kingdom_falcon_cane_sword', slot: 'weapon', nameKo: '지팡이 속 한 줄', region: '왕국', tone: '수수께끼', concept: '매 머리 손잡이의 신사 지팡이검', art: 'an elegant gentlemans cane-sword with a polished dark shaft and a brass falcon-head handle', wornDesc: 'a polished dark cane with a brass falcon-head handle concealing a thin blade', lore: '' },

  // ── 신전 · 무기(5) — 서리/설산 ─────────────────────────────────────────────
  { key: 'temple_first_snow_musket', slot: 'weapon', nameKo: '첫눈을 겨눈 총신', region: '신전', tone: '영웅담', concept: '첫눈을 겨누는 설산 사냥꾼의 의식용 장총', art: 'an ornate antique fantasy flintlock musket — the long ceremonial hunting gun of a snow-temple hunter, a single long decorated barrel with an engraved wooden stock and frost-rune fittings, no telescopic scope, not a modern rifle, splendid frost-white and silver, a beautiful clean fantasy anime RPG gacha-game weapon, isolated object on a plain flat empty background, large, pixel art', wornDesc: 'a long white-silver hunting musket with frost-rune accents and fur trim, held one-handed at rest', lore: '' },
  { key: 'temple_glacier_lance', slot: 'weapon', nameKo: '빙하가 벼린 창', region: '신전', tone: '전설', concept: '빙하 속에서 자라난 크리스탈 랜스', art: 'a lance — the glacier-forged cavalry lance of a snow-temple knight, sacred and unbreakable', wornDesc: 'a tall crystalline ice lance with a frost-blue tip and a silver grip', lore: '' },
  { key: 'temple_runeblade_greatsword', slot: 'weapon', nameKo: '글자를 새긴 대검', region: '신전', tone: '영웅담', concept: '성스러운 룬을 새긴 설산 기사의 대검', art: 'a broad frost greatsword in silver and ice-blue with etched sacred runes along the blade', wornDesc: 'a broad silver-and-ice-blue greatsword with sacred runes etched along the blade', lore: '' },
  { key: 'temple_frost_odachi', slot: 'weapon', nameKo: '서리를 벼린 대도', region: '신전', tone: '아름다운', concept: '눈보라를 길게 가르는 날렵한 설산 대도', art: 'a long slender frost odachi greatsword with a pale ice-blue blade and a silver-wrapped hilt', wornDesc: 'a long slender frost odachi with a pale ice-blue blade and a silver-wrapped hilt', lore: '' },
  { key: 'temple_snowcrystal_staff', slot: 'weapon', nameKo: '여섯 갈래 눈꽃', region: '신전', tone: '희망', concept: '육각 눈꽃 결정을 인 은빛 지팡이', art: 'a tall silver staff topped with a six-sided snow-crystal and trailing ribbons', wornDesc: 'a tall silver staff topped with a six-sided snow crystal and trailing ribbons', lore: '' },

  // ── 오크 부락 · 무기(5) — 부족/뼈·청록·호박 ────────────────────────────────
  { key: 'orc_skypiercer_warbow', slot: 'weapon', nameKo: '하늘을 당기는 활', region: '오크 부락', tone: '영웅담', concept: '하늘을 겨누는 부족의 거대 전투활', art: 'a great tribal warbow of horn and sinew wrapped with teal cords and feather charms', wornDesc: 'a great tribal warbow of horn and sinew with teal cords and feather charms', lore: '' },
  { key: 'orc_festival_glaive', slot: 'weapon', nameKo: '축제의 언월', region: '오크 부락', tone: '화려', concept: '축제 전사무용수의 화려한 언월도', art: 'a tribal war-glaive — the festival glaive of an orc dancer-warrior, vivid and joyful, fierce yet splendid', wornDesc: 'a heavy curved blade of carved ivory tusk with a teal-wrapped grip', lore: '' },
  { key: 'orc_hunt_obsidian_spear', slot: 'weapon', nameKo: '사냥의 첫 걸음', region: '오크 부락', tone: '영웅담', concept: '흑요석 촉을 단 부족 사냥창', art: 'a long tribal hunting spear with a chipped obsidian head and feather streamers', wornDesc: 'a long tribal hunting spear with an obsidian head and feather streamers', lore: '' },

  // ── 화산 · 무기(5) — 흑요석/잿불금 ─────────────────────────────────────────
  { key: 'volcano_emberveined_greatsword', slot: 'weapon', nameKo: '잿불을 머금은 칼', region: '화산', tone: '전설', concept: '용암 혈맥이 흐르는 거대 흑요석 대검', art: 'a massive obsidian greatsword veined with ember-orange lava and a gold-edged blade', wornDesc: 'a massive obsidian greatsword veined with ember lava and a gold-edged blade', lore: '' },
  { key: 'volcano_dragonjaw_halberd', slot: 'weapon', nameKo: '용의 턱', region: '화산', tone: '영웅담', concept: '용의 머리를 본뜬 몰튼골드 할버드', art: 'a halberd — the dragon-jaw poleaxe of a volcano forge-knight, fierce yet splendid', wornDesc: 'a grand halberd with a molten-gold dragon-jaw axe head and a black haft', lore: '' },
  { key: 'volcano_emberline_katana', slot: 'weapon', nameKo: '한 줄의 불씨', region: '화산', tone: '아름다운', concept: '칼날에 한 줄 불씨가 흐르는 흑강 카타나', art: 'a sleek black katana with a single ember-orange edge-line and a gold tsuba', wornDesc: 'a sleek black katana with an ember-orange edge-line and a gold tsuba', lore: '' },
  { key: 'volcano_cinder_whipblade', slot: 'weapon', nameKo: '흩어지는 불티', region: '화산', tone: '화려', concept: '마디마디 불티가 튀는 흑강 채찍검', art: 'a segmented ember whip-blade of black steel linked with molten-gold joints', wornDesc: 'a segmented black-steel whip-blade linked with molten-gold joints and an ornate grip', lore: '' },
  { key: 'volcano_forgeheart_warhammer', slot: 'weapon', nameKo: '대장간의 심장', region: '화산', tone: '영웅담', concept: '용광로 심장을 박은 거대 워해머', art: 'a warhammer — the forge-heart maul of a volcano smith-warrior, molten and mighty', wornDesc: 'a great warhammer with a blocky obsidian head and a molten-gold ember core', lore: '' },

  // ── 늪지대 · 무기(5) — 요정 민트/핑크 ──────────────────────────────────────
  { key: 'swamp_blossom_rapier', slot: 'weapon', nameKo: '피어나는 한 송이', region: '늪지대', tone: '아름다운', concept: '꽃이 피어난 가드의 요정 레이피어', art: 'a rapier — the blooming fairy rapier of a swamp duelist, delicate and lovely', wornDesc: 'a slim fairy rapier with a blooming flower-shaped guard in mint and soft pink', lore: '' },
  { key: 'swamp_lotus_trident', slot: 'weapon', nameKo: '세 갈래 물줄기', region: '늪지대', tone: '아름다운', concept: '수련 줄기처럼 뻗은 세 갈래 요정 삼지창', art: 'an elegant fairy trident of living mint wood with three slender prongs and small water-lily blooms', wornDesc: 'an elegant mint-wood trident with three slender prongs and small water-lily blooms', lore: '' },
  { key: 'swamp_fireflylantern_staff', slot: 'weapon', nameKo: '반딧불을 품은 가지', region: '늪지대', tone: '희망', concept: '반딧불 등불을 인 버드나무 지팡이', art: 'a slim willow staff topped with a small firefly-gold lantern orb and leaf charms', wornDesc: 'a slim willow staff topped with a firefly-gold lantern orb and leaf charms', lore: '' },
  { key: 'swamp_lily_scythe', slot: 'weapon', nameKo: '수련을 베는 낫', region: '늪지대', tone: '수수께끼', concept: '수련잎을 닮은 곡선 날의 늪 낫', art: 'an elegant scythe with a curved teal lily-leaf blade and a vine-wrapped snath', wornDesc: 'an elegant scythe with a curved teal lily-leaf blade and a vine-wrapped snath', lore: '' },
  { key: 'swamp_dewdrop_twin_daggers', slot: 'weapon', nameKo: '이슬 두 방울', region: '늪지대', tone: '화려', concept: '이슬 보석을 박은 잎사귀 쌍단검', art: 'a pair of leaf-shaped fairy daggers with dewdrop gems and mint-green hilts', wornDesc: 'a pair of leaf-shaped daggers with dewdrop gems and mint-green hilts, one per hand', lore: '' },

  // ── 타락천사 · 무기(5) — 천상 백금(애니풍·고딕X) ──────────────────────────
  { key: 'angel_dawnlight_longsword', slot: 'weapon', nameKo: '여명의 빛줄기', region: '타락천사', tone: '영웅담', concept: '여명빛을 머금은 백금 장검', art: 'a longsword — the dawn-light blade of a celestial guardian, radiant and noble', wornDesc: 'a luminous white-and-gold longsword with a feather-etched guard', lore: '' },
  { key: 'angel_halo_glaive', slot: 'weapon', nameKo: '후광을 두른 날', region: '타락천사', tone: '전설', concept: '칼날 밑동에 금빛 후광 고리를 단 언월', art: 'a glaive — the haloed warglaive of a celestial knight, radiant and graceful', wornDesc: 'an elegant white glaive with a golden halo-ring at the base of the blade', lore: '' },
  { key: 'angel_featherfletch_bow', slot: 'weapon', nameKo: '깃을 단 활', region: '타락천사', tone: '아름다운', concept: '금빛 깃을 단 천상의 장궁', art: 'a graceful white longbow fledged with soft golden feathers along the limbs', wornDesc: 'a graceful white longbow with soft golden feather fletching', lore: '' },
  { key: 'angel_morningstar_spear', slot: 'weapon', nameKo: '새벽별 한 점', region: '타락천사', tone: '희망', concept: '끝에 새벽별을 박은 가는 천상 창', art: 'a spear — the morning-star lance of a celestial sentinel, radiant and noble', wornDesc: 'a slender white-and-gold spear tipped with a golden morning-star ornament', lore: '' },
  { key: 'angel_seraph_rapier', slot: 'weapon', nameKo: '세라프의 한 줄', region: '타락천사', tone: '화려', concept: '날개 가드와 옅은 청보석의 빛 레이피어', art: 'a shining slim rapier with a winged gold guard and a pale-blue gem', wornDesc: 'a shining slim rapier with a winged gold guard and a pale-blue gem', lore: '' },

  // ── 키퍼 신규 무기(확정 이미지) ───────────────────────────────────────────
  { key: 'kingdom_guard_warhammer', slot: 'weapon', nameKo: '근위의 망치', region: '왕국', tone: '영웅담', concept: '왕궁 근위대장의 의장 워해머', art: 'a warhammer — the ceremonial guard warhammer of the royal palace, regal and commanding', wornDesc: '', lore: '' },
  { key: 'kingdom_banner_spear', slot: 'weapon', nameKo: '왕실 깃발 창', region: '왕국', tone: '영웅담', concept: '왕실 깃발을 단 의장창', art: 'a royal banner spear', wornDesc: '', lore: '', keeper: true },
  { key: 'volcano_ember_scythe', slot: 'weapon', nameKo: '잿불을 거두는 낫', region: '화산', tone: '수수께끼', concept: '불꽃이 이는 화산 대낫', art: 'a flaming scythe', wornDesc: '', lore: '', keeper: true },
  { key: 'angel_star_wand', slot: 'weapon', nameKo: '별을 인 지팡이', region: '타락천사', tone: '화려', concept: '날개 단 금빛 별 지팡이', art: 'a winged star wand', wornDesc: '', lore: '', keeper: true },
];

// 방어구 30 — 머리/투구 없는 '입은 옷'(buildArt가 강제). 풀판금 금지·경갑은 스커트 달린 경장.
// 밝은 톤 위주로 무기의 무거움 보정 + 코스튬(기모노·야회복·무희)·캐주얼(교복·니트·후드티) 혼합.
export const ARMOR_90: ItemV2[] = [
  // ── 왕국 · 방어구(5) ───────────────────────────────────────────────────────
  { key: 'kingdom_moonwaltz_gown', slot: 'armor', nameKo: '회전하는 달빛', region: '왕국', tone: '아름다운', concept: '무도회에서 도는 춤꾼의 가볍고 산뜻한 무도복', art: 'an elegant court ballgown with a fitted bodice and a flowing lilac-and-silver layered skirt', wornDesc: 'an elegant lilac-and-silver ballgown with a fitted bodice and a flowing layered skirt', lore: '' },
  { key: 'kingdom_academy_uniform', slot: 'armor', nameKo: '왕립 학원의 아침', region: '왕국', tone: '희망', concept: '왕립 학원 학생의 단정한 제복', art: 'a smart royal academy uniform with a tailored navy coat gold buttons and a pleated skirt', wornDesc: 'a smart navy academy uniform with a tailored gold-buttoned coat and a pleated skirt', lore: '' },
  { key: 'kingdom_masquerade_suit', slot: 'armor', nameKo: '가면 무도의 밤', region: '왕국', tone: '화려', concept: '가면무도회 귀족의 슬림 야회복', art: 'a sleek black-and-gold masquerade evening suit with a crimson damask sash', wornDesc: 'a sleek black-and-gold evening suit with a crimson damask sash and brocade lapels', lore: '' },

  // ── 신전 · 방어구(5) ───────────────────────────────────────────────────────
  { key: 'temple_breathwoven_vestment', slot: 'armor', nameKo: '입김으로 짠 예복', region: '신전', tone: '화려', concept: '프로스트 프리스티스의 룬 자수 예복', art: 'a sacred vestment — the rune-woven robe of a frost-temple priestess, serene and luminous', wornDesc: 'a flowing white-and-gold vestment with rune embroidery and silver-trimmed sleeves', lore: '' },
  { key: 'temple_firstsnow_furdress', slot: 'armor', nameKo: '첫눈을 덮은 털옷', region: '신전', tone: '희망', concept: '눈 내린 아침의 포근한 털안감 겨울 드레스', art: 'a cozy fur-lined wool winter dress in cream and soft blue with a fur-trimmed hood and a fluffy white scarf', wornDesc: 'a cozy cream-and-blue fur-lined wool winter dress with a fur-trimmed hood and a fluffy scarf', lore: '' },
  { key: 'temple_runeguard_armor', slot: 'armor', nameKo: '글자를 새긴 경갑', region: '신전', tone: '전설', concept: '룬을 새긴 설산 기사의 은빛 경장갑', art: 'slim silver-and-ice-blue rune light armor with a short tasset skirt and etched sacred glyphs', wornDesc: 'slim silver-and-ice-blue rune light armor with a short tasset skirt and etched glyphs', lore: '' },
  { key: 'temple_aurora_gown', slot: 'armor', nameKo: '새벽빛 자락', region: '신전', tone: '아름다운', concept: '오로라빛이 흐르는 흰 드레스', art: 'an aurora gown — the shimmering dress of a winter temple oracle, serene and lovely', wornDesc: 'an elegant white gown with a flowing layered skirt and a pale-blue shimmer', lore: '' },
  { key: 'temple_frostguard_garb', slot: 'armor', nameKo: '설산 파수꾼', region: '신전', tone: '수수께끼', concept: '설산 성소를 지키는 파수꾼의 단정한 무장', art: 'a guardian garb — the frost-guard outfit of a snow-temple sentinel, disciplined and noble', wornDesc: 'a long ice-blue ranger coat with a cinched belt, leather straps and a fur half-cape', lore: '' },

  // ── 오크 부락 · 방어구(5) ─────────────────────────────────────────────────
  { key: 'orc_featherdance_dress', slot: 'armor', nameKo: '여명빛 깃털무희', region: '오크 부락', tone: '아름다운', concept: '새벽빛 구슬이 흔들리는 깃털 무희옷', art: 'a vibrant amber-and-teal feather dance dress over a fitted beaded bodice', wornDesc: 'a vibrant amber-and-teal feather dance dress over a fitted beaded bodice', lore: '' },
  { key: 'orc_beadwarrior_garb', slot: 'armor', nameKo: '불씨 엮은 전사복', region: '오크 부락', tone: '영웅담', concept: '잔불 구슬을 엮은 축제 전사의 가죽옷', art: 'a fitted tan-hide warrior outfit with amber beadwork fur trim and feather shoulder cords', wornDesc: 'a fitted tan-hide warrior outfit with amber beadwork, fur trim and feather shoulder cords', lore: '' },
  { key: 'orc_skyfeather_mantle', slot: 'armor', nameKo: '하늘깃 부족장', region: '오크 부락', tone: '전설', concept: '청록 깃털이 흐르는 부족장의 망토 복장', art: 'white bone-laced robes under a flowing teal-feather mantle with gold totem clasps', wornDesc: 'white bone-laced robes under a flowing teal-feather mantle with gold totem clasps', lore: '' },

  // ── 화산 · 방어구(5) ───────────────────────────────────────────────────────
  { key: 'volcano_emberpriest_dress', slot: 'armor', nameKo: '잿불맥동', region: '화산', tone: '아름다운', concept: '용암 혈맥이 흐르는 불꽃 사제의 흉갑드레스', art: 'a cuirass dress — the ember-priestess attire of a volcano shrine, fierce and elegant', wornDesc: 'an obsidian bodice dress with ember-orange vein patterns flaring into a gold-trimmed skirt', lore: '' },
  { key: 'volcano_ronin_garb', slot: 'armor', nameKo: '잿불 무사', region: '화산', tone: '희망', concept: '화산을 떠도는 불의 무사의 거친 한 벌', art: 'a wanderer garb — the ember-ronin outfit of a volcano swordsman, bold and rugged', wornDesc: 'a long obsidian-black coat with molten-gold embroidery and an ember-orange sash', lore: '' },
  { key: 'volcano_dragonscale_armor', slot: 'armor', nameKo: '흑룡비늘 경갑', region: '화산', tone: '전설', concept: '흑요석 비늘을 엮은 용기사의 슬림 경갑', art: 'slim layered obsidian dragon-scale armor edged in molten gold with a long scaled skirt', wornDesc: 'slim layered obsidian dragon-scale armor edged in molten gold with a long scaled skirt', lore: '' },
  { key: 'volcano_embersilk_dress', slot: 'armor', nameKo: '불티를 두른 실크', region: '화산', tone: '화려', concept: '잿불 무늬가 흐르는 흑색 실크 드레스', art: 'an ember-silk dress — the flame-shrine gown of a volcano priestess, elegant and fierce', wornDesc: 'a flowing black ember-silk dress with molten-gold flame patterns and a red-and-gold sash', lore: '' },
  { key: 'volcano_rider_coat', slot: 'armor', nameKo: '용을 탄 자의 가죽코트', region: '화산', tone: '영웅담', concept: '하늘 용기수의 단정한 가죽 롱코트', art: 'a fitted black dragon-rider leather longcoat with molten-gold buckles ember stitching and a high collar', wornDesc: 'a fitted black dragon-rider leather longcoat with molten-gold buckles, ember stitching and a high collar', lore: '' },

  // ── 늪지대 · 방어구(5) ─────────────────────────────────────────────────────
  { key: 'swamp_petal_fairy_dress', slot: 'armor', nameKo: '요정의 첫 꽃잎', region: '늪지대', tone: '아름다운', concept: '어린 늪요정의 첫 비행 꽃잎 드레스', art: 'a petal dress — the first-flight gown of a young bog-fairy woven from dawn flower petals, light and joyful', wornDesc: 'a layered pastel-pink-and-mint petal fairy dress with sheer gossamer wings', lore: '' },
  { key: 'swamp_lotus_dress', slot: 'armor', nameKo: '수련을 두른 사람', region: '늪지대', tone: '아름다운', concept: '수련을 두른 늪 소녀의 산뜻한 드레스', art: 'a lotus dress — the bloom-gown of a swamp lily maiden, fresh and lovely', wornDesc: 'a short layered teal witch dress with a soft knit shawl and a little star-charm belt', lore: '' },
  { key: 'swamp_warden_garb', slot: 'armor', nameKo: '이끼 파수꾼', region: '늪지대', tone: '수수께끼', concept: '이끼와 잎비늘로 짠 늪 파수꾼의 후드 복장', art: 'a hooded swamp-warden outfit of mossy leaf-scale tunic with a layered cloak and bound trousers', wornDesc: 'a hooded mossy leaf-scale warden tunic with a layered cloak and bound trousers', lore: '' },
  { key: 'swamp_mushroom_robe', slot: 'armor', nameKo: '갓 쓴 아이', region: '늪지대', tone: '희망', concept: '둥근 버섯 갓을 후드처럼 두른 작은 약초사의 로브', art: 'a long soft robe with a rosy mushroom-cap hood and a soft pink dotted hem', wornDesc: 'a long soft robe with a rosy mushroom-cap hood and a soft pink dotted hem', lore: '' },
  { key: 'swamp_lampkeeper_coat', slot: 'armor', nameKo: '반딧불 등지기', region: '늪지대', tone: '희망', concept: '반딧불 등불을 든 밤 등지기의 긴 외투', art: 'a long teal night-lampkeeper coat with firefly-gold lantern trims and a high collar', wornDesc: 'a long teal lampkeeper coat with firefly-gold lantern trims and a high collar', lore: '' },

  // ── 타락천사 · 방어구(5) ─────────────────────────────────────────────────
  { key: 'angel_radiant_gown', slot: 'armor', nameKo: '햇살을 두른 예복', region: '타락천사', tone: '화려', concept: '금실 광선이 흐르는 천상 무희의 예복', art: 'a flowing white-and-gold radiant gown with golden ray patterns and a feathered hem', wornDesc: 'a flowing white-and-gold radiant gown with golden ray patterns and a feathered hem', lore: '' },
  { key: 'angel_starprince_garb', slot: 'armor', nameKo: '별을 두른 사람', region: '타락천사', tone: '아름다운', concept: '별자리 자수를 두른 천상 왕자의 단정한 복장', art: 'a celestial prince outfit of white and gold with a star-embroidered tunic a sash and tailored trousers', wornDesc: 'a white-and-gold celestial prince tunic with star embroidery, a sash and tailored trousers', lore: '' },
  { key: 'angel_seraphguard_armor', slot: 'armor', nameKo: '수호의 백은 경갑', region: '타락천사', tone: '영웅담', concept: '작은 날개를 단 천상 기사의 백은 경갑', art: 'holy light armor — the winged guard-plate of a celestial knight, slim and radiant', wornDesc: 'slim white-silver holy light armor with small back wings, feather-etched pauldrons and a short skirt', lore: '' },
  { key: 'angel_cherub_outing', slot: 'armor', nameKo: '어린 천사의 나들이', region: '타락천사', tone: '희망', concept: '작은 날개와 리본을 단 케루빔의 나들이옷', art: 'a cute white-and-gold winged outfit with tiny wings ribbon sashes and a short skirt', wornDesc: 'a cute white-and-gold winged outfit with tiny wings, ribbon sashes and a short skirt', lore: '' },
  { key: 'angel_lightpriest_vestment', slot: 'armor', nameKo: '빛을 섬기는 사제복', region: '타락천사', tone: '전설', concept: '금빛 띠와 작은 후광 장식의 빛 사제 제의', art: 'a white-and-blue light-priest vestment with golden trim and a small halo motif', wornDesc: 'a white-and-blue light-priest vestment with golden trim and a small halo motif', lore: '' },

  // ── 키퍼 신규 방어구(확정 이미지) ─────────────────────────────────────────
  { key: 'kingdom_goldknight_plate', slot: 'armor', nameKo: '황금 기사 갑주', region: '왕국', tone: '영웅담', concept: '금·심홍 자락의 백기사 판금', art: 'a gold-and-crimson knight plate', wornDesc: '', lore: '', keeper: true },
  { key: 'kingdom_azure_outfit', slot: 'armor', nameKo: '푸른 기사의 한 벌', region: '왕국', tone: '화려', concept: '청백·금 망토의 마법기사 복장', art: 'a blue-and-white knight outfit', wornDesc: '', lore: '', keeper: true },
];

// 장신구 30 — 종류 다양화(안경류·머리장식·가방·시계·책·부채·악기·구슬·가면·목걸이·부적 등).
// 머리/얼굴·휴대·착용 골고루(빈손 불필요). 'glow/glowing'은 강화 글로우와 충돌하니 색으로만.
export const ACCESSORIES_90: ItemV2[] = [
  // ── 왕국 · 장신구(5) — 존재감 위주(머리·휴대·동행) ─────────────────────────
  { key: 'kingdom_plumed_hat', slot: 'accessory', nameKo: '깃을 꽂은 모자', region: '왕국', tone: '화려', concept: '깃털을 꽂은 귀족의 챙 넓은 모자', art: 'a dashing wide-brimmed royal hat with a sweeping ostrich plume and a gold band', wornDesc: 'a dashing wide-brimmed royal hat with a sweeping ostrich plume and a gold band', lore: '' },
  { key: 'kingdom_opera_parasol', slot: 'accessory', nameKo: '오페라의 양산', region: '왕국', tone: '아름다운', concept: '오페라 가는 귀부인의 큰 레이스 양산', art: 'an elegant large lace opera parasol in ivory and gold with a ribboned handle', wornDesc: 'an elegant large ivory-and-gold lace parasol with a ribboned handle', lore: '' },
  { key: 'kingdom_court_lyre', slot: 'accessory', nameKo: '궁정의 수금', region: '왕국', tone: '희망', concept: '궁정 음유시인의 황금 수금', art: 'an elegant golden court lyre strung with silver and wound with a blue ribbon', wornDesc: 'an elegant golden court lyre strung with silver and wound with a blue ribbon', lore: '' },
  { key: 'kingdom_herald_banner', slot: 'accessory', nameKo: '선포하는 깃발', region: '왕국', tone: '영웅담', concept: '전령관의 그리핀 문장 손깃발', art: 'a handheld royal heraldic banner of crimson and gold with a griffin crest on a gilded pole', wornDesc: 'a handheld crimson-and-gold heraldic banner with a griffin crest on a gilded pole', lore: '' },

  // ── 신전 · 장신구(5) ───────────────────────────────────────────────────────
  { key: 'temple_snowflake_crown', slot: 'accessory', nameKo: '눈꽃의 관', region: '신전', tone: '아름다운', concept: '큰 육각 눈꽃을 세운 은빛 왕관', art: 'a radiant silver crown shaped from large six-sided snowflake crystals', wornDesc: 'a radiant silver crown shaped from large six-sided snowflake crystals', lore: '' },
  { key: 'temple_fur_stole', slot: 'accessory', nameKo: '흰 털 목도리', region: '신전', tone: '희망', concept: '어깨를 감싸는 포근한 흰 털 목도리', art: 'a fur stole — a winter temple\'s cozy white shoulder wrap, soft and luxurious', wornDesc: 'a luxurious fluffy white fur stole with frost-blue ribbon ties and silver clasps', lore: '' },
  { key: 'temple_hunting_horn', slot: 'accessory', nameKo: '설산의 뿔피리', region: '신전', tone: '영웅담', concept: '어깨에 메는 큰 은장식 뿔피리', art: 'a large ornate silver-banded hunting horn with frost-rune engravings worn on a fur strap', wornDesc: 'a large ornate silver-banded hunting horn with frost-rune engravings on a fur strap', lore: '' },
  { key: 'temple_prayer_lantern', slot: 'accessory', nameKo: '기도의 등불', region: '신전', tone: '전설', concept: '지팡이 끝에 단 서리 기도 등불', art: 'a lantern on a staff — the frost prayer-lantern of a snow temple, serene and luminous', wornDesc: 'a tall silver prayer-lantern on a slender staff holding a pale-blue frost crystal', lore: '' },
  { key: 'temple_fur_hat', slot: 'accessory', nameKo: '눈밭의 털모자', region: '신전', tone: '희망', concept: '귀를 덮는 포근한 설산 털모자', art: 'a cozy oversized fur hat with ear-flaps in cream and soft blue with a snowflake pin', wornDesc: 'a cozy oversized cream-and-blue fur hat with ear-flaps and a snowflake pin', lore: '' },

  // ── 오크 부락 · 장신구(5) ─────────────────────────────────────────────────
  { key: 'orc_festival_mask', slot: 'accessory', nameKo: '웃는 축제 가면', region: '오크 부락', tone: '화려', concept: '활짝 웃는 큰 채색 목각 가면', art: 'a large colorful carved wooden tribal festival mask with a wide smile teal paint and tall feathers', wornDesc: 'a large colorful carved wooden festival mask with a wide smile, teal paint and tall feathers', lore: '' },
  { key: 'orc_war_horn', slot: 'accessory', nameKo: '부족의 뿔나팔', region: '오크 부락', tone: '전설', concept: '옆구리에 멘 부족의 큰 전투 뿔나팔', art: 'a war horn — the great curved battle-horn of an orc festival, bone bound with feathers, slung at the side', wornDesc: 'a grand towering tribal headdress of sweeping teal and amber feathers with bone clasps', lore: '' },
  { key: 'orc_totem_charmstaff', slot: 'accessory', nameKo: '토템 부적 지팡이', region: '오크 부락', tone: '수수께끼', concept: '가면과 깃을 단 부족 토템 지팡이', art: 'a tall tribal totem charm-staff topped with a carved teal mask and dangling feathers and bones', wornDesc: 'a tall tribal totem charm-staff topped with a carved teal mask and dangling feathers and bones', lore: '' },

  // ── 화산 · 장신구(5) ───────────────────────────────────────────────────────
  { key: 'volcano_dragonhorn_circlet', slot: 'accessory', nameKo: '용뿔 서클릿', region: '화산', tone: '화려', concept: '용의 뿔을 본뜬 흑금 서클릿', art: 'a circlet — the dragon-horn diadem of a volcano champion, bold and regal', wornDesc: 'a striking black-and-gold dragon-horn circlet set with ember-orange gems', lore: '' },
  { key: 'volcano_dragonscale_satchel', slot: 'accessory', nameKo: '용비늘 봇짐', region: '화산', tone: '화려', concept: '비스듬히 메는 흑요석 비늘 크로스백', art: 'a large black dragon-scale leather satchel with molten-gold buckles worn across the body on a braided strap', wornDesc: 'a large black dragon-scale leather satchel with molten-gold buckles worn across the body', lore: '' },
  { key: 'volcano_obsidian_warfan', slot: 'accessory', nameKo: '흑요석 군선', region: '화산', tone: '전설', concept: '흑요석 살을 펼친 큰 전쟁 부채', art: 'a large black-and-gold war-fan with obsidian ribs and ember-orange edges', wornDesc: 'a large black-and-gold war-fan with obsidian ribs and ember-orange edges', lore: '' },
  { key: 'volcano_forge_lantern', slot: 'accessory', nameKo: '꺼지지 않는 등불', region: '화산', tone: '영웅담', concept: '사슬에 매단 잿불 단조 등불', art: 'a lantern — the ever-burning forge lantern of a volcano smith on a chain, warm and bold', wornDesc: 'an iron forge-lantern on a chain holding ember-orange embers with obsidian framing', lore: '' },
  { key: 'volcano_ashrelic_tome', slot: 'accessory', nameKo: '잿빛 비책', region: '화산', tone: '수수께끼', concept: '펼쳐 든 큰 잿빛 마도서', art: 'an open grimoire — the ash-sage spellbook of the volcano, arcane and bold', wornDesc: 'a large thick ash-grey leather grimoire with molten-gold sigils and a brass clasp', lore: '' },

  // ── 늪지대 · 장신구(5) ─────────────────────────────────────────────────────
  { key: 'swamp_lily_crown', slot: 'accessory', nameKo: '수련 꽃관', region: '늪지대', tone: '아름다운', concept: '큼직한 분홍 수련 머리 꽃관', art: 'a lush flower crown woven of large pink water-lilies and green leaves', wornDesc: 'a lush flower crown woven of large pink water-lilies and green leaves', lore: '' },
  { key: 'swamp_mushroom_hat', slot: 'accessory', nameKo: '버섯 모자', region: '늪지대', tone: '희망', concept: '둥근 분홍 버섯 갓 모자', art: 'a hat — the oversized mushroom-cap hat of a swamp herbalist, cute and cozy', wornDesc: 'a cute oversized rosy mushroom-cap hat with soft white spots', lore: '' },
  { key: 'swamp_flower_basket', slot: 'accessory', nameKo: '꽃바구니', region: '늪지대', tone: '화려', concept: '늪 꽃이 가득한 엮은 꽃바구니', art: 'a charming woven basket overflowing with pink lilies mint ferns and dangling vines', wornDesc: 'a charming woven basket overflowing with pink lilies, mint ferns and dangling vines', lore: '' },
  { key: 'swamp_firefly_jar', slot: 'accessory', nameKo: '반딧불 병', region: '늪지대', tone: '희망', concept: '반딧불을 담은 유리병 등불', art: 'a jar lantern — a swamp child\'s jar of fireflies, charming and warm', wornDesc: 'a charming glass jar lantern filled with tiny golden fireflies and a cork lid', lore: '' },
  { key: 'swamp_lilypad_parasol', slot: 'accessory', nameKo: '연잎 양산', region: '늪지대', tone: '수수께끼', concept: '큰 연잎을 펼친 듯한 양산', art: 'a whimsical parasol made from a large green lily-pad with a dewdrop-beaded rim', wornDesc: 'a whimsical green lily-pad parasol with a dewdrop-beaded rim', lore: '' },

  // ── 타락천사 · 장신구(5) ─────────────────────────────────────────────────
  { key: 'angel_glide_wings', slot: 'accessory', nameKo: '깃든 날개', region: '타락천사', tone: '화려', concept: '등에 다는 작고 우아한 깃털 날개', art: 'a pair of small feathered angel wings — delicate white-and-gold wings worn at the back, light and radiant', wornDesc: 'a radiant white-gold tiara crowned with a large golden star and pale gems', lore: '' },
  { key: 'angel_feather_fan', slot: 'accessory', nameKo: '바람을 부르는 깃부채', region: '타락천사', tone: '아름다운', concept: '흰 깃을 크게 펼친 부채', art: 'an elegant large folding fan spread with soft white feathers and a gold-pearl rivet', wornDesc: 'an elegant large folding fan spread with soft white feathers and a gold-pearl rivet', lore: '' },
  { key: 'angel_golden_censer', slot: 'accessory', nameKo: '흔들리는 향로', region: '타락천사', tone: '희망', concept: '긴 사슬에 매달려 흔들리는 황금 향로', art: 'an ornate golden censer on long chains trailing soft incense smoke', wornDesc: 'an ornate golden censer on long chains trailing soft incense smoke', lore: '' },
  { key: 'angel_halo', slot: 'accessory', nameKo: '머리 위 후광', region: '타락천사', tone: '전설', concept: '머리 위에 떠오른 금빛 후광', art: 'a luminous floating golden halo ring hovering above with a faint feather motif', wornDesc: 'a luminous golden halo ring hovering above the head with a faint feather motif', lore: '' },
  // ── 키퍼 신규 장신구(확정 이미지) — 별 셉터는 무기로 이동(angel_star_wand) ──
  { key: 'kingdom_court_fan', slot: 'accessory', nameKo: '봉황 부채', region: '왕국', tone: '화려', concept: '크림슨·금 봉황 궁정 접부채', art: 'a crimson-and-gold phoenix court fan', wornDesc: '', lore: '', keeper: true },
];
