// 신규 120종 아바타-코디 카탈로그 작업 데이터(docs/ITEMS.md). 배치 단위로 채워 나간다.
// 워크플로: ①컨셉·이름·프롬프트 검수 → ②이미지(객체) 생성·검수 → ③이미지 보고 로어 작성.
// 프롬프트 원칙(memory pixellab-item-prompt-balance):
//   - 최대한 디테일·특색(아이템마다 애정 생기게). 형태/구성 디테일 자세히.
//   - 지역이 왕국이어도 '로열+보석'으로 도배 금지 — 아이템마다 재질·역할·캐릭터를 제각각.
//     보석은 그게 진짜 컨셉인 것만. 화려함은 다양한 장인적 재질(강철·실크·라커·호두나무·은각인 등)로.
//   - 무기: large·diagonal·clean/straight(가드는 칼날에 수직), 두꺼운 타입 적극.
export type ItemV2 = {
  key: string;
  slot: 'weapon' | 'armor' | 'accessory';
  nameKo: string;
  region: string;
  tone: string;
  concept: string;
  art: string; // 컨셉-온리 프롬프트 조각 "a <종류> — <역할·무드>"(외형묘사 X). buildArt가 품질 tail을 덧붙임.
  wornDesc: string;
  lore: string;
  keeper?: boolean; // 사용자가 고른 확정 이미지(생성 스킵·잠금)
};

import { EXTRA_ITEMS } from './items-extra';
import { WEAPONS_90, ARMOR_90, ACCESSORIES_90 } from './items90';

const INLINE_ITEMS: ItemV2[] = [
  // ── 왕국 · 무기 (10) · 아이템마다 다른 재질·캐릭터 ───────────────────────────
  {
    key: 'kingdom_ribbon_rapier',
    slot: 'weapon',
    nameKo: '푸른 매듭',
    region: '왕국',
    tone: '화려',
    concept: '파란 실크 리본의 결투용 레이피어',
    art: 'an ornate royal rapier with a flowing ribbon, elegant and splendid, large, pixel art',
    wornDesc: 'a slim golden rapier with an ornate guard and a trailing blue ribbon',
    lore: '',
  },
  {
    key: 'kingdom_coronation_greatsword',
    slot: 'weapon',
    nameKo: '왕관의 무게',
    region: '왕국',
    tone: '영웅담',
    concept: '크라운 폼멜의 묵직한 강철 대검',
    art: 'a grand ornate royal two-handed greatsword, majestic and splendid, premium game-art, isolated object, plain background, large, pixel art',
    wornDesc: 'a magnificent heroic greatsword with a broad gleaming steel blade and a golden crown-shaped pommel, rested over one shoulder',
    lore: '',
  },
  {
    key: 'kingdom_court_twinblades',
    slot: 'weapon',
    nameKo: '마주 든 한 쌍',
    region: '왕국',
    tone: '화려',
    concept: 'X자 교차·자개 라커 손잡이 쌍곡검',
    art: 'two slim curved court sabers crossed in a big X shape, black lacquered hilts inlaid with mother-of-pearl and hanging silk tassels, lavishly ornate in a fantasy anime style, graceful and exotic, isolated object, plain background, large, pixel art',
    wornDesc: 'a pair of slim curved sabers with black lacquered, pearl-inlaid hilts, one per hand',
    lore: '',
  },
  {
    key: 'kingdom_coronation_spear',
    slot: 'weapon',
    nameKo: '즉위를 알린 창',
    region: '왕국',
    tone: '영웅담',
    concept: '긴 물푸레 자루에 왕실 깃발 단 의장창',
    art: 'a very long slender processional spear, a tall finely polished shaft with gold fittings, a gleaming steel head, a rich royal banner streaming from below the blade, ceremonial and majestic, full length, pixel art',
    wornDesc: 'a long processional spear with a pale wooden shaft, a steel head and a royal banner below the blade',
    lore: '',
  },
  {
    key: 'kingdom_jewel_longsword',
    slot: 'weapon',
    nameKo: '보석을 삼킨 날',
    region: '왕국',
    tone: '화려',
    concept: '자수정이 박힌 넓은 의장 장검(보석이 컨셉)',
    art: 'a magnificent fantasy longsword, a broad ornate blade set with a glittering row of amethyst gems, an elaborate gilded guard and a large amethyst gem pommel, lavishly jeweled in a fantasy anime JRPG style, gorgeous and splendid, clean and straight with the guard perpendicular to the blade, large, pixel art',
    wornDesc: 'a broad longsword with a row of amethyst gems along the blade and a gilded hilt',
    lore: '',
  },
  {
    key: 'kingdom_guard_halberd',
    slot: 'weapon',
    nameKo: '문 앞의 맹세',
    region: '왕국',
    tone: '영웅담',
    concept: '왕실 정문을 지키는 화려한 의장 할버드',
    art: 'a magnificent fantasy royal halberd, a long ornate shaft with a large gold-engraved axe blade and a spike, lavishly ornate in a fantasy anime style, splendid and grand, isolated object, plain background, full length, pixel art',
    wornDesc: 'an ornate royal halberd with a long shaft and a large gold-engraved axe blade',
    lore: '',
  },
  {
    key: 'kingdom_cane_sword',
    slot: 'weapon',
    nameKo: '지팡이 속 한 줄',
    region: '왕국',
    tone: '수수께끼',
    concept: '호두나무·놋쇠 손잡이 지팡이검',
    art: "an exquisite fantasy gentleman's cane, lustrous dark wood with elaborate gold scrollwork and a jeweled bird-head handle, concealing a thin hidden blade, luxurious in a fantasy anime style, refined and splendid, large, pixel art",
    wornDesc: 'a polished dark-walnut cane with a brass bird-head handle that conceals a thin blade',
    lore: '',
  },
  {
    key: 'kingdom_duel_pistol',
    slot: 'weapon',
    nameKo: '정중한 한 발',
    region: '왕국',
    tone: '화려',
    concept: '은각인 호두나무 플린트락 결투 권총',
    art: 'an exquisite flintlock dueling pistol, a fine dark walnut stock with chased silver scrollwork and gold inlay, a long engraved barrel, refined and elegant, large, pixel art',
    wornDesc: 'an antique flintlock dueling pistol with a dark walnut stock and chased silver scrollwork',
    lore: '',
  },
  {
    key: 'kingdom_scepter_mace',
    slot: 'weapon',
    nameKo: '보석을 인 홀',
    region: '왕국',
    tone: '전설',
    concept: '거대한 루비가 얹힌 황금 왕홀(보석이 컨셉)',
    art: 'a golden royal scepter-mace crowned with one enormous ruby, ornate gold flanges, lavishly regal and gorgeous, large, pixel art',
    wornDesc: 'an ornate golden scepter-mace topped with one enormous ruby',
    lore: '',
  },
  {
    key: 'kingdom_ribbon_whip',
    slot: 'weapon',
    nameKo: '풀린 리본의 춤',
    region: '왕국',
    tone: '아름다운',
    concept: '강철 비늘 박힌 크림슨 실크 리본 채찍',
    art: 'a long flowing ribbon-whip of crimson silk lined with tiny steel scales, an ornate grip, graceful and beautiful, large, pixel art',
    wornDesc: 'a long crimson silk ribbon-whip lined with tiny steel scales and an ornate grip',
    lore: '',
  },

  // ── 새 방식(종류+컨셉+스타일) 테스트 — 신전·늪지 ──────────────────────────
  {
    key: 'temple_frostvein_rifle',
    slot: 'weapon',
    nameKo: '첫눈을 겨눈 총신',
    region: '신전',
    tone: '영웅담',
    concept: '성스러운 설산 사냥꾼의 의식용 장총',
    art: 'a long fantasy flintlock musket (a snow-temple hunter who aims at the first snowfall) — a splendid, gorgeous, lavishly detailed premium visual pixel-art game item, dazzling frost-touched fantasy game art, no telescopic scope, isolated object, plain background, large, pixel art',
    wornDesc: 'a long ornate hunting rifle, white-silver with frost-rune accents and fur trim, held one-handed at rest',
    lore: '',
  },
  {
    key: 'swamp_petal_dress',
    slot: 'armor',
    nameKo: '요정의 첫 꽃잎',
    region: '늪지대',
    tone: '아름다운',
    concept: '어린 늪요정의 첫 비행 꽃잎 드레스',
    art: 'a layered petal fairy dress — the first-flight gown of a young bog-fairy, woven from dawn-dewed flower petals with gossamer wings, light and joyful — drawn in a cute charming fantasy-anime style, soft luminous pastel pink and mint, a graceful slender silhouette, isolated object, plain background, pixel art',
    wornDesc: 'a layered pastel-pink-and-mint petal fairy dress with sheer gossamer wings',
    lore: '',
  },
];

// 재설계: 새 90종(items90)을 카탈로그로 사용. 이전 120종은 보류 — 삭제하지 않고
// HELD_ITEMS로 보존(나머지 30을 여기서 골라 추가할 풀). 현재 무기 30만 작성됨(방어구·장신구 추가 예정).
export const HELD_ITEMS: ItemV2[] = [...INLINE_ITEMS, ...EXTRA_ITEMS];


// ── V4 확장 14종 · 4차(2026-08-02) — 3차에서 장미 채찍검 1종 채택(+2차 임프 날개).
//    채택작의 공통 결: 흐르는 실루엣·단일 색 이야기·형태 자체가 컨셉. 넓은 날에 장식을
//    박는 방식(트럼프·태엽 대검류)을 버리고 전체 형태가 컨셉인 12종으로 재설계.
export const V4_ITEMS: ItemV2[] = [
  // ── 무기 8/8 확정 ──
  {
    key: 'general_twin_flintlocks',
    slot: 'weapon',
    nameKo: '금당초 쌍권총',
    region: '일반',
    tone: '화려',
    concept: '금 세공 쌍발 플린트락 권총',
    art: 'a pair of ornate flintlock pistols crossed — polished black barrels with swirling gold engravings and ruby-set grips, dashing and elegant, clearly pistol weapons, no text, no letters, no labels, large, diagonal',
    wornDesc: 'a crossed pair of black-and-gold flintlock pistols with ruby grips',
    lore: '검은 총신에 금빛 당초가 휘감기고 손잡이마다 루비가 박혔다. 두 자루의 총성이 서로 다르다. 하나는 높고 하나는 낮은데, 동시에 당기면 두 소리가 겹쳐 한 발로 들린다. 몇 발이 나갔는지는 맞은 쪽만 안다.',
    keeper: true,
  },
  {
    key: 'general_spiral_lance',
    slot: 'weapon',
    nameKo: '나선을 감은 랜스',
    region: '일반',
    tone: '영웅담',
    concept: '흑금 나선 세공의 기사 랜스',
    art: 'a black and gold spiral-fluted knight lance tapering to a piercing point, dramatic and imposing, clearly a lance weapon, large, diagonal',
    wornDesc: 'a black-and-gold spiral-fluted lance tapering to a fine point',
    lore: '검은 자루를 금빛 홈이 나선으로 감아 올라가 끝에서 한 점이 된다. 자루 전체가 그 한 점을 향해 비틀려 있다. 겨눈 것을 놓친 적이 없다는 말은 과장이지만, 빗나간 자리마다 나선 자국이 남는 것은 사실이다.',
    keeper: true,
  },
  {
    key: 'general_starfield_blade',
    slot: 'weapon',
    nameKo: '별자리가 흐르는 장검',
    region: '일반',
    tone: '수수께끼',
    concept: '별과 별자리 선이 흐르는 심야 검신',
    art: 'a longsword forged of the night sky — a deep midnight-blue translucent blade filled with tiny stars and glowing gold constellation lines, a dark silver hilt with a star-shaped pommel, mystical and elegant, clearly a sword weapon, large, diagonal',
    wornDesc: 'a midnight-blue blade filled with tiny stars and gold constellation lines',
    lore: '검신이 깊은 남색으로 가라앉고 그 속에 잔별이 금빛 선으로 이어진다. 이 별자리는 어느 하늘에도 없다. 검을 기울이면 배열이 조금씩 달라지는데 같은 모양이 두 번 나온 적이 없다. 아직 완성되지 않은 밤이다.',
    keeper: true,
  },
  {
    key: 'general_kintsugi_katana',
    slot: 'weapon',
    nameKo: '흑금 대도',
    region: '일반',
    tone: '아름다운',
    concept: '깨졌던 자리를 금으로 이은 킨츠기 카타나',
    art: 'a magnificent kintsugi katana — a long jet-black blade once shattered and rejoined with luminous molten-gold veins branching like lightning across the steel, warm gold light softly leaking from the seams, an ornate engraved gold tsuba and a black-and-gold silk-wrapped hilt, breathtaking and resolute, clearly a katana sword weapon, large, diagonal',
    wornDesc: 'a jet-black katana with bright gold veins mending old cracks along the blade',
    lore: '칠흑 도신을 금빛 줄기가 번개처럼 가로지르고 금 츠바가 받친다. 길이 석 자 두 치, 무게는 같은 길이 칼의 절반. 금이 채운 자리가 쇠보다 가볍기 때문인데, 그래서 오래 휘둘러도 팔이 덜 무겁다.',
    keeper: true,
  },
  {
    key: 'fallen_half_blade',
    slot: 'weapon',
    nameKo: '빛과 밤을 가른 대검',
    region: '타락천사',
    tone: '전설',
    concept: '세로로 갈라진 반빛·반흑 대검 — 검은 깃털',
    art: 'a half-fallen greatsword — a blade split lengthwise, one half radiant white-gold and the other jet-black with falling dark feathers, a wing-shaped guard half gold half black, dramatic and tragic, clearly a greatsword weapon, large, diagonal',
    wornDesc: 'a greatsword split lengthwise into radiant gold and jet-black halves, dark feathers falling',
    lore: '검신이 세로로 갈라져 한쪽은 백금빛, 다른 쪽은 칠흑이다. 가드의 날개도 한쪽만 금이고 아래로 검은 깃이 떨어진다. 이름은 나중에 붙었다. 처음 본 이는 빛이라 불렀고 다음 이는 밤이라 불렀는데, 둘은 같은 검을 말하고 있었다.',
    keeper: true,
  },
  { key: 'temple_icicle_longbow', slot: 'weapon', nameKo: '고드름이 자란 장궁', region: '신전', tone: '아름다운',
    concept: '고드름이 자란 백은 장궁',
    art: 'an icicle longbow — a tall pale silver bow with clusters of clear icicles growing along its limbs, a shimmering frost-blue string, cold mist drifting from the grip, elegant and freezing, clearly a longbow weapon, no text, large, diagonal',
    wornDesc: 'a tall silver longbow with icicles growing along its limbs', lore: '백은 활대를 따라 맑은 고드름이 무리 지어 자랐다. 이 활은 소리로 먼저 알려진다. 시위를 놓는 순간 얼음이 한꺼번에 갈라지는데, 그 소리를 들은 짐승은 화살이 닿기 전에 이미 멈춰 선다.', keeper: true },
  { key: 'fallen_pinion_twinblades', slot: 'weapon', nameKo: '한 쌍의 깃', region: '타락천사', tone: '전설',
    concept: '흰 깃·검은 깃의 쌍검',
    art: 'a pair of pinion twinblades — two curved wing-shaped blades crossed in an X, one white-gold with radiant feather etching and one jet-black with dark feather etching, matching hilts, dualistic and striking, clearly twin sword weapons, no text, large, diagonal',
    wornDesc: 'two crossed wing-shaped blades, one white-gold and one jet-black', lore: '날개 모양으로 휜 칼 둘이 X자로 맞물린다. 한 자루는 백금빛 깃, 다른 자루는 칠흑 깃. 흰 날에 베인 자는 무릎을 꿇고 용서를 빌었고, 검은 날에 베인 자는 일어나 제 손으로 신전을 불태웠다. 벤 사람은 같았다.', keeper: true },
  { key: 'fallen_grace_greatbow', slot: 'weapon', nameKo: '날개였던 대궁', region: '타락천사', tone: '전설',
    concept: '한쪽은 금빛·한쪽은 흑빛인 대궁',
    art: 'a magnificent fallen grace greatbow — a tall elegant bow with a deep recurve, its upper limb sculpted as a radiant white-gold angel wing with layered luminous feathers, its lower limb as a charred jet-black wing with ragged dark feathers, an ornate gilded center grip with fine filigree and a single pale gem, a taut string of pale light, a few loose feathers drifting, majestic and tragic, no halo, no ring, clearly a longbow weapon, no text, large, diagonal',
    wornDesc: 'a tall bow with one radiant gold limb and one charred black limb', lore: '활대 위쪽은 금빛 깃이 겹겹이 펼쳐지고 아래쪽은 그을린 검은 깃이 늘어진다. 시위 자리가 비어 있다. 대신 겨눈 방향으로 깃이 한 장씩 빠져나가는데, 빠진 자리는 다음 날이면 다시 차 있다.', keeper: true },
  // ── 장신구 2/4 확정 ──
  {
    key: 'general_star_eyepatch',
    slot: 'accessory',
    nameKo: '가려야 보이는 안대',
    region: '일반',
    tone: '수수께끼',
    concept: '금 별 장식의 검은 가죽 안대',
    art: 'a black leather eyepatch over the left eye with a slim strap and a small gold star stud, roguish and stylish',
    wornDesc: 'a black leather eyepatch with a gold star stud over the left eye',
    lore: '검은 가죽을 둥글게 오려 가는 끈으로 묶고 가운데 금빛 별을 박았다. 왼눈을 덮는다. 덮은 쪽이 어두워질수록 남은 눈이 밝아지고, 밝아진 눈은 남들이 못 보는 것을 먼저 본다. 이 안대는 벗을 때가 가장 어둡다.',
    keeper: true,
  },
  {
    key: 'general_imp_wings',
    slot: 'accessory',
    nameKo: '한 뼘짜리 마왕 날개',
    region: '일반',
    tone: '희망',
    concept: '작은 악마의 박쥐 날개 한 쌍',
    art: 'a small pair of imp bat wings — two little glossy crimson-and-black bat wings with cute rounded tips and gold wing-claws, sized to sit on the upper back, charming and mischievous, not large dragon wings',
    wornDesc: 'small crimson bat wings perched on the upper back',
    lore: '등 위쪽에 손바닥만 한 박쥐 날개 한 쌍. 진홍과 검정이 섞인 막에 끝마다 금빛 발톱이 달렸다. 접혀 있을 때는 한 뼘이다. 펼친 폭을 적어 둔 기록이 여럿 남았는데 같은 숫자가 하나도 없다.',
    keeper: true,
  },
  // ── 방어구 5/5 확정 (라이브 3종 제외 전제) ──
  { key: 'kingdom_lionguard_plate', slot: 'armor', nameKo: '백금 사자 갑주', region: '왕국', tone: '영웅담',
    concept: '사자 흉갑의 백금 근위 풀플레이트',
    art: 'a royal lionguard full plate — polished white-silver plate armor with a golden lion embossed on the breastplate, gold-trimmed pauldrons and a deep blue cape falling from the shoulders, stately and unyielding, a single garment floating on a plain empty background, no buildings, no scenery, no text',
    wornDesc: 'white-silver plate with a golden lion breastplate and blue cape', lore: '백금 판금 가슴에서 황금 사자가 갈기를 세우고 어깨에서 청색 망토가 발끝까지 흐른다. 판금은 대장장이가, 망토는 직조공이 맡았고, 사자만은 이름을 남기지 않은 자가 맡았다.' , keeper: true },
  { key: 'kingdom_herald_tabard', slot: 'armor', nameKo: '푸른 서약 기사복', region: '왕국', tone: '화려',
    concept: '문장 태버드를 두른 사슬갑',
    art: 'a royal herald tabard over mail — a crisp blue-and-gold heraldic tabard bearing a crowned emblem worn over fine silver chainmail, a wide belt and gold-fringed hem, ceremonial and proud, a single garment floating on a plain empty background, no buildings, no scenery, no text',
    wornDesc: 'a blue-and-gold heraldic tabard over silver chainmail', lore: '은빛 사슬갑 위에 청색 겉옷, 가슴에는 금실 왕관을 수놓았다. 해마다 지난 실을 뽑고 다시 놓는다. 뽑을 때마다 바탕천에 바늘 자국이 남아, 오래 입은 옷일수록 왕관 자리가 조금씩 커져 있다.' , keeper: true },
  { key: 'swamp_bogwitch_rags', slot: 'armor', nameKo: '이끼 자란 넝마 드레스', region: '늪지대', tone: '수수께끼',
    concept: '넝마 자락에 반딧불이 붙은 늪 마녀 드레스',
    art: 'a bog witch dress — a layered ragged dark-green dress with torn uneven hems and trailing moss, tiny golden fireflies clinging to the fabric, a knotted vine sash, eerie and enchanting, a single garment floating on a plain empty background, no buildings, no scenery, no text',
    wornDesc: 'a ragged dark-green witch dress with moss and clinging fireflies', lore: '짙은 초록 천이 겹겹이 찢긴 채 늘어지고 이끼와 잔가지가 엉겼다. 자락마다 반딧불이 붙어 깜빡인다. 봄에는 이끼가 자라고 여름에는 반딧불이 늘고 가을에는 잔가지가 는다. 겨울에만 옷이 옷다워진다.' , keeper: true },
  { key: 'fallen_gilded_ruin_plate', slot: 'armor', nameKo: '도금이 벗겨진 갑주', region: '타락천사', tone: '전설',
    concept: '금 도금이 벗겨진 폐허의 갑주',
    art: 'a gilded ruin armor — once-golden plate armor with its gilding flaked away to reveal blackened metal beneath, cracked engravings and a torn dark mantle, faint gold light in the fractures, ruined and majestic, a single garment floating on a plain empty background, no buildings, no scenery, no text',
    wornDesc: 'flaking gold plate armor revealing blackened metal beneath', lore: '금박이 조각조각 일어나 그 아래 검은 쇠가 드러났다. 갈라진 틈마다 남은 금이 희미하게 빛난다. 벗겨질수록 가벼워지고 가벼워질수록 잘 움직인다. 이 갑주는 금을 다 잃는 날 가장 좋은 갑주가 된다.' , keeper: true },
  { key: 'general_beastmaster_hide', slot: 'armor', nameKo: '냄새를 덮는 가죽옷', region: '일반', tone: '영웅담',
    concept: '짐승 가죽과 발톱 장식의 조련사 차림',
    art: 'a beastmaster outfit — layered tawny animal hides with a clawed shoulder mantle, fur-lined boots and bone-clasped belts, braided leather cords, primal and free, a single garment floating on a plain empty background, no buildings, no scenery, no text',
    wornDesc: 'layered tawny hides with a clawed shoulder mantle and bone clasps', lore: '누런 가죽을 겹겹이 두르고 목에는 두툼한 털을 둘렀다. 가슴과 허리를 가로지른 끈마다 손때가 짙다. 산에 갈 때 지킬 것 — 씻지 말 것, 빨지 말 것. 규칙을 어긴 자는 산에서 사람으로 읽힌다.' , keeper: true },
  // ── 라이브 카탈로그에서 제외 확정(catalog-v4 편성 시 삭제):
  //    frostwarden_coat(설원 파수꾼의 외투) · angel_risen_mantle(부러진 적 있는 날개)
  //    · angel_duskwing_armor(저무는 해의 날개) → 방어구 38-3+5 = 40
  // ── 장신구 4/4 확정 ──
  { key: 'volcano_ashglass_goggles', slot: 'accessory', nameKo: '재를 막는 눈', region: '화산', tone: '영웅담',
    concept: '그을린 황동 고글',
    art: 'a pair of soot-stained brass goggles — smoked amber glass lenses in a scorched brass frame with a worn leather strap, worn pushed up on the forehead, industrious and rugged, isolated object on a plain background, no text',
    wornDesc: 'soot-stained brass goggles with amber lenses on the forehead', lore: '황동테가 그을려 검붉게 얼룩졌고 호박빛 알에는 잔 기스가 가득하다. 새것보다 헌것이 비싸게 팔린다. 기스가 많을수록 불길을 오래 견딘 물건이라, 값을 매기는 쪽은 알부터 해에 비춰 본다.', keeper: true },
  { key: 'general_wing_hairclip', slot: 'accessory', nameKo: '백은 깃 머리핀', region: '일반', tone: '아름다운',
    concept: '흰 깃 머리핀',
    art: 'a white feather hair clip — two soft white plumes on a small pearl-set silver clip, worn at the side of the head, light and elegant, isolated object on a plain background, no text',
    wornDesc: 'a white feather hair clip at the side of the head', lore: '은실을 꼬아 만든 작은 집게에 흰 깃 두 장이 얹혔다. 집게는 한 번 물면 좀처럼 풀리지 않는다. 세공한 자가 깃보다 집게에 공을 들였기 때문인데, 정작 사는 사람들은 늘 깃만 보고 고른다.', keeper: true },
  
  
  
  
];



// ── V4 후보 풀 30종(2026-08-02, key1 대량 생성) — 사용자가 2/2/2 선별 예정.
export const V4_POOL30: ItemV2[] = [
  { key: 'kingdom_signet_ring', slot: 'accessory', nameKo: '인장이 찍히는 손', region: '왕국', tone: '화려',
    concept: '사자 인장이 새겨진 금반지',
    art: 'an ornate gold signet ring — a heavy band with a carved lion crest on a deep blue lapis face, fine engraving around the shoulders, authoritative and regal, isolated object on a plain background, no text',
    wornDesc: 'a heavy gold signet ring with a carved lion crest', lore: '' },
  { key: 'kingdom_epaulette_cord', slot: 'accessory', nameKo: '어깨에 걸린 계급', region: '왕국', tone: '화려',
    concept: '금 수술이 늘어진 견장',
    art: 'a pair of ornate gold epaulettes — braided bullion cords with hanging gold fringe and a small crown pin, worn on the shoulders, ceremonial and proud, isolated object on a plain background, no text',
    wornDesc: 'gold bullion epaulettes with hanging fringe on the shoulders', lore: '' },
  { key: 'kingdom_lily_circlet', slot: 'accessory', nameKo: '이마 위의 백합', region: '왕국', tone: '아름다운',
    concept: '백합 세공 은빛 서클릿',
    art: 'a slender silver circlet — delicate openwork lilies across the brow band with a small pearl at the center, refined and graceful, isolated object on a plain background, no text',
    wornDesc: 'a slender silver circlet of openwork lilies with a center pearl', lore: '' },
  { key: 'swamp_firefly_jar', slot: 'accessory', nameKo: '유리병에 든 밤', region: '늪지대', tone: '수수께끼',
    concept: '반딧불 몇 마리가 든 유리병',
    art: 'a small glass jar of fireflies — a corked jar hung from a leather cord with several golden fireflies glowing inside and moss at the bottom, quiet and magical, isolated object on a plain background, no text',
    wornDesc: 'a corked glass jar of glowing fireflies hung at the belt', lore: '' },
  { key: 'swamp_frogskull_charm', slot: 'accessory', nameKo: '늪이 남긴 뼈', region: '늪지대', tone: '기괴',
    concept: '작은 두개골 부적 세 개',
    art: 'three small pale animal skulls strung on a braided cord — mossy bone with tiny green vines threading the eye sockets, primitive and eerie, isolated object on a plain background, no text',
    wornDesc: 'three small mossy skulls strung on a braided cord', lore: '' },
  { key: 'swamp_lotus_hairpin', slot: 'accessory', nameKo: '머리에 핀 수련', region: '늪지대', tone: '아름다운',
    concept: '백련 비녀',
    art: 'a lotus hairpin — a long silver pin topped with a white lotus blossom and two tiny jade leaves, a thin dangling chain, serene and delicate, isolated object on a plain background, no text',
    wornDesc: 'a silver hairpin topped with a white lotus blossom', lore: '' },
  { key: 'volcano_ember_pauldron', slot: 'accessory', nameKo: '타오르는 한쪽', region: '화산', tone: '전설',
    concept: '잉걸이 흐르는 한쪽 견갑',
    art: 'a single heavy shoulder pauldron of blackened iron — glowing orange ember veins running through its plates with small flames licking the rim, worn on one shoulder, imposing and molten, isolated object on a plain background, no text',
    wornDesc: 'a blackened iron pauldron with glowing ember veins on one shoulder', lore: '' },
  { key: 'volcano_obsidian_earrings', slot: 'accessory', nameKo: '귀에 건 흑요석', region: '화산', tone: '화려',
    concept: '흑요석 물방울 귀걸이',
    art: 'a pair of obsidian teardrop earrings — polished black glass drops on fine gold hooks with a faint inner red glimmer, sleek and elegant, isolated object on a plain background, no text',
    wornDesc: 'obsidian teardrop earrings with a faint red inner glimmer', lore: '' },
  { key: 'volcano_ashglass_goggles', slot: 'accessory', nameKo: '재를 막는 눈', region: '화산', tone: '영웅담',
    concept: '그을린 황동 고글',
    art: 'a pair of soot-stained brass goggles — smoked amber glass lenses in a scorched brass frame with a worn leather strap, worn pushed up on the forehead, industrious and rugged, isolated object on a plain background, no text',
    wornDesc: 'soot-stained brass goggles with amber lenses on the forehead', lore: '' },
  { key: 'temple_frost_veil', slot: 'accessory', nameKo: '서리가 내린 면사', region: '신전', tone: '아름다운',
    concept: '서리 맺힌 은사 면사포',
    art: 'a sheer silver veil edged with frost — fine translucent fabric with tiny ice crystals along the hem, held by a small snowflake clasp, ethereal and cold, isolated object on a plain background, no text',
    wornDesc: 'a sheer frost-edged silver veil held by a snowflake clasp', lore: '' },
  { key: 'temple_prayer_stole', slot: 'accessory', nameKo: '어깨에 두른 서원', region: '신전', tone: '전설',
    concept: '금 자수 백색 스톨',
    art: 'a white ceremonial stole — a long narrow band of white silk draped over both shoulders with gold embroidered prayer patterns and fringed ends, solemn and sacred, isolated object on a plain background, no text',
    wornDesc: 'a white silk stole with gold embroidery draped over the shoulders', lore: '' },
  { key: 'temple_icicle_earcuff', slot: 'accessory', nameKo: '귀 끝의 겨울', region: '신전', tone: '수수께끼',
    concept: '고드름 이어커프',
    art: 'an ear cuff of clustered clear icicles — pale blue ice shards set in a thin silver band curving along the ear, faint cold mist, delicate and striking, isolated object on a plain background, no text',
    wornDesc: 'an ear cuff of clustered pale-blue icicles', lore: '' },
  { key: 'fallen_broken_wing', slot: 'accessory', nameKo: '한쪽만 남은 날개', region: '타락천사', tone: '전설',
    concept: '부러진 검은 날개 한 짝',
    art: 'a single broken black wing worn on one side of the back — dark feathers with several gaps and one bent pinion, faint gold light at the fracture, tragic and beautiful, isolated object on a plain background, no text',
    wornDesc: 'a single broken black wing on one side of the back', lore: '' },
  { key: 'fallen_chain_collar', slot: 'accessory', nameKo: '끊지 못한 사슬', region: '타락천사', tone: '수수께끼',
    concept: '늘어진 사슬 목걸이',
    art: 'a heavy dark iron collar with a broken chain hanging from it — tarnished links trailing down the chest with a small gold clasp, somber and severe, isolated object on a plain background, no text',
    wornDesc: 'a dark iron collar with a broken chain trailing down', lore: '' },
  { key: 'fallen_ashfeather_crown', slot: 'accessory', nameKo: '재로 엮은 관', region: '타락천사', tone: '화려',
    concept: '검은 깃털을 엮은 금관',
    art: 'a crown woven from black feathers and dull gold wire — layered dark plumes rising from a tarnished gold band with one pale gem, fallen and majestic, isolated object on a plain background, no text',
    wornDesc: 'a crown of black feathers woven into a tarnished gold band', lore: '' },
  { key: 'orc_tusk_necklace', slot: 'accessory', nameKo: '엄니를 꿴 목걸이', region: '오크 부락', tone: '영웅담',
    concept: '거수 엄니 목걸이',
    art: 'a necklace of large curved beast tusks strung on rough leather cord with wooden beads between them, worn across the chest, savage and proud, isolated object on a plain background, no text',
    wornDesc: 'a necklace of curved beast tusks on rough leather cord', lore: '' },
  { key: 'orc_warpaint_mask', slot: 'accessory', nameKo: '얼굴에 그린 전투', region: '오크 부락', tone: '수수께끼',
    concept: '붉은 전투 문양의 나무 반가면',
    art: 'a carved wooden half-mask painted with bold crimson war stripes — rough grain, bone studs along the edge and a feather at one side, tribal and fierce, isolated object on a plain background, no text',
    wornDesc: 'a carved wooden half-mask with crimson war stripes', lore: '' },
  { key: 'orc_totem_backbanner', slot: 'accessory', nameKo: '등에 세운 토템', region: '오크 부락', tone: '전설',
    concept: '등에 꽂는 토템 깃대',
    art: 'a tribal totem back-banner — a short carved wooden pole strapped to the back topped with a horned beast skull, hung with feathers bones and red cords, wild and commanding, isolated object on a plain background, no text',
    wornDesc: 'a carved totem pole with a horned skull strapped to the back', lore: '' },
  { key: 'general_monocle_chain', slot: 'accessory', nameKo: '한쪽만 진지한 눈', region: '일반', tone: '수수께끼',
    concept: '사슬 달린 은테 모노클',
    art: 'a silver-rimmed monocle on a fine chain — a round polished lens with an engraved rim and a small clip, dignified and witty, isolated object on a plain background, no text',
    wornDesc: 'a silver monocle on a fine chain', lore: '' },
  { key: 'general_rose_corsage', slot: 'accessory', nameKo: '가슴에 꽂은 한 송이', region: '일반', tone: '아름다운',
    concept: '붉은 장미 코사지',
    art: 'a deep red rose corsage pinned at the lapel — a single velvet bloom with two dark green leaves and a small gold pin, romantic and sharp, isolated object on a plain background, no text',
    wornDesc: 'a deep red rose corsage pinned at the lapel', lore: '' },
  { key: 'general_pocket_square', slot: 'accessory', nameKo: '접어 넣은 격식', region: '일반', tone: '화려',
    concept: '금실 수 놓은 실크 포켓스퀘어',
    art: 'a folded silk pocket square — deep burgundy silk with fine gold thread edging, folded in a crisp peak, refined and dapper, isolated object on a plain background, no text',
    wornDesc: 'a burgundy silk pocket square folded at the chest', lore: '' },
  { key: 'general_feather_quillpen', slot: 'accessory', nameKo: '귀에 꽂은 깃펜', region: '일반', tone: '수수께끼',
    concept: '귀에 꽂는 흰 깃펜',
    art: 'a white quill pen tucked behind the ear — a long clean feather with a small brass nib and a trace of dark ink at the tip, scholarly and casual, isolated object on a plain background, no text',
    wornDesc: 'a white quill pen tucked behind the ear', lore: '' },
  { key: 'general_lantern_hand', slot: 'accessory', nameKo: '밤을 드는 손', region: '일반', tone: '희망',
    concept: '손에 든 놋쇠 손전등',
    art: 'a small brass hand lantern — a glass-paned lamp with a warm candle glow inside, a curved carry handle and a hook, cozy and steadfast, isolated object on a plain background, no text',
    wornDesc: 'a small brass hand lantern glowing warmly', lore: '' },
  { key: 'general_wanted_poster', slot: 'accessory', nameKo: '내 얼굴이 붙은 종이', region: '일반', tone: '수수께끼',
    concept: '돌돌 만 현상수배 전단',
    art: 'a rolled wanted poster tucked under the arm — aged yellowed paper tied with twine, torn edges and a wax stamp, roguish and cinematic, isolated object on a plain background, no text',
    wornDesc: 'a rolled aged wanted poster tucked under the arm', lore: '' },
  { key: 'general_wing_hairclip', slot: 'accessory', nameKo: '머리에 앉은 깃', region: '일반', tone: '아름다운',
    concept: '흰 깃 머리핀',
    art: 'a white feather hair clip — two soft white plumes on a small pearl-set silver clip, worn at the side of the head, light and elegant, isolated object on a plain background, no text',
    wornDesc: 'a white feather hair clip at the side of the head', lore: '' },
  { key: 'general_tarot_card', slot: 'accessory', nameKo: '뽑고 만 카드', region: '일반', tone: '수수께끼',
    concept: '손에 든 타로 카드 한 장',
    art: 'a single ornate tarot card held between the fingers — deep indigo back with gold star filigree and a worn gilt edge, mysterious and stylish, isolated object on a plain background, no text',
    wornDesc: 'an ornate indigo tarot card held between the fingers', lore: '' },
  { key: 'general_music_box', slot: 'accessory', nameKo: '태엽을 감는 소리', region: '일반', tone: '아름다운',
    concept: '손바닥만 한 오르골',
    art: 'a small ornate music box — a polished walnut case with brass filigree and a tiny wind-up key, its lid open showing a spinning gold figure, nostalgic and precious, isolated object on a plain background, no text',
    wornDesc: 'a small walnut music box with a brass wind-up key', lore: '' },
  { key: 'general_bandaged_cheek', slot: 'accessory', nameKo: '붙여 둔 반창고', region: '일반', tone: '희망',
    concept: '뺨에 붙인 반창고 두 장',
    art: 'two small cream bandage patches crossed on the cheek — soft fabric with rounded corners, plain and endearing, isolated object on a plain background, no text',
    wornDesc: 'two small bandage patches crossed on the cheek', lore: '' },
  { key: 'general_shoulder_cat', slot: 'accessory', nameKo: '어깨에 앉은 고양이', region: '일반', tone: '희망',
    concept: '어깨에 앉은 삼색 고양이',
    art: 'a small calico cat curled up sitting — soft white orange and black fur with green eyes and a tiny red collar bell, tail curled around its paws, warm and charming, exactly one cat and nothing else, no person, no buildings, no architecture, no scenery, isolated object on a plain background, no text',
    wornDesc: 'a small calico cat sitting on the shoulder', lore: '' },
  { key: 'general_crystal_orb', slot: 'accessory', nameKo: '손 위에 뜬 구슬', region: '일반', tone: '수수께끼',
    concept: '손 위에 떠 있는 수정 구슬',
    art: 'a crystal orb floating above an open palm — a clear sphere with swirling violet mist inside and faint sparkles orbiting it, mystical and elegant, isolated object on a plain background, no text',
    wornDesc: 'a crystal orb with violet mist floating above the palm', lore: '' },
];

// ── V4 장신구 추가 후보 20종(2026-08-03) — 기존 30종과 함께 총 50 후보.
export const V4_POOL20: ItemV2[] = [
  { key: 'kingdom_medal_bar', slot: 'accessory', nameKo: '가슴에 단 이력', region: '왕국', tone: '화려',
    concept: '줄지어 단 약장 훈장',
    art: 'a row of military ribbon medals pinned at the chest — five short striped ribbon bars in navy crimson and gold above two small hanging star medals, orderly and distinguished, isolated object on a plain background, no text, no buildings, no scenery',
    wornDesc: 'a row of striped ribbon medals with two hanging stars at the chest', lore: '' },
  { key: 'kingdom_livery_chain', slot: 'accessory', nameKo: '목에 두른 직책', region: '왕국', tone: '전설',
    concept: '문장 메달이 달린 금 사슬 목걸이',
    art: 'a heavy gold livery chain — large interlocking gold links draped across both shoulders with a crowned lion medallion hanging at the center, ceremonial and weighty, isolated object on a plain background, no text, no buildings, no scenery',
    wornDesc: 'a heavy gold link chain with a crowned lion medallion', lore: '' },
  { key: 'swamp_frog_ring', slot: 'accessory', nameKo: '손가락에 앉은 것', region: '늪지대', tone: '희망',
    concept: '청동 개구리 반지',
    art: 'a bronze frog ring — a small verdigris frog crouched on a wide band with tiny emerald eyes and lily-pad engraving, whimsical and earthy, isolated object on a plain background, no text, no buildings, no scenery',
    wornDesc: 'a bronze frog ring with emerald eyes', lore: '' },
  { key: 'swamp_reed_flute', slot: 'accessory', nameKo: '갈대로 만든 소리', region: '늪지대', tone: '아름다운',
    concept: '갈대 팬플루트',
    art: 'a bundled reed pan flute — seven graduated hollow reeds bound with braided green cord and a small feather charm, rustic and gentle, isolated object on a plain background, no text, no buildings, no scenery',
    wornDesc: 'a bundled reed pan flute with braided cord', lore: '' },
  { key: 'volcano_lava_bracer', slot: 'accessory', nameKo: '팔에 채운 열기', region: '화산', tone: '전설',
    concept: '용암이 흐르는 흑철 팔보호대',
    art: 'a blackened iron forearm bracer — thick plates with glowing orange lava seams running between them and heat shimmer at the edges, riveted straps, imposing and molten, isolated object on a plain background, no text, no buildings, no scenery',
    wornDesc: 'a blackened iron bracer with glowing lava seams', lore: '' },
  { key: 'volcano_cinder_anklet', slot: 'accessory', nameKo: '발목의 불티', region: '화산', tone: '화려',
    concept: '불티가 도는 청동 발찌',
    art: 'a bronze ankle band strung with small ember beads — tiny glowing cinders drifting around it and fine chain loops, warm and striking, isolated object on a plain background, no text, no buildings, no scenery',
    wornDesc: 'a bronze anklet strung with glowing ember beads', lore: '' },
  { key: 'temple_holywater_vial', slot: 'accessory', nameKo: '한 방울의 허락', region: '신전', tone: '수수께끼',
    concept: '성수가 든 은병',
    art: 'a small silver vial of holy water — an engraved flask with a cross-etched stopper on a fine chain, faint pale light glowing through the metal, sacred and quiet, isolated object on a plain background, no text, no buildings, no scenery',
    wornDesc: 'a small engraved silver vial glowing faintly on a chain', lore: '' },
  { key: 'temple_snowflake_brooch', slot: 'accessory', nameKo: '가슴에 앉은 눈', region: '신전', tone: '아름다운',
    concept: '은세공 눈꽃 브로치',
    art: 'a silver snowflake brooch — a delicate six-armed crystal in fine filigree with a pale blue gem at its heart and tiny frost dust, elegant and cold, isolated object on a plain background, no text, no buildings, no scenery',
    wornDesc: 'a silver snowflake brooch with a pale blue center gem', lore: '' },
  { key: 'fallen_feather_earrings', slot: 'accessory', nameKo: '귀에 걸린 깃', region: '타락천사', tone: '수수께끼',
    concept: '검은 깃털 귀걸이',
    art: 'a pair of black feather earrings — long glossy dark plumes hanging from small gold hooks with tiny gold caps, one feather slightly frayed, elegant and fallen, isolated object on a plain background, no text, no buildings, no scenery',
    wornDesc: 'black feather earrings with gold caps', lore: '' },
  { key: 'fallen_cracked_mask', slot: 'accessory', nameKo: '금이 간 얼굴', region: '타락천사', tone: '전설',
    concept: '금으로 이은 백자 반가면',
    art: 'a white porcelain half-mask cracked and mended with veins of gold — smooth glazed surface over the upper face with an empty calm expression, tragic and beautiful, isolated object on a plain background, no text, no buildings, no scenery',
    wornDesc: 'a white porcelain half-mask mended with gold veins', lore: '' },
  { key: 'orc_bone_pauldron', slot: 'accessory', nameKo: '어깨에 얹은 뼈', region: '오크 부락', tone: '영웅담',
    concept: '거수 뼈 한쪽 견갑',
    art: 'a massive single shoulder guard carved from beast bone — pale ridged bone lashed with leather straps and iron studs, small tusks along the rim, savage and heavy, isolated object on a plain background, no text, no buildings, no scenery',
    wornDesc: 'a massive bone shoulder guard lashed with leather straps', lore: '' },
  { key: 'orc_bone_piercings', slot: 'accessory', nameKo: '귀에 꿴 뼈', region: '오크 부락', tone: '수수께끼',
    concept: '뼈 고리 귀 장식',
    art: 'a set of bone piercing rings — three carved pale bone hoops of different sizes with a small tusk pendant, rough and tribal, isolated object on a plain background, no text, no buildings, no scenery',
    wornDesc: 'carved bone hoop piercings with a small tusk pendant', lore: '' },
  { key: 'general_heirloom_watch', slot: 'accessory', nameKo: '물려받은 시간', region: '일반', tone: '아름다운',
    concept: '뚜껑 열린 금 회중시계',
    art: 'an open gold pocket watch on a chain — an engraved lid hinged back showing a worn enamel face with fine hands, a small photo locket inside the lid, nostalgic and precious, isolated object on a plain background, no text, no buildings, no scenery',
    wornDesc: 'an open engraved gold pocket watch on a chain', lore: '' },
  { key: 'general_velvet_bowtie', slot: 'accessory', nameKo: '목 아래의 예의', region: '일반', tone: '화려',
    concept: '벨벳 나비넥타이',
    art: 'a deep burgundy velvet bow tie — a crisply tied bow with a subtle sheen and a small gold pin at the knot, dapper and neat, isolated object on a plain background, no text, no buildings, no scenery',
    wornDesc: 'a burgundy velvet bow tie with a gold knot pin', lore: '' },
  { key: 'general_silk_gloves', slot: 'accessory', nameKo: '맨손은 실례', region: '일반', tone: '아름다운',
    concept: '팔꿈치까지 오는 실크 장갑',
    art: 'a pair of long white silk opera gloves — smooth elbow-length gloves with three small pearl buttons at the wrist, refined and graceful, isolated object on a plain background, no text, no buildings, no scenery',
    wornDesc: 'long white silk opera gloves with pearl buttons', lore: '' },
  { key: 'general_stethoscope', slot: 'accessory', nameKo: '심장 소리를 듣는 일', region: '일반', tone: '희망',
    concept: '목에 건 청진기',
    art: 'a stethoscope worn around the neck — polished steel chest piece with black rubber tubing draped over both shoulders, clean and reassuring, isolated object on a plain background, no text, no buildings, no scenery',
    wornDesc: 'a steel stethoscope draped around the neck', lore: '' },
  { key: 'general_marten_stole', slot: 'accessory', nameKo: '어깨에 두른 겨울', region: '일반', tone: '화려',
    concept: '담비 모피 목도리',
    art: 'a sable fur stole — a rich dark-brown pelt draped over the shoulders with a small gold clasp and two hanging tails, luxurious and warm, isolated object on a plain background, no text, no buildings, no scenery',
    wornDesc: 'a dark sable fur stole with a gold clasp', lore: '' },
  { key: 'general_leather_bracelets', slot: 'accessory', nameKo: '손목에 감은 세월', region: '일반', tone: '영웅담',
    concept: '가죽 팔찌 다발',
    art: 'a stack of worn leather wrist bracelets — braided and studded bands in mixed browns with small metal rings and one bone bead, rugged and casual, isolated object on a plain background, no text, no buildings, no scenery',
    wornDesc: 'a stack of braided leather wrist bracelets', lore: '' },
  { key: 'general_paper_crown', slot: 'accessory', nameKo: '종이로 쓴 왕', region: '일반', tone: '희망',
    concept: '삐뚤게 접은 종이 왕관',
    art: 'a lopsided paper crown — folded from bright yellow craft paper with uneven points and a crayon star drawn on the front, endearing and silly, isolated object on a plain background, no text, no buildings, no scenery',
    wornDesc: 'a lopsided yellow paper crown', lore: '' },
  { key: 'general_glass_butterfly', slot: 'accessory', nameKo: '유리로 앉은 나비', region: '일반', tone: '아름다운',
    concept: '스테인드글라스 나비 브로치',
    art: 'a stained-glass butterfly brooch — translucent jewel-toned wing panes in fine gold leading with a small gem body, light passing through, delicate and radiant, isolated object on a plain background, no text, no buildings, no scenery',
    wornDesc: 'a stained-glass butterfly brooch with gold leading', lore: '' },
];

export const ITEMS_V2: ItemV2[] = [...WEAPONS_90, ...ARMOR_90, ...ACCESSORIES_90, ...V4_ITEMS, ...V4_POOL30, ...V4_POOL20];

// 컨셉-온리 확정 방식(2026-06-27): art = "a <종류> — <역할·무드>"(외형묘사 X). buildArt가 슬롯별 품질 tail만 덧붙임.
// 자유를 줄수록 결과가 좋다(사용자 검증). 아바타가 일본 애니메 미소년/미소녀라 톤은 밝고 깔끔한 애니/JRPG.
const TAIL: Record<string, string> = {
  weapon: 'a beautiful clean fantasy anime RPG gacha-game weapon, bright and stylish, not gothic, a single isolated object on a plain flat empty background, large, pixel art',
  armor: 'a beautiful clean fantasy anime RPG gacha-game outfit, bright and stylish, not gothic, shown as the worn outfit on its own with no head and no neck, a slim full-length figure, a single isolated object on a plain flat empty background, pixel art',
  accessory: 'a beautiful clean fantasy anime RPG gacha-game item, bright and stylish, not gothic, a single isolated object on a plain flat empty background, pixel art',
};
export function buildArt(it: ItemV2): string {
  if (it.art.includes('pixel art')) return it.art; // 이미 완성된 프롬프트면 그대로
  return `${it.art}, ${TAIL[it.slot] ?? TAIL.accessory}`;
}
