// 신규 120종 아바타-코디 카탈로그 작업 데이터(docs/ITEMS.md). 배치 단위로 채워 나간다.
// 워크플로: ①컨셉·이름·프롬프트 검수 → ②이미지(객체) 생성·검수 → ③이미지 보고 로어 작성.
// 프롬프트 원칙(memory pixellab-item-prompt-balance):
//   - 최대한 디테일·특색(아이템마다 애정 생기게). 형태/구성 디테일 자세히.
//   - 지역이 왕국이어도 '로열+보석'으로 도배 금지 — 아이템마다 재질·역할·캐릭터를 제각각.
//     보석은 그게 진짜 컨셉인 것만. 화려함은 다양한 장인적 재질(강철·실크·라커·호두나무·은각인 등)로.
//   - 무기: large·diagonal·clean/straight(가드는 칼날에 수직), 두꺼운 타입 적극.
export type ItemV2 = {
  key: string;
  slot: 'weapon' | 'armor' | 'accessory';
  nameKo: string;
  region: string;
  tone: string;
  concept: string;
  art: string; // 컨셉-온리 프롬프트 조각 "a <종류> — <역할·무드>"(외형묘사 X). buildArt가 품질 tail을 덧붙임.
  wornDesc: string;
  lore: string;
  keeper?: boolean; // 사용자가 고른 확정 이미지(생성 스킵·잠금)
};

import { EXTRA_ITEMS } from './items-extra';
import { WEAPONS_90, ARMOR_90, ACCESSORIES_90 } from './items90';

const INLINE_ITEMS: ItemV2[] = [
  // ── 왕국 · 무기 (10) · 아이템마다 다른 재질·캐릭터 ───────────────────────────
  {
    key: 'kingdom_ribbon_rapier',
    slot: 'weapon',
    nameKo: '푸른 매듭',
    region: '왕국',
    tone: '화려',
    concept: '파란 실크 리본의 결투용 레이피어',
    art: 'an ornate royal rapier with a flowing ribbon, elegant and splendid, large, pixel art',
    wornDesc: 'a slim golden rapier with an ornate guard and a trailing blue ribbon',
    lore: '',
  },
  {
    key: 'kingdom_coronation_greatsword',
    slot: 'weapon',
    nameKo: '왕관의 무게',
    region: '왕국',
    tone: '영웅담',
    concept: '크라운 폼멜의 묵직한 강철 대검',
    art: 'a grand ornate royal two-handed greatsword, majestic and splendid, premium game-art, isolated object, plain background, large, pixel art',
    wornDesc: 'a magnificent heroic greatsword with a broad gleaming steel blade and a golden crown-shaped pommel, rested over one shoulder',
    lore: '',
  },
  {
    key: 'kingdom_court_twinblades',
    slot: 'weapon',
    nameKo: '마주 든 한 쌍',
    region: '왕국',
    tone: '화려',
    concept: 'X자 교차·자개 라커 손잡이 쌍곡검',
    art: 'two slim curved court sabers crossed in a big X shape, black lacquered hilts inlaid with mother-of-pearl and hanging silk tassels, lavishly ornate in a fantasy anime style, graceful and exotic, isolated object, plain background, large, pixel art',
    wornDesc: 'a pair of slim curved sabers with black lacquered, pearl-inlaid hilts, one per hand',
    lore: '',
  },
  {
    key: 'kingdom_coronation_spear',
    slot: 'weapon',
    nameKo: '즉위를 알린 창',
    region: '왕국',
    tone: '영웅담',
    concept: '긴 물푸레 자루에 왕실 깃발 단 의장창',
    art: 'a very long slender processional spear, a tall finely polished shaft with gold fittings, a gleaming steel head, a rich royal banner streaming from below the blade, ceremonial and majestic, full length, pixel art',
    wornDesc: 'a long processional spear with a pale wooden shaft, a steel head and a royal banner below the blade',
    lore: '',
  },
  {
    key: 'kingdom_jewel_longsword',
    slot: 'weapon',
    nameKo: '보석을 삼킨 날',
    region: '왕국',
    tone: '화려',
    concept: '자수정이 박힌 넓은 의장 장검(보석이 컨셉)',
    art: 'a magnificent fantasy longsword, a broad ornate blade set with a glittering row of amethyst gems, an elaborate gilded guard and a large amethyst gem pommel, lavishly jeweled in a fantasy anime JRPG style, gorgeous and splendid, clean and straight with the guard perpendicular to the blade, large, pixel art',
    wornDesc: 'a broad longsword with a row of amethyst gems along the blade and a gilded hilt',
    lore: '',
  },
  {
    key: 'kingdom_guard_halberd',
    slot: 'weapon',
    nameKo: '문 앞의 맹세',
    region: '왕국',
    tone: '영웅담',
    concept: '왕실 정문을 지키는 화려한 의장 할버드',
    art: 'a magnificent fantasy royal halberd, a long ornate shaft with a large gold-engraved axe blade and a spike, lavishly ornate in a fantasy anime style, splendid and grand, isolated object, plain background, full length, pixel art',
    wornDesc: 'an ornate royal halberd with a long shaft and a large gold-engraved axe blade',
    lore: '',
  },
  {
    key: 'kingdom_cane_sword',
    slot: 'weapon',
    nameKo: '지팡이 속 한 줄',
    region: '왕국',
    tone: '수수께끼',
    concept: '호두나무·놋쇠 손잡이 지팡이검',
    art: "an exquisite fantasy gentleman's cane, lustrous dark wood with elaborate gold scrollwork and a jeweled bird-head handle, concealing a thin hidden blade, luxurious in a fantasy anime style, refined and splendid, large, pixel art",
    wornDesc: 'a polished dark-walnut cane with a brass bird-head handle that conceals a thin blade',
    lore: '',
  },
  {
    key: 'kingdom_duel_pistol',
    slot: 'weapon',
    nameKo: '정중한 한 발',
    region: '왕국',
    tone: '화려',
    concept: '은각인 호두나무 플린트락 결투 권총',
    art: 'an exquisite flintlock dueling pistol, a fine dark walnut stock with chased silver scrollwork and gold inlay, a long engraved barrel, refined and elegant, large, pixel art',
    wornDesc: 'an antique flintlock dueling pistol with a dark walnut stock and chased silver scrollwork',
    lore: '',
  },
  {
    key: 'kingdom_scepter_mace',
    slot: 'weapon',
    nameKo: '보석을 인 홀',
    region: '왕국',
    tone: '전설',
    concept: '거대한 루비가 얹힌 황금 왕홀(보석이 컨셉)',
    art: 'a golden royal scepter-mace crowned with one enormous ruby, ornate gold flanges, lavishly regal and gorgeous, large, pixel art',
    wornDesc: 'an ornate golden scepter-mace topped with one enormous ruby',
    lore: '',
  },
  {
    key: 'kingdom_ribbon_whip',
    slot: 'weapon',
    nameKo: '풀린 리본의 춤',
    region: '왕국',
    tone: '아름다운',
    concept: '강철 비늘 박힌 크림슨 실크 리본 채찍',
    art: 'a long flowing ribbon-whip of crimson silk lined with tiny steel scales, an ornate grip, graceful and beautiful, large, pixel art',
    wornDesc: 'a long crimson silk ribbon-whip lined with tiny steel scales and an ornate grip',
    lore: '',
  },

  // ── 새 방식(종류+컨셉+스타일) 테스트 — 신전·늪지 ──────────────────────────
  {
    key: 'temple_frostvein_rifle',
    slot: 'weapon',
    nameKo: '첫눈을 겨눈 총신',
    region: '신전',
    tone: '영웅담',
    concept: '성스러운 설산 사냥꾼의 의식용 장총',
    art: 'a long fantasy flintlock musket (a snow-temple hunter who aims at the first snowfall) — a splendid, gorgeous, lavishly detailed premium visual pixel-art game item, dazzling frost-touched fantasy game art, no telescopic scope, isolated object, plain background, large, pixel art',
    wornDesc: 'a long ornate hunting rifle, white-silver with frost-rune accents and fur trim, held one-handed at rest',
    lore: '',
  },
  {
    key: 'swamp_petal_dress',
    slot: 'armor',
    nameKo: '요정의 첫 꽃잎',
    region: '늪지대',
    tone: '아름다운',
    concept: '어린 늪요정의 첫 비행 꽃잎 드레스',
    art: 'a layered petal fairy dress — the first-flight gown of a young bog-fairy, woven from dawn-dewed flower petals with gossamer wings, light and joyful — drawn in a cute charming fantasy-anime style, soft luminous pastel pink and mint, a graceful slender silhouette, isolated object, plain background, pixel art',
    wornDesc: 'a layered pastel-pink-and-mint petal fairy dress with sheer gossamer wings',
    lore: '',
  },
];

// 재설계: 새 90종(items90)을 카탈로그로 사용. 이전 120종은 보류 — 삭제하지 않고
// HELD_ITEMS로 보존(나머지 30을 여기서 골라 추가할 풀). 현재 무기 30만 작성됨(방어구·장신구 추가 예정).
export const HELD_ITEMS: ItemV2[] = [...INLINE_ITEMS, ...EXTRA_ITEMS];


// ── V4 확장 14종 · 4차(2026-08-02) — 3차에서 장미 채찍검 1종 채택(+2차 임프 날개).
//    채택작의 공통 결: 흐르는 실루엣·단일 색 이야기·형태 자체가 컨셉. 넓은 날에 장식을
//    박는 방식(트럼프·태엽 대검류)을 버리고 전체 형태가 컨셉인 12종으로 재설계.
export const V4_ITEMS: ItemV2[] = [
  // ── 무기 8/8 확정 ──
  {
    key: 'general_twin_flintlocks',
    slot: 'weapon',
    nameKo: '두 발의 대답',
    region: '일반',
    tone: '화려',
    concept: '금 세공 쌍발 플린트락 권총',
    art: 'a pair of ornate flintlock pistols crossed — polished black barrels with swirling gold engravings and ruby-set grips, dashing and elegant, clearly pistol weapons, no text, no letters, no labels, large, diagonal',
    wornDesc: 'a crossed pair of black-and-gold flintlock pistols with ruby grips',
    lore: '',
    keeper: true,
  },
  {
    key: 'general_spiral_lance',
    slot: 'weapon',
    nameKo: '나선을 그리는 끝',
    region: '일반',
    tone: '영웅담',
    concept: '흑금 나선 세공의 기사 랜스',
    art: 'a black and gold spiral-fluted knight lance tapering to a piercing point, dramatic and imposing, clearly a lance weapon, large, diagonal',
    wornDesc: 'a black-and-gold spiral-fluted lance tapering to a fine point',
    lore: '',
    keeper: true,
  },
  {
    key: 'general_starfield_blade',
    slot: 'weapon',
    nameKo: '밤하늘을 벼린 날',
    region: '일반',
    tone: '수수께끼',
    concept: '별과 별자리 선이 흐르는 심야 검신',
    art: 'a longsword forged of the night sky — a deep midnight-blue translucent blade filled with tiny stars and glowing gold constellation lines, a dark silver hilt with a star-shaped pommel, mystical and elegant, clearly a sword weapon, large, diagonal',
    wornDesc: 'a midnight-blue blade filled with tiny stars and gold constellation lines',
    lore: '',
    keeper: true,
  },
  {
    key: 'general_kintsugi_katana',
    slot: 'weapon',
    nameKo: '금으로 기운 상처',
    region: '일반',
    tone: '아름다운',
    concept: '깨졌던 자리를 금으로 이은 킨츠기 카타나',
    art: 'a magnificent kintsugi katana — a long jet-black blade once shattered and rejoined with luminous molten-gold veins branching like lightning across the steel, warm gold light softly leaking from the seams, an ornate engraved gold tsuba and a black-and-gold silk-wrapped hilt, breathtaking and resolute, clearly a katana sword weapon, large, diagonal',
    wornDesc: 'a jet-black katana with bright gold veins mending old cracks along the blade',
    lore: '',
    keeper: true,
  },
  {
    key: 'fallen_half_blade',
    slot: 'weapon',
    nameKo: '절반의 추락',
    region: '타락천사',
    tone: '수수께끼',
    concept: '세로로 갈라진 반빛·반흑 대검 — 검은 깃털',
    art: 'a half-fallen greatsword — a blade split lengthwise, one half radiant white-gold and the other jet-black with falling dark feathers, a wing-shaped guard half gold half black, dramatic and tragic, clearly a greatsword weapon, large, diagonal',
    wornDesc: 'a greatsword split lengthwise into radiant gold and jet-black halves, dark feathers falling',
    lore: '',
    keeper: true,
  },
  { key: 'temple_icicle_longbow', slot: 'weapon', nameKo: '고드름을 당기다', region: '신전', tone: '아름다운',
    concept: '고드름이 자란 백은 장궁',
    art: 'an icicle longbow — a tall pale silver bow with clusters of clear icicles growing along its limbs, a shimmering frost-blue string, cold mist drifting from the grip, elegant and freezing, clearly a longbow weapon, no text, large, diagonal',
    wornDesc: 'a tall silver longbow with icicles growing along its limbs', lore: '', keeper: true },
  { key: 'fallen_pinion_twinblades', slot: 'weapon', nameKo: '한 쌍의 깃', region: '타락천사', tone: '전설',
    concept: '흰 깃·검은 깃의 쌍검',
    art: 'a pair of pinion twinblades — two curved wing-shaped blades crossed in an X, one white-gold with radiant feather etching and one jet-black with dark feather etching, matching hilts, dualistic and striking, clearly twin sword weapons, no text, large, diagonal',
    wornDesc: 'two crossed wing-shaped blades, one white-gold and one jet-black', lore: '', keeper: true },
  { key: 'fallen_grace_greatbow', slot: 'weapon', nameKo: '반쯤 남은 은총', region: '타락천사', tone: '전설',
    concept: '한쪽은 금빛·한쪽은 흑빛인 대궁',
    art: 'a magnificent fallen grace greatbow — a tall elegant bow with a deep recurve, its upper limb sculpted as a radiant white-gold angel wing with layered luminous feathers, its lower limb as a charred jet-black wing with ragged dark feathers, an ornate gilded center grip with fine filigree and a single pale gem, a taut string of pale light, a few loose feathers drifting, majestic and tragic, no halo, no ring, clearly a longbow weapon, no text, large, diagonal',
    wornDesc: 'a tall bow with one radiant gold limb and one charred black limb', lore: '', keeper: true },
  // ── 장신구 2/4 확정 ──
  {
    key: 'general_star_eyepatch',
    slot: 'accessory',
    nameKo: '감아 둔 왼눈',
    region: '일반',
    tone: '수수께끼',
    concept: '금 별 장식의 검은 가죽 안대',
    art: 'a black leather eyepatch over the left eye with a slim strap and a small gold star stud, roguish and stylish',
    wornDesc: 'a black leather eyepatch with a gold star stud over the left eye',
    lore: '',
    keeper: true,
  },
  {
    key: 'general_imp_wings',
    slot: 'accessory',
    nameKo: '등에 돋은 장난',
    region: '일반',
    tone: '희망',
    concept: '작은 악마의 박쥐 날개 한 쌍',
    art: 'a small pair of imp bat wings — two little glossy crimson-and-black bat wings with cute rounded tips and gold wing-claws, sized to sit on the upper back, charming and mischievous, not large dragon wings',
    wornDesc: 'small crimson bat wings perched on the upper back',
    lore: '',
    keeper: true,
  },
  // ── 미확정(방어구 2 · 장신구 2 자리) — 후보, 채택 대기 ──
  {
    key: 'general_kintsugi_armor',
    slot: 'armor',
    nameKo: '깨진 적 있는 갑옷',
    region: '일반',
    tone: '영웅담',
    concept: '금맥으로 기운 흑칠 킨츠기 갑주',
    art: 'a kintsugi armor — a sleek black lacquered plate armor mended with branching veins of bright gold across the chest and pauldrons, warm gold light in the cracks, a dark sash, resolute and beautiful, a single garment floating on a plain empty background, no buildings',
    wornDesc: 'black lacquered plate armor mended with branching veins of bright gold',
    lore: '',
  },
  {
    key: 'general_rosevine_dress',
    slot: 'armor',
    nameKo: '가시로 지은 옷',
    region: '일반',
    tone: '화려',
    concept: '가시 넝쿨로 짠 장미 아머드 드레스',
    art: 'an armored dress of living rose vines — a fitted bodice woven from dark green thorned vines with deep red roses blooming at the shoulder and waist, thorn-plated skirt layers, elegant and dangerous, a single garment floating on a plain empty background, no buildings',
    wornDesc: 'a bodice of dark thorned vines with deep red roses at the shoulder and waist',
    lore: '',
  },
  {
    key: 'general_hero_scarf',
    slot: 'accessory',
    nameKo: '바람을 기억하는 머플러',
    region: '일반',
    tone: '영웅담',
    concept: '바람에 길게 휘날리는 진홍 머플러',
    art: 'a long crimson hero scarf — a deep red muffler wrapped once around the neck with both ends streaming dramatically in the wind, frayed tips and gold-stitched edges, heroic and free, isolated object on a plain background',
    wornDesc: 'a deep red muffler with both ends streaming dramatically behind',
    lore: '',
  },
  {
    key: 'general_guardian_daggers',
    slot: 'accessory',
    nameKo: '주인을 지키는 세 자루',
    region: '일반',
    tone: '수수께끼',
    concept: '등 뒤에 부유하는 호위 소검 세 자루',
    art: 'three small guardian daggers floating in formation — ornate silver-and-gold daggers hovering in a fan arrangement with faint magic glow trails, vigilant and mysterious, isolated objects on a plain background, no text',
    wornDesc: 'three ornate daggers floating in a fan formation behind the back',
    lore: '',
  },
];



// ── V4 후보 풀 30종(2026-08-02, key1 대량 생성) — 사용자가 2/2/2 선별 예정.
export const V4_POOL30: ItemV2[] = [
  { key: 'kingdom_lionguard_plate', slot: 'armor', nameKo: '문 앞을 지킨 백 년', region: '왕국', tone: '영웅담',
    concept: '사자 흉갑의 백금 근위 풀플레이트',
    art: 'a royal lionguard full plate — polished white-silver plate armor with a golden lion embossed on the breastplate, gold-trimmed pauldrons and a deep blue cape falling from the shoulders, stately and unyielding, a single garment floating on a plain empty background, no buildings, no scenery, no text',
    wornDesc: 'white-silver plate with a golden lion breastplate and blue cape', lore: '' },
  { key: 'kingdom_herald_tabard', slot: 'armor', nameKo: '소식을 입은 자', region: '왕국', tone: '화려',
    concept: '문장 태버드를 두른 사슬갑',
    art: 'a royal herald tabard over mail — a crisp blue-and-gold heraldic tabard bearing a crowned emblem worn over fine silver chainmail, a wide belt and gold-fringed hem, ceremonial and proud, a single garment floating on a plain empty background, no buildings, no scenery, no text',
    wornDesc: 'a blue-and-gold heraldic tabard over silver chainmail', lore: '' },
  { key: 'kingdom_courtmage_robe', slot: 'armor', nameKo: '왕좌 옆의 자리', region: '왕국', tone: '수수께끼',
    concept: '금 자수 남청 궁정 마도사 로브',
    art: 'a court mage regalia — a deep navy floor-length robe with elaborate gold thread embroidery along the hem and wide sleeves, a high stiff collar and a jeweled clasp, scholarly and authoritative, a single garment floating on a plain empty background, no buildings, no scenery, no text',
    wornDesc: 'a deep navy court mage robe with gold thread embroidery', lore: '' },
  { key: 'swamp_bogwitch_rags', slot: 'armor', nameKo: '늪이 지어 준 옷', region: '늪지대', tone: '수수께끼',
    concept: '넝마 자락에 반딧불이 붙은 늪 마녀 드레스',
    art: 'a bog witch dress — a layered ragged dark-green dress with torn uneven hems and trailing moss, tiny golden fireflies clinging to the fabric, a knotted vine sash, eerie and enchanting, a single garment floating on a plain empty background, no buildings, no scenery, no text',
    wornDesc: 'a ragged dark-green witch dress with moss and clinging fireflies', lore: '' },
  { key: 'swamp_bonecharm_leathers', slot: 'armor', nameKo: '부적을 꿰어 입다', region: '늪지대', tone: '영웅담',
    concept: '뼈 부적을 엮은 늪 사냥꾼 가죽 경갑',
    art: 'swamp hunter leathers — dark weathered leather armor with strapped shoulder guards, small carved bone charms strung across the chest, a hooded collar and mud-toned wraps, rugged and superstitious, a single garment floating on a plain empty background, no buildings, no scenery, no text',
    wornDesc: 'dark leather armor strung with small carved bone charms', lore: '' },
  { key: 'swamp_lotus_robe', slot: 'armor', nameKo: '물 위에 앉은 옷', region: '늪지대', tone: '아름다운',
    concept: '백련 자수의 물빛 로브',
    art: 'a lotus robe — a flowing pale water-green robe with white lotus blossoms embroidered rising from the hem, sheer layered sleeves and a silver sash, serene and graceful, a single garment floating on a plain empty background, no buildings, no scenery, no text',
    wornDesc: 'a pale water-green robe with white lotus embroidery rising from the hem', lore: '' },
  { key: 'volcano_forge_apron', slot: 'armor', nameKo: '불 앞에 선 하루', region: '화산', tone: '영웅담',
    concept: '대장장이 가죽 앞치마와 팔토시',
    art: 'a forgemaster outfit — a heavy scorched leather apron with brass rivets over a dark sleeveless shirt, thick arm bracers and a tool belt, soot marks and ember burns, industrious and sturdy, a single garment floating on a plain empty background, no buildings, no scenery, no text',
    wornDesc: 'a scorched leather forge apron with brass rivets and arm bracers', lore: '' },
  { key: 'volcano_ember_plate', slot: 'armor', nameKo: '안에서 타는 것', region: '화산', tone: '전설',
    concept: '균열마다 잉걸이 빛나는 흑철 판금',
    art: 'an ember plate armor — blackened iron plate armor with glowing orange ember cracks running through every seam and joint, heat shimmer rising from the shoulders, menacing and molten, a single garment floating on a plain empty background, no buildings, no scenery, no text',
    wornDesc: 'blackened plate armor with glowing ember cracks in every seam', lore: '' },
  { key: 'volcano_ashen_haori', slot: 'armor', nameKo: '재를 걸친 어깨', region: '화산', tone: '수수께끼',
    concept: '불티가 흩날리는 잿빛 하오리',
    art: 'an ashen haori — a long charcoal-grey open haori jacket with a faded ember-orange inner lining, fine ash drifting from its hem and a few cinders glowing in the weave, wandering and melancholic, a single garment floating on a plain empty background, no buildings, no scenery, no text',
    wornDesc: 'a charcoal-grey haori with ember-orange lining and drifting ash', lore: '' },
  { key: 'temple_snowpriest_robe', slot: 'armor', nameKo: '첫눈의 예복', region: '신전', tone: '아름다운',
    concept: '은장식 설백 사제 예복',
    art: 'a snow priest vestment — a pristine white ceremonial robe with silver embroidery in snowflake patterns, a pale blue stole draped over the shoulders and a silver chain clasp, sacred and cold, a single garment floating on a plain empty background, no buildings, no scenery, no text',
    wornDesc: 'a white priest robe with silver snowflake embroidery and a pale stole', lore: '' },
  { key: 'temple_frostguard_plate', slot: 'armor', nameKo: '얼음이 지키는 문', region: '신전', tone: '전설',
    concept: '서리 낀 백은 근위 판금',
    art: 'a frostguard plate — pale silver plate armor rimed with frost along the edges, ice-blue crystal accents at the chest and pauldrons, a white fur mantle, resolute and freezing, a single garment floating on a plain empty background, no buildings, no scenery, no text',
    wornDesc: 'pale silver plate rimed with frost and an ice-blue chest crystal', lore: '' },
  { key: 'temple_veil_dress', slot: 'armor', nameKo: '기도 뒤에 선 사람', region: '신전', tone: '수수께끼',
    concept: '면사를 드리운 신전 예복 드레스',
    art: 'a temple veil dress — a long ivory dress with a sheer flowing veil falling from the shoulders, fine gold prayer-bead cords at the waist, soft translucent layers, devout and mysterious, a single garment floating on a plain empty background, no buildings, no scenery, no text',
    wornDesc: 'an ivory dress with a sheer flowing veil and gold prayer-bead cords', lore: '' },
  { key: 'fallen_featherfall_coat', slot: 'armor', nameKo: '떨어지며 남긴 것', region: '타락천사', tone: '수수께끼',
    concept: '검은 깃털이 흘러내리는 흑금 롱코트',
    art: 'a featherfall longcoat — a black high-collar longcoat with layered dark feathers cascading down the shoulders and back, dull gold trim and buckles, loose feathers drifting, fallen and elegant, a single garment floating on a plain empty background, no buildings, no scenery, no text',
    wornDesc: 'a black longcoat with dark feathers cascading from the shoulders', lore: '' },
  { key: 'fallen_gilded_ruin_plate', slot: 'armor', nameKo: '벗겨진 금', region: '타락천사', tone: '전설',
    concept: '금 도금이 벗겨진 폐허의 갑주',
    art: 'a gilded ruin armor — once-golden plate armor with its gilding flaked away to reveal blackened metal beneath, cracked engravings and a torn dark mantle, faint gold light in the fractures, ruined and majestic, a single garment floating on a plain empty background, no buildings, no scenery, no text',
    wornDesc: 'flaking gold plate armor revealing blackened metal beneath', lore: '' },
  { key: 'fallen_mourning_gown', slot: 'armor', nameKo: '조문하는 밤', region: '타락천사', tone: '아름다운',
    concept: '검정에 금실을 놓은 상복 드레스',
    art: 'a mourning gown — a floor-length matte black gown with fine gold thread tracing feather patterns across the bodice, sheer black sleeves and a long trailing hem, solemn and beautiful, a single garment floating on a plain empty background, no buildings, no scenery, no text',
    wornDesc: 'a matte black gown with gold feather-pattern thread and trailing hem', lore: '' },
  { key: 'orc_warchief_pelt', slot: 'armor', nameKo: '부락의 등', region: '오크 부락', tone: '영웅담',
    concept: '뼈 견갑과 모피의 족장 차림',
    art: 'an orc warchief attire — a thick beast-fur mantle over a bare-shouldered leather harness, a massive bone pauldron on one side, iron-studded belts and war-paint stripes, savage and commanding, a single garment floating on a plain empty background, no buildings, no scenery, no text',
    wornDesc: 'a beast-fur mantle with a massive bone pauldron and studded belts', lore: '' },
  { key: 'orc_ironjaw_halfplate', slot: 'armor', nameKo: '주워 붙인 갑옷', region: '오크 부락', tone: '수수께끼',
    concept: '고철을 리벳으로 덧댄 하프플레이트',
    art: 'a scrap half-plate — mismatched riveted iron plates lashed over a leather jerkin with rope and chain, jagged edges and rust patches, one oversized shoulder plate, crude and intimidating, a single garment floating on a plain empty background, no buildings, no scenery, no text',
    wornDesc: 'mismatched riveted iron plates lashed over a leather jerkin', lore: '' },
  { key: 'orc_warpaint_wraps', slot: 'armor', nameKo: '문양만 두르고', region: '오크 부락', tone: '화려',
    concept: '전투 문양의 가죽 붕대 경장',
    art: 'orc war wraps — minimal armor of crimson-dyed cloth wraps binding the torso and arms over dark leather straps, bold white war-paint patterns, bone beads and feathers, wild and agile, a single garment floating on a plain empty background, no buildings, no scenery, no text',
    wornDesc: 'crimson cloth wraps over leather straps with white war-paint patterns', lore: '' },
  { key: 'general_ronin_haori', slot: 'armor', nameKo: '주인을 잃은 옷', region: '일반', tone: '수수께끼',
    concept: '해진 자락의 낭인 하오리',
    art: 'a ronin haori — a worn indigo open haori with frayed hem and a faded family crest on the back, layered over a grey kimono and a dark obi with a sword cord, weary and dignified, a single garment floating on a plain empty background, no buildings, no scenery, no text',
    wornDesc: 'a worn indigo haori with frayed hem over a grey kimono', lore: '' },
  { key: 'general_gunslinger_duster', slot: 'armor', nameKo: '먼지가 앉은 코트', region: '일반', tone: '영웅담',
    concept: '바람에 갈라지는 총잡이 더스터 코트',
    art: 'a gunslinger duster coat — a long tan canvas duster with a caped shoulder yoke, worn leather belts and a dark vest beneath, sun-bleached and dusty, wind-swept hem, rugged and cinematic, a single garment floating on a plain empty background, no buildings, no scenery, no text',
    wornDesc: 'a long tan duster coat with caped shoulders over a dark vest', lore: '' },
  { key: 'general_plague_doctor_coat', slot: 'armor', nameKo: '전염되지 않는 옷', region: '일반', tone: '수수께끼',
    concept: '밀랍 먹인 흑색 역병 의사 코트',
    art: 'a plague doctor coat — a long waxed black coat with a wide brim silhouette collar, many small brass buttons, leather gloves and a satchel of vials at the belt, ominous and clinical, a single garment floating on a plain empty background, no buildings, no scenery, no text',
    wornDesc: 'a long waxed black coat with brass buttons and a vial satchel', lore: '' },
  { key: 'general_musketeer_tabard', slot: 'armor', nameKo: '넷이 하나로', region: '일반', tone: '화려',
    concept: '십자 문장 총사 튜닉과 케이프',
    art: 'a musketeer tunic — a deep blue tabard with a silver cross emblem and gold fleur accents worn over a white shirt with lace cuffs, a short cape and a leather baldric, dashing and gallant, a single garment floating on a plain empty background, no buildings, no scenery, no text',
    wornDesc: 'a blue musketeer tabard with a silver cross over a laced white shirt', lore: '' },
  { key: 'general_snowqueen_gown', slot: 'armor', nameKo: '겨울을 부르는 옷', region: '일반', tone: '전설',
    concept: '얼음 결정 왕관 깃의 설녀 드레스',
    art: 'a snow queen gown — a shimmering pale-blue gown with a tall crystalline collar rising behind the neck, frost patterns spreading across the skirt and a translucent icy train, regal and glacial, a single garment floating on a plain empty background, no buildings, no scenery, no text',
    wornDesc: 'a pale-blue gown with a crystalline standing collar and frosted train', lore: '' },
  { key: 'general_beastmaster_hide', slot: 'armor', nameKo: '짐승과 같은 편', region: '일반', tone: '영웅담',
    concept: '짐승 가죽과 발톱 장식의 조련사 차림',
    art: 'a beastmaster outfit — layered tawny animal hides with a clawed shoulder mantle, fur-lined boots and bone-clasped belts, braided leather cords, primal and free, a single garment floating on a plain empty background, no buildings, no scenery, no text',
    wornDesc: 'layered tawny hides with a clawed shoulder mantle and bone clasps', lore: '' },
  { key: 'general_starlet_tuxedo', slot: 'armor', nameKo: '조명을 받는 각도', region: '일반', tone: '화려',
    concept: '금 라펠의 백색 무대 턱시도',
    art: 'a white stage tuxedo — a crisp white tailcoat tuxedo with satin gold lapels, a gold waistcoat and black bow tie, a small star pin at the chest, glamorous and sharp, a single garment floating on a plain empty background, no buildings, no scenery, no text',
    wornDesc: 'a white tailcoat tuxedo with gold satin lapels and waistcoat', lore: '' },
  { key: 'general_scholar_uniform', slot: 'armor', nameKo: '줄 세운 지식', region: '일반', tone: '희망',
    concept: '금 술 장식의 학사 제복',
    art: 'a scholar academy uniform — a dark green double-breasted uniform coat with gold braid cords across the chest, a stiff collar with an emblem pin and gold shoulder tassels, disciplined and elegant, a single garment floating on a plain empty background, no buildings, no scenery, no text',
    wornDesc: 'a dark green uniform coat with gold braid cords and shoulder tassels', lore: '' },
  { key: 'general_witchhunter_coat', slot: 'armor', nameKo: '버클마다 이유가', region: '일반', tone: '수수께끼',
    concept: '버클이 줄지은 흑색 마녀사냥꾼 코트',
    art: 'a witch hunter coat — a fitted black longcoat with many silver buckles and straps across the chest, a high collar, dark leather gloves and a wide belt with hanging charms, austere and relentless, a single garment floating on a plain empty background, no buildings, no scenery, no text',
    wornDesc: 'a fitted black longcoat lined with silver buckles and straps', lore: '' },
  { key: 'general_puppet_dress', slot: 'armor', nameKo: '실이 남은 드레스', region: '일반', tone: '수수께끼',
    concept: '실이 매달린 인형사 드레스',
    art: 'a marionette dress — an elegant layered dress in dusty rose and cream with fine silver strings trailing up from the shoulders and wrists, small wooden joint accents at the elbows, uncanny and delicate, a single garment floating on a plain empty background, no buildings, no scenery, no text',
    wornDesc: 'a dusty-rose layered dress with fine strings trailing from the shoulders', lore: '' },
  { key: 'general_ringmaster_coat', slot: 'armor', nameKo: '오늘의 진행자', region: '일반', tone: '화려',
    concept: '금 장식 진홍 서커스 단장 연미복',
    art: 'a ringmaster coat — exactly one outfit, a single composition, no repeated variants, a vivid crimson tailcoat with heavy gold frogging and epaulettes, black trousers with a gold stripe, a black waistcoat and white cravat, theatrical and commanding, a single garment floating on a plain empty background, no buildings, no scenery, no text',
    wornDesc: 'a crimson tailcoat with gold frogging and epaulettes', lore: '' },
  { key: 'general_frostwolf_cloak', slot: 'armor', nameKo: '겨울을 견디는 법', region: '일반', tone: '영웅담',
    concept: '늑대 모피를 두른 겨울 사냥꾼 차림',
    art: 'a frostwolf hunter outfit — a thick grey wolf-fur cloak clasped at the shoulder over layered leather and wool, fur-trimmed bracers and a rope belt, frost dusting the fur, hardy and wild, a single garment floating on a plain empty background, no buildings, no scenery, no text',
    wornDesc: 'a thick grey wolf-fur cloak over layered leather and wool', lore: '' },
];

export const ITEMS_V2: ItemV2[] = [...WEAPONS_90, ...ARMOR_90, ...ACCESSORIES_90, ...V4_ITEMS, ...V4_POOL30];

// 컨셉-온리 확정 방식(2026-06-27): art = "a <종류> — <역할·무드>"(외형묘사 X). buildArt가 슬롯별 품질 tail만 덧붙임.
// 자유를 줄수록 결과가 좋다(사용자 검증). 아바타가 일본 애니메 미소년/미소녀라 톤은 밝고 깔끔한 애니/JRPG.
const TAIL: Record<string, string> = {
  weapon: 'a beautiful clean fantasy anime RPG gacha-game weapon, bright and stylish, not gothic, a single isolated object on a plain flat empty background, large, pixel art',
  armor: 'a beautiful clean fantasy anime RPG gacha-game outfit, bright and stylish, not gothic, shown as the worn outfit on its own with no head and no neck, a slim full-length figure, a single isolated object on a plain flat empty background, pixel art',
  accessory: 'a beautiful clean fantasy anime RPG gacha-game item, bright and stylish, not gothic, a single isolated object on a plain flat empty background, pixel art',
};
export function buildArt(it: ItemV2): string {
  if (it.art.includes('pixel art')) return it.art; // 이미 완성된 프롬프트면 그대로
  return `${it.art}, ${TAIL[it.slot] ?? TAIL.accessory}`;
}
